### ISSUE TITLE
Implement learning rate annealing

### ISSUE THREAD

**Issue by Islandman93** [tensorforce/tensorforce#103]
Now that model.py has a timestep it should be possible to anneal/decay (and others like stepped annealing) the learning rate.

This can be done by using a tf.placeholder for the learning rate that is passed into the optimizer.

**Comment by wil3** [comment]
Any progress on this front? I've experience significantly better results with learning rate decay using the OpenAI baselines PPO implementation.

**Comment by AlexKuhnle** [comment]
Not much happened, to be honest. I have an idea of how to support this, and if you're keen to look into an implementation, let's talk over Gitter or so. I may also be able to do it myself at some point, but may take some time (rather busy these days).

**Comment by wil3** [comment]
Sounds good, I'll let you know if I get to a point to implement it my self.

**Comment by AlexKuhnle** [comment]
Will be supported in the upcoming new version (see branch).
