### ISSUE TITLE
Feature Request: Direct Future Prediction (DFP)

### ISSUE THREAD

**Issue by Mazecreator** [tensorforce/tensorforce#159]
There is another paper on Direct Future Prediction which I have had some luck with in the past:
https://arxiv.org/pdf/1611.01779.pdf

It would be nice if TensorForce supported this algorithm.

**Comment by michaelschaarschmidt** [comment]
Looks interesting, but it will not be on the roadmap for us in the coming months (we will release this roadmap soon). Feel free to get started on contributing an implementation

**Comment by AlexKuhnle** [comment]
On roadmap, but probably not anytime soon.
