### ISSUE TITLE
add acktr?

### ISSUE THREAD

**Issue by brantbzhang** [tensorforce/tensorforce#167]
Hi, can you  add acktr model ? thanks!

**Comment by lefnire** [comment]
https://github.com/openai/baselines/tree/master/baselines/acktr for ref

**Comment by michaelschaarschmidt** [comment]
We can, and we will at some point, but we have many other structural things to do so it would be very welcome if someone started on an implementation.

**Comment by michaelschaarschmidt** [comment]
I suppose first we need to implement KFAC, which could the in theory be used with all models, not just ACKTR

**Comment by AlexKuhnle** [comment]
Contribution welcome.
