### ISSUE TITLE
Code style editor configuration files

### ISSUE THREAD

**Issue by mryellow** [tensorforce/tensorforce#170]
`.editorconfig`

http://editorconfig.org/

`pylintrc`

https://github.com/PyCQA/pylint/blob/master/pylintrc

**Comment by mryellow** [comment]
Tom Rickmeyer @trickmeyer 03:30

> hey @michaelschaarschmidt @mryellow google also has a nice python formatter that has configs, etc. i've been pleased with it so far: https://github.com/google/yapf

**Comment by AlexKuhnle** [comment]
PR welcome, but won't look into that anytime soon.
