### ISSUE TITLE
Update categorical DQN to new API

### ISSUE THREAD

**Issue by michaelschaarschmidt** [tensorforce/tensorforce#185]

**Comment by brantbzhang** [comment]
When do you plan to finish update?I want to use 0.3, but wait for categorical DQN.

**Comment by AlexKuhnle** [comment]
Hey @brantbzhang,

I fear this might take anoter 1-2 weeks, since there are still quite a few little TODOs that we consider more urgent (bug fixes etc). You can of course run on 0.2 for now to use the model, but (in our own interest) we'll try our best to be quick about it. :-)

**Comment by brantbzhang** [comment]
Thanks!

**Comment by watterm** [comment]
Is this still a problem? I updated to the current version and DQN agents throw no errors, but also don't seem to improve.

**Comment by michaelschaarschmidt** [comment]
Categorical DQN is not available but that is unrelated to DQN not improving, which are not aware of.

**Comment by AlexKuhnle** [comment]
On roadmap
