### ISSUE TITLE
FEATURE REQUEST: Rainbow RL DeepMinds

### ISSUE THREAD

**Issue by Mazecreator** [tensorforce/tensorforce#186]
Rainbow: Combining Improvements in Deep Reinforcement Learning

Another great paper for consideration:
https://arxiv.org/abs/1710.02298

**Comment by AlexKuhnle** [comment]
Yes, most of the components are actually there in the framework and it's only a question of combining them. I don't think we will find the time to implement it in the next 2-3 weeks, though, but if you give it a try as contribution, we're happy to be of help.

**Comment by Mazecreator** [comment]
I am not very familiar with your code and library structure yet, let me take a look.  I think it would be good to have the ability to turn-on/off the different features during the INIT of the library.  I will see if I can identify the different parts as well.

If you have any helpful hints, I am all ears.

**Comment by AlexKuhnle** [comment]
What do you mean by "turning on/off features during INIT of the library"? When initializing the respective Agent class, so in its constructor, __init__(...)? If so, we are planning to change this soon(ish). But the `default_config` there should give you an idea what values can be set in the config.

If you want to look at implementing Rainbow, the best way probably is first figuring out what is missing / what is different to our `q_model`. I would have to take a closer look at the paper to answer this, will do at some point...

**Comment by Mazecreator** [comment]
I am taking a stab at eh "RainbowAgent".  I took a first look through the library for the 6 different DQN extension features.  I could only find 2 (Double Q and Prioritized Replay) of the 6:

    The Rainbow Extensions to DQN inclusions consist of the following parameters:

    * [Double Q-learning] `double_q_model`: boolean indicating whether to use a double q.
    * [Prioritized Replay] `memory`: string of memory type ('replay' or 'prioritized_replay')
    * [Dueling Networks] (https://arxiv.org/pdf/1511.06581.pdf) - Network Topology
    * [Multi-step Learning] (Complex Loss function)
    * [Distributional RL] (Distribution of returns rather than Expected Returns)
    * [Noisy Nets] (https://arxiv.org/abs/1706.10295) Injecting Noise into Network

I haven't looked much into how networks are built, but seems like Dueling might be able to be handled through a network "type" such as DUELING (which splits stream into Expected and Advantage and merges back).

I am a bit at a loss (no pun intended) for the Multi-step Learning which appears to be a complex Loss Function to minimize.

Distributional RL might be possible but I am not sure how "distributions" are implemented in your library yet. 

Noisy Nets might also be a Network change where noise is injected into the weights of a layer.  It seems like this is at the output of the network actions so another "type" NOISY might work here.

Any thoughts or pointers to anything I may have missed would be helpful.  Given this approach, I am not sure the RainbowAgent can turn on and off each of the 6 features if they involve the network topology, but certainly can enable/disable a few features depending upon the implementation details.

**Comment by Mazecreator** [comment]
I may have a solution for the Dueling as a layer "dueling".  Please take a look at this code to see if you think it will work correctly.  This implements splitting the Expectation and Advantage function in the network layer.
https://github.com/Mazecreator/tensorforce/blob/dueling/tensorforce/core/networks/layer.py#L481-L574

**Comment by AlexKuhnle** [comment]
We still have to update the Distributional RL implementation, but that's on the way. Noisy nets could be a bit tougher, I will have to think about that, but it seems like a feature that is best integrated 'at the very bottom', i.e. in the `Model` baseclass. Multi-step learning, I thought, just corresponds to our `q_nstep_model`, but might be wrong. I will have a look at your dueling implementation.

**Comment by AlexKuhnle** [comment]
Just gave the noisy nets a try: The new model parameter `variable_noise`, if not None, specifies the stddev of the noise to add when retrieving an action. The relevant part of the `Model` code is [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L550). I still have to look at the paper in more detail, what additional tricks they use and whether/how we can integrate them, but this config option should be a start...

**Comment by Mazecreator** [comment]
With the change to the DDQN model yesterday with the double_Q_model flag moved to the obligatory section (@etardis is my other account, sorry to confuse you), does this mean I can no longer enable/disable this feature as part of the DDQN model?  I was basing Rainbow on that model, but now should I use the DQN and set this flag to True?

**Comment by AlexKuhnle** [comment]
We thought it would become clearer that way, since in many frameworks DDQN is a separate agent. So yes, the DQN agent is the more general one (since you can set `double_q` to `True` still), while the DDQN agent is specifically `double_q`.

**Comment by Mazecreator** [comment]
@AlexKuhnle ,

I am trying to figure out how the models handle the conversion from the last line of the Network configuration to the appropriate number of actions.

For example:

    * Network as list of layers
    network_spec = [
        dict(type='dense', size=32, activation='tanh'),
        dict(type='dense', size=32, activation='tanh'),
        dict(type='dueling', size=20, activation='none')
    ]

If there are only 2 actions, is another layer put in place automatically to convert the 20 outputs to 2 actions?

    * Network as list of layers
    network_spec = [
        dict(type='dense', size=32, activation='tanh'),
        dict(type='dense', size=32, activation='tanh'),
        dict(type='dueling', size=2, activation='none')
    ]

Where as in this one, if I have 2 actions and the final layer is 2 outputs is something put in place to convert these two outputs to 2 outputs (another layer) or is it recognized there are 2 outputs and onlyl two actions?

The reason I ask is the dueling layers implies it should be left raw and the final output to the network and I don't know how to confirm that is the case. (BTW, there is a PULL request for the update pending)

**Comment by AlexKuhnle** [comment]
All agents use a `Distribution` object to model the (generally stochastic) policy, and all of them introduce another linear (!) layer, doesn't matter whether the output of the network is of appropriate size or not. Since it's linear, you could not add a non-linearity (in case you do), so that the combination of two linear layers equals one linear layer, kind of.

I haven't had a closer look at the PR, but will do soon.

**Comment by marintoro** [comment]
Hello, I am interested too in implementing Rainbow. I am currenlty getting started with tensorforce and I just wanted to know if there were some new information about this feature request?

**Comment by michaelschaarschmidt** [comment]
Hi,

almost all peaces are there, the biggest hurdle is https://github.com/reinforceio/tensorforce/issues/185.

We had categorical dqn in the previous version but fitting it into the new architecture is a bit of work and we are really busy right now, so it will probably take another ~2 months (because other architecture tasks are more urgent) to do this, unless someone goes ahead on that issue

**Comment by Mazecreator** [comment]
We might need to create a distribution for Dueling, right now it is a layer, but the implementation in the paper implies it is the raw output of the net.  The code is available, just needs to be implemented as a distribution to assure it is the raw output of the net:
  - [Dueling Networks] (https://arxiv.org/pdf/1511.06581.pdf) - Network Topology

I started to write the agent for this, but it is likely a trivial implementation once all 6 pieces are in place.  I can write the final agent once that occurs but it will be likely you can enable the 6 piece through the configuration as well.

**Comment by marintoro** [comment]
@Mazecreator , I am not sure to understand what you mean there. Are you working on the 0.2 version of Tensorforce so Categorical Dqn is working (and so you can "merge" all the pieces of Rainbow)?
And when you say "The code is available", the code for doing what?

**Comment by Mazecreator** [comment]
The code for the Dueling Networks is within TensorForce.  This should be created as a distribution (output function) for the network for it to match the paper.  This update is in addition to what @michaelschaarschmidt has stated needs to be added to meet the features in the Rainbow paper.

**Comment by phuicy** [comment]
@Mazecreator @marintoro Can we not proceed without Categorical DQN? The results won't be as good but similarly improved.

**Comment by AlexKuhnle** [comment]
On roadmap.
