### ISSUE TITLE
Add some examples/*.json w new optimizers (natural_gradient, evolutionary, etc)

### ISSUE THREAD

**Issue by lefnire** [tensorforce/tensorforce#222]
Per the latest blog post, those look cool! Would be nice to see them in context w/ their best-fit agents & the sort. 

Some personal confusion this would mitigate: the way ppo_agent.json uses an adam step_optimizer is confusing as to whether that replaces a natural_gradient optimizer or augments it, or whether natural_gradient is kind of "assumed" w/ ppo_agent under the hood or needs to be specified. Same for dqn + evolutionary; does that go _with_ adam, or replace it?

**Comment by AlexKuhnle** [comment]
Good idea to add some interesting configs which we want to emphasize.

PPO does not use the `natural_gradient` optimizer, PPO uses `MultiStep(Adam)` while TRPO uses `OptimizedStep(NaturalGradient)`. The `MultiStep` part is considered specific to PPO, while whether the internal optimizer is `Adam` or `RMSProp` or so is not specified (although we should maybe just fix it for clarity).

`Evolutionary` is a different optimizer (not using gradient information), so does not combine with `Adam`. In the blogpost, we put this optimizer overview diagram, which hopefully gives an intuition how optimizers work -- only `MetaOptimizer` modify another optimizer, all others are atomic but interchangeable.

Hope that clarifies things... :-)

**Comment by AlexKuhnle** [comment]
Outdated
