### ISSUE TITLE
Feature request: state dependent action space

### ISSUE THREAD

**Issue by sriumcp** [tensorforce/tensorforce#330]
The [tensorforce blog](http://reinforce.io/blog/introduction-to-tensorforce/) mentions state dependent action spaces under the **Further Considerations** section. Is this in the works / coming soon? If not, if I were to contribute an implementation of this feature, how can I go about this?

**Comment by michaelschaarschmidt** [comment]
Hey, 

this is not coming soon from our end - just as an FYI, we are currently in the process of completing the in-graph move in the memory branch (here on github), which will take another 1-2 weeks and is binding our resources. I think this feature might need some discussion, feel free to describe some initial thoughts, or join the developer chat, and then we can take it from there.

**Comment by tianv** [comment]
Who have some ideas about the question [ state dependent action spaces] ?

**Comment by AlexKuhnle** [comment]
I assume this can be closed.

**Comment by AlexKuhnle** [comment]
Hey, that's definitely on the roadmap for the new version 0.5 coming soon (currently under work, see branch). It would be helpful to specify different situations of changing action spaces and what the common patterns are. It seems to me that one common pattern is that a small subset of actions may not be available (~remove a few options), and a more general pattern that only a subset of actions are available (~only offer a few options). The second link talks about something even more general (I think), conditioned on the internal state -- that sounds much more complex, and I don't yet see where this could be useful (or how it could be implemented). Thoughts and feedback welcome. :-)

**Comment by coolsurf** [comment]
Hi Alex, Thanks for the information.  Great to hear it's on the roadmap!
To me, the common pattern you described should cover my use scenario.  For example,
  1. All actions {p, q, r, s, t} always exist in the network.
  2. In state 0, only {p, q, r} are valid.  (Disable subset {s, t})
  3. In state 1, only {p, s, t} are valid.  (Disable subset {q, r})
Looking forward to it.  Many thanks.  :-)

**Comment by AlexKuhnle** [comment]
On roadmap

**Comment by MarsEleven** [comment]
Hi, 
is the state-dependent action space already implemented in the current stable version (0.5.4)?
I wasn´t able to find it in the docs.

Thank you so much in advance!
