### ISSUE TITLE
[BUG] ThreadedRunner is broken and its test is not covering this

### ISSUE THREAD

**Issue by matwilso** [tensorforce/tensorforce#384]
When I run the test for ThreadedRunner (https://github.com/reinforceio/tensorforce/blob/master/tensorforce/tests/test_vpg_multithreaded.py#L74-L75) it passes when it shouldn't

In the test, the runner runs for 100 episodes so we expect `runner.episode_rewards` to have length 100.  I test this with `assert(len(runner.episode_rewards) == 100)`, and the test now fails.  When the test fails, it shows a huge long TensorFlow stack trace that is usually not shown when the test passes.  The end of this trace is shown here:

```
InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [36,2], indices.shape [3], params.shape [100,2]
	 [[Node: vpg/observe-timestep/store/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@vpg/initialize/latest/initialize/state-state"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](vpg/initialize/latest/initialize/state-state, vpg/observe-timestep/store/mod, vpg/strided_slice, ^vpg/observe-timestep/store/AssignSub)]]

```

As it turns out, there seems to be a bigger problem where ThreadedRunner is causing the shapes of tensors to be wrong somehow.  I noticed this problem on trying to use it on a different environment.

You should be able to reproduce this with a fresh clone of the repo and inserting the `assert` statement after the `runner.run(num_episodes=100)` line.  You also can just run the unmodified test with the `-s` flag to see the InvalidArgumentError
```bash
pytest -s test_vpg_multithreaded.py 
```

**Comment by michaelschaarschmidt** [comment]
The reason this is likely the case is because there is a counter counting acts and observes, and they are likely out of sync because there are more acts than observes. (See the act() documentation for independent flag). I will try to have a look

**Comment by michaelschaarschmidt** [comment]
```
            while True:
                action = agent.act(states=state, deterministic=deterministic)
                reward = 0
                for repeat in xrange(self.repeat_actions):
                    state, terminal, step_reward = environment.execute(actions=action)
                    reward += step_reward
                    if terminal:
                        break

                agent.observe(reward=reward, terminal=terminal)
```
In essence it seems to me that since this is threaded, there can be a case where we observe, but have acted and not observed yet in another thread, and as the same model is shared, the counters are imbalanced. This is indeed a problem that did not exist before because things werent stored together in a tensorflow variable

**Comment by michaelschaarschmidt** [comment]
I think this is a principal issue with splitting up storing of action/state/internals and reward/terminals. Clearly, if we passed everything in observe (maybe via optional flags), that race condition wouldnt exist . Unfortunately very busy in phd now so cant work on it

**Comment by matwilso** [comment]
No worries.  That information is helpful.  I will probably see about trying to fix it and submitting a PR if I can in the next few weeks.

**Comment by michaelschaarschmidt** [comment]
I have now implemented and pushed to master a basic structure i) unbuffered act which returns interals and states, ii) an atomic observe which passes everything to the memory in one session call. 

Test seems at least to run but dont have time to extensively test everything, but this I think addresses the race conditions

**Comment by AlexKuhnle** [comment]
Outdated
