### ISSUE TITLE
Preprocessing operation like `divide` should be done after sampling experience

### ISSUE THREAD

**Issue by dmuestc** [tensorforce/tensorforce#389]
Training atari, frames will be scale by 255.0, if do this before storing in memory,  will waste more space (unit8-->float32), here:
https://github.com/reinforceio/tensorforce/blob/475512828adfebe644901b6459b53d075b787ac9/tensorforce/models/model.py#L264

So maybe doing this after sampling experience from buffer will be better.

**Comment by AlexKuhnle** [comment]
Works differently now
