### ISSUE TITLE
learning from random agent recorded sessions

### ISSUE THREAD

**Issue by chanansh** [tensorforce/tensorforce#466]
how can I use q-learning in an off-policy manner, meaning learning the optimal policy while playing a random one?

**Comment by AlexKuhnle** [comment]
Technically, Q-learning is always considered "off-policy", but the best option to achieve what you describe is probably using `constant` exploration of `1.0`. You can also set the ` target_sync_frequency` to something very high, and generally `update_mode`. You can then store and load the model with a different configuration if you want to start learning. Hope that helps and roughly corresponds to what you want!

**Comment by chanansh** [comment]
Not exactly.
I don't want a real environment, but use historical random runs to learn
from.
In that sense, I don't want the agent to make any actions, just observe
sessions. So exploration =1 will indeed make the agent random but I want to
use the recorded randomness.

**Comment by AlexKuhnle** [comment]
In this case you want to probably use [this method](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/agents/learning_agent.py#L144) for exporting experience...

**Comment by chanansh** [comment]
@AlexKuhnle  thanks, can you please provide a usage example? there is no proper documentation on this function or usage. Plus, it expect value for state and action which is the thing I want to learn...

**Comment by AlexKuhnle** [comment]
It works essentially in the same way as demonstrations are added for DQFD, e.g. [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/tests/test_dqfd_agent.py#L124) (plus preceding lines).

**Comment by AlexKuhnle** [comment]
Did it help?

**Comment by AlexKuhnle** [comment]
Possible now
