### ISSUE TITLE
Can you provide an example for the environment of Unreal Engine 4 Games?

### ISSUE THREAD

**Issue by davidhopper2003** [tensorforce/tensorforce#469]
As mentioned in the documentation: `https://github.com/reinforceio/tensorforce/blob/master/docs/environments.md`, the environment of Unreal Engine 4 Games is supported. Can you give an example? Thank you very much.

**Comment by AlexKuhnle** [comment]
[This example script](https://github.com/reinforceio/tensorforce/blob/master/examples/unreal_engine.py) should hopefully help to get started.

**Comment by davidhopper2003** [comment]
@AlexKuhnle Great, thanks again.

**Comment by davidhopper2003** [comment]
@AlexKuhnle 
When I tried to install the engine2learn plugin with the command `pip install engine2learn`, I encountered the following error:
```
Could not find a version that satisfies the requirement engine2learn (from versions: ) No matching distribution found for engine2learn
```
Can tell me how you installed successfully? Thanks.

**Comment by daggertye** [comment]
It seems that engine2learn is not being supported through pypi. However, the actual source (like the environment) is integrated within TensorForce and is supported. You don't need to install an extra library. 

Source
[engine2learn](https://github.com/ducandu/MaRLEnE/tree/master) removed all environment stuff, but the other branches still work.

[tensorforce env](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/contrib/unreal_engine.py) doesn't import engine2learn. 

I hope that helps!

**Comment by davidhopper2003** [comment]
@daggertye Thank you. 
When I follow your instructions to run the command `python examples/unreal_engine.py 6025 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 50000 -m 2000`, the following error occurs:
```
usage: unreal_engine.py [-h] [-P PORT] [-H HOST] [-a AGENT_CONFIG]
                        [-n NETWORK_SPEC] [-e EPISODES] [-t TIMESTEPS]
                        [-m MAX_EPISODE_TIMESTEPS] [-d] [-l LOAD] [-D] [-R]
unreal_engine.py: error: unrecognized arguments: 6025
```
How to solve this problem? Can you give me some tips? Thanks once more.

**Comment by daggertye** [comment]
The example is incorrect. It should be

python examples/unreal_engine.py **-P** 6025 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 50000 -m 2000.

I'll be making a PR to fix this documentation soon, but the above command seems to be working.

**Comment by davidhopper2003** [comment]
@daggertye 
Got it. I run the command `python examples/unreal_engine.py -P 6025 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 50000 -m 2000` again according to your instructions, there are no errors, but no hints for a long time. What should be the correct situation? Can the program display some words to indicate that it is running correctly?
![screenshot 2018-08-03 14 25 49](https://user-images.githubusercontent.com/31435476/43627478-285560a4-9729-11e8-8c5d-e6570a73a75f.png)
![screenshot from 2018-08-03 14-25-20](https://user-images.githubusercontent.com/31435476/43627488-2d539238-9729-11e8-8369-6b2ccbc1935b.png)

**Comment by daggertye** [comment]
It seems to be getting stuck at line 80 (where the environment is declared) meaning that I'll have to look more deeply into what exactly is going on (it's an env problem). 

I'll raise an issue and try to debug through this environment. But for now, it's unusable.

**Comment by davidhopper2003** [comment]
@daggertye 
I run the command python examples/unreal_engine.py -P 6025 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 50000 -m 2000 again according to your instructions.

After a few minutes of waiting, the following connection error occurred:
```
^CTraceback (most recent call last):
  File "examples/unreal_engine.py", line 171, in <module>
    main()
  File "examples/unreal_engine.py", line 79, in main
    environment = UE4Environment(host=args.host, port=args.port, connect=True, discretize_actions=True, num_ticks=6)
  File "/home/davidhopper/code/tensorforce/tensorforce/contrib/unreal_engine.py", line 72, in __init__
    self.connect()
  File "/home/davidhopper/code/tensorforce/tensorforce/contrib/unreal_engine.py", line 79, in connect
    RemoteEnvironment.connect(self, timeout)
  File "/home/davidhopper/code/tensorforce/tensorforce/contrib/remote_environment.py", line 82, in connect
    time.sleep(1)
KeyboardInterrupt
```
![screenshot 2018-08-03 14 46 15](https://user-images.githubusercontent.com/31435476/43628224-00e911de-972c-11e8-97c3-55dd6b21d83a.png)

What should I do for the Unreal engine so that this program can properly connect to the Unreal engine?

**Comment by davidhopper2003** [comment]
@daggertye 
I ran the command `python examples/unreal_engine.py -P 6025 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 50000 -m 2000` again according to your instructions.

After a few minutes of waiting, the following connection error occurred:
```
Traceback (most recent call last):
  File "examples/unreal_engine.py", line 171, in <module>
    main()
  File "examples/unreal_engine.py", line 79, in main
    environment = UE4Environment(host=args.host, port=args.port, connect=True, discretize_actions=True, num_ticks=6)
  File "/home/davidhopper/code/tensorforce/tensorforce/contrib/unreal_engine.py", line 72, in __init__
    self.connect()
  File "/home/davidhopper/code/tensorforce/tensorforce/contrib/unreal_engine.py", line 79, in connect
    RemoteEnvironment.connect(self, timeout)
  File "/home/davidhopper/code/tensorforce/tensorforce/contrib/remote_environment.py", line 85, in connect
    format(self.host, self.port, err, errno.errorcode[err], os.strerror(err)))
tensorforce.exception.TensorForceError: Error when trying to connect to localhost:6025: errno=103 errcode='ECONNABORTED' 'Software caused connection abort'
```
![screenshot 2018-08-03 14 53 30](https://user-images.githubusercontent.com/31435476/43628501-02e0a500-972d-11e8-963d-fd172fea3a21.png)

What should I do for the Unreal engine so that this program can properly connect to the Unreal engine?

**Comment by daggertye** [comment]
It's broken or at least needs to be fixed. I will be looking to fix this soon.

**Comment by davidhopper2003** [comment]
@daggertye Looking forward to your improvement.

**Comment by daggertye** [comment]
Looking more into it, it definitely still requires the engine2learn plugin in order to run. The only way I could find to install this would be to install it manually from a separate branch. 

https://github.com/ducandu/MaRLEnE/tree/builder

However, it still requires a lot of setup to use.

**Comment by AlexKuhnle** [comment]
Outdated
