### ISSUE TITLE
Please add support for a new simulator `CARLA`

### ISSUE THREAD

**Issue by davidhopper2003** [tensorforce/tensorforce#476]
First of all, I'd like to highly appreciate contributions of  all `tensorforce`'s developers for providing us with a powerful deep reinforcement learning framework. This framework is really awesome. With this framework, the difficulty of implementing deep reinforcement learning theory is greatly reduced. 

[`CARLA`](https://github.com/carla-simulator/carla) is an open-source simulator which can support development, training, and validation of autonomous urban driving systems. The simulation platform supports flexible specification of sensor suites and environmental conditions.

In my opinion, it is very helpful for improving the reputation of `tensorforce` if the support for `CARLA` is provided. Please consider my suggestion carefully. 

Thank you once more.

**Comment by AlexKuhnle** [comment]
Thanks, glad you like the framework! Would you consider [contributing](https://github.com/reinforceio/tensorforce/tree/master/tensorforce/contrib) an environment implementation for CARLA (particularly if you look into that anyway)? I won't have the time (nor resources probably) to look into that, so we rely on contribution here.

**Comment by davidhopper2003** [comment]
@AlexKuhnle

**Comment by AlexKuhnle** [comment]
Outdated
