### ISSUE TITLE
Documentation omitting bullet points

### ISSUE THREAD

**Issue by phuicy** [tensorforce/tensorforce#484]
https://tensorforce.readthedocs.io/en/latest/tensorforce/tensorforce.agents.html#module-tensorforce.agents.agent

https://github.com/reinforceio/tensorforce/blob/master/tensorforce/agents/agent.py

Documentation omitting bullet points

**Comment by AlexKuhnle** [comment]
Would you mind creating a PR adding the missing bullet points?

**Comment by phuicy** [comment]
I think it is an issue with your formatting engine.

**Comment by AlexKuhnle** [comment]
Hmm, in that case if you know how to resolve it, a PR would be great. I've never looked into that.

**Comment by phuicy** [comment]
Something like this: https://github.com/phuicy/tensorforce/blob/master/tensorforce/agents/agent.py#L47

**Comment by AlexKuhnle** [comment]
Improved
