### ISSUE TITLE
Create pb file

### ISSUE THREAD

**Issue by SestoAle** [tensorforce/tensorforce#499]
Hi,

I'm a newbie with tensorforce and tensorflow. I need a pb file to export my trained model but when i use agent.save model i get only 4 files: .data, .index, .meta and a file named checkpoint with no extension. How can i get the pb file from these?

**Comment by AlexKuhnle** [comment]
I'm not sure, best to look up how the `tf.train.Saver` functionality relates to pb files, or how alternatively one can store a TensorFlow model as pb instead of the `Saver` format. Won't be able to look into this, but let us know if you found a solution.

**Comment by SestoAle** [comment]
I found some methods to convert the files saved by tensorforce to a pb file but i need the name of the output node, how can i get it?

**Comment by AlexKuhnle** [comment]
Would you mind sharing, for the sake of completeness (if someone else comes across this issue)?

Two ways to get the name of the output node: First, use summaries to store the graph and then investigate in TensorBoard (might be quite messy, there are lots of operations). Second, use `print(...)` statements to get the name in code, e.g. the fetched tensors [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L1394). While it's quite straightforward to get the name, I can't exactly remember the name-scopes etc, so one of these solutions is probably easiest.

**Comment by wil3** [comment]
My research involves embedding trained neural networks into hardware so I'll add my approach for anyone trying to achieve the same thing. I am exploring the possibility of migrating from OpenAI baselines to Tensorforce given the many difficulties in extending the OpenAI code base.

There are a few approaches to obtain the pb file. If you can modify the code  as @AlexKuhnle mentioned adding a print statement will get you the tensor name probably the quickest. I added mine right after [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L1446).

Another approach is to analyze your checkpoint file and or Tensorboard. If you have a checkpoint you can use this [script](https://gist.github.com/wil3/38b9ff40c6012a229f711944b1e2e170) to convert the checkpoint to a pb file. Now however this will be the _entire_ graph which you most likely do not want. You only want the trained network. Once you have the full pb graph you can use Tensorflows summarize_graph tool which will identify all the possible input and output nodes. For my example (I am using this [network](https://github.com/reinforceio/tensorforce/blob/master/examples/configs/mlp2_network.json) with this [agent](https://github.com/reinforceio/tensorforce/blob/master/examples/configs/ppo.json)) the input node was ppo/state-state which is easy to cross reference with Tensorboard. The output node is more difficult as there are hundreds. Depending on your network your output will typically be the mean of a distribution if deterministic or a sample. Knowing this we have an idea where the output code will be, in my case for PPO using the [beta distribution](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/distributions/beta.py#L81). As we can see in the return a condition operation is used to return whether it is deterministic or not. In the image below we can see the corresponding Tensorboard translation. The select node selects the output depending on the condition (which ends up being the ppo/deterministic placeholder). The output (also confirmed by the print statement) is ppo/actions-and-internals/action/sample/add_1:0 (please correct me if I'm wrong, I did test it and it appears to be correct). Now that we have our input and output nodes we can use another tool, [freeze_graph](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) to convert all placeholders to constants and prepare our graph for deployment. Freezing the graph will extract the subgraph so you can minimize the file size. 

Now unfortunately with Tensorforce this isn't that straight forward (if we want to optimize the graph as small as possible). As we can see from Tensorboard, there are additional operations that depend on the output of the Select operation. Therefore we can't simply specify the node before the Select statement as the output node. Our goal for deployment is to have a deterministic graph and we want to remove all the unnecessary sampling operations. Currently this isn't possible without additional postprocessing, you need to use the graph containing the non-deterministic operations and use the additional input ppo/deterministic set to true to force the deterministic output. 

There are two fixes for this. Do this post processing using Tensorflows graph transforms to rewire the graph, or modify the distribution code so its possible to specify an output node that has the deterministic value (this is probably less of a pain and less error prone, rewiring graphs can be dangerous). Hope this gets you in the right direction.

![tensorboard](https://user-images.githubusercontent.com/4587660/48212492-b397fc00-e349-11e8-9662-5af45b342135.png)

**Comment by AlexKuhnle** [comment]
I think I've been looking into similar things, how to best extract the right subgraphs from TensorFlow architectures -- after all, this is one of the main motivations for TensorForce's full-tf design ([blogpost](https://reinforce.io/blog/end-to-end-computation-graphs-for-reinforcement-learning/)). If you're keen discussing / potentially collaborating on such a feature for TensorForce in general, that would be very welcome, best message me on Gitter then. :-)

**Comment by wil3** [comment]
Hi @AlexKuhnle, having flexible network architectures and the beta distribution led me here, I'm currently doing some benchmarks right now. If I end up migrating over to Tensorforce I will certainly hit you up to collaborate on this.
