### ISSUE TITLE
load .h5 model file for training

### ISSUE THREAD

**Issue by richa-verma** [tensorforce/tensorforce#500]
How can I load a pre-trained .h5 model (say a CNN) and start training from there? I understand that loading from a checkpoint is possible but how can I use Tensorforce to load a pre-trained model and then begin training again using a Tensorforce agent?

**Comment by Deathn0t** [comment]
I am not sure but maybe it can help, look at the part about how to integrate new layers and custom networks : https://reinforce.io/blog/introduction-to-tensorforce/

**Comment by AlexKuhnle** [comment]
The variable initialization would have to happen [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L682), or similar. There could be a special argument `load_h5` in the `saver` argument which, if given, initializes the variables accordingly, a bit like [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L663) for global/local model sync. If you look into it, a PR would be welcome and I'm happy to help where I can, but won't be able to implement it myself.

**Comment by AlexKuhnle** [comment]
Added to roadmap
