### ISSUE TITLE
Testing a trained model

### ISSUE THREAD

**Issue by clemensmb** [tensorforce/tensorforce#519]
Hi,
is there a straightforward way to test a model by restoring it and using the runner? I have already tried it's flag 'testing', but the results seem to deviate from the optimal training results.

**Comment by AlexKuhnle** [comment]
Did you specify the saver argument accordingly and check whether something is restored? Also, by how far do they deviate, complete random or good but not on par with training performance?

**Comment by clemensmb** [comment]
The performance seems to be bad but not random.
I restore the model and start the runner with testing=True. The runner then continues with time step x+1, where x is the maximum number of episodes of the training session and repeats.
I would like to establish a test configuration, that runs for example 1000 tests by evaluating the trained model.

**Comment by AlexKuhnle** [comment]
Hmm, that's unexpected. I don't know why this happens, but can have a look at the runner class etc later. Just to check: You're on the most recent GitHub version (not pip)?

**Comment by clemensmb** [comment]
Yes, I'm in the most recent. Thank you for your help!

**Comment by AlexKuhnle** [comment]
This should work now.
