### ISSUE TITLE
DDPG - very rare convergence

### ISSUE THREAD

**Issue by Jonathan-Livingston-Seagull** [tensorforce/tensorforce#523]
I have been experimenting DDPG against the inverted pendulam problem and noticed that, it converges very very rarely. PPO and my local implementation of ddpg  converge almost all the time for the same problem. I have had a look at the implementation of DDPG and it looks ok.

 [Tensorforce ddpg experiment gist can be found here ](https://gist.github.com/Jonathan-Livingston-Seagull/a970034a0b5ec754ae855d779f6d31a4) and [my local implementation can be found here](https://github.com/Jonathan-Livingston-Seagull/DDPG)

**Comment by AlexKuhnle** [comment]
Outdated, but the plan generally is to add more benchmarks, so contributions/collaborations welcome.
