### ISSUE TITLE
Is the DeepMind Lab API Deprecated

### ISSUE THREAD

**Issue by ryanprinster** [tensorforce/tensorforce#530]
Is the DeepMind Lab API deprecated? When, if at all, will it be updated?

I noticed the comment in `deepmind_lab.py` that says `TODO this has not been tested since 0.3 - potentially deprecated API`.

When I follow the instructions in `deepmind_lab.py` and run `bazel run //tensorforce:lab_runner`, I hit basic python errors, and after fixing those I hit things like `TypeError: __init__() got an unexpected keyword argument 'update_mode'`.

**Comment by AlexKuhnle** [comment]
I can have a look at the `update_mode` problem, and it would be great if you could commit the fixes you had to made.

**Comment by AlexKuhnle** [comment]
PR on this welcome, otherwise likely won't happen anytime soon.
