### ISSUE TITLE
Can't run quickstart example after installing Tensorforce with pip

### ISSUE THREAD

**Issue by greggaree** [tensorforce/tensorforce#532]
Command for quickstart example tries to invoke openai_gym from examples directory, but there is no examples directory under the Tensorforce directory. 

Python 3.6.6 on Ubuntu Mate 18.04
Tensorforce 0.4.3
Tensorflow 1.12.0

**Comment by AlexKuhnle** [comment]
I'm not sure what exactly you mean. You execute the `examples/quickstart.py` script, and it tries to invoke `openay_gym` from the `examples/` directory? I don't see a mention of `examples/` in `quickstart.py`. Or are you in the `examples/` directory when executing `quickstart.py`? This may not work (at least unless you installed Tensorforce), try instead to run it from the parent directory: `python examples/quickstart.py`.

**Comment by greggaree** [comment]
The quickstart example is on the TensorForce GitHub home page:

> **Examples and documentation**
> 
> For a quick start, you can run one of our example scripts using the provided configurations, e.g. to run the TRPO agent on CartPole, execute from the examples folder:
> 
> python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json


When pip installs TensorForce, it does not install an examples directory under the TensorForce directory. Therefore, when you  invoke examples/openai_gym.py ..., python tells you it cannot find the file.

**Comment by AlexKuhnle** [comment]
Oh, I see... Needs to be fixed, yes.

**Comment by AlexKuhnle** [comment]
Outdated
