### ISSUE TITLE
Reward Network

### ISSUE THREAD

**Issue by guytenn** [tensorforce/tensorforce#534]
This is more of a question.
My reward function is a GaN network that is trained during the training epochs of the agent. How can I integrate this network into tensorforce? You build your graph in model.py, but is it possible to add my reward network without changing the class?

**Comment by AlexKuhnle** [comment]
Currently this is unfortunately not possible without changing the code. While I expect the reward estimation to develop in the near future, it may take a while to support such a general setup. It's probably easiest for now to do the reward estimation "outside of Tensorforce", if that's possible. Nonetheless, just to check: i would guess that the reward produces the reward internally based on the state values as input, or something like that? That's at least a type of reward estimation I would like to work towards for Tensorforce...

**Comment by guytenn** [comment]
Thank you for your reply.
Yes, the reward function is based on the state of the environment and is also trained together with the agent.

**Comment by AlexKuhnle** [comment]
Okay, I expect that this feature will exist for Tensorforce in the longer run, but it's currently not possible without some non-trivial code changes. I could give you some ideas about how to achieve it, but it may be easiest to just handle it as an external "reward preprocessing" step... what do you think?
