### ISSUE TITLE
LSTM using PPO gives "Cannot use '.../Identity' as input to '.../Identity_4' because they are in different while loops"

### ISSUE THREAD

**Issue by 80dB** [tensorforce/tensorforce#539]
I'm trying to get a simple LSTM network running with the PPO agent.

I've successfully managed to get it running with conv1d and dense layers. But as soon as I specify a LSTM layer I get:

> ValueError: Cannot use 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/Add_1/Identity' as input to 'ppo/observe-timestep/cond/optimization/multi-step/step/while/Identity_4' because they are in different while loops. See info log for more details.

The network is rather simple:
```python
network_spec = [
    dict(type='lstm', size=256, dropout=0.1, return_final_state=False),
    dict(type='lstm', size=64, dropout=0.1, return_final_state=True),
    dict(type='dense', size=32, activation='tanh')
]
```

And the agent is left completely default:
```python
agent = PPOAgent(
    states=env.states,
    actions=env.actions,
    network=network_spec,
)
```

Is it something I'm doing wrong?

Using latest Tensorflow (1.12) and 0.43 of tensorforce.

**Comment by AlexKuhnle** [comment]
Hey, no, this is a problem with Tensorforce (related to TensorFlow). For a quick fix, you could try unrolling the loop (`unroll_loop=True` [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/optimizers/multi_step.py#L32)). Otherwise, I hope that the restructuring I'm currently working on (see branch) will fix this problem. It's unfortunately quite a fundamental mismatch in variable handling, but I hope it will work eventually -- in fact, it may already work, but the branch is still under construction, so not sure whether you want to already try it.

**Comment by 80dB** [comment]
I've tried the new branch didn't get very far. Errors in restoring a model and errors while training/testing (didn't find "act" in model or some error). But I'll try later.

**Comment by AlexKuhnle** [comment]
Oh yes, restoring old models won't work with the new branch, unfortunately, too many changes. Restoring in general I haven't tested yet, definitely still (pre-)alpha version, so otherwise worth just waiting if other solutions don't help.

**Comment by 80dB** [comment]
Well I wasn't getting very far, granted I didn't have a lot of time to look at it. I'll see if I can help a bit, can't help much with the tensorflow yet, I've mostly been playing with Keras, just a little easier ;)  But I can probably help with the generic python code.

**Comment by AlexKuhnle** [comment]
(Did you try the `unroll_loop` argument?)

**Comment by 80dB** [comment]
> unroll_loop

Yes, it worked. Performance really seemed to decrease though. Also had to change it in ppo_agent.py since I wasn't able to change the settings of the optimizer otherwise. Eventually I got the  "Retval[0] does not have value" error though (after a few episodes).

**Comment by AlexKuhnle** [comment]
Hmm, I'm not sure what could go wrong there. Hope we can soon try it with the new version, and hope even more that the problem goes... :-)

**Comment by 80dB** [comment]
A heads up, at the moment it doesn't work yet. 
(had a small hope that the lstm fixes would have fixed this)

**Comment by AlexKuhnle** [comment]
Is it the exact same error message as you reported above? I know that for multi-state/action environments, PPO annoyingly still doesn't work for some reason (all other agents except TRPO do, by the way).

**Comment by 80dB** [comment]
Same error, small test case:
(Note, I didn't perform the unroll_loop modification as it requires editing the ppo agent code)

```python
import numpy as np

class TestEnv():
    def reset(self):
        return self.get_state()

    def get_state(self):
        return np.zeros((112,5))

    def execute(self, actions):
        return self.get_state(), False, 0

def main():
    network_spec = [
        dict(type='lstm', size=256),
        dict(type='internal_lstm', size=256)
    ]

    agent_spec = dict(
        type="ppo",
        discount=0.999
    )

    from tensorforce.agents import Agent
    agent = Agent.from_spec(
        spec=agent_spec,
        states=dict(type='float', shape=[112,5]),
        actions=dict(type='int', shape=(), num_values=2),
        network=network_spec
    )

    from tensorforce.execution import Runner
    runner = Runner(agent, TestEnv())
    runner.run(num_episodes=1000)

if __name__ == "__main__":
    main()
```

**Comment by AlexKuhnle** [comment]
Will try it out.

**Comment by AlexKuhnle** [comment]
I made some progress on that, and as a by-product fixed TRPO (using an unofficial new `while_loop` [implementation](https://github.com/tensorflow/tensorflow/issues/24866)). However, unfortunately I didn't manage to get PPO + LSTM to work, since this version of the loop causes other problems in combination with Adam (so that PPO in general fails). May have another go at some point, but may also be that we have to wait for TensorFlow 2.0 for that. :-/

**Comment by AlexKuhnle** [comment]
Think I managed to solve the problem if you update to the (not yet official) TensorFlow 1.13 version via `pip install --upgrade tensorflow==1.13.0rc0`. Let me know if not...
