### ISSUE TITLE
example A3C-Gym/train-atari errors

### ISSUE THREAD

**Issue by jheffez** [tensorforce/tensorforce#541]
Getting the following on a CUDA/GPU machine as well as on colab (with gpu).
`WRN User-provided custom session config may not work due to TF bugs. See h
ttps://github.com/tensorpack/tensorpack/issues/497 for workarounds.
Traceback (most recent call last):
  File "./train-atari.py", line 303, in <module>
    train()
  File "./train-atari.py", line 262, in train
    trainer = SimpleTrainer() if config.nr_tower == 1 else AsyncMultiGPUTrainer(train_tower)
AttributeError: 'TrainConfig' object has no attribute 'nr_tower'`

 Tried adding the two lines as suggested in the forum but no change.
`    gpu_options = tf.GPUOptions(allow_growth=True) #jh
    sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)) #jh
`

Also, is there a way to run this on non-gpu/google TPU?

**Comment by AlexKuhnle** [comment]
Is this related to Tensorforce? The exception code doesn't look like Tensorforce...
