### ISSUE TITLE
Cannot make OpenAIGym environments from gym.Env objects

### ISSUE THREAD

**Issue by nathanhjay** [tensorforce/tensorforce#543]
OpenAIGym objects can only be built from the gym name. Being able to build from a `gym.Env` instance would make it easier to use custom environments. It looks to me like the only thing happening in the code for the `OpenAiGym.__init__(...)` is one call to `gym.make()` and there's a printout of the environment name elsewhere. Would it be possible to detect if the `gym_id` input is a string vs an instance of `gym.Env` and accept either?

**Comment by AlexKuhnle** [comment]
Sounds doable, would you mind testing this and creating a PR, if you have a custom Gym environment at hand?

**Comment by AlexKuhnle** [comment]
Works now.
