### ISSUE TITLE
NAF unconstrained action space

### ISSUE THREAD

**Issue by giorgionicola** [tensorforce/tensorforce#545]
Hi I am trying to use NAF for robotic arm control of a custom robot (http://www.mujoco.org/forum/index.php?resources/universal-robots-ur5-robotiq-s-model-3-finger-gripper.22/). The following appears:

`tensorforce.exception.TensorForceError: Only unconstrained float actions valid for NAFModel.`

Is there a method to use constrained actions, since in the real world joints torque are limited?
For the moment I have set unlimited joints torque in the model of the robot, although `tensorforce.contrib.openai_gym.action_from_space` return me an action space like this:
`{'max_value': 0.0, 'min_value': 0.0, 'type': 'float', 'shape': (6,)}`

for the moment I have solved it by modifying the code at line 165 as following:

```
        elif isinstance(space, gym.spaces.Box):
            if (space.low == space.low[0]).all() and (space.high == space.high[0]).all():
                
                if space.low[0]==space.high[0]:
                    return dict(type='float', shape=space.low.shape)    #####################
                else:                                                   #####################
                    return dict(type='float', shape=space.low.shape,
                                min_value=np.float32(space.low[0]),
                                max_value=np.float32(space.high[0]))
```

Probably it exists a smarter way but for now seems to work

**Comment by AlexKuhnle** [comment]
Hi, I think your solution is fine, but note that the model obviously won't know about the min/max constraints then. However, I have no strong evidence suggesting that learning won't work (as long as it doesn't clash with strict requirements of the environment). You can alternatively use a policy gradient model like PPO, which can handle all action types. Bounded continuous actions are internally parametrized by a Beta as opposed to a Gaussian distribution, that's the difference.

**Comment by AlexKuhnle** [comment]
Improved
