### ISSUE TITLE
How to write a custom Environment for tensorforce?  Cant find examples. Please provide one

### ISSUE THREAD

**Issue by arunavo4** [tensorforce/tensorforce#546]

**Comment by AlexKuhnle** [comment]
Hi,

First, you can find example environments [here](https://github.com/tensorforce/tensorforce/tree/master/tensorforce/contrib), in particular `openai_gym.py` is worth looking at.

Second, your environment looks about right. From a first look, what is missing / needs changing is the following:
- `step(self, act)` needs to be `execute(self, action)`.
- `@property def states(self)` and `def actions(self)` need to be defined, which here seem to be:

```python
@property
def states(self):
    return dict(type='float', shape=self.history_t)

@property
def actions(self):
    return dict(type='int', shape=())
```

Hope that helps!

**Comment by AlexKuhnle** [comment]
Closing this, reopen or just post here if not.
