### ISSUE TITLE
major-revision branch restore_model issue

### ISSUE THREAD

**Issue by 80dB** [tensorforce/tensorforce#547]
I'm not sure if you want major-revision branch issues?  If you don't feel free to close.

If you do, feel free to read:
When creating an agent and then calling "restore_model" will generate an "AttributeError: 'QModel' object has no attribute 'saver'". This is due to initialize not being called before calling restore_model (initialize calls model.setup()).

In previous versions, the initialize function was called from the agent constructor, now it is called in the Runner.__init__ instead.

I'm wondering if this is correct behavior. Sure I can call initialize first, or create a runner first. But I can't seem to find a check that stops re-initializing of the model.   

I would think that double initialize would cause the model to be initialized twice and result in a "reset" of the model. If that's the case then creating a Runner will have a large undocumented (imho unwanted) side effect.

Possible solutions would be adding a check on initialize/model.setup that stops it from double initializing. Or have a "is_initialized" property and let the caller determine if he/she wants to reinitialize (and possibly let runner throw a "not initialized" error).  Having the is_initialized flag helps in various instances where you try to use the agent before initializing.

**Comment by AlexKuhnle** [comment]
Hey @80dB,

Yes, branch issues are also welcome, in particular if it's not obviously just about a not-yet-working feature. You're right, an `is_initialized` flag makes sense here, to prevent initializing twice (which is likely to break the code right now, I would expect). I don't think re-initialization is actually desirable, as it's better/clearer to just properly instantiate a new agent then. Also, I realize that saving and loading hasn't been tested yet, but I can also look into that next, and probably add a simple unittest.

**Comment by AlexKuhnle** [comment]
I think the latest commit should address all these points, can you verify (and let me know otherwise)? Also, maybe wanna have a look at `tensorforce/tests/test_saving.py` which covers different save/restore situations. Closing this for now.
