### ISSUE TITLE
example use remote environment

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#548]
@sven1977 do you have a working example of how one should use your remote environment?

**Comment by jerabaul29** [comment]
@AlexKuhnle @MiroK I was thinking about implementing the following as a general way to easily send an environment to a remote socket. Basically, I want to always write non socketed environments, but be able to send them very easily to a socket.

- on the server side (the side running the environment): a **RemoteEnvironmentServer(Environment)** class that wraps a 'normal' environment but sockets the communications.

- on the client side (the side given to the Runner): a templated **RemoteEnvironmentClient(Environment)** that only features the socketing for communication to the **RemoteEnvironment**.

Any comments? Am I missing something?

**Comment by AlexKuhnle** [comment]
Sounds good, that's how I would go about it.

**Comment by jerabaul29** [comment]
Good.
