### ISSUE TITLE
Maze Explorer example doesn't work

### ISSUE THREAD

**Issue by Jet132** [tensorforce/tensorforce#550]
Hi, I was just trying the maze explorer example out and it seems that something isn't working on your side.
Here is the traceback it seems that mazeexp is missing:
```
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    from tensorforce.contrib.maze_explorer import MazeExplorer
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorforce\contrib\maze_explorer.py", line 21, in <module>
    import mazeexp as mx
ModuleNotFoundError: No module named 'mazeexp'
```
I installed tensorforce through pypi.

**Comment by AlexKuhnle** [comment]
Hi @Jet132,
have you installed the [MazeExplorer library](https://github.com/mryellow/maze_explorer)?

**Comment by Jet132** [comment]
@AlexKuhnle Thanks for the fast answer. I didn't have the lib installed, but now it doesn't give that error anymore. Could you also please tell me what parameters I need to input?
It would be nice if the required parameters were in a comment block like in the 2048 example.

Thanks in advanced.

**Comment by Jet132** [comment]
OK, thanks! I'm going to try it out.
