### ISSUE TITLE
how saving model is done

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#551]
@AlexKuhnle if I understand well this:

https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/execution/parallel_runner.py#L116

means that if the *save_frequency* is set but not the *save_directory*, bad things will happen? Is that a bit error prone? Should there be some reasonable default *save_directory* set at this point if still none? Or is it done in the saving function?

**Comment by AlexKuhnle** [comment]
Hmm, good point, while filename defaults to "model", there is no default directory unless given via `saver`. Actually, I forgot about this before, and would rather remove it entirely, as the `saver` argument of `Agent`/`Model` is the preferred way of periodically saving the agent...

**Comment by jerabaul29** [comment]
Ok. I do not use these features now, was just browsing the code. Maybe you can fix a bit this and choose the best solution, and then we will use it in later codes writeups from scratch? ;)

**Comment by AlexKuhnle** [comment]
Yes, will do.

**Comment by AlexKuhnle** [comment]
Latest commit should improve this. For periodic saving, now configure the `saver` argument: `saver=dict(directory='[YOURDIR]')`.

**Comment by AlexKuhnle** [comment]
I would rather look [here](https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/agents/ppo_agent.py#L34). ;-)  It's a general argument of the agent, and [here](https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/tests/test_saving.py) the corresponding test illustrating some configurations.
