### ISSUE TITLE
major-revision branch - Two small issues with Runner

### ISSUE THREAD

**Issue by 80dB** [tensorforce/tensorforce#552]
Just some small issues:

- When setting evaluation_frequency to 10, it will actually execute after the 9th train episode rather then the 10th (I expected it to run after the 10th). Due to self.episode being incremented after running a train episode, and it checks if it needs to run an eval before it runs the train episode. global_episode is still at 9, but the "internal" episode is at 10.
- num_episodes is checked on global_episode and not episode. As such, multiple calls to run means you need to increment the num_episodes parameter everytime

Not really an issue, more a wishes?
- Since the refactor of episode_finished into callback and evaluation_callback, it's required to have different callbacks as there's no way to otherwise know it its an train/eval run. Maybe add a parameter to the callback?
- The eval-environment was a nice addition, but I do miss the option to perform an eval-run (e.g. testing+deterministic) without performing training run(s)

**Comment by AlexKuhnle** [comment]
The latest commit should address the first issue. And I'm not sure about the first wish, what is more desirable here?

You're right about the other two points -- I expect the runner utilities to still change a bit, for instance, probaby replace `Runner.run()` with `Runner.train()` and have an additional `Runner.evaluate()` option. Feel free to post further feedback.

**Comment by 80dB** [comment]
The first wish becomes a non-issue if training/evaluating is split. The "problem" is that "callback" is for training episodes, "evaluation_callback" is for evaluation episodes. But in my usecase they basically do the same except for 1 small difference (if the evaluation is of a certain level, I save it). 

So basically I end up with "episode_finished(runner): print_stats(runner, runner.environment)" and "eval_episode_finished(runner): print_stats(runner, runner.eval_env)".   Anyhow no biggy, lets not worry about this now ;)  There's bigger fish to fry (*cough* exploration *cough*  ;)

**Comment by AlexKuhnle** [comment]
Any problems with exploration? I earlier wrote about it in Gitter, if you haven't seen yet.

**Comment by AlexKuhnle** [comment]
Closing this now.
