### ISSUE TITLE
allow deterministic evaluation during training to benchmark performance

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#553]
Would it be possible to get a flag to have the ```runner``` to perform one deterministic evaluation (no exploration noise, i.e. ```agent.act()```) each time a network update has been performed? (idea would be that this gives maybe a better idea of what happens, for looking at the convergence curves).

**Comment by jerabaul29** [comment]
(possibly could be not only a flag but a None or value, so that the deterministic evaluation can be chosen to take place only once in a while if wanted).

**Comment by jerabaul29** [comment]
Just brainstorming, but a possibility would be to give a dict otherwise, so that one can set how often updated, and if the env is very stochastic, also how many deterministic evaluations to use to compute the reward statistics?

**Comment by jerabaul29** [comment]
Ok! Is not update happening at a given ```frequency```? Something like ```epoch % frequency == 0```? Or am I missing something? ;)

**Comment by jerabaul29** [comment]
I see, problem when not episode-based. What about just choosing arbitrarily when should be done?

**Comment by AlexKuhnle** [comment]
For episode-based updates it would of course be possible to just read out the update details and use them, for sure. Timestep-based updates are messier, particularly in combination with buffering. Anyway, let's see...  using the information from update_mode is actually a quick-to-implement idea...

**Comment by jerabaul29** [comment]
I ask this because we had observed on one of the dynamic systems some very strange effects, where the strategy works during training but not in deterministic mode. This is because the system had a strong frequency response for a forcing of let us say f1, and actuation was done at 10 * f1. Therefore, there was some sort of random forcing at f1 taking place. Weird, but we observed it reliably.

**Comment by AlexKuhnle** [comment]
I'll add a comment. Basically, it approximates the maximum number of episodes for an update to happen: timestep-frequency / max-timesteps-per-episode.

**Comment by AlexKuhnle** [comment]
Not great, but I assume this feature can be improved in general by actually retrieving frmo the model whether an update has happened.

**Comment by AlexKuhnle** [comment]
Evaluation supported by runner, and observe returns boolean indicating whether an update happened.
