### ISSUE TITLE
saver: save both model and best model so far

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#554]
Sometimes during training performance gets good and then later collapses. Can we get a flag on the ```runner``` or else (maybe the saver?) to maintain a dump of the best model encountered so far, based on performance evaluation with or without the deterministic evaluation (see issue https://github.com/tensorforce/tensorforce/issues/553 )

**Comment by AlexKuhnle** [comment]
Yes, that should be possible and makes sense (although ideally I'd like to eliminate performance collapses, of course :-).

**Comment by jerabaul29** [comment]
Perfect!

Agreed, but sometimes I am afraid it is the nature of ANNs to get 'randomly' unstable?

**Comment by AlexKuhnle** [comment]
Yes, but this is the case for RL much more than for other ANN applications, afaik. Would be great to improve that aspect of RL... but first things first... :-)

**Comment by AlexKuhnle** [comment]
I quickly added a `save_best_agent` parameter, assuming the `evaluation_callback` returns a float (greater is better) or by default using the mean reward of the evaluation runs. Can you check whether it does what you had in mind?

**Comment by jerabaul29** [comment]
That looks good :)

**Comment by AlexKuhnle** [comment]
Closing this then.
