### ISSUE TITLE
callbacks as list of functions

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#557]
Would it be possible for the callback:

https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/execution/parallel_runner.py#L69

To become a list? This may make the code more modular?

**Comment by AlexKuhnle** [comment]
Have a look at the latest commit, where lists of callbacks are allowed and sequentially executed -- is that what you have in mind?

**Comment by jerabaul29** [comment]
Yes, excellent!
