### ISSUE TITLE
list of projects / repos / blogs / publications that use tensorforce

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#560]
Maybe either in a separate file or in the readme, it would be nice to have a list of projects / repos / blog posts / publications that use tensorforce. This may help:

- create interest in the project for people quickly browsing the repo why looking for a DRL framework.
- help newcomers because those links will feature discussions on how to use / examples / discussions of pitfalls etc.
- be a nice boost for the authors if they need to show some achievements of their library one day.

**Comment by AlexKuhnle** [comment]
Yes, I think that's a very good idea, I actually also thought to include such a list with the next bigger update. Whoever comes across this issue and wants to be mentioned in the list, feel free to post here or write in Gitter. I will probably also reach out to some projects soon...

**Comment by AlexKuhnle** [comment]
Added now
