### ISSUE TITLE
[Question] model/parameters optimization?

### ISSUE THREAD

**Issue by jheffez** [tensorforce/tensorforce#562]
Is there a way, or AutoML tool like Adanet/mcfly, that we can use to optimize model/parameters?

**Comment by AlexKuhnle** [comment]
Hi @jheffez,
There is no script for hyperparameter tuning currently, but it shouldn't be too problematic to write one, as all hyperparameters are chosen when initializing the agent. Also happy to accept PRs for a tuning script (and of course to answer questions for its development).
Any specific reason why it may be problematic?
(Closing this for now.)
