### ISSUE TITLE
models/model.py create_atomic_observe_operations() is using buffers?

### ISSUE THREAD

**Issue by dwang9302** [tensorforce/tensorforce#566]
It seems `models/model.py create_atomic_observe_operations()` line 1223-1230 is using buffers instead of states, actions passed in? although the comment on line 1226 states ` # Not using buffers here.`

**Comment by AlexKuhnle** [comment]
That's weird indeed... :-)  The code looks generally wrong, I will fix it. Why do you want to use `atomic_observe`, if I may ask?

**Comment by AlexKuhnle** [comment]
Committed a (hopefully) correction.

**Comment by dwang9302** [comment]
I am using `atomic_observe` because it seems 'observe' directly associates the rewards, terminal with last executed actions, and I want to modify that... so that I could customize what an observation looks like. 
(also I think `atomic_observe` is used in `ThreadedRunner` too...)

**Comment by AlexKuhnle** [comment]
Improved
