### ISSUE TITLE
TensorForce Actions-Exploration

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#568]
Hi. I'm new to Reinforcement learning and I have a question regarding a parameter in tensorforce agents. What exactly does the actions exploration parameter do? You see, my agent will only move one time only, and then won't really move a whole lot more... So, what can I do to basically try to force it to move?

**Comment by AlexKuhnle** [comment]
Hi @ZeroMaxinumXZ ,

Action exploration randomizes the actions an agent takes (more precisely, for discrete actions the parameter gives the probability for a random action, for continuous actions the parameter gives the stddev of Gaussian noise added to every action).

Importantly, your reward function should ideally make it desirable for the agent to move, by punishing non-movement and/or give partial rewards for small "goals" in case the agent is unlikely to ever reach rewards by chance.

**Comment by ZeroMaxinumXZ** [comment]
Okay, thanks for explaining that... I'm wanting my agent to be curious, so how should I go about doing this? I could crea5te

**Comment by ZeroMaxinumXZ** [comment]
start.py 	v1.0.2 	an hour ago

**Comment by ZeroMaxinumXZ** [comment]
close.
