### ISSUE TITLE
Rewarding knowledge...

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#569]
Sorry if I sound like an idiot, but how should I create an agent that's curious and wants to explore it's environment instead of simply "aiming" for an reward... Letting the reward be to know more would work, but then again, what is knowledge in an agent? Do the default DQN or PPO tensorforce agents have something like knowledge of all previous states, and how should I use it as a reward? Do I have to create my own agent to do this?

 I know there's a memories file thing in tensorforce.core, but I don't know how to use it, let alone use it as a reward...

**Comment by AlexKuhnle** [comment]
Hi, there is currently only rather simple exploration mechanisms, which encourage some degree of randomness in the decisions, but not (yet) any curiosity-driven approaches. You can of course modify rewards on the environment side to encourage certain things, but of course that is not quite the same. Extending models with this type of curiosity is of course possible, but I would only recommend attempting that if you feel like you have good knowledge of Tensorforce's internal functioning.

**Comment by ZeroMaxinumXZ** [comment]
Are there any resources you could recommend for me to help me build what I want to do?

**Comment by ZeroMaxinumXZ** [comment]
Accidentally closed this... Reopening...

**Comment by AlexKuhnle** [comment]
I haven't yet read up on the various approaches around, but there are definitely quite a few papers recently. When googling I find [this article](https://towardsdatascience.com/curiosity-in-deep-reinforcement-learning-understanding-random-network-distillation-747b322e2403), for instance, which may be a good starting point. I may look into it as well, if it's only a smaller change, I can potentially implement such a feature in the near future, but as said, have to get a good idea myself about what people did recently.

**Comment by ZeroMaxinumXZ** [comment]
Okay, thanks for the help. I'm closing this now...

**Comment by ZeroMaxinumXZ** [comment]
I've read some parts of this paper... https://pathak22.github.io/noreward-rl/resources/icml17.pdf...

Is there anything in a Tensorforce agent that can predict the next state based on an existing state and actions?

**Comment by ZeroMaxinumXZ** [comment]
Nevermind...
