### ISSUE TITLE
Does tensorforce's action exploration randomness decrease over time?

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#571]
Does the noise decrease over time in Tensorforce's action_exploration? Also, can I set the amount of noise manually?

**Comment by AlexKuhnle** [comment]
Hi @ZeroMaxinumXZ,
The noise decreases over time if configured accordingly, using one of the available decay mechanisms ([here](https://github.com/tensorforce/tensorforce/tree/master/tensorforce/core/explorations)). On the `major-revision` branch, there are similar decay mechanisms available, and additionally the possibility to set the noise manually (which is not possible on the `master` branch currently).

**Comment by ZeroMaxinumXZ** [comment]
Thanks for your quick response. Closing this now.
