### ISSUE TITLE
Can I add my own activation function to my agent?

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#574]
Can I add my own activation function to a Tensorforce agent? If so how do I do it?

**Comment by AlexKuhnle** [comment]
There is a [unittest](https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/tests/test_specifications.py) on the revision branch which illustrates various ways of configuring a module, at the example of the network argument. For instance, passing the class as type like [here](https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/tests/test_specifications.py#L71) could work for you. It should work the same on the master branch, and should work more or less wherever a module is specified that way (`type=???, ...`).

**Comment by ZeroMaxinumXZ** [comment]
I'm now pretty confused... But I took a look into your code, and saw that I couldn't create my own activation function for a network in Tensorforce, I'd like to see that functionality in Tensorforce...

**Comment by AlexKuhnle** [comment]
My answer wasn't meant to confuse. :-)  What I meant is that it should work to do something like this as part of the network specification:
```
network=[ ...
    dict(type='linear', size=64),
    dict(type=MyActivationClass, **kwargs),
    ... ]
```
Alternatively, it should be possible to use `type=my_module.my_class.MyClass`, for instance.
