### ISSUE TITLE
Add the ability to add new activation functions to tensorforce's network...

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#575]
I'd like to suggest a new feature to TensorForce, and that is the ability to add new activation functions to a network. Right now, it appears that all the activation functions are locked into place, i.e. a string.

**Comment by AlexKuhnle** [comment]
As I posted in the other thread, something like this should work, as part of the network specification:
```
network=[ ...
    dict(type='linear', size=64),
    dict(type=MyActivationClass, **kwargs),
    ... ]
```
Alternatively, it should be possible to use `type=my_module.my_class.MyClass`, for instance. Let me know if it doesn't.

**Comment by ZeroMaxinumXZ** [comment]
@AlexKuhnle Oh, ok... i \was quite confused about that... I'm sorry about that. I've only used the dict(type=Whatever, activation_function=Whatever) method... My apologies... How would I do it? Do I just define a function or what? Again, I'm sorry about all these questions I've been asking.

**Comment by ZeroMaxinumXZ** [comment]
I've only been programming for 9 months so I'm rather slightly inexperienced...

**Comment by AlexKuhnle** [comment]
No worries. Unfortunately it's currently not quite as easy. You will have to implement your own activation function as a subclass of `Layer` and also implement its `tf_apply` function ([here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/networks/layer.py#L77)) where you define your custom activation. So something like this should work (haven't tested it):
```
from tensorforce.core.networks import Layer
class MyActivation(Layer):
    def tf_apply(self, x, update):
        return tf.nn.relu(x)
```

**Comment by AlexKuhnle** [comment]
But it's a good point, ideally a function would suffice... Something to add to the next version... :-)

**Comment by AlexKuhnle** [comment]
Improved
