### ISSUE TITLE
Limit gpu resources 

### ISSUE THREAD

**Issue by Bumblebeena** [tensorforce/tensorforce#578]
Normally in Tensorflow, if I wanted to prevent my processes from using as much vram as they should consume I would do something like:

`opts = tf.GPUOptions(per_process_gpu_memory_fraction=0.5) `
`sess = tf.Session(config=tf.ConfigProto(gpu_options=opts))`

but I'm not calling tf.Session directly so I'm not sure how that parameter should be passed. I assumed that I may be able to specify this in my vpg config json but I'm not sure what the syntax would be and can't find any examples.

I appreciate any help, I'm very new to this.

**Comment by AlexKuhnle** [comment]
Hi,
This should be possible by passing it as part of the `execution` dict argument as `session_config` value (see [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/models/model.py#L138)).

**Comment by Bumblebeena** [comment]
`"execution": {
        "type": "single",
        "session_config": {
            "GPUOptions": {
                "per_process_gpu_memory_fraction": 0.5
            }
        },
        "distributed_spec": null
    }`

**Comment by Bumblebeena** [comment]
So expanding upon the examples provided in this GitHub, I tried putting the following in my vpg.json:
```
{"execution": { 
    "type": "single",
    "session_config": {
        "GPUOptions": {
            "per_process_gpu_memory_fraction": 0.5
        }
    },
    "distributed_spec": null
}
```

Which gives an error:
`TypeError: config must be a tf.ConfigProto, but got <type 'dict'>` 

This is contradictory to:
`sanity_check_specs.py:112: -session_config: dict with options for a TensorFlow ConfigProto object (default: None)`

So instead I tried specifying the session config directly by doing:
```
config = json.load(vpg.json)
gpu_opts = tf.GPUOptions(per_process_gpu_memory_fraction=0.5)
session_config = tf.ConfigProto(gpu_options=gpu_opts)
execution = {'type': 'single',
             'session_config': session_config,
             'distributed_spec': None
            }

worker = WorkerAgentGenerator(AgentsDictionary[agent_type])(execution=execution,
                                                            **config)
```

This doesn't break but `watch -n 0.5 nvidia-smi` shows that my process is still taking up all remaining gpu memory.

If it helps I'm using:

- Ubuntu 16.04
- tensorflow 1.9
- tensorforce 0.4.3
- EVGA gtx 1080ti

**Comment by AlexKuhnle** [comment]
Sorry, I wasn't involved in this part, it was done by an earlier contributor, but you're right, this is indeed wrong documentation. I'm surprised it doesn't work, since it is passed to the session [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/models/model.py#L804) (unless you're on pip 0.4.3 and something changed since then), so I'm not sure what could go wrong. I assume this config option usually works for you?

**Comment by Bumblebeena** [comment]
I haven't actually done it before but it is the common solution in a number of threads on how to limit gpu usage in tensorflow.

**Comment by Bumblebeena** [comment]
So I must have spelled something wrong because I made a minor change:
```
config = json.load(vpg.json)
gpu_opts = tf.GPUOptions(per_process_gpu_memory_fraction=0.5)
session_config = tf.ConfigProto(gpu_options=gpu_opts)
config["execution"]["session_config"] = session_config

worker = WorkerAgentGenerator(AgentsDictionary[agent_type])(**config)
```
...and it works now. 

I'm not sure why my previous code didn't work because they're functionally the same. Thanks for your help!

**Comment by AlexKuhnle** [comment]
Cool, glad it works now!
