### ISSUE TITLE
actions generated at begining almost zero

### ISSUE THREAD

**Issue by giorgionicola** [tensorforce/tensorforce#581]
Hi I have noticed that at the beginning of the training while using VPG and DDPG in continuous spaces, the action array generated without action exploration is always almost zero. Is it normal?
I am using as activation function tanh and the action space is limited between -1 and +1

**Comment by AlexKuhnle** [comment]
When you say "at the beginning", does that imply that it changes later? I think the weight initialization of the distribution likely leads to the middle value, 0.0 here, as the "default" at the start, so if it does change later on, I would say this is probably "expected behavior"...

**Comment by giorgionicola** [comment]
yes it changes but I would have expected a more random behavior. I believe it can be closed

**Comment by AlexKuhnle** [comment]
It's a good point, but I would say that's what exploration is there for. Since a bounded continuous action is modeled as Beta distribution, it will initially behave that way, if initialized randomly.
