### ISSUE TITLE
Tensorforce Installation Issue Major-Revision 

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#583]
I'm having issues with the installation of the major revision of tensorforce...

Installation I tried using:
`~/tensorforce-major-revision $ sudo python3 setup.py install`

Error:

```
>>> from tensorforce import agents
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'agents'
>>>
```

Observations:

In my dist-packages/tensorforce directory there's only three files (not including __pycache__). Files are util, __init__, and exception... 

Please let me know if you need anything else to help me fix this error.

**Comment by AlexKuhnle** [comment]
Have you also tried this one: `pip install -e .`? Need to check what the difference is, but it works for me.

**Comment by ZeroMaxinumXZ** [comment]
Doesn't work, same error...

I've noticed in the __init__.py this:
```
from tensorforce.exception import TensorforceError
from tensorforce import util


__all__ = ['TensorforceError', 'util']

__version__ = '0.5.0'
```
Does this have something to do with the above error? Because only these files are showing up...

**Comment by AlexKuhnle** [comment]
Weird, don't know, need to check...

**Comment by AlexKuhnle** [comment]
I just checked locally, and the framework seems to install and work. Then I realized: you want to import `from tensorforce import agents`, which I think doesn't work since `agents` is not a class or so. What if you do `from tensorforce.agents import Agent` and then later on `Agent.from_spec(...)`?

**Comment by ZeroMaxinumXZ** [comment]
OK, huh, don't really know what I did differently, but... I reinstalled and it works.. Closing this...
