### ISSUE TITLE
How to preprocess reward?

### ISSUE THREAD

**Issue by bbliao** [tensorforce/tensorforce#585]
Hi, thanks for the great work.
The range of my reward is [0, 1m], so I want to preprocess the reward for stability. I found that there are several [preprocessors](https://github.com/tensorforce/tensorforce/tree/master/tensorforce/core/preprocessors), so I tried the `divide`/`running_standardize` preprocessor in the agent_config.json:
```
"reward_preprocessing": {
		"type": "divide",
		"scale": 1000
	},
```
However, it seems that it doesn't work (the performances of without/`divide`/`running_standardize` preprocessors are almost the same and the scale of these preprocessors are the same). 
So I am wondering whether I preprocessed the reward in the right way? If not, could you please give me some advice (examples would be better) on the reward preprocessing?

**Comment by AlexKuhnle** [comment]
Hey,
What do you mean by the scale of the preprocessors is the same? Generally, I wouldn't expect at least division to make a big difference, in particular if it still ranges up to 1k after division. However, I would expect running_standardize to make a difference in general. Do you observe learning? If not, can you verify learning works in principle in a simpler setup, and check the effect of these settings there? All I can say is that it looks correct what you're doing.

**Comment by bbliao** [comment]
@AlexKuhnle Thanks, I'll try that later.
