### ISSUE TITLE
Modify rewards for model.

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#589]
Hi. I'm looking for a way to modify the rewards given to a model. I want to implement some level of curiosity in your models and set the rewards to this 'curiosity'. How should I set the rewards and getting the state for, for example, a PPO2 agent without just completely modifying the code?

**Comment by ZeroMaxinumXZ** [comment]
Ok, this was meant for OpenAI's Baseline, so sorry...

**Comment by AlexKuhnle** [comment]
Hehe, no problem. ;-)
