### ISSUE TITLE
How-to beautifully restrict actions depend on environment state?

### ISSUE THREAD

**Issue by madpower2000** [tensorforce/tensorforce#592]
Normally, the set of actions that the agent can execute does not change over time, but some actions can become impossible in different states (for example, not every move is possible in any position of the TicTacToe game).  

How I can beautifully implement this action restrict depended on environment state in TensorForce?

Something like:
```
ava_actions = env.available_actions()
action = agent.act(state, ava_actions)
state, reward, done, info = env.step(action)
```

**Comment by AlexKuhnle** [comment]
Hi, #586 is about the same problem, I think, with a solution proposal. Maybe also ask there whether it worked. Masking actions is on the roadmap for the new version as well, but may take a while still.

**Comment by AlexKuhnle** [comment]
Masking is now possible and will be added to the documentation.
