### ISSUE TITLE
tensorflow 2.0 as backend

### ISSUE THREAD

**Issue by ZhenhuiTang** [tensorforce/tensorforce#593]
can we use tensorflow2.0 as backend?

environment:
ubuntu16.04
tensorflow2.0
tensorforce0.4.3
when i run “Quickstart example code”， it report error：
        AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdadeltaOptimizer'

**Comment by ZhenhuiTang** [comment]
when i use tensorflow 1.13.1 as backend,  it report:
    tensorforce.exception.TensorForceError: Action requires value 'num_actions' set!

**Comment by AlexKuhnle** [comment]
Regarding your first question: No, Tensorforce is not TF2 compatible, and probably won't be anytime soon.
Re the exception: If you use actions of type `int`, you need to specify `num_actions`, so something like that: ` dict(type='int', num_actions=5)`.
