### ISSUE TITLE
how to begin  to use tensorforce

### ISSUE THREAD

**Issue by yangtianyong** [tensorforce/tensorforce#596]
Hello,i am a new learner about tensorforce .It seems really difficult  for me to understand the code,i mean , What is the function of each line of code.So i don't know  how to make a first step about learning tensorforce.
        Well ,i want to know the PPOAgent module,about how it works ,the design idea behind it.It is really appreciate if you can provide any suggestions or learning materials .
        Thank you!

**Comment by AlexKuhnle** [comment]
Hi @yangtianyong, I think a good starting point to learn more about PPO is probably [OpenAI
s Spinning Up library and docs](https://spinningup.openai.com/en/latest/). From an educational perspective, Tensorforce code is in some aspects "unnecessarily" complex (for other reasons), but once PPO is clear, you should be able to identify elements in Tensorforce code as well.

**Comment by yangtianyong** [comment]
OK，thank you for your advice!

**Comment by AlexKuhnle** [comment]
No problem. I will close this issue then, but feel free to post here or get in touch via Gitter if you have specific questions about differences and implementation choices in Tensorforce later on.
