### ISSUE TITLE
restore  error

### ISSUE THREAD

**Issue by CreamyLong** [tensorforce/tensorforce#597]
`# Start learning
episodes = 100
for i in range(1):
    runner.run(episodes=episodes, max_episode_timesteps=200, episode_finished=episode_finished)
    agent.save_model(directory='savefile/ppo')
runner.close()

# Print statistics
print("Learning finished. Total episodes: {ep}. Average reward of last 100 episodes: {ar}.".format(
    ep=runner.episode,
    ar=np.mean(runner.episode_rewards[-100:]))
)

saved_agent = agent.restore_model(directory="savefile/ppo" , file="checkpoint")
env = gym.make("CartPole-v0")
s = env.reset()
done = False
while not done:
    env.render()
    action = saved_agent.act(s)
    s, r, done, _ = env.step(action)`

I want to restore the model I trained, then watch it performance in the game. I got a error like this.

RuntimeError: Attempted to use a closed Session.

**Comment by AlexKuhnle** [comment]
Hey, it looks like you're using the same agent to restore, after closing the runner -- which closes the agent, which closes the session, which I think causes the problem. :-)  What you need to do is create a new agent instance, which will open a new session, and then restore it from the directory. Maybe a bit counter-intuitive, or at least undocumented behavior, will consider changing that.

**Comment by CreamyLong** [comment]
> Hey, it looks like you're using the same agent to restore, after closing the runner -- which closes the agent, which closes the session, which I think causes the problem. :-) What you need to do is create a new agent instance, which will open a new session, and then restore it from the directory. Maybe a bit counter-intuitive, or at least undocumented behavior, will consider changing that.

thanks for the reply. In fact, I tried to change agent.restore_model(directory="savefile/ppo" , file="checkpoint")  to  Agent.restore_model(directory="savefile/ppo" , file="checkpoint"). it appears that
TypeError: restore_model() missing 1 required positional argument: 'self'.......
is there any demonstration code for restore the model to test the game

**Comment by AlexKuhnle** [comment]
What I meant is not to use the class instead, but a new agent, so something like:
```python
agent = XXXAgent(...)
runner = Runner(agent=agent, ...)
...
runner.close()

agent = XXXAgent(...)
agent.restore_model(...)
...
```

**Comment by CreamyLong** [comment]
> What I meant is not to use the class instead, but a new agent, so something like:
> 
> ```python
> agent = XXXAgent(...)
> runner = Runner(agent=agent, ...)
> ...
> runner.close()
> 
> agent = XXXAgent(...)
> agent.restore_model(...)
> ...
> ```

get error as well...
DataLossError (see above for traceback): Unable to open table file .\checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

I have tried all different file I stored

**Comment by AlexKuhnle** [comment]
Ah, but that's a different error message, right? In fact, this has come up in issues before, may be worth having a look. Are you using the latest master version of Tensorforce? And for the second initialization of the agent, do you use the same arguments as for the first? What if you train an agent again (just for a short period) and see whether it works to restore it with this setup?

**Comment by AlexKuhnle** [comment]
Also, what Python version are you using?

**Comment by CreamyLong** [comment]
> Also, what Python version are you using?

3.6.6

**Comment by CreamyLong** [comment]
> Ah, but that's a different error message, right? In fact, this has come up in issues before, may be worth having a look. Are you using the latest master version of Tensorforce? And for the second initialization of the agent, do you use the same arguments as for the first? What if you train an agent again (just for a short period) and see whether it works to restore it with this setup?

yeah, I tried many ways including what you said. If you are happy, you may play with it and see how it is going... it is better someone has some demo code for restoring an agent

**Comment by AlexKuhnle** [comment]
If you could post the entire code snippet, that may be helpful.

And re your other issue, that is because you use the `Agent` class to call `restore_model`, not an `agent` instance.

**Comment by CreamyLong** [comment]
`# Make sure you have tensorforce installed: pip install tensorforce
from tensorforce.agents import PPOAgent
from tensorforce.execution import Runner
from tensorforce.contrib.openai_gym import OpenAIGym
def make_np_float(feature):
    return np.array(feature).astype(np.float32)

def featurize(obs):
    board = obs["board"].reshape(-1).astype(np.float32)
    bomb_blast_strength = obs["bomb_blast_strength"].reshape(-1).astype(np.float32)
    bomb_life = obs["bomb_life"].reshape(-1).astype(np.float32)
    position = make_np_float(obs["position"])
    ammo = make_np_float([obs["ammo"]])
    blast_strength = make_np_float([obs["blast_strength"]])
    can_kick = make_np_float([obs["can_kick"]])

    teammate = obs["teammate"]
    if teammate is not None:
        teammate = teammate.value
    else:
        teammate = -1
    teammate = make_np_float([teammate])

    enemies = obs["enemies"]
    enemies = [e.value for e in enemies]
    if len(enemies) < 3:
        enemies = enemies + [-1]*(3 - len(enemies))
    enemies = make_np_float(enemies)

    return np.concatenate((board, bomb_blast_strength, bomb_life, position, ammo, blast_strength, can_kick, teammate, enemies))

class TensorforceAgent(BaseAgent):
    def act(self, obs, action_space):
        pass
# Instantiate the environment
config = ffa_v0_fast_env()
env = Pomme(**config["env_kwargs"])
env.seed(0)

# Create a Proximal Policy Optimization agent
agent = PPOAgent(
    states=dict(type='float', shape=env.observation_space.shape),
    actions=dict(type='int', num_actions=env.action_space.n),
    network=[
        dict(type='dense', size=64),
        dict(type='dense', size=64)
    ],
    batching_capacity=1000,
    step_optimizer=dict(
        type='adam',
        learning_rate=1e-4
    )
)

# Add 3 random agents
agents = []
for agent_id in range(3):
    agents.append(SimpleAgent(config["agent"](agent_id, config["game_type"])))

# Add TensorforceAgent
agent_id += 1
agents.append(TensorforceAgent(config["agent"](agent_id, config["game_type"])))
env.set_agents(agents)
env.set_training_agent(agents[-1].agent_id)
env.set_init_game_state(None)

# Instantiate the environment
config = ffa_v0_fast_env()
env = Pomme(**config["env_kwargs"])
env.seed(0)

# Create a Proximal Policy Optimization agent
agent = PPOAgent(
    states=dict(type='float', shape=env.observation_space.shape),
    actions=dict(type='int', num_actions=env.action_space.n),
    network=[
        dict(type='dense', size=64),
        dict(type='dense', size=64)
    ],
    batching_capacity=1000,
    step_optimizer=dict(
        type='adam',
        learning_rate=1e-4
    )
 saver=dict(
                    directory="PPOAgent/models/ppo",
                    seconds=300)
)
# Add 3 random agents
agents = []
for agent_id in range(3):
    agents.append(SimpleAgent(config["agent"](agent_id, config["game_type"])))

# Add TensorforceAgent
agent_id += 1
agents.append(TensorforceAgent(config["agent"](agent_id, config["game_type"])))
env.set_agents(agents)
env.set_training_agent(agents[-1].agent_id)
env.set_init_game_state(None)

# Instantiate and run the environment for 5 episodes.
wrapped_env = WrappedEnv(env, True)
runner = Runner(agent=agent, environment=wrapped_env)
runner.run(episodes=5, max_episode_timesteps=2000)
print("Stats: ", runner.episode_rewards, runner.episode_timesteps, runner.episode_times)

try:
    runner.close()
except AttributeError as e:
    pass`

this is the game I experiment, I can use saver to save the model but what I can I do to restore it.

**Comment by AlexKuhnle** [comment]
Hint: Use the following environment for code:
\`\`\`python
[CODE]
\`\`\`

To restore the model, the following should work:
```python
agent = PPOAgent(
    states=dict(type='float', shape=env.observation_space.shape),
    actions=dict(type='int', num_actions=env.action_space.n),
    network=[
        dict(type='dense', size=64),
        dict(type='dense', size=64)
    ],
    batching_capacity=1000,
    step_optimizer=dict(
        type='adam',
        learning_rate=1e-4
    )
)

agent.restore_model(directory='PPOAgent/models/ppo')
```

Have you already tried this?

**Comment by CreamyLong** [comment]
> Hint: Use the following environment for code:
> ```python
> [CODE]
> ```
> 
> To restore the model, the following should work:
> 
> ```python
> agent = PPOAgent(
>     states=dict(type='float', shape=env.observation_space.shape),
>     actions=dict(type='int', num_actions=env.action_space.n),
>     network=[
>         dict(type='dense', size=64),
>         dict(type='dense', size=64)
>     ],
>     batching_capacity=1000,
>     step_optimizer=dict(
>         type='adam',
>         learning_rate=1e-4
>     )
> )
> 
> agent.restore_model(directory='PPOAgent/models/ppo')
> ```
> 
> Have you already tried this?

Thx, it works!

**Comment by AlexKuhnle** [comment]
Cool, closing then.
