### ISSUE TITLE
Error while installing tensorflow on python2.7

### ISSUE THREAD

**Issue by AshuKV** [tensorforce/tensorforce#600]
is there exist any older version of tensorforce which can be installed in python2.7 ? Or is there any another way by which I can handle tensorforce on python2.7 . 
Thanks in advance.

**Comment by AlexKuhnle** [comment]
The Github master version or pip < 0.5 should work with Python 2. Later versions, currently in pre-release, won't anymore, and I'm not sure whether there is a good way to make it run with Python 2, unfortunately.

**Comment by AlexKuhnle** [comment]
The Github master version or pip < 0.5 should work with Python 2. Later versions, currently in pre-release, won't anymore, and I'm not sure whether there is a good way to make it run with Python 2, unfortunately.
