### ISSUE TITLE
model checkpoint with and without exploration

### ISSUE THREAD

**Issue by andermi** [tensorforce/tensorforce#601]
Hi,

I'm experiencing an issue when loading a checkpoint with and without exploration. The error I receive is this:

`OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key vpg/action-exploration/ornstein_uhlenbeck not found in checkpoint`

In my code, when training, I'd like to use exploration. When I'm in testing mode, I'd like to turn exploration off (as in I don't set exploration in the config). The issue seems to be that when I switch to testing mode after training, the checkpoint model is loaded and then overwritten without the exploration keys. When I go back to training, exploration is then missing from the original checkpoint and can't load.

Is there something I'm missing? Am I using exploration incorrectly, and Is there another way to turn it off for testing?

Thanks!

**Comment by AlexKuhnle** [comment]
The agent has to be loaded with the same config, yes. To evaluate the agent, it's best to use `deterministic=True` and `independent=True` for `act(...)` (and don't call observe), which will turn off exploration and don't add anything to memory.

**Comment by andermi** [comment]
I have tried to set `deterministic=true` in the past and this resulted in only a constant action from the agent (VPG) for any input. Is there something I am doing wrong there?

**Comment by AlexKuhnle** [comment]
Doesn't sound like it. It more sounds like the agent may actually have collapsed to a trivial policy. What is the agent's performance in that case? What is the problem you're applying it to? Is it possible that the agent's performance during training is due to constant+exploration?

**Comment by andermi** [comment]
The deterministic and independent flags are working. It must have been constant+exploration when I ttried before like you said. thanks!

**Comment by AlexKuhnle** [comment]
Great! Yes, documentation could be better, and I hope the new soon-to-be-master branch will do a better job... :-)
