### ISSUE TITLE
Testing large array of input states

### ISSUE THREAD

**Issue by andermi** [tensorforce/tensorforce#602]
I would like to load a pre-trained agent and pass a large array of independant input states to the agent to check actions. Is there any way I can pass large batches of inputs to agent.act at once?

**Comment by AlexKuhnle** [comment]
This is not currently not possible, bur could be implemented without too many problems. However, is it not possible to just iterate through them and pass them to act independently? I assume it's a lot and so just takes too much time?

**Comment by andermi** [comment]
I'm passing close to 20M inputs... rough calc says it will take close to 20 hours. Not intractable, but not great. If you can think of a quick hack or where in the code I could get started on batching, I'd be grateful. I'm using version 0.4.3 for now.

**Comment by AlexKuhnle** [comment]
I can look into that, but it won't happen within the next 20h :-)  So in the short-term at least may be worth just doing it that way.

**Comment by andermi** [comment]
reminds me of an joke... an engineer spends 2 hours to make a 3 hour job take only 1 hour

**Comment by AlexKuhnle** [comment]
Hehe... with RL these times are sometimes even less favorable... :-)  Well, independently, I may look into it soon, but unfortunately can't in the next days.

**Comment by AlexKuhnle** [comment]
This should work now when setting `act(..., independent=True, ...)`.
