### ISSUE TITLE
how to get saved/best data 

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#603]
Hi 
I want to know how to load the saved/best model for running a case and processing the data.
this files saved from the agent are binary file. which I don't know how to use them.

Thanks

**Comment by AlexKuhnle** [comment]
The saved files are the normal TensorFlow files (although I also don't know what the format of them is). You can just load your agent again using Tensorforce and then run it on new data, can't you?

**Comment by AlexKuhnle** [comment]
Improvement added to roadmap.
