### ISSUE TITLE
Incomplete installation using PyPi

### ISSUE THREAD

**Issue by MarkYu98** [tensorforce/tensorforce#605]
Hi, I've noticed that the new version 0.5.0 was released, and I updated using PyPi. But it looks like the installation is not complete, for example:

Python3 >>> from tensorforce.agents import Agent

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorforce.agents'

**Comment by AlexKuhnle** [comment]
Yes, sorry, I screwed up something in the setup file. Upgraded the version to 0.5.1 now and this one should hopefully work. Note that it's a completely revised version including quite a few API changes. Let me know if you need help with upgrading, and feedback welcome. :-)

**Comment by AlexKuhnle** [comment]
Hi @gregarious9612, I realize that this is not documented in the update notes, but some of the environments were moved from `contrib` to `environments` [here](https://github.com/tensorforce/tensorforce/tree/master/tensorforce/environments) and their API may have changed (while others were removed). Does that help?

**Comment by gregarious9612** [comment]
Hi @AlexKuhnle  thank you for the quick reply ,and yup that helped a lot 👍. Thank you so much for the assistance.

**Comment by AlexKuhnle** [comment]
No problem. Closing this...
