### ISSUE TITLE
Custom Metrics for Tensorboard

### ISSUE THREAD

**Issue by JNC96** [tensorforce/tensorforce#611]
Pardon my ignorance, but if I wanted to display a custom scalar in Tensorboard what would be the best way to do this? I'm using TFRC's runner, and I'm not sure if there's an integrated method that allows me to easily define a custom metric that I want to be included in the tensorboard summary file.

TIA!

**Comment by AlexKuhnle** [comment]
Do you mean that you want to "pass" a metric when you call the agent, which then should be internally recorded? I have to admit, I hadn't so far thought about that use case, and I'm not sure whether I would add functionality to do so in the near future. However, it may not be a big problem to "hack" something together which does the job, basically by accessing the internal TensorFlow `session` and `summarizer` object and just "injecting" additional summaries. Does that sound like what you want?

**Comment by JNC96** [comment]
> Do you mean that you want to "pass" a metric when you call the agent, which then should be internally recorded?

Yes. I'm currently doing a project around investigating how to integrate user input in a "traditional" reinforcement learning framework, so I wanted to utilise Tensorboard to keep track of self-defined custom metrics since it's already integrated into TRFC. 

> However, it may not be a big problem to "hack" something together which does the job, basically by accessing the internal TensorFlow session and summarizer object and just "injecting" additional summaries.

Yeah that would probably be the way to go - just wanted to see if there was already a feature to  supplement this or if there was an easier way. In any case, thank you for replying! I'll do it the old-fashioned way 😄

**Comment by AlexKuhnle** [comment]
Let me know if you get stuck with it, the "hacky" solution should be an easy way to achieve what you want.

If other people think that would be a cool feature to have, post here... :-)

**Comment by AlexKuhnle** [comment]
Custom summaries are now supported, see [here](https://tensorforce.readthedocs.io/en/latest/basics/features.html#tensorboard).
