### ISSUE TITLE
Feature Request: OpenAI Gym instance to Tensorforce Environment

### ISSUE THREAD

**Issue by notadamking** [tensorforce/tensorforce#612]
Currently, it is only possible to convert an OpenAI Gym environment into a Tensorforce Environment by registry string, using `tensorforce.environments.openai_gym`.

**Request:**
Allow initializing a Tensorforce Environment via an existing OpenAI Gym instance.

```python
from tensorforce.environments.openai_gym import OpenAIGym

existing_env = SomeGymEnv(API_KEY="SECRET_API_KEY")
tf_env = OpenAIGym.create(existing_env)
```

**Reasoning:**
The Gym standard for RL environments has been widely adapted, and as such, not all environments will be registered via the `gym` registry.

In fact, it is not possible for some environments to be registered, as they require runtime parameters such as API keys, etc.

**Comment by AlexKuhnle** [comment]
That sounds like a perfectly reasonable feature, and not very problematic to add... Will look into that soon.

**Comment by AlexKuhnle** [comment]
Should be possible now, as illustrated in the [unittest](https://github.com/tensorforce/tensorforce/blob/master/test/test_environments.py#L51). Let me know if it doesn't work...
