### ISSUE TITLE
Manually inputting an action for the agent to take

### ISSUE THREAD

**Issue by JNC96** [tensorforce/tensorforce#614]
How "deep" into the code would I need to edit to be able to manually set an action for an agent to take? What I'm doing currently requires me to generate a bunch of actions (5 actions) for the same state at the same timestep, and then have a user select a certain action. I know I can do this by setting independence to True so that the expectation of running agent.observe after agent.act is bypassed. However, the reverse relationship still holds true when I then try to run agent.observe. Since I've run agent.act 5 times independently, it doesn't acknowledge agent.act as being run before and therefore agent.observe errors out (at least I think that's the reason why it's error-ing out).

```Traceback (most recent call last):
  File "C:\WINDOWS\system32\venv\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\WINDOWS\system32\venv\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\WINDOWS\system32\venv\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (agent.observe/strided_slice:0) = ] [1] [y (agent.observe/strided_slice_1:0) = ] [0]
	 [[{{node agent.observe/assert_equal_1/Assert/AssertGuard/Assert}}]]
```
I also don't think I can simply "inject" a certain action in between calling agent.act and agent.observe because the action that the agent takes won't be the same as the action that the agent ***believes*** it takes, right? Which brings me to my initial question - how deep into the code would I need to tinker to be able to achieve what I hope to?

Once again, thanks in advance and sorry for the barrage of questions on the forum recently. I did spend quite sometime to figure out different ways to get around it but haven't been successful.

**Comment by AlexKuhnle** [comment]
What you say about the use of the `independent` flag etc makes sense. Could you give some more information about the state space you're looking at? Is specifying 5 instead of 1 action in the action space a solution? Something like `dict(action1=dict(...), action2=dict(...), action3=dict(...), ...)`. Otherwise running the agent 4 times with `independent=True` and once with `independent=False`, could also be an option, depending on what's the goal. In the latter version, the problem is that the action is implicitly stored, so not necessarily the one that was actually taken. If that's the problem, how about: `act(..., independent=True)` five times, then call [experience(...)](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/agents/policy_agent.py#L313) with the full timestep information. Does that sound like a solution?

**Comment by AlexKuhnle** [comment]
Re-reading your issue, I think the `experience(...)` function in combination with `independent=True` is the way to go...

**Comment by JNC96** [comment]
I did see the experience function but wasn't 100% sure about it's functionality. Does it pass an action-reward pair to the model and it "learns" from that as though it took a step? If so, I would still have the same issue with `agent.observe` right? I'm still using the runner in its normal operation, except the model will wait for user input during the action phase.

**Comment by AlexKuhnle** [comment]
Experience is supposed to just feed a timestep quadruple (state, action, terminal, reward) to the memory. But good point, I don't think it would trigger an update, as the usual act-observe cycle does. Let me have a look at that, if generally that sounds like what you want.

**Comment by JNC96** [comment]
Yeah, I just wanted to be able to force `agent.act` to take a user-selected action. I've also been trying to maybe change the `agent.act` code to facilitate this as well but the code gets a bit challenging for me at the level. Thanks for helping me out on this @AlexKuhnle even though you didn't need to, I really appreciate it.

**Comment by AlexKuhnle** [comment]
Yes, modifying the core code is not that straightforward and I wouldn't necessarily recommend it... :-)  May take 2-3 days to look into that.

**Comment by AlexKuhnle** [comment]
Sorry for the delay. I thought a bit more about it, and decided that probably the best way for these kind of "more customized" agent-environment interactions is to not use the usual `act(...) - observe(...)` loop, but instead a combination of `act(..., independent=True)` - experience(...) - update(...)`. I added a unittest for this type of interaction [here](https://github.com/tensorforce/tensorforce/blob/master/test/test_policy_agent.py#L25). Note that update is configured to be episodes-based and `agent.update()` can  be called for the first time only after `batch_size` episodes (here `1`, so immediately). I think that should help, but let me know if there are still problems...
