### ISSUE TITLE
quickstart with seed raises an exception (typo in agent.py)

### ISSUE THREAD

**Issue by christianhidber** [tensorforce/tensorforce#615]
Setting the seed in the quickstart.py example results in an exception:
![grafik](https://user-images.githubusercontent.com/51879047/66191233-27dc3c00-e68e-11e9-98e9-3a0ed62da67d.png)

![grafik](https://user-images.githubusercontent.com/51879047/66191270-417d8380-e68e-11e9-84ef-1193398506c1.png)

Changing the named argument from 'n' to 'a' solves the problem:
![grafik](https://user-images.githubusercontent.com/51879047/66191338-6bcf4100-e68e-11e9-8fd6-b74dbe54edb4.png)

**Comment by AlexKuhnle** [comment]
Stupid bug. :-/  Mind creating a PR with a fix for this?

**Comment by christianhidber** [comment]
no problem, with pleasure.

**Comment by AlexKuhnle** [comment]
Fixed by #616.

**Comment by AlexKuhnle** [comment]
Since I assume you were playing around with seeds, maybe you also realised that there is a problem and execution is not completely deterministic. Just to let you know that I fixed this problem with the latest commit.

**Comment by AlexKuhnle** [comment]
Hehe, I just came across that framework a few days ago, but didn't connect the account name... :D  Yes, that's fine of course. Feel free to get in touch if there are other questions.

The next release will contain the seed fix, yes, although I have to admit that there's currently no "principled" way of releasing new versions, just happens every now and then when it seems like a good deal and/or important things have changed.

**Comment by christianhidber** [comment]
great. Thanks a lot.
