### ISSUE TITLE
Error message for  'get_current_state' 

### ISSUE THREAD

**Issue by sunchipsster1** [tensorforce/tensorforce#617]
Hello, this is probably a very trivial issue from a beginner to this awesome resource, but after downloading tensorforce, I attempted to run the quickstart example code. An error message appeared-- NameError: name 'get_current_state' is not defined
Does anyone know how to fix this? Thank you!

**Comment by AlexKuhnle** [comment]
Hi,
The quickstart example in the readme is not intended to run on its own, but is supposed to illustrate how Tensorforce can be integrated with your application. So `get_current_state(...)` and `execute_decision(...)` are "placeholders" where your RL application comes in. A better quickstart example would probably be [this one](https://github.com/tensorforce/tensorforce/blob/master/examples/quickstart.py), which should be linked in the Readme as well.
