### ISSUE TITLE
0.5.1 OpenAIGym unable to create level from custom environment

### ISSUE THREAD

**Issue by codeninja** [tensorforce/tensorforce#618]
OpenAIGym#create_level() has an error when a custom gym has not been registered in the gym environment. The code is attempting to concatenate `level + '-v0'` in order to create a name to use to iterate over the env.registry but level is an object and not a string.

I've created a bugfix on a local fork which I will append to the ticket.

**Comment by AlexKuhnle** [comment]
Hi, thanks for raising. Actually, this problem may have been addressed in a recent commit, if you want to try out the GitHub master version. But will look into it later, and it's probably time to update the pip version.

**Comment by AlexKuhnle** [comment]
I think this problem has been addressed with a recent change, but otherwise let's discuss in the PR.
