### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by soqt** [tensorforce/tensorforce#622]
Is there any chance to use a different type of progress bar? Maybe like tensorflow keras's.  I have a large dataset, and the progress bar takes so long to get first update. A more frequent update rate for progress bar may help

**Comment by AlexKuhnle** [comment]
Certainly possible. Currently, the [runner class](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/execution/runner.py#L134) uses [tqdm](https://github.com/tqdm/tqdm). It may be just a matter of configuring it differently, or if you have suggestions for other progress bars (like Keras'), offering that as an alternative option would be great. Contribution via PR is very welcome, feel free to get in touch via e.g. [Gitter](https://gitter.im/tensorforce/community) if you're planning to look into it and need help.

**Comment by AlexKuhnle** [comment]
Relying on contribution here, so closing this...
