### ISSUE TITLE
no longer python2 compatible: update readme

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#624]
@AlexKuhnle should the readme be updated there:

```
# PyPI version plus TensorFlow CPU version
pip install tensorforce[tf]

# GitHub version plus TensorFlow GPU version
pip install -e .[tf_gpu]
```

to ```pip3``` instead, as 0.5.XX is only python3?

**Comment by jerabaul29** [comment]
PS: there are a couple more places where it is written ```python``` instead of ```python3``` ;)

**Comment by AlexKuhnle** [comment]
Good point, will do. I always use it in a Py3 virtual env, but that shouldn't implicitly be assumed.

**Comment by AlexKuhnle** [comment]
Will be improved with the next commit.
