### ISSUE TITLE
PyGameLearningEnvironment documentation

### ISSUE THREAD

**Issue by dengelt** [tensorforce/tensorforce#625]
The tensorforce PyGameLearningEnvironment documentation found [here](https://tensorforce.readthedocs.io/en/latest/environments/ple.html) mentions the following possible string values for `level`: `‘doom’, ‘flappybird’, ‘monsterkong’, ‘catcher’, ‘pixelcopter’, ‘pong’, ‘puckworld’, ‘raycastmaze’, ‘snake’, ‘waterworld’`.

However, running `PyGameLearningEnvironment.levels()` actually yields `['Catcher', 'FlappyBird', 'MonsterKong', 'Pixelcopter', 'Pong', 'PuckWorld', 'RaycastMaze', 'Snake', 'WaterWorld']`.

It seems the documentation is missing the correct capitalization.

**Comment by AlexKuhnle** [comment]
You're right, good catch. Will change that with the next commit.
