### ISSUE TITLE
'dict' object has no attribute 'modules' - network.modules.values()

### ISSUE THREAD

**Issue by Capr1sna** [tensorforce/tensorforce#631]
When using a 'layered' or a 'custom' type network with a PPOAgent I always got this error:

_Exception has occurred: AttributeError
'dict' object has no attribute 'modules'_

-------------------------------------------------------------------
**Code line 140 in network.py** 
`for layer in network.modules.values():`

**This are my agent settings:**
```
    agent = PPOAgent(
        discount=0.9999,
        states=environment.states,
        actions=environment.actions,
        max_episode_timesteps=200,
        network=network_spec,
        critic_network=baseline_spec,
```

**Here the according network specification I use:**
```
    network_spec = dict(
        type='layered', 
        layers=[
            dict(type='dense', size=32,activation='relu'),
            dict(type='dense', size=32,activation='relu'),
            dict(type='internal_lstm', size=32)
            ]
        )
```
```
    baseline_spec = dict(
        type='custom', 
        layers=[
            dict(type='lstm', size=32),
            dict(type='dense', size=32, activation='relu'),
            dict(type='dense', size=32, activation='relu')
            ]
        )
```

**Comment by Capr1sna** [comment]
Found the issue by myself.
seems that the "execution" block in my agents definition made the problem, so I removed i and now the error is gone
        #execution=dict(
        #    type='single',
        #    session_config=None,
        #    distributed_spec=None
        #)

**Comment by AlexKuhnle** [comment]
Surprising error message, but glad you managed to solve it. :-)
