### ISSUE TITLE
Tensorforce DPG Actions parameter 

### ISSUE THREAD

**Issue by gregarious9612** [tensorforce/tensorforce#633]
Hi Guys, I was looking into implementing the Deterministic Policy Gradient, and am running to an issue where setting my DPG Agent with the following: 

```
DPGAgent(
    states=dict(type='float', shape=env.observation_space.shape),
    actions=dict(type='int',num_values=env.action_space.n),
    max_episode_timesteps = 1000)
```

 Also, not sure if the current document is up to date with the parameters the Agent takes. As 'num_values' replaced 'num_actions' and the doc didn't mention that. 

Gave an error : 

> Traceback (most recent call last):
>   File "ddpg_script.py", line 104, in <module>
>     max_episode_timesteps = 1000)
>   File "/home/ec2-user/pommergan/greg_pommerman_exp/tensorforce_exp_env/lib/python3.7/site-packages/tensorforce/agents/dpg.py", line 266, in __init__
>     raise TensorforceError.unexpected()
> tensorforce.exception.TensorforceError: Unexpected error!.

**Comment by gregarious9612** [comment]
Also, running to an issue when initiating the Advance Actor Critic Agent: `TypeError: execute() got an unexpected keyword argument 'actions'`

Not sure if I'm doing something wrong or miss something, but I've pretty much set the out of the box parameters, with the same open_ai env that works on the other Agents (i.e. Deep Q, PPO, etc). 

Full stack trace: 

 

>  File "a2c_agent.py", line 121, in <module>
>     runner.run(num_episodes=100,max_episode_timesteps=100)
>   File "/home/ec2-user/pommergan/greg_pommerman_exp/tensorforce_exp_env/lib/python3.7/site-packages/tensorforce/execution/runner.py", line 233, in run
>     evaluation=self.evaluation
>   File "/home/ec2-user/pommergan/greg_pommerman_exp/tensorforce_exp_env/lib/python3.7/site-packages/tensorforce/execution/runner.py", line 333, in run_episode
>     states, terminal, step_reward = environment.execute(actions=actions)
> TypeError: execute() got an unexpected keyword argument 'actions'
> Episodes:   0%| | 0/100 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]
>

**Comment by AlexKuhnle** [comment]
Hi, regarding the first issue: DPG only works for continuous actions, so in the case here something like PPO is a better choice. Also, you're right, `num_values` is outdated in the docs.

Regarding the second issue: Are you using a custom env implementation? If so, can you check whether the `execute(...)` argument is called `action` instead of `actions`? I think it used to be that way but was renamed a while ago already. That would need updating from the env side...

**Comment by gregarious9612** [comment]
@AlexKuhnle ah okay, yeah that makes sense for DPG. I just assume that it was able to also take discrete actions, since the doc seems to gave that impression to me. In regards to the second issue, will check if modifying the custom open_ai env execute () will be a fix. Thanks again for the quick and helpful response :D

**Comment by AlexKuhnle** [comment]
You're right, the continuous constraint should be mentioned in the docs.
