### ISSUE TITLE
execute() got an unexpected keyword argument 'actions'

### ISSUE THREAD

**Issue by Capr1sna** [tensorforce/tensorforce#635]
> Exception has occurred: TypeError
> execute() got an unexpected keyword argument 'actions'
>   File "/home/xxx/Downloads/tensorforce-0.5.2/tensorforce/execution/runner.py", line 333, in run_episode
>     states, terminal, step_reward = environment.execute(actions=actions)
>   File "/home/xxx/Downloads/tensorforce-0.5.2/tensorforce/execution/runner.py", line 233, in run
>     evaluation=self.evaluation
>   /home/xxx/yyy.py", line 149, in main
>     train_runner.run(num_episodes=100, max_episode_timesteps=200)
>   File "/home/xxl/yyy.py", line 158, in <module>
>     main()

The error happens when I call the Runner.run:
train_runner.run(num_episodes=100, max_episode_timesteps=200)

This is the agent I use:
```

agent = Agent.create(
        agent='ppo',
        states=environment.states,
        actions=environment.actions,
        max_episode_timesteps=200,
        network=dict(type='auto'),
        preprocessing=None,
        batch_size=32,
        update_frequency=10,
        entropy_regularization=0.0,  # None
        critic_network=dict(type='auto'),
        critic_optimizer=dict(
            type='multi_step',
            optimizer=dict(
                type='adam',
                learning_rate=(1e-4)  # 3e-4
            ),
            num_steps=5
        ),
        likelihood_ratio_clipping=0.2,
        learning_rate=(1e-4),  # 1e-4
        subsampling_fraction=0.2,  # 0.1
        optimization_steps=10,
        )
```

**Comment by gregarious9612** [comment]
Had a similar issue @Capr1sna  #633

**Comment by AlexKuhnle** [comment]
Yes, looks like you're using a custom environment implementation, which hasn't yet updated the execute argument name `action` to `actions`. This was changed a while ago, to be more consistent with argument names...  Reopen if that doesn't help.

**Comment by Capr1sna** [comment]
Thanks for the hint. Yes I use a custom environment, and changing the execute argument to actions solved it!
