### ISSUE TITLE
OpenAI Gym environment assumes termination after max_episode_timesteps

### ISSUE THREAD

**Issue by janblumenkamp** [tensorforce/tensorforce#640]
Hi,
I am having troubles getting tensorforce to run with custom OpenAI Gym environments (the problem also occurs with some standard environments, for example [MountainCarEnv](https://github.com/openai/gym/blob/master/gym/envs/classic_control/mountain_car.py)). Consider the following example:

```
from gym.envs.classic_control.mountain_car import MountainCarEnv
from tensorforce.environments import OpenAIGym
from tensorforce.agents import Agent
from tensorforce.execution import Runner

if __name__ == '__main__':
    environment = OpenAIGym(MountainCarEnv(), max_episode_timesteps=100)
    agent = Agent.create(agent='dqn', environment=environment)
    runner = Runner(agent=agent, environment=environment)
    runner.run(num_episodes=10)
    runner.close()
```
It crashes with the following error:
```
  File "tf_mountain.py", line 10, in <module>
    runner.run(num_episodes=10)
  File "[...]/tensorforce/execution/runner.py", line 233, in run
    evaluation=self.evaluation
  File "[...]/tensorforce/execution/runner.py", line 333, in run_episode
    states, terminal, step_reward = environment.execute(actions=actions)
  File "[...]/tensorforce/environments/openai_gym.py", line 200, in execute
    assert terminal
AssertionError
```
The problem is that the OpenAI Gym wrapper requires the environment to [terminate (return True as the done flag)](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/environments/openai_gym.py#L223) after `max_episode_timesteps`, but not all environments terminate after a fixed amount of steps. The `assert terminal` then just terminates the application. Why is that? Am I missing something? Why is assumed that all OpenAI Gym environments terminate after `max_episode_timesteps` steps?

**Comment by AlexKuhnle** [comment]
That shouldn't be the case unless the environment explicitly specifies a `max_episode_steps` value (otherwise it's `None` and the comparison should fail). I will look into it asap.

**Comment by janblumenkamp** [comment]
I see, that makes sense. For some reason I thought the max_episode_timesteps argument is required, maybe because if I leave it I get a different error:

```
Episodes:   0%|                                                                                                 | 0/10 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]Traceback (most recent call last):
  File "[...]/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "[...]/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "[...]/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [Condition x <= y did not hold element-wise:] [x (agent.observe/agent.core_observe/agent.core_experience/cond_1/memory.enqueue/strided_slice:0) = ] [100] [y (agent.observe/agent.core_observe/agent.core_experience/cond_1/memory.enqueue/sub_2:0) = ] [99]
	 [[{{node agent.observe/agent.core_observe/agent.core_experience/cond_1/memory.enqueue/assert_less_equal/Assert/AssertGuard/Assert}}]]
```

**Comment by AlexKuhnle** [comment]
I checked your example now. The problem is in the way you specify the environment: you call the `OpenAIGym` class directly, but the `max_episode_timesteps` argument is not handled there (anymore), but is also not recognized as invalid argument, since unrecognized `**kwargs` are passed on to the environment (assuming they are env config args). It should work if you use `Environment.create(...)` (generally recommended), for instance:
```python
environment = Environment.create(
    environment='gym', level=MountainCarEnv(), max_episode_timesteps=100
)
```
Let me know if there are other problems.

**Comment by janblumenkamp** [comment]
Unfortunately I get the exact same error as in my initial question if I use `Environment.create`.

**Comment by AlexKuhnle** [comment]
Are you on the most recent version? For me it works...

**Comment by janblumenkamp** [comment]
I did have the wrong tensorflow version installed, but I created a new virtualenv and installed everything with `pip install tensorforce[tf] gym`. I am using Python 3.7. `pip list` gives:
```
Package              Version 
-------------------- --------
absl-py              0.9.0   
astor                0.8.1   
attrs                19.3.0  
cloudpickle          1.2.2   
cycler               0.10.0  
future               0.18.2  
gast                 0.3.2   
grpcio               1.26.0  
gym                  0.15.4  
h5py                 2.10.0  
importlib-metadata   1.3.0   
Keras-Applications   1.0.8   
Keras-Preprocessing  1.1.0   
kiwisolver           1.1.0   
Markdown             3.1.1   
matplotlib           3.1.2   
mock                 3.0.5   
more-itertools       8.0.2   
numpy                1.18.0  
opencv-python        4.1.2.30
packaging            19.2    
pip                  19.3.1  
pluggy               0.13.1  
protobuf             3.11.2  
py                   1.8.0   
pyglet               1.3.2   
pyparsing            2.4.6   
pytest               5.3.2   
python-dateutil      2.8.1   
scipy                1.4.1   
setuptools           41.2.0  
six                  1.13.0  
tensorboard          1.13.1  
tensorflow           1.13.1  
tensorflow-estimator 1.13.0  
Tensorforce          0.5.2   
termcolor            1.1.0   
tqdm                 4.41.0  
wcwidth              0.1.7   
Werkzeug             0.16.0  
wheel                0.33.6  
zipp                 0.6.0   
```
If I set the `max_episode_timesteps` parameter, I get the `assert terminal` error from above. If I leave it, I get the following error:

```
  File "tf_mountain.py", line 11, in <module>
    runner.run(num_episodes=10)
  File "[...]/tensorforce/execution/runner.py", line 233, in run
    evaluation=self.evaluation
  File "[...]/tensorforce/execution/runner.py", line 333, in run_episode
    states, terminal, step_reward = environment.execute(actions=actions)
  File "[...]/tensorforce/environments/openai_gym.py", line 204, in execute
    self.timestep < self._max_episode_timesteps
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
I am not entirely sure if I understand the `max_episode_timesteps` parameter correctly - when should it be used? I understand it as "terminate this episode either if the returned done flag is true or after max_episode_timesteps iterations". Is that correct?

**Comment by AlexKuhnle** [comment]
Hi,
I see, you're using the pip version of Tensorforce. I wanted to fix a new version today anyway, so should hopefully work better soon. If there are still problems (possible, hard to tell), let's see what the new exception is.

**Comment by janblumenkamp** [comment]
It works now (tensorforce 0.5.3, tensorflow 2.0.0), thank you!

**Comment by AlexKuhnle** [comment]
Great, glad to hear that! :-)
