### ISSUE TITLE
Installation Missing Documentation

### ISSUE THREAD

**Issue by STRATZ-Ken** [tensorforce/tensorforce#641]
Hey guys, getting pretty basic : 

`ModuleNotFoundError: No module named 'tensorforce.agents'; 'tensorforce' is not a package`

Just created a new virtualenv, pip install tensorflow-gpu, pip install tensorforce, run quickstart.py provided in Git, and get this error.

Tried downloading the latest git and doing pip install -e . and still same error.

Python 3.7.6.
Windows 10.

**Comment by AlexKuhnle** [comment]
That's weird. Can you check whether at least `import tensorforce` works in this virtualenv python? Can you check whether `pip list` shows `tensorforce` as an installed package?

**Comment by STRATZ-Ken** [comment]
Debug output below 

I do not get any errors on the following script 👍 

```
import os
import logging

import tensorforce



def main():
    print('hi')


if __name__ == '__main__':
    main()
```

```
(env) C:\Git\stratz-stats\openai>pip list
Package              Version
-------------------- ----------
absl-py              0.9.0
astor                0.8.1
atomicwrites         1.3.0
attrs                19.3.0
cachetools           4.0.0
certifi              2019.11.28
chardet              3.0.4
cloudpickle          1.2.2
colorama             0.4.3
cycler               0.10.0
future               0.18.2
gast                 0.2.2
google-auth          1.10.0
google-auth-oauthlib 0.4.1
google-pasta         0.1.8
grpcio               1.26.0
gym                  0.15.4
h5py                 2.10.0
idna                 2.8
importlib-metadata   1.3.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
Markdown             3.1.1
matplotlib           3.1.2
more-itertools       8.0.2
numpy                1.18.1
oauthlib             3.1.0
opencv-python        4.1.2.30
opt-einsum           3.1.0
packaging            20.0
pip                  19.2.3
pluggy               0.13.1
protobuf             3.11.2
py                   1.8.1
pyasn1               0.4.8
pyasn1-modules       0.2.7
pyglet               1.3.2
pyparsing            2.4.6
pytest               5.3.2
python-dateutil      2.8.1
requests             2.22.0
requests-oauthlib    1.3.0
rsa                  4.0
scipy                1.4.1
setuptools           41.2.0
six                  1.13.0
tensorboard          2.0.2
tensorflow-estimator 2.0.1
tensorflow-gpu       2.0.0
Tensorforce          0.5.3
termcolor            1.1.0
tqdm                 4.41.1
urllib3              1.25.7
wcwidth              0.1.8
Werkzeug             0.16.0
wheel                0.33.6
wrapt                1.11.2
zipp                 0.6.0
```

**Comment by STRATZ-Ken** [comment]
Attempted the same installation on another Physical machine I have with Windows 2012 R2 installation, same errors with `quickstart.py`

**Comment by AlexKuhnle** [comment]
That's weird. I know this was a problem at some point, but the usage of `find_packages` [here](https://github.com/tensorforce/tensorforce/blob/master/setup.py#L86) resolved it. For you it seems the package was correctly installed, but the "sub-packages" not identified. Are you using Anaconda or so for Python?

**Comment by STRATZ-Ken** [comment]
Nope, straight Python.

**Comment by AlexKuhnle** [comment]
One thing you could try is what happens if you change the quickstart to just `import tensorforce` and then prefix all imports with `tensorforce.agents` etc... But even if it works, this is of course no final solution. Not sure what could go wrong here, since this definitely works when I try it. :/

**Comment by STRATZ-Ken** [comment]
No Go.

```
(env) C:\Git\stratz-stats\openai>tensorforce.py
2020-01-07 09:39:55.731200: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "C:\Git\stratz-stats\openai\tensorforce.py", line 49, in <module>
    main()
  File "C:\Git\stratz-stats\openai\tensorforce.py", line 14, in main
    environment = tensorforce.Environment.create(environment='gym', level='draft_agent:draft_agent-v0')
AttributeError: module 'tensorforce' has no attribute 'Environment'
```

**Comment by STRATZ-Ken** [comment]
I am also in your Gitter channel, if you want to speak in real time.

**Comment by AlexKuhnle** [comment]
Following up on Gitter: The problem seems to be the name of the script, `tensorforce.py`, which clashes with the library name, so import doesn't work. Feel free to reopen if it doesn't solve the problem.

**Comment by STRATZ-Ken** [comment]
Correct, fixed.
