### ISSUE TITLE
cannot set execution_spec?

### ISSUE THREAD

**Issue by qZhang88** [tensorforce/tensorforce#643]
I want to set up how many CPUs to be used since now it takes all my CPUs, but I find it strange in tensorforce/core/models/model.py, self.execution_spec well always be none here.
```
          self.execution_spec = None
          if self.execution_spec is not None:
              self.execution_type = self.execution_spec['type']
              self.session_config = self.execution_spec['session_config']
              self.distributed_spec = self.execution_spec['distributed_spec']
```

**Comment by AlexKuhnle** [comment]
Hi,
The original distributed execution feature, which was the main reason for `execution_spec`, is currently not working, unfortunately (and probably won't in the near future, in favor of more basic parallelization strategies outside of TensorFlow). But what you want to do is probably to just set the `session_config` argument? This can certainly be changed, as it's unrelated to the main distributed stuff. Let me know if that would help...

**Comment by AlexKuhnle** [comment]
If the main problem was related to the session config, I hope that with the latest commit (the changes [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/models/model.py#L552)) this is now working, so passing `execution=dict(session_config=...)` should hopefully be accepted now.

**Comment by AlexKuhnle** [comment]
Re-open if this didn't help...

**Comment by qZhang88** [comment]
I do as you recommended by passing the execution parameter. I set up session_config as following
```
config = tf.compat.v1.ConfigProto(allow_soft_placement=True, log_device_placement=False)
config.gpu_options.allow_growth = True
execution=dict(session_config=config)
```
But an error by JSON serialization
```
  File "/battle/tensorforce/tensorforce/agents/agent.py", line 86, in create
    return Agent.create(agent=agent, environment=environment)
  File "/battle/tensorforce/tensorforce/agents/agent.py", line 63, in create
    agent.initialize()
  File "/battle/tensorforce/tensorforce/agents/agent.py", line 319, in initialize
    json.dump(obj=self.spec, fp=fp, cls=NumpyJSONEncoder)
  File "/usr/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/battle/tensorforce/tensorforce/core/utils/json_encoder.py", line 30, in default
    return super().default(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ConfigProto' is not JSON serializable
```

**Comment by AlexKuhnle** [comment]
You're right, I forgot about this problem. I added a quickfix now, which hopefully helps. Let me know if there are still problems.

**Comment by AlexKuhnle** [comment]
Actually, I added the possibility to specify the ConfigProto as a dictionary (with sub-dictionaries for values like `gpu_options`). So you should be able to specify as follows:
```python
execution=dict(
    session_config=dict(
        allow_soft_placement=True, log_device_placement=False,
        gpu_options=dict(allow_growth=True)
    )
)
```
Could you try whether this works? Thanks!

**Comment by qZhang88** [comment]
great, thanks, it works well
