### ISSUE TITLE
Rainbow Agent Request

### ISSUE THREAD

**Issue by kiranmaya** [tensorforce/tensorforce#647]
where can i find road map of this Project.  want a add RainBow Agent Feature Request .

**Comment by AlexKuhnle** [comment]
You can find a roadmap [here](https://github.com/tensorforce/tensorforce/blob/master/ROADMAP.md). The two main features missing, I think, are prioritized replay memory and the "distributional/categorical DQN" feature. Realistically it will probably take a while, particularly prioritized replay.

**Comment by AlexKuhnle** [comment]
As a feature request, this issue is okay.
