### ISSUE TITLE
[Bug Report] 'name' is used without declaration

### ISSUE THREAD

**Issue by zkx741481546** [tensorforce/tensorforce#648]
openai_gym.py
![image](https://user-images.githubusercontent.com/31107435/73590451-7951e600-451d-11ea-90b1-77d1086770c3.png)
'name' is used without declaration

**Comment by AlexKuhnle** [comment]
Good spot. :-)  However, I think this was actually fixed in a very recent commit. If you're on the official pip version, moving to GitHub master should help (but I'm sure a new version will be fixed soon).
