### ISSUE TITLE
Quick start example is not working

### ISSUE THREAD

**Issue by giranntu** [tensorforce/tensorforce#650]
if we simply install the tensorforce in any method that provided, 
the quick start example is not working in line 18.

`state = get_current_state()  # (float array of shape [10])`

which would occur error:

> 
> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> <ipython-input-1-e4afb07ca8c3> in <module>
>      16 
>      17 # Retrieve the latest (observable) environment state
> ---> 18 state = get_current_state()  # (float array of shape [10])
>      19 
>      20 # Query the agent for its action decision
> 
> NameError: name 'get_current_state' is not defined

**Comment by AlexKuhnle** [comment]
Hi, the quickstart example in the readme is more for illustrative purposes, so `get_current_state` and `execute_decision` are supposed to be provided by the application. Maybe this isn't the best quickstart example here, so I may change that to something that executes right away. Anyway, better to look at these: [docs](https://tensorforce.readthedocs.io/en/latest/basics/getting-started.html) or [example](https://github.com/tensorforce/tensorforce/blob/master/examples/quickstart.py). Let me know if there are still questions.
