### ISSUE TITLE
Quickstart.py example is inoperable

### ISSUE THREAD

**Issue by jeffreywillert** [tensorforce/tensorforce#652]
It looks like the quickstart example in the readme is outdated.

**Comment by AlexKuhnle** [comment]
I assume that you solved the problem? Because as far as I'm aware, the example should work...

**Comment by jeffreywillert** [comment]
The quickstart example in the readme did not work when I "pip-installed" the package, however worked just fine when I cloned the project from github.

**Comment by AlexKuhnle** [comment]
Ah yes, I upgraded the example yesterday, as the old one was not as great. Will update the pip version soon as well.
