### ISSUE TITLE
RandomAgent fails with and without "parallel_interactions" parameter

### ISSUE THREAD

**Issue by stheid** [tensorforce/tensorforce#653]
```
from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensorforce.execution import Runner

environment = Environment.create(
    environment='gym', level='CartPole', max_episode_timesteps=500
)
agent = Agent.create(agent='random', environment=environment, name='agent', device=None)
runner = Runner(agent=agent, environment=environment)
```
gives
`KeyError: 'parallel_interactions'`

when adding the parameter to the agents constructor i get
`TypeError: __init__() got an unexpected keyword argument 'parallel_interactions'`

I assume its related to the implementation of the "TensorforceAgent", which expects this argument, but the RandomAgent inheriting from "Agent"

---
python 3.8
tf 2.1
tensorforce git

**Comment by stheid** [comment]
![image](https://user-images.githubusercontent.com/2736207/74533088-0ee37180-4f31-11ea-9cf7-6c39fad4db7d.png)

**Comment by AlexKuhnle** [comment]
Thanks for reporting. I'm surprised, I thought that this is covered by the unittests. I'll have a look now.

**Comment by AlexKuhnle** [comment]
Ah wait, you say it's when you add the `parallel_interactions` parameter to the arguments? That is indeed not possible currently, as there is no need to explicitly parallelize interactions with the random (or constant) agent, they behave the same anyway. Is there a reason why it would nonetheless be good to just "formally" support this argument?

**Comment by stheid** [comment]
There is no way to run it properly right now: 
1. ommiting the argument results in an keyerror later
2. adding the argument is obviously wrong and not supported

**Comment by AlexKuhnle** [comment]
Okay, will have a look

**Comment by AlexKuhnle** [comment]
I think the latest commit should fix the problem. :-)

**Comment by stheid** [comment]
you're lightning fast. I think its fixed :)

Thank you
