### ISSUE TITLE
"parallel_interactions" breaks Agent.create()   (Tensorforce 0.5.3)

### ISSUE THREAD

**Issue by MariusHolm** [tensorforce/tensorforce#654]
Hi,

I'm working on my Master thesis using the PPO agent to control fluid mechanical flows with Tensorforce. Very similar to the work done by @jerabaul29. I have previously used one of his Docker images with Tensorforce 0.5.0, but wanted to create my own with at least 0.5.3 so I can use the "save_best_agent" feature added for that version. 

I need to run my simulations in parallel, and when creating the Agent I have used the following setup:
```python
agent = Agent.create(
    # Agent + Environment
    agent='ppo', environment=example_environment,
    # Network
    network=network, # dict
    # Optimization
    batch_size=20, learning_rate=1e-3, subsampling_fraction=0.2, optimization_steps=25,
    # Reward estimation
    likelihood_ratio_clipping=0.2, estimate_terminal=True, 
    # Critic
    critic_network=network,
    critic_optimizer=dict(
         type='multi_step', num_steps=5,
         optimizer=dict(type='adam', learning_rate=1e-3)
    ),
    # Regularization
    entropy_regularization=0.01,
    # TensorFlow etc
    parallel_interactions=number_servers, # int defined previously in code
    saver=dict(directory=os.path.join(os.getcwd(), 'saver_data'), frequency=72000) 
)
```

However, when I try to use the same code with 0.5.3 I get an assertion error from the same line in code as here https://github.com/tensorforce/tensorforce/issues/653#issuecomment-586274933 (without a specification to any of the arguments). 
If I comment out the line of "parallel_interactions" everything seems to run fine, but I'm not sure if this would break the parallel training?

**Comment by AlexKuhnle** [comment]
Hi, I think that should work in principle, however, the assertions may currently be a bit "too" strict. Two comments: (a) Do you use `Runner`, and if so, do you use the `evaluation` option? If `evaluation`, the last environment in the list is used for evaluation, and so only `number_servers - 1` parallel streams are required, so that may help (but admittedly a case of being unnecessarily strict in assertions). (b) You can also pass the agent as specification dict (replace `Agent.create` with `dict`), and the `parallel_interactions` argument will be set internally.

**Comment by MariusHolm** [comment]
(a) I'm using ParallelRunner with an evaluation environment. Will try redefining with `parallel_interactions = num_servers - 1`. 

(b) Will try this if (a) shouldn't work.

**Comment by MariusHolm** [comment]
Simply using `number_servers - 1` seems to be working. 
Thanks for the quick response!

**Comment by AlexKuhnle** [comment]
No problem. Since this is strictly speaking no requirement, just one unused parallel buffer, it would be better to throw a warning here, or at least a more informative exception. Will look into that.
