### ISSUE TITLE
summarizer arguments (refs #651)

### ISSUE THREAD

**Issue by stheid** [tensorforce/tensorforce#655]
similar to the issue #651 i think the "variables" argument is not working. Maybe you should run tests with 'all' an see if they are running.

It takes quite a while (5 episodes or so) until the error comes up. probably the first time it wants to export the stuff

tf 2.1

**Comment by AlexKuhnle** [comment]
Yes, the "variables" label is not working currently, and unfortunately I'm not sure right now whether it will be easy to fix it. What is the exception that is thrown? I would have expected that it just doesn't record the summaries, but no exception...

**Comment by AlexKuhnle** [comment]
I will look into it again, but if you could post the stacktrace, or even better a minimal example, that would be helpful.

**Comment by stheid** [comment]
If i am able to reproduce it again. Its the ugly kind of bug that only occures every n-th execution :see_no_evil:

**Comment by AlexKuhnle** [comment]
Any updates, or did you manage to solve the problem?

**Comment by stheid** [comment]
no, right now i am not working with tensorforce. i will reopen the ticket if i can find the issue again.
