### ISSUE TITLE
Can training and running be separated ?

### ISSUE THREAD

**Issue by kikikio** [tensorforce/tensorforce#660]
Can training and running be separated ?
For example, put training on the cloud, and run locally.
And what should I do if I want to separate the two operation?

**Comment by AlexKuhnle** [comment]
Hmm, I could swear I responded to this issue -- I must have forgotten to submit it or messed up something. Sorry for that.

Unfortunately, you can't really separate training and execution, if it's supposed to happen at the same time. In theory this would be possible, but Tensorforce doesn't focus on such more sophisticated execution scenarious. Obviously you can train the model, then subsequently deploy it.
