### ISSUE TITLE
Can training and running be separated ?

### ISSUE THREAD

**Issue by kikikio** [tensorforce/tensorforce#661]
Can training and running be separated ?
For example, traing on cloud and running locally.
If ture,what should I do to separate two operations?

**Comment by AlexKuhnle** [comment]
You can train the model and then subsequently load and apply it elsewhere, if that's what you're looking for. Otherwise, there is no dedicated functionality to distribute processes in a sophisticated way as part of this framework.

**Comment by AlexKuhnle** [comment]
You may be able to manually set it up by recording interactions locally, sending data to the cloud, explicitly scheduling updates there, sending updated weights to the workers, but I would recommend looking at other libraries, particularly [RLlib](https://ray.readthedocs.io/en/latest/rllib.html), which supports such execution setups much better out of the box.

**Comment by AlexKuhnle** [comment]
Feel free to reopen if that doesn't answer your question.
