### ISSUE TITLE
Agent class actions and states arguments are not type dict

### ISSUE THREAD

**Issue by sccrthlt** [tensorforce/tensorforce#664]
Documentation states the `states` argument to `TensorforceAgent.act` (and subsequently the parent class: tensorforce.agents.agent.Agent.act` is a dictionary:
```python
class Agent(object):
    """
    Tensorforce agent interface.
    """
    ...
    def act(
        self, states, internals=None, parallel=0, independent=False, deterministic=False,
        evaluation=False, query=None, **kwargs
    ):
        """
        Returns action(s) for the given state(s), needs to be followed by `observe(...)` unless
        independent mode set via `independent`/`evaluation`.

        Args:
            states (dict[state] | iter[dict[state]]): Dictionary containing state(s) to be acted on
                (<span style="color:#C00000"><b>required</b></span>).
```

However, it seems the actual implementation passes `states` around as a `numpy.ndarray`.  

That being said, I notice that within `tensorforce.agents.agent.Agent.act`, `util.normalize_values` converts a `numpy.ndarray` to an `collections.OrderedDict`. :

```python
def normalize_values(value_type, values, values_spec):
    if not is_valid_value_type(value_type=value_type):
        raise TensorforceError.value(
            name='util.normalize_values', argument='value_type', value=value_type
        )

    if len(values_spec) == 1 and next(iter(values_spec)) == value_type:
        # Spec defines only a single value
        if isinstance(values, dict):
            if len(values) != 1 or value_type not in values:
                raise TensorforceError.value(
                    name='util.normalize_values', values='values', value=values
                )
            return values

        else:
            return OrderedDict([(value_type, values)])
    ...
```

Is the `TensorforceAgent.act` intended to be allow more datatypes?  If so, the documentation may need to be updated.

**Comment by AlexKuhnle** [comment]
Hi,
You're right, there is another option missing in the docs: if you just have a single state, and you specified it as such (`states=dict(type='float', shape=())` or so, so no state component keys), you are supposed to just pass this single state array. One purpose of the `normalize_values` function is to normalize this special case to a state dict with a single `"state"` key. But I agree that the documentation could be extended here. I hope that at least the default behavior is not counter-intuitive...

**Comment by AlexKuhnle** [comment]
Apart from this special case, act is supposed to only accept dict-like states inputs (or a batched act call, as indicated by `iter[dict[state]]`).

**Comment by AlexKuhnle** [comment]
Any updates?

**Comment by sccrthlt** [comment]
Hey sorry for the delayed response.  This makes sense.  Thank you for the clarification.  This can be closed.
