### ISSUE TITLE
customized gym environment run into 'float division by zero'

### ISSUE THREAD

**Issue by YingxiaoKong** [tensorforce/tensorforce#668]
Hello,

I just create a simple environment and registered it under gym. Then I run the environment and there is some problem coming out: float division by zero. Do you have any clue of how this problem comes out? I also tried it in my own PPO code and there is no problem.

**Comment by AlexKuhnle** [comment]
Hi,
Would it be possible to post the environment code here, if it is simple? And/or could you post the code which runs the agent and env (shouldn't be more than a few lines, I expect)? Otherwise hard to say what may be going wrong...

**Comment by YingxiaoKong** [comment]
Hello Alexander,

Thank you for your reply!!! Sorry I just saw it. I uploaded the files to my github repository. Here is the link: https://github.com/YingxiaoKong/Customized-gym-envionment

The code is is very simple:
import gym
from gym import error, spaces, utils
from gym.utils import seeding
import numpy as np
class UAVenv_2(gym.Env):
    """A stock trading environment for OpenAI gym"""
    metadata = {'render.modes': ['human']}
    def __init__(self):
        super(UAVenv_2, self).__init__()
        self.action_space = spaces.Box(\
            low=np.array([-2, -2]), high=np.array([2, 2]), dtype=np.float16)
        self.observation_space = spaces.Box(\
            low=np.array([0,0,0,0]), high=np.array([20,20,100,100]), dtype=np.float16)
        self.state=[]
        self.count=0
        self.reward = 0
        self.done = False


    def step(self, action):
        self.count+=1
        done =False
        old_pos = self.state[2:]
        new_state = np.zeros((4))
        new_state[:2] = self.state[:2]+action
        new_state[2:] = self.state[2:]+new_state[:2]
        new_pos = new_state[2:]
        self.state = new_state

        old_dis = np.linalg.norm(old_pos-np.array([100,100]))
        new_dis = np.linalg.norm(new_pos-np.array([100,100]))
#         self.reward = 1-new_dis/np.linalg.norm([100,100])
        t_go = new_dis/np.linalg.norm(self.state[:2])
        v_targ = (np.array([100,100]) - self.state[2:])/new_dis*self.v0*(1-np.exp(-t_go/10))
        self.reward = -np.linalg.norm([v_targ-self.state[:2]])*.01

        if self.state[-1]>100:
            done = True
            if np.linalg.norm(self.state[:2])<5 and np.linalg.norm(self.state[:2])>0:
                self.reward=100
                if new_dis<5:
                    self.reward = 200
        return self.state,self.reward,done,{}
    def reset(self):
        self.count=0
        self.state=np.array([10,10,50,0])
        self.v0 = self.state[:2]
        return self.state

    def render(self, mode='human', close=False):
        ### this one we just leave it like this.
        pass
I just didn't know whether I added it to gym correctly. The files in my github may give you more clues of the potential mistakes I made. It's the complete folder of the enviroment after I installed it on my PC.

Best regards,
Yingxiao
________________________________

**Comment by AlexKuhnle** [comment]
Where exactly does the division by zero happen, could you post the stacktrace?

**Comment by AlexKuhnle** [comment]
If it's on environment-side, I don't think it's Tensorforce's fault, since the environment should "guarantee" that it's correctly simulating its state.

**Comment by YingxiaoKong** [comment]
Hi Alexander,

The stacktrace are shown in the picture. I'm not sure whether I correctly made it a gym accpected game.

Bisides, the custom environment you provided also has the 'float division by zero' error. The custom example I used is from here: https://tensorforce.readthedocs.io/en/latest/basics/getting-started.html

The command I used to run the custom environment is:

import os
import logging

import tensorflow as tf

from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensorforce.execution import Runner


os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
logger = tf.get_logger()
logger.setLevel(logging.ERROR)


def main():
    # Create an OpenAI-Gym environment
    environment = Environment.create(
    environment='custom_env.CustomEnvironment', max_episode_timesteps=10
)

    # Create a PPO agent
    agent = Agent.create(
        agent='ppo', environment=environment,
        # Automatically configured network
        network='auto',
        # Optimization
        batch_size=10, update_frequency=2, learning_rate=1e-3, subsampling_fraction=0.2,
        optimization_steps=5,
        # Reward estimation
        likelihood_ratio_clipping=0.2, discount=0.99, estimate_terminal=False,
        # Critic
        critic_network='auto',
        critic_optimizer=dict(optimizer='adam', multi_step=10, learning_rate=1e-3),
        # Preprocessing
        preprocessing=None,
        # Exploration
        exploration=0.0, variable_noise=0.0,
        # Regularization
        l2_regularization=0.0, entropy_regularization=0.0,
        # TensorFlow etc
        name='agent', device=None, parallel_interactions=1, seed=None, execution=None, saver=None,
        summarizer=None, recorder=None
    )

    # Initialize the runner
    runner = Runner(agent=agent, environment=environment)

    # Start the runner
    runner.run(num_episodes=300)
    runner.close()


if __name__ == '__main__':
    main()

​The stacktrace for this one is as below:

ZeroDivisionError Traceback (most recent call last) <ipython-input-2-49b18d4350ff> in <module> 53 54 if __name__ == '__main__':---> 55 main()<ipython-input-2-49b18d4350ff> in main() 48 49 # Start the runner---> 50 runner.run(num_episodes=300) 51 runner.close() 52 ~\Anaconda3\envs\tensorforce\lib\site-packages\tensorforce\execution\runner.py in run(self, num_episodes, num_timesteps, num_updates, batch_agent_calls, sync_timesteps, sync_episodes, num_sleep_secs, callback, callback_episode_frequency, callback_timestep_frequency, use_tqdm, mean_horizon, evaluation, save_best_agent, evaluation_callback) 503 else: 504 # Terminal--> 505 self.handle_terminal(parallel=n) 506 507 self.prev_terminals = list(self.terminals)~\Anaconda3\envs\tensorforce\lib\site-packages\tensorforce\execution\runner.py in handle_terminal(self, parallel) 653 if self.terminate == 0 and (( 654 self.episodes % self.callback_episode_frequency == 0 and--> 655 not self.callback(self, parallel) 656 ) or self.episodes >= self.num_episodes): 657 self.terminate = 1~\Anaconda3\envs\tensorforce\lib\site-packages\tensorforce\execution\runner.py in tqdm_callback(runner, parallel) 333 mean_agent_sec = float(np.mean(runner.episode_agent_seconds[-mean_horizon:])) 334 mean_ms_per_ts = mean_sec_per_ep * 1000.0 / mean_ts_per_ep --> 335 mean_rel_agent = mean_agent_sec * 100.0 / mean_sec_per_ep 336 runner.tqdm.postfix[0] = mean_reward 337 runner.tqdm.postfix[1] = mean_ts_per_ep ZeroDivisionError: float division by zero

I'm looking forward to your reply! Thank you for your time!
________________________________

**Comment by YingxiaoKong** [comment]
Hi Alexander,

My problem is solved. I tested it totday and found out the problem. There is some tiny problems is my environment, but the main problem is how to call the customizied gym environment. Insead of using 'environment = 'gym', level='custom_env'', I should first import the gym and the custom_env module, then env = gym.make('custom_env'), then tensorforce_env = Environment.create(env). This would work in my case. Thank you for your time!
________________________________

**Comment by AlexKuhnle** [comment]
Thanks, the stack trace is helpful. So currently your code looks something like this, I assume:

```python
import custom_env_module
env = gym.make('custom_env')
env = Environment.create(env)
```

I assume that the first `import` line registers the Gym environment. Could you try whether the following also works:

```python
import custom_env_module
env = Environment.create('gym', level='custom_env')
```

I would hope this works, too.

**Comment by YingxiaoKong** [comment]
I just checked and the way you suggested also works! I just need to import the custom environment module. Thanks!

在 2020年4月29日，上午3:40，Alexander Kuhnle <notifications@github.com> 写道：

﻿

Thanks, the stack trace is helpful. So currently your code looks something like this, I assume:

import custom_env_module
env = gym.make('custom_env')
env = Environment.create(env)

I assume that the first import line registers the Gym environment. Could you try whether the following also works:

import custom_env_module
env = Environment.create('gym', level='custom_env')

I would hope this works, too.
