### ISSUE TITLE
Getting started: Custom environment

### ISSUE THREAD

**Issue by mpettis** [tensorforce/tensorforce#669]
Based on the documentation here (https://tensorforce.readthedocs.io/en/latest/basics/getting-started.html), I thought this would work, but it does not (see below).  I think I can get this to work if I create the Custom environment by constructing it directly and *not* going through `Environment.create()`.  But then I think I have to create some other state variables, based on looking at the code from the `EnvironmentWrapper` class -- instance attributes such as `timestep`.

Should the getting started example be changed to show how to setup a custom class with the proper attributes?

```
from tensorforce.environments import Environment

class CustomEnvironment(Environment):

    def __init__(self):
        super().__init__()

    def states(self):
        return dict(type='float', shape=(8,))

    def actions(self):
        return dict(type='int', num_values=4)

    # Optional, should only be defined if environment has a natural maximum
    # episode length
    def max_episode_timesteps(self):
        return super().max_episode_timesteps()

    # Optional
    def close(self):
        super().close()

    def reset(self):
        state = np.random.random(size=(8,))
        return state

    def execute(self, actions):
        assert 0 <= actions.item() <= 3
        next_state = np.random.random(size=(8,))
        terminal = np.random.random() < 0.5
        reward = np.random.random()
        return next_state, terminal, reward

environment = Environment.create(
    environment='CustomEnvironment', max_episode_timesteps=10
)

environment.execute(1)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-6e6afaadda0f> in <module>
     37 )
     38 
---> 39 environment.execute(1)

~\Anaconda3\envs\tf2\lib\site-packages\tensorforce\environments\environment.py in execute(self, actions)
    363 
    364     def execute(self, actions):
--> 365         assert self.timestep < self._max_episode_timesteps
    366         states, terminal, reward = self.environment.execute(actions=actions)
    367         terminal = int(terminal)

AttributeError: 'EnvironmentWrapper' object has no attribute 'timestep'

```

**Comment by AlexKuhnle** [comment]
Hi,

The problem here is actually just that the environment needs to be reset before starting a new episode, as the `self.timestep` attribute is only created as part of `reset()`. It's a good point, though -- the exception here could be much more informative. I will change that.

More generally re `EnvironmentWrapper`: This class really only takes care of constraining a potentially unbound environment to `max_episode_timesteps`. The reason is that many algorithms (in Tensorforce) require episodes with well-defined max-length, but leaving it to the user to take care of in an env implementation doesn't seem the right thing to do, particularly because of subtleties around how arbitrary terminals influence reward. However, a custom `Environment` subclass should not need to care about this. One thing that may happen is that you want to access attributes of your environment, but you can't because it's wrapped. That's also a good point, could be made more intuitive by forwarding such requests to the wrapped env.

**Comment by mpettis** [comment]
Thank you Alex,

This makes sense (for what little experience I have so far in this).  To that end, assuming I got the sense of what should be done, I added a call to `environment.reset()` before calling the action.  I'm now getting a different error.  Is this error expected as well?  It seems a bit odd to me that the stack includes a call to gym ai specific classes.

```
from tensorforce.environments import Environment

class CustomEnvironment(Environment):

    def __init__(self):
        super().__init__()

    def states(self):
        return dict(type='float', shape=(8,))

    def actions(self):
        return dict(type='int', num_values=4)

    # Optional, should only be defined if environment has a natural maximum
    # episode length
    def max_episode_timesteps(self):
        return super().max_episode_timesteps()

    # Optional
    def close(self):
        super().close()

    def reset(self):
        state = np.random.random(size=(8,))
        return state

    def execute(self, actions):
        assert 0 <= actions.item() <= 3
        next_state = np.random.random(size=(8,))
        terminal = np.random.random() < 0.5
        reward = np.random.random()
        return next_state, terminal, reward

environment = Environment.create(
    environment='CustomEnvironment', max_episode_timesteps=10
)

environment.reset()
environment.execute(1)

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-39849be03ae4> in <module>
     37 
     38 environment.reset()
---> 39 environment.execute(1)

~\Anaconda3\envs\tf2\lib\site-packages\tensorforce\environments\environment.py in execute(self, actions)
    364     def execute(self, actions):
    365         assert self.timestep < self._max_episode_timesteps
--> 366         states, terminal, reward = self.environment.execute(actions=actions)
    367         terminal = int(terminal)
    368         self.timestep += 1

~\Anaconda3\envs\tf2\lib\site-packages\tensorforce\environments\openai_gym.py in execute(self, actions)
    219             self.environment.render()
    220         actions = OpenAIGym.unflatten_action(action=actions)
--> 221         states, reward, terminal, _ = self.environment.step(actions)
    222         self.timestep += 1
    223         if self.timestep == self.max_episode_steps:

~\Anaconda3\envs\tf2\lib\site-packages\gym\envs\algorithmic\algorithmic_env.py in step(self, action)
    161 
    162     def step(self, action):
--> 163         assert self.action_space.contains(action)
    164         self.last_action = action
    165         inp_act, out_act, pred = action

AssertionError:

```

**Comment by AlexKuhnle** [comment]
Oh, interesting... I overlooked this before, but I think you need to pass the actual class, not the string name, so `environment=CustomEnvironment`. As a last default, the `create(..)` procedure assumes that the string corresponds to a Gym environment, that's why the exception comes from Gym. However, the place at which it is thrown is very surprising... I should check how to catch this from the beginning if the environment doesn't exist in Gym either.

**Comment by AlexKuhnle** [comment]
Cool, glad it works. I was wondering, though, where the assert with `.item()` was coming from? I think this was added by you, is that possible? :+1:  (There should be an exception now for your previous problem.)

**Comment by AlexKuhnle** [comment]
Guess this specific issue can then be closed.

**Comment by mpettis** [comment]
> Cool, glad it works. I was wondering, though, where the assert with `.item()` was coming from? I think this was added by you, is that possible? 👍 (There should be an exception now for your previous problem.)

The class I used is copied directly from your example here, with no modifications: https://tensorforce.readthedocs.io/en/latest/basics/getting-started.html

The `reset()` and `execute()` calls are what I added to just see what I would get by executing the environment with a single action.

**Comment by AlexKuhnle** [comment]
Ah :-D  I was only checking the main `Environment` class. Well, I'd say that's an unnecessary assert, more confusing than helpful, so I will remove it.

**Comment by AlexKuhnle** [comment]
(Tensorflow always returns Numpy arrays, and so did Tensorforce even when the return value was only a scalar. However, this can be counter-intuitive, because numpy objects are not always compatible with Python, but the other way round is fine. I think Tensorforce should now always simplify it if it's a singleton value.)

**Comment by YingxiaoKong** [comment]
Seems in your example the action space is discrete, have you tried to create a continuous action space? And is there a way to add action space bounds and state space bounds?

**Comment by AlexKuhnle** [comment]
I leave the first question to @mpettis, the second: You can add bounds via e.g. `actions=dict(type='float', shape=(), min_value=-1.0, max_value=1.0)`. Doing so for states likely won't affect the Tensorforce agent, but for actions it will affect performance.

**Comment by YingxiaoKong** [comment]
Ok thank you for your reply! I will add the action boundary and see what will change.

在 2020年5月12日，上午6:05，Alexander Kuhnle <notifications@github.com> 写道：

﻿

I leave the first question to @mpettis<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmpettis&data=02%7C01%7Cyingxiao.kong%40vanderbilt.edu%7C7703963a2ea44bd3bbcf08d7f6646b5a%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637248783467627594&sdata=EfVLI67kbTf2sBcK5GdooRgo7U0rURHbq14gkyF1yek%3D&reserved=0>, the second: You can add bounds via e.g. actions=dict(type='float', shape=(), min_value=-1.0, max_value=1.0). Doing so for states likely won't affect the Tensorforce agent, but for actions it will affect performance.
