### ISSUE TITLE
SavedModel Integration

### ISSUE THREAD

**Issue by aitechrepo** [tensorforce/tensorforce#67]
Hi all, thank you for the amazing product. Really love what you have done so far! 

Going forward, I would really love to see integration with Tensorflow SavedModel for CloudML deployment. So far I was able to achieve this fairly easily with my own code, however, I had to work around model finalization in tensorforce.model.init. If you can add this functionality to work out of the box, I think it will help enable faster adoption.

**Comment by michaelschaarschmidt** [comment]
Hey, thanks for letting us now - we will see what we can do there, although (see other issues), there are a lot of structural things in the next 2-3 months until we have a more stabilised version ready for deployments, sorry about that

We will provide docker containers for benchmarking purposes soon though

**Comment by suvam-bag** [comment]
Hi guys, thank you for addressing this issue. @michaelschaarschmidt is there a a deployment example that I can get help from? I am trying to use a model learnt through PPOAgent in deployment through the Tensorflow C++ api. In the trained model, I supply a stacked 1D image array in "states_spec". For the deployment code, I use tensorflow's C++ API to load the meta graph and add to the session. A snippet from my deployment code - 

  // Read in the protobuf graph we exported
  MetaGraphDef graph_def;
  status = ReadBinaryProto(Env::Default(), pathToGraph, &graph_def);
  if (!status.ok()) {
      throw std::runtime_error("Error reading graph definition from " + pathToGraph + ": " + status.ToString());
  }

  // Add the graph to the session
  status = session->Create(graph_def.graph_def());
  if (!status.ok()) {
      throw std::runtime_error("Error creating graph: " + status.ToString());
  }

While adding the graph to the session, I get the following error - 

"terminate called after throwing an instance of 'std::runtime_error'
  what():  Error creating graph: Invalid argument: Input 1 of node ppo/actions-and-internals/categorical/sample/Select was passed int64 from ppo/actions-and-internals/categorical/sample/ArgMax:0 incompatible with expected int32."

After debugging, I found that this is coming from the "actions_spec" which expects int32. 
However, I am not completely sure at this point,how to resolve this.

Any help or an example if it already exists would help a lot. It doesn't necessarily have to be in C++. 

Thank you

**Comment by michaelschaarschmidt** [comment]
Hello, im not certain why 64 is passed. In general, have a look at util tf.datatype, where data type conversion happens from specifciations. Maybe we need to add a mapping for 64 bit data types there? I added these mappings now so maybe that helps..

**Comment by suvam-bag** [comment]
Hi @michaelschaarschmidt, I resolved it. It was a tensorflow issue on my end. Thank you for the awesome work that you have done.

**Comment by AlexKuhnle** [comment]
On roadmap.
