### ISSUE TITLE
Is it possible to build a hybrid continuous and discrete action model using tensorforce?

### ISSUE THREAD

**Issue by YingxiaoKong** [tensorforce/tensorforce#675]
Hello,

Recently I read a paper about building a hybrid continuous and discrete action model using the actor-critic method. Here is the link for the paper: https://arxiv.org/abs/1903.01344

Its idea is very simple but also very powerful. In real life, sometimes the action space is a mix of continuous and discrete data types. For example, there are two actions in a particular problem: climb and turn left. And the 'climb' and 'turn left' magnitude can be any continuous value. You can choose to climb 10 meters at time 10 seconds, then for the next second, you can choose to turn left for 30 degrees.  What they did is that they build two separate actor models (it's not completely separated, they share the first state layer), using two different loss functions. However, the loss functions are similar to the one in PPO. So they call this method as a hybrid  PPO (HPPO). The critic network is the same as PPO. 

As Tensorforce already implement PPO, I'm wondering whether we can develop HPPO using Tenforforce (as the only difference I think is just having two loss functions for the two types of actions)？ Do you think it's doable?

**Comment by AlexKuhnle** [comment]
Let me have a look at the paper and get back to you. Doesn't sound too problematic, but sometimes there are subtleties, so not sure without a closer look.

**Comment by YingxiaoKong** [comment]
Ok! Thank you for your reply! Take your time!

在 2020年5月3日，下午4:42，Alexander Kuhnle <notifications@github.com> 写道：

﻿

Let me have a look at the paper and get back to you. Doesn't sound too problematic, but sometimes there are subtleties, so not sure without a closer look.

**Comment by AlexKuhnle** [comment]
Sorry for the delay, finally had a look at the paper. It seems like the method more or less corresponds to what Tensorforce is doing if you specify multiple actions (like `actions=dict(action1=dict(type='int', shape=??), action2=dict(type='float', shape=??))`). One difference is that the default in the policy gradient objective for `early_reduce` should be changed to false [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/objectives/policy_gradient.py#L35) (not sure that makes a big difference, though). Have you looked more into this?

**Comment by YingxiaoKong** [comment]
That’s totally fine! I haven’t have a look at the code. I’m not a very good programmer, but I will try to understand the code you point out and see whether I can make it work after the modification. Thank you!

在 2020年5月10日，下午4:55，Alexander Kuhnle <notifications@github.com> 写道：

﻿

Sorry for the delay, finally had a look at the paper. It seems like the method more or less corresponds to what Tensorforce is doing if you specify multiple actions (like actions=dict(action1=dict(type='int', shape=??), action2=dict(type='float', shape=??))). One difference is that the default in the policy gradient objective for early_reduce should be changed to false here<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftensorforce%2Ftensorforce%2Fblob%2Fmaster%2Ftensorforce%2Fcore%2Fobjectives%2Fpolicy_gradient.py%23L35&data=02%7C01%7Cyingxiao.kong%40vanderbilt.edu%7C6a84fd78e49e4dd1811208d7f52cdbb4%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637247445336667030&sdata=WHHeRawM7ljyO%2FUmKZwMnseiIfhIWP5%2B6eTacLSb22Q%3D&reserved=0> (not sure that makes a big difference, though). Have you looked more into this?

**Comment by AlexKuhnle** [comment]
Sorry, maybe haven't been clear. You probably don't need to go deep into the code. On the one hand, you can use Tensorforce's PPO as it is, and specify a complex discrete-continuous action space via a "dict of dicts" like `actions=dict(action1=dict(type='int', shape=??), action2=dict(type='float', shape=??))`, if you just want to get it to work. On the other hand, if it's important to you to be closer to the paper, you would need to either change the Tensorforce code [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/agents/ppo.py#L263) or copy-paste the [PPO specification](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/agents/ppo.py#L281) of the `TensorforceAgent` and adapt the `objective` argument. In either case, the option you need to add is `early_reduce=False`. I'm not sure whether there are other differences between Tensorforce PPO and the paper, but if so, these may be a bit more difficult to replicate. Since it answers the question about hybrid continuous+discrete action space, I will close this.

**Comment by YingxiaoKong** [comment]
Thanks for your reply! Can you still see this comment?

 By saying 'early_reduce=False', did you mean this one?
            reward_estimation = dict(
                horizon='episode', discount=discount,
                estimate_horizon=(False if critic_network is None else 'early'),
                estimate_terminal=estimate_terminal, estimate_advantage=True
            )

Need to be changed to:
            reward_estimation = dict(
                horizon='episode', discount=discount,
                estimate_horizon=False,
                estimate_terminal=estimate_terminal, estimate_advantage=True
            )

**Comment by YingxiaoKong** [comment]
I think I misunderstood what You meant before. I guess I need to add early_reduce=False in the objective dict like:         
objective = dict(
            type='policy_gradient', ratio_based=True, clipping_value=likelihood_ratio_clipping, early_reduce = False)

**Comment by AlexKuhnle** [comment]
Yes exactly, your second message is what I meant.

**Comment by YingxiaoKong** [comment]
Thank you for your reply! I just added it to the objective in PPO.py. Hopefully it will do some nice work.

在 2020年5月12日，上午6:07，Alexander Kuhnle <notifications@github.com> 写道：

﻿

Yes exactly, your second message is what I meant.
