### ISSUE TITLE
Does Tensorforce require a normalized action space?

### ISSUE THREAD

**Issue by CristianMonea** [tensorforce/tensorforce#678]
I am learning to use OpenAI Gym to make a custom environment with continuous action and observation spaces and apply reinforcement learning algorithms using the Tensorforce library. The problem is that the action space must be normalized (values in the [-1, 1] interval) in order to work; otherwise, when using the required (not normalized) values, it gives an error.

These are the lines I'm using:

```
self.action_space = spaces.Box(np.array([4.6, 80.0]), np.array([4.8, 180.0]), dtype=np.float32) # Gives error 
self.action_space = spaces.Box(np.array([-1, -1]), np.array([1, 1]), dtype=np.float32) # OK, but not desired
```
The error I get when using the required (not normalized) values:

```
File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\environments\openai_gym.py", line 378, in unflatten_action
    if np.isinf(action).any() or np.isnan(action).any():

TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
where action is {'2'}.

Is there something I'm missing here? Or does OpenAI Gym or Tensorforce work only with normalized action values? If so, why? And how can this be avoided?

**Comment by AlexKuhnle** [comment]
Hi,
this looks like it may be a bug on side of Tensorforce when un-/wrapping from/to the Gym space format, since the action in these lines should not be `{'2'}`. I'll check and fix if needed...

**Comment by AlexKuhnle** [comment]
Could you try the latest master commit? I think there was indeed a bug which should now be solved.

**Comment by CristianMonea** [comment]
I get the following error:

```
Traceback (most recent call last):

  File "c:\users\user\reinforcement learning\rl.py", line 188, in <module>
    states, done, reward = environment.execute(actions=actions) # La Gym este states, rewards, done

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\environments\environment.py", line 377, in execute
    states, terminal, reward = self.environment.execute(actions=actions)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\environments\openai_gym.py", line 224, in execute
    actions = OpenAIGym.unflatten_action(action=actions)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\environments\openai_gym.py", line 409, in unflatten_action
    return np.array(object=actions).reshape(shape=shape)

TypeError: 'shape' is an invalid keyword argument for this function
```

**Comment by AlexKuhnle** [comment]
Hmm, wrongly using a keyword argument it seems. I'm surprised I haven't come across this problem before -- doesn't seem to be a super-specific Gym space configuration... Hope it works now, and sorry for that.

**Comment by CristianMonea** [comment]
It generates the correct actions, however they seem to be packed as a Numpy array of dictionaries and the assert function cannot properly verify them.

The function:

```
def step(self, action):
        assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action))
```

gives the following error:
```
File "C:\Users\User\Anaconda3\lib\site-packages\gym\spaces\box.py", line 115, in contains
    return x.shape == self.shape and np.all(x >= self.low) and np.all(x <= self.high)

TypeError: '>=' not supported between instances of 'dict' and 'float'
```
where `self.action` is:

`array([{'2': 4.6708026}, {'2': 94.08409}], dtype=object)`

If I used a normalized action space, it is e.g.:

`array([-0.31074834,  0.55088663], dtype=float32)`

This may be a bug. Otherwise, I will have to implement the assert function in a try-except block and evaluate it as an array of dictionaries in the except block.

**Comment by AlexKuhnle** [comment]
I think I found the problem, have a look at the latest commit. The unit-tests didn't include a Box space with varying min/max_value, it seems...

**Comment by CristianMonea** [comment]
Thank you. It is fine now.

**Comment by AlexKuhnle** [comment]
Great, thanks for reporting! Closing then...
