### ISSUE TITLE
Agent does not learn in continuous environments

### ISSUE THREAD

**Issue by CristianMonea** [tensorforce/tensorforce#681]
Hello! I've tried several agents provided by Tensorforce (like PPO, TRPO, VPG, others) on continuous environments such as `LunarLanderContinuous-v2` and `BipedalWalker-v3`. I've used thousands of training episodes and saw that no learning is performed. Basically, the total reward after each episode is the same as when the training started and is similar to that of the random agent; also, the evaluation of the "trained" agent shows poor results. 

What is the issue? Can someone confirm this?

This is my code:

```
import os
import logging
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensorforce.execution import Runner

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
logger = tf.get_logger()
logger.setLevel(logging.ERROR)

NUM_EP_TRAIN = 6000

ENV = 'LunarLanderContinuous-v2'
#ENV = 'BipedalWalker-v3'

AGENT_NAME = 'agent_test_lunarLanderCont'
#AGENT_NAME = 'agent_test_bipedalWalker'

def PlotData(pltNo, timeX, timeY, time_x_label, time_y_label, legend1=None, title=None):
    plt.close(pltNo)
    fig = plt.figure(pltNo)
    fig.canvas.set_window_title(title)
    
    subplot1 = fig.add_subplot(1,1,1)
    
    if (legend1 is not None):
        subplot1.plot(timeX, timeY, label=legend1)
    else:
        subplot1.plot(timeX, timeY)
    subplot1.set_ylabel(time_y_label)
    subplot1.set_xlabel(time_x_label)
    if (legend1 is not None):
        subplot1.legend(loc='upper right')
 
    fig.tight_layout()
    plt.show()
    
def main():
    # Create an OpenAI-Gym environment
    environment = Environment.create(environment='gym', level=ENV, visualize=False)

    agent = Agent.create(agent='ppo', environment=environment, batch_size=32) 
    #agent = Agent.create(agent='trpo', environment=environment, batch_size=32)
    #agent = Agent.create(agent='vpg', environment=environment, batch_size=32)
    #agent = Agent.create(agent='a2c', environment=environment, discount=0.9, batch_size=32)
    #agent = Agent.create(agent='random', environment=environment)
    
    runner = Runner(agent=agent, environment=environment)
    runner.run(num_episodes=NUM_EP_TRAIN)
    
    print("\nLearning finished. Total episodes: {ep}. Average reward of last 100 episodes: {ar}.".format(ep=runner.episodes, ar=np.mean(runner.episode_rewards[-100:])))
    
    PlotData(1, 
              timeX = np.linspace(1, runner.episodes, runner.episodes), 
              timeY = runner.episode_rewards, 
              time_x_label = 'Episode', 
              time_y_label = 'Total reward')
    
    runner.close()
    environment.close()
    agent.close()
    
if __name__ == '__main__':
    main()
```

**Comment by Luca96** [comment]
Hi. Try to train the agent for more episodes, like 100k. You can also increase the policy network's capacity (e.g more layers and units) if the results are still not good.

Cheers.

**Comment by AlexKuhnle** [comment]
Agree with @Luca96, and it's generally worth mentioning that the default parameters are by no means expected to work out of the box on a variety of problems, and different parameters may work better for different problems. It can take quite some time to investigate both environment and agent behavior and figure out what works best.

**Comment by CristianMonea** [comment]
I've tried training on 100k episodes. It took 10 hours and the agent appears to learn something, although I would have expected better performance taking into account the very long training time. See reward plot below.

https://ibb.co/nQMJrdH

I guess I'll have to search for the optimal parameters to speed things up.

**Comment by AlexKuhnle** [comment]
Which environment is this? It looks like it reaches this performance level very quicky... Certainly not a bad starting point to tune, and if you post the config, maybe I can give a few tips what might be interesting to play around with. But I assume this issue can be closed... (re-open if not, and feel free to still continue the conversation)
