### ISSUE TITLE
How to load a supervised pre-trained model 

### ISSUE THREAD

**Issue by fanbbbb** [tensorforce/tensorforce#682]
I have trained a supervised tensorflow model by some data. The model accepts obs as input, and action as output (thinking the model as a classified model).

1. And now I want to load this model to initialize a tensorforce agent (PPO agent).
2. Or whether can I train a train a supervised model which has the same operation name as tensorforce model, then I can load the supervised model by `TensorforceAgent.load()`

An old related issue is #357 #363 

Any advice will be grateful. Thanks

**Comment by fanbbbb** [comment]
I found the api `TensorforceAgent.assign_variable(variable, value)` of tensorforce from [https://tensorforce.readthedocs.io/en/latest/agents/agent.html?highlight=variable#tensorforce.agents.TensorforceAgent.assign_variable](url).

I trained a supervised model, and then read the variables which used to assign to the agent by `agent.assign_variable()`.

**Comment by AlexKuhnle** [comment]
I seem to have missed this issue. Usually I try to answer within 1-3 days, sorry for that. But you're right, `assign_variable` is how to achieve what you want. Maybe there will be a "Keras network" with a simple way of loading a model into Tensorforce in the near future, but haven't started looking into that.
