### ISSUE TITLE
Calling agent.act must be preceded by agent.observe when running a customized environment

### ISSUE THREAD

**Issue by YingxiaoKong** [tensorforce/tensorforce#683]
**Hi,

I used the customized environment from: https://github.com/tensorforce/tensorforce/issues/669#issuecomment-619554479**

from tensorforce.environments import Environment
import numpy as np

class CustomEnvironment(Environment):

    def __init__(self):
        super().__init__()

    def states(self):
        return dict(type='float', shape=(8,))

    def actions(self):
        return dict(type='int', num_values=4)

    # Optional, should only be defined if environment has a natural maximum
    # episode length
    def max_episode_timesteps(self):
        return super().max_episode_timesteps()

    # Optional
    def close(self):
        super().close()

    def reset(self):
        state = np.random.random(size=(8,))
        return state

    def execute(self, actions):
        assert 0 <= actions.item() <= 3
        next_state = np.random.random(size=(8,))
        terminal = np.random.random() < 0.5
        reward = np.random.random()
        return next_state, terminal, reward

environment = Environment.create(
    environment=CustomEnvironment, max_episode_timesteps=10
)

**### I run the episode here:**
for _ in range(10):
    score=0
    print('episode: '+str(_))
    states = environment.reset()
    all_s.append(states)
    terminal = False
    while not terminal:
        actions = agent.act(states=states)
        states, terminal, reward = environment.execute(actions=actions)
        score+=reward       
        agent.observe(terminal=terminal, reward=reward)
**And then it gives some error:**
---------------------------------------------------------------------------
TensorforceError                          Traceback (most recent call last)
<ipython-input-11-58dffb0ff9ad> in <module>
      6     terminal = False
      7     while not terminal:
----> 8         actions = agent.act(states=states)
      9         states, terminal, reward = environment.execute(actions=actions)
     10         score+=reward

~\Anaconda3\envs\tensorforce\lib\site-packages\tensorforce\agents\agent.py in act(self, states, internals, parallel, independent, deterministic, evaluation, query, **kwargs)
    470 
    471         if not independent and not all(self.timestep_completed[n] for n in parallel):
--> 472             raise TensorforceError(message="Calling agent.act must be preceded by agent.observe.")
    473 
    474         # Auxiliaries

TensorforceError: Calling agent.act must be preceded by agent.observe.  

**I'm trying to build a hybrid action space environment, The example above is a discrete one I guess. I also tried to build one in gym.
The customized environment looks like:**

  import gym
from gym import error, spaces, utils
from gym.utils import seeding
import numpy as np
import logging
log = logging.getLogger(__name__)
log.info('%s logger started.',__name__)
print('version: UAV_v5')
print('hybrid action space ')
class UAVenv(gym.Env):
  
    metadata = {'render.modes': ['human']}
    def __init__(self):
#         super(UAVenv, self).__init__()
#### in the action space, the first one is angle change, the second one is speed change.
        self.action_space = spaces.Tuple(spaces=
        (spaces.Box(low=-1,high=1,shape=(3,),dtype=np.float32),spaces.Discrete(n=3)))
        self.observation_space = spaces.Box(\
            low=np.array([-10,-10,-10,-10]), high=np.array([100,100,100,100]), dtype=np.float16)
        self.state=[]
        self.count=0
        self.reward = 0
        self.done = False
        self.des = np.array([100,5])
        self.action_list = np.array([100,200,300])
    
    def step(self, action):
        self.count+=1
        done =False
        v = np.squeeze(action)
        print('action: '+str(type(v)))
        new_state = np.zeros_like(self.state)
        print('action 1: '+str(v[0]))
        print('action 2 : '+str(v[1]))
        print('first action: '+str(v[0][0]))
        new_state[0] = self.state[0]+v[0][0]
        new_state[1] = self.state[1]+v[0][1]
        new_state[2] = self.state[2]+v[0][2]
        new_state[3] = self.state[3]+self.action_list[v[-1]]
        self.state = new_state
        self.reward = -1
        return self.state,self.reward,done,{}
    def reset(self):
        self.count=0
        ini_angle = np.random.uniform(low = 0.,high = 1.)
        ini_speed = 2.
        ### it's very important to write the initial value in float format, otherwise 
        ### it would be considered as interger
        ini_x = 0.
        ini_y = 0.
        self.state =np.array([ini_angle,ini_speed,ini_x,ini_y]) 
        self.v0 = self.state[0]
        return self.state
        
    def render(self, mode='human', close=False):
        ### this one we just leave it like this.
        pass  
**The code to create the environment and run the episode is as below:**
import os
import logging

import tensorflow as tf

from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensorforce.execution import Runner

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
logger = tf.get_logger()
logger.setLevel(logging.ERROR)

import gym
import UAV_3
env_original = gym.make('UAV-v5')
all_all_s=[]
all_score=[]
for _ in range(10):
    all_s=[]
    score=0
    print('episode: '+str(_))
    states = environment.reset()
    all_s.append(states)
    terminal = False
    while not terminal:
        actions = agent.act(states=states)
#         print('action: '+str(actions))
        states, terminal, reward = environment.execute(actions=actions)
        score+=reward
        all_s.append(states)
#         print('reward '+str(reward))
#         print('states: '+str(states))
        agent.observe(terminal=terminal, reward=reward)
    all_all_s.append(all_s)
    all_score.append(score)

**The error is like:**
---------------------------------------------------------------------------
TensorforceError                          Traceback (most recent call last)
<ipython-input-9-37fc62fb2a3e> in <module>
      9     terminal = False
     10     while not terminal:
---> 11         actions = agent.act(states=states)
     12 #         print('action: '+str(actions))
     13         states, terminal, reward = environment.execute(actions=actions)

~\Anaconda3\envs\tensorforce\lib\site-packages\tensorforce\agents\agent.py in act(self, states, internals, parallel, independent, deterministic, evaluation, query, **kwargs)
    470 
    471         if not independent and not all(self.timestep_completed[n] for n in parallel):
--> 472             raise TensorforceError(message="Calling agent.act must be preceded by agent.observe.")
    473 
    474         # Auxiliaries

TensorforceError: Calling agent.act must be preceded by agent.observe.

**This one has the same error as the one above. But I didn't have this kind of error when I just create a continuous action space environment and registered is in gym. Do you know what may be the reason?**

**Comment by YingxiaoKong** [comment]
I just figured out that I made a tiny mistake. Now both of them works.

**Comment by MANU-CHAUHAN** [comment]
> I just figured out that I made a tiny mistake. Now both of them works.

What was the error? I am new to TensorForce and getting same issue... not sure if the current version has changed few steps. Will have to check that as well.
