### ISSUE TITLE
AttributeError: 'StepEnv' object has no attribute 'stepsize'

### ISSUE THREAD

**Issue by DroneMesh** [tensorforce/tensorforce#685]
Hi,

I am running your quickstart demo on a custom gym I don't know what the` Enviroment.create` is looking for exactly to fix it. Any help in the right direction would be very useful.

Error:
`AttributeError: 'StepEnv' object has no attribute 'stepsize'
`
Thanks in advanced.

**Comment by AlexKuhnle** [comment]
Hi,
You can find out more about `Environment.create` [here](https://tensorforce.readthedocs.io/en/latest/basics/getting-started.html#initializing-an-environment). Could you post the relevant lines of code where you try to initialize the environment Also, `StepEnv` and `stepsize` don't seem to come from Tensorforce, but likely Gym-internal classes/attributes (assuming it's not in your code either). If you haven't updated Gym for a while, maybe also worth doing that, just to be sure.

**Comment by AlexKuhnle** [comment]
Any updates? Re-open if still an issue...
