### ISSUE TITLE
Again Custom Metrics for Tensorboard

### ISSUE THREAD

**Issue by chenyu97** [tensorforce/tensorforce#690]
When I am using this code:

```
Agent.create(...
    summarizer=dict(
        directory='data/summaries',
        # list of labels, or 'all'
        labels=['graph', 'entropy', 'kl-divergence', 'losses', 'rewards'],
        frequency=100,  # store values every 100 timesteps
        # (infrequent update summaries every update; other configurations possible)
        custom=dict(  # custom summaries which need to be recorded explicitly
            custom_summary1=dict(type='image', max_outputs=10), ...
        )
    ), ...
)
```

Why do I have the following error? It seems that 'custom' is not allowded to use in 'summarizer'?

> hint='not from {directory,flush,frequency,labels,max-summaries}'

> tensorforce.exception.TensorforceError: Invalid value for agent argument summarizer: directory,labels,frequency,custom not from {directory,flush,frequency,labels,max-summaries}.

Thanks！

**Comment by chenyu97** [comment]
> Hi, could you check whether you're on the latest master version? It should work there... Or are you on the pip version? If so, that should definitely be updated, thanks for letting me know.

It does work when I turn to the latest master version later on. 
And I think the pip version is not the latest version.
Thanks very much!

**Comment by AlexKuhnle** [comment]
Great. The pip version hasn't been updated for a while, but will happen soon.
