### ISSUE TITLE
full-feature example

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#691]
Do you think it would be possible to have a 'full-feature' example demonstrating 'all' goodies obtainable from tensorforce, including saving automatically, parallel training, etc? Something like an extension of this:

https://github.com/tensorforce/tensorforce/blob/master/examples/temperature-controller.ipynb

But maybe temperature-controller_full_features.ipynb ? :)

I think it would be helpful, because there are many very nice features of tensorflow that are available but maybe it is not clear always what is the intended use / best practice. I know this is what tests show, but this is quite spread around :) .

**Comment by AlexKuhnle** [comment]
More docs and examples have been, and will continue to be added, so I think this can be closed.
