### ISSUE TITLE
unbound actionspace in env result in nan actions

### ISSUE THREAD

**Issue by stheid** [tensorforce/tensorforce#696]
I have an environment that implements the OpenAI Gym interface, hence i load it with the openai gym env wrapper.

when my env returns an unbounded actionspace
```python
self.action_space = gym.spaces.Box(low=np.full(d_i, -np.inf), high=np.full(d_i, np.inf))
```

```
Episodes:   0%|                                                                                                                                     | 0/10 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]Traceback (most recent call last):
  File "/home/sheid/sheid/openmodelica-microgrid-gym/experiments/PPO/tensorforce_exp/main.py", line 22, in <module>
    runner.run(num_episodes=10)
  File "/home/sheid/miniconda3/envs/openmodelica-microgrid-gym-py37/lib/python3.7/site-packages/tensorforce/execution/runner.py", line 469, in run
    observation = self.environments[n].receive_execute()
  File "/home/sheid/miniconda3/envs/openmodelica-microgrid-gym-py37/lib/python3.7/site-packages/tensorforce/environments/environment.py", line 325, in receive_execute
    states, terminal, reward = self.execute(actions=self._actions)
  File "/home/sheid/miniconda3/envs/openmodelica-microgrid-gym-py37/lib/python3.7/site-packages/tensorforce/environments/environment.py", line 366, in execute
    states, terminal, reward = self.environment.execute(actions=actions)
  File "/home/sheid/miniconda3/envs/openmodelica-microgrid-gym-py37/lib/python3.7/site-packages/tensorforce/environments/openai_gym.py", line 220, in execute
    actions = OpenAIGym.unflatten_action(action=actions)
  File "/home/sheid/miniconda3/envs/openmodelica-microgrid-gym-py37/lib/python3.7/site-packages/tensorforce/environments/openai_gym.py", line 379, in unflatten_action
    raise TensorforceError("Action contains inf or nan.")
tensorforce.exception.TensorforceError: Action contains inf or nan.
```

## Workaround

when my env returns a bounded actionspace
```python
self.action_space = gym.spaces.Box(low=np.full(d_i, -10e24), high=np.full(d_i, 10e24))
```
everything seems to run fine

**Comment by stheid** [comment]
Unbounded observation spaces however cause no issues!

```python
self.observation_space = gym.spaces.Box(low=np.full(d_o, -np.inf), high=np.full(d_o, np.inf))
```

**Comment by AlexKuhnle** [comment]
I will have a look at that, likely something related to a recent change I made. It's on the `tf2` branch, right? And could you mention again which line causes problems? Because your last message seems to say that it doesn't cause problems, but it looks the same as the first one...

**Comment by stheid** [comment]
no, **pypi package**v0.5.4. i was able to revert my python dependency and was therefore capable to use everything on python 3.7

**Comment by AlexKuhnle** [comment]
That's most likely due to my recent changes, I will investigate.

**Comment by AlexKuhnle** [comment]
Could you try it again? Haven't found a suitable Gym env with inf action space (the standard ones all use bounded spaces), but I fixed something which I think may have caused the problem.

**Comment by stheid** [comment]
in which branch. you did not link the issue in the commit

**Comment by stheid** [comment]
i checked out this commit d09d047130bd3565205a62bfc80f3306470ca2e5

seems to work, but only if i use tf2.2 (at least it crashes with 2.0.1 which i had previously installed.)!

**Comment by AlexKuhnle** [comment]
Yes, that's the commit I meant. Really, it crashes with TF2.0? Sorry for that, I really hoped that TF2 would not have such inconsistencies between versions anymore... :-/

**Comment by bezineb5** [comment]
I also had issues with version 2.1, it was missing an import in tf.python if I remember correctly. However, I'm perfectly fine with tf 2.2 as minimum requirement.
