### ISSUE TITLE
Cannot retrieve action tensor using 'retrieve' special layer

### ISSUE THREAD

**Issue by lviala** [tensorforce/tensorforce#697]
Hi,

I am want to feed the previous action tensor as an input to a Multi-input network. When trying to define the network as a list of layer lists in the following way:
```
network = [
    [   
        dict(type='retrieve', tensors='state'),
        ...
        dict(type='register' , tensor ='intermed-1')
    ],
    [   
        dict(type='retrieve', tensors='action'),
        ...
        dict(type='register' , tensor ='intermed-2')
    ],
    [
        dict(type='retrieve', tensors=['intermed-1','intermed-2'], aggregation='concat'),
        ...
    ]
]
```

I get the following error: `TensorforceError: Invalid value for Module.get_tensor_spec argument name: action.` Is there a way to gracefully pass the action tensor as an input to a layer?

Thanks!

**Comment by AlexKuhnle** [comment]
Hi, it's not possible to pass the action as input to a layer, since the network is used to parametrize the action distribution (so the action is not yet known at the time of the network being applied). What is the idea here? Is this the baseline which is supposed to use the action? Or do you mean to access the action of the previous timestep?

**Comment by lviala** [comment]
Hi, thanks for the response!

I am working on RL for continuous control of partially observable systems.

The idea is to feed the action of the previous timestep to the policy network, as well as the current state, much in the same fashion as done in this paper: [https://openreview.net/pdf?id=SklPFVXUsN](url) (which I believe you have co-authored), or this paper [https://arxiv.org/pdf/1704.07978](url).

I wanted to see if there was a graceful way to access the action of the previous timestep directly within the policy network definition.

**Comment by AlexKuhnle** [comment]
Okay, I see. Right now, the way this can be done is to implement a suitable mechanism on the environment side: expand the state space to include the action as well (e.g. `dict(state=dict(...), action=dict(...))`), then include the action as part of the next state in `execute()`. However, it makes me think that this could also be provided as a feature from Tensorforce side (after all, it can be annoying to have to write this env wrapper)... Need to look more into this, so the short answer for now is what I outlined above about extending the state space and manually including the action.

**Comment by lviala** [comment]
Fair enough, that is what I figured. It was easy enough to implement and works well.

Thank you for the help!
