### ISSUE TITLE
Pretrain data structure extremely sensitive

### ISSUE THREAD

**Issue by stheid** [tensorforce/tensorforce#700]
I tried to create my own trajectories by first recording some trajectories and than create my trace files to align exactly with the .npz files that the recorder produces. [doc](https://tensorforce.readthedocs.io/en/latest/basics/features.html#record-pretrain)

Strangely even the datatypes have to match **exactly**. if the states, e.g., are of type float64 instead of float32 the pretrain fails with a completely odd error
![image](https://user-images.githubusercontent.com/2736207/84645537-057b0d80-af01-11ea-8670-22b59b8aaaf2.png)

i think it would be possible to reproduce it by simply changing the datatype in the trajectory files that are generated by the recorder.

i used a similar PPO script like in #699

**Comment by stheid** [comment]
maybe this was only coincidence. i tried so many things. the most crucial thing seems to be the prefix 'trace-' of the filenames in the folder.

**Comment by stheid** [comment]
its only a documentation issue. works definetly also with float 64!

**Comment by AlexKuhnle** [comment]
Thanks for reporting, I will have a look and improve docs (or in that case rather dtype-tolerance). Could you mention what exactly were counter-intuitive problems, besides potential silent expectations of dtypes?

**Comment by stheid** [comment]
So it would be good to mention that the trace file needs to obey the following structure:
- filename must start with "trace-"  [this was my biggest confusion]
- it must contain the 4 numpy arrays with the following names and shapes
['state', 'action', 'terminal', 'reward']
(n, inputdim) float32
(n, outputdim) float32
(n,) int64 (booleanarray.astype(int))
(n,) float32

**Comment by stheid** [comment]
Are you sure that pretraining works properly in the version of the master? To be honest, i am not even sure how i would validate that. I export all variable to tensorboard.

![image](https://user-images.githubusercontent.com/2736207/84664016-374e9d00-af1e-11ea-88b3-bb4d311c27fb.png)
For example how can the empirical reward be constant and 5 magnitutes larger than the worst reward i have in the pretrain trajectories (about -2)

**Comment by AlexKuhnle** [comment]
Need to look more at this, but general comment: The current pretrain implementation is very simplistic, it just uses `experience` to fill the agent's memory/buffer and `update` to perform updates (which is basically the same as what happens during normal training interactions). In particular the policy right now is not trained in a supervised fashion, which is probably not optimal I realized recently, and so I hope to improve it soon. I'd be happy to look into it very soon if you want to test it out -- makes development much easier if there's a user working on a real use case for the feature.

There should probably be two versions of "pretrain": one which assumes expert demonstrations and pretrains the policy in a more supervised fashion, another which just assumes interaction traces and might work in the way the current function works, more "unsupervised".

Regarding whether the feature is working: I was definitely able to test the feature on CartPole with some success, but that was before the developments towards version 0.6.

**Comment by stheid** [comment]
i should be able to pretrain in supervised manner and use the save/load to provide the agent with my pretrained policy, right? maybe this is a good workarround/startingpoint for now. But thanks a lot for your comments!

**Comment by AlexKuhnle** [comment]
Yes, that should also be possible. If you're interested in doing that, would you be okay with testing a Tensorforce implementation of the same / similar functionality in a few days? It shouldn't take me too long to put it together...

**Comment by stheid** [comment]
that would be cool.

**Comment by AlexKuhnle** [comment]
I've started looking more into this. First, the existing implementation should make sense, however, if a critic/baseline is used, this method of pretraining is rather sensitive. I also have two ideas for small modifications to make the function more customizable, will let you know if/when they are implemented.

For now, I played around with the PPO CartPole script, first recording:

```python
from tensorforce import Runner

runner = Runner(
    agent=dict(agent='benchmarks/configs/ppo1.json', recorder=dict(directory='ppo1-traces', start=100)),
    environment='benchmarks/configs/cartpole.json'
)
runner.run(num_episodes=200)
runner.close()
```

Then pretraining, and it seems to learn to 500 in only 10 iterations:

```python
from tensorforce import Agent, Environment, Runner

environment = Environment.create(environment='benchmarks/configs/cartpole.json')
agent = Agent.create(agent='benchmarks/configs/ppo1.json', environment=environment)
agent.pretrain(directory='ppo1-traces', num_iterations=10, num_traces=1, num_updates=1)
runner = Runner(agent=agent, environment=environment)
runner.run(num_episodes=100, evaluation=True)
runner.close()
agent.close()
environment.close()
```

**Comment by stheid** [comment]
It makes a lot of sense to allow to record the data within tensorforce. Stable baseline offers a simmilar function for their pretraining. However the recording function should also allow to use agents that are not created by tensorforce. e.g. Stable baselines recorder function only needs a "act function" that is feed with the state and whose action is recorded. Therefore it is fairly easy to create the pretrain data from a teacher agent that is not part of the tensorforce ecosystem.

https://stable-baselines.readthedocs.io/en/master/guide/pretrain.html#generate-expert-trajectories

**Comment by AlexKuhnle** [comment]
Interested, and yes, that makes a lot of sense. I'll think about how to integrate that best. Shouldn't be a problem to offer something similar.

Also, fyi, related issue: https://github.com/tensorforce/tensorforce/issues/708

**Comment by AlexKuhnle** [comment]
It is now possible to record interaction traces for a (non-Agent) act-function, see [docs](https://tensorforce.readthedocs.io/en/latest/basics/features.html#record-pretrain). I think this can be closed now.
