### ISSUE TITLE
Error evaluating imported "pb-actonly" model

### ISSUE THREAD

**Issue by pintaric** [tensorforce/tensorforce#705]
Affected version: [0.5.5](https://github.com/tensorforce/tensorforce/releases/tag/0.5.5)

I'm exporting a trained model using `format='tensorflow'`: 
```
agent = Agent.create(agent='ppo', ...)
# Run training...
agent.save(filename='model', format='tensorflow')
```

Later, I'm importing the model again, this time using `format='pb-actonly'`, which will create an `ActonlyAgent` instance.

```
actonly_agent = Agent.load(filename='model', format='pb-actonly')
```

However, **evaluating the imported model fails**, whereas evaluating the original model succeeds.
```
observation = numpy.zeros(shape=(n,), dtype=numpy.float) # create a dummy observation
agent.act(states=observation, evaluation=True) # succeeds
actonly_agent.act(states=observation, evaluation=True) # fails (see error below)
```

The following error message is generated:
```
File "[...]/python3.7/site-packages/tensorforce/agents/agent.py", line 1101, in act
    batched = (np.asarray(states[name]).ndim > len(self.states_spec[name]['shape']))
KeyError: 'type'
```

Upon closer inspection, I noticed that `Agent` stores the model's JSON states/actions metadata differently than `ActonlyAgent`:

**ActonlyAgent** ([agent.py, Line 1056](https://github.com/tensorforce/tensorforce/blob/0.5.5/tensorforce/agents/agent.py#L1056)):
```
self.states_spec = states
self.actions_spec = actions
```

**Agent** ([agent.py, Line 209](https://github.com/tensorforce/tensorforce/blob/0.5.5/tensorforce/agents/agent.py#L209))
```
self.states_spec = util.valid_values_spec(
  values_spec=states, value_type='state', return_normalized=True
)
self.actions_spec = util.valid_values_spec(
  values_spec=actions, value_type='action', return_normalized=True
)
```

After patching the code in ActonlyAgent's constructor to use `util.valid_values_spec` (see above), I can now evaluate my imported model as follows:
```
observation = numpy.zeros(shape=(n,), dtype=numpy.float) # create a dummy observation
actonly_agent.act(states=observation, evaluation=True) # still does not work
actonly_agent.act(states=dict(state=observation), evaluation=True) # this works now!
```

Is this a bug, or am I doing something wrong?

**Comment by AlexKuhnle** [comment]
I think you're right, there's a problem with how the agent config is stored. The single-state case is internally transformed to `dict(state=...)`, and since the optimized PB model version file needs to be called that way, I would say it's better to keep it that way, even if it means that what works for the main Tensorforce agent (pass single states) doesn't work anymore for the PB version. This may be improved in version 0.6+, but a few things will change here anyway.

Despite this small inconsistency, it would be great to include your fix. Would you mind creating a PR for that?

**Comment by AlexKuhnle** [comment]
Closing since inactive.
