### ISSUE TITLE
Trying to export variables from the environment.

### ISSUE THREAD

**Issue by junwoony** [tensorforce/tensorforce#712]
I'm using a gym-based environment and tensorforce agent/runner to run it using multiprocess. If my environment is built like,

```
class MyEnv():
    ....
    self.variable (but not one of state variables)
    ....

```
how can I look up the `self.variable` in callback when the variable is not in the state space.
I could do this by something like `runner.environments[0].environment.environment.env.variable` when I use a single environment. However, when I run the model in parallel (multiprocessing), I can no longer to this because "MultiprocessingEnvironment" object has no attribute environment. 
Please share with me if there is a cool way to do this. 
Thank you

**Comment by AlexKuhnle** [comment]
For non-remote environments, attribute lookups should be passed on to the internal environment object (see [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/environments/environment.py#L386)). Is that not working? Note that currently only getting is possible, not setting (do you want to write as well?). I need to check, but it shouldn't be too problematic to implement something similar for remote environments (obvs there is a computational cost to it in that case).

**Comment by junwoony** [comment]
It works for non-remote env, but my env is remote. Can you check if there's a way to look up internal environment attribute/variable for remote env?

**Comment by junwoony** [comment]
Or is there a way to choose state variables that I'm interested in for learning?
For example, if my state space is consist of `(state_1, state_2, state_3, etc.)`, can I only choose `state_1` and `state_3` for training and disregard the rest? Sometimes variables not used for learning are also useful to analyze results.

**Comment by AlexKuhnle** [comment]
No, this is unfortunately not possible. However, the attribute lookup should definitely be possible, I just didn't have the time yet to implement it. Also, I had a look at the current implementation, and I think arbitrary function calls should actually be possible via:
```python
environment.send(function='FN_NAME', **kwargs)
outputs = self.receive(function='FN_NAME')
```
So if you wrap the attributes in getter functions, that may already work.

**Comment by junwoony** [comment]
Hmm not quite sure how I can try this. So I ended up with saving attributes directly from the gym environment (not the ideal way tho). :)
Thank you!

**Comment by AlexKuhnle** [comment]
It should now be possible to access (and write) attributes from/to remote environments arbitrarily.
