### ISSUE TITLE
Readme tensorflow flag has disappeared

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#714]
It looks like the relevant ```[]``` addition to make sure the right tensorflow version is installed together with pip has disappeared from the readme, may be a good idea to put back?

**Comment by AlexKuhnle** [comment]
I realised recently that there are no two options for TF (CPU vs GPU) anymore since TF2. That's why TF is now included by default, instead of as before leaving it to the user to decide which version they want.
