### ISSUE TITLE
set up a dockerfile / docker container

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#717]
I think it may be a good idea to use a dockerfile / docker container to make sure things are easy to set up. I may have time in the next few days to take care of this @AlexKuhnle :) .

**Comment by AlexKuhnle** [comment]
Hey @jerabaul29, still planning to look into this, or shall we close it?

**Comment by jerabaul29** [comment]
@AlexKuhnle if you put the following in a file name ```Dockerfile``` , you should be able to build a working container.

```
# This container is for building a tensorforce image.
# 
# To build:
#     docker build .
# 
# To use:
# - find which docker container has been built:
#     $ sudo docker image ls -a
#     REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
#     <none>              <none>              567fffdc0afb        14 seconds ago      2.97GB
# - run, for example in interactive modus:
#     $ sudo docker run -it 567fffdc0afb /bin/bash

FROM ubuntu:20.04

RUN \
  apt-get update --fix-missing && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y apt-utils && \
  apt-get -y autoremove && \
  apt-get -y clean && \
  apt-get install -y python3-pip && \
  pip3 install tensorflow && \
  pip3 install matplotlib && \
  apt install -y git && \
  apt install -y vim && \
  apt install -y tmux && \
  apt install -y htop && \
  git clone https://github.com/tensorforce/tensorforce.git && \
  cd tensorforce && pip3 install -e . && cd ..
```

I just tested it now, works fine.

Do you want to create directly a ```docker/Dockerfile``` path with this content, or do you want a pull request?? :) .

**Comment by jerabaul29** [comment]
@AlexKuhnle what is your opinion there? :)

**Comment by AlexKuhnle** [comment]
Sorry, haven't had time to look at this yet, but if you say that does the job, I'm happy to integrate it via PR, and will try it at some point later (would be good to get familiar with Docker at some point... :-).

**Comment by bezineb5** [comment]
My 2 cents: it's not really useful to provide a Dockerfile for a library, as the user will anyway have to install its own application above it, and they'll likely have more python dependencies than tensorforce, so providing a dockerfile doesn't help in practice.

However, a simpler (but equivalent) dockerfile would be:
```dockerfile
FROM python:3.8
RUN pip install tensorforce
```

**Comment by jerabaul29** [comment]
OK :)

The reason why we though about this is that we had several projects where people had problems with their code because their local python install was not compatible / did not work well with the latest tensorforce. I agree these people were mostly not very experienced with programming, but still, they are part of the user base and having the dockerfile helped quite a bit.

Nice and shorter container :) But then it is very limited, right? I like the idea of having a bit more 'fluff' around so that it allows a bit of simple development. We could have a "minimal" and a "ubuntu-like" dockerfile maybe?

**Comment by AlexKuhnle** [comment]
Hmm, while I can see that the development "fluff" :-) is helpful, I don't think it should be part of the "Tensorforce Dockerfile", but up for the user to set up (no reason to be prescriptive about the use of VIM or so). If it's really just two lines to set up the container, then I agree that there's little reason for providing a Dockerfile (since it's a Python library, I think it's okay to expect the user to handle incompatibilities, particularly given that Python 2 is deprecated anyway). Maybe 1-2 lines in the install docs with copy-paste command line instructions for Tensorforce+virtualenv, and Tensorforce+Docker? I wouldn't mind providing a less minimal Dockerfile like yours, @jerabaul29, in the examples directory, as a starting point for people to customize if they have little Docker experience (like me :-).

**Comment by jerabaul29** [comment]
I think one difference with 'my' container is that it install from sources, which may be good or bad.

Whatsoever, we can well drop it if you think this is not necessary.

**Comment by AlexKuhnle** [comment]
I've now added a paragraph to the [installation docs](https://tensorforce.readthedocs.io/en/latest/basics/installation.html), with both the PyPI and the latest GitHub version. That should be enough to get started.
