### ISSUE TITLE
act-function mapping states to actions cann't work

### ISSUE THREAD

**Issue by mazelin** [tensorforce/tensorforce#723]
def fn_act(states):
    return 0

def run_best_math():
    environment = Environment.create(environment=mm_env, max_episode_timesteps=52)
    agent = Agent.create(agent=fn_act, recorder=dict(directory='math-best-traces'))
    runner = Runner(agent=agent,environment=environment)
    runner.run(num_episodes=100)
    runner.close()

when I run, I got error 'tensorforce.exception.TensorforceError: Invalid type for Agent.create argument agent: <class 'function'>.'
how to fix it?
tks!

**Comment by AlexKuhnle** [comment]
Hi @mazelin 
Is it possible that you use the pip version of Tensorforce, so v0.5.5? If so, then the solution right now is to use the Github version of Tensorforce instead, as this is a new feature and the current "beta" version of 0.6 has not yet been added as PyPI package.

**Comment by mazelin** [comment]
ok，thank you！

**Comment by AlexKuhnle** [comment]
Cool, closing this then.
