### ISSUE TITLE
Timeline for Stable Release v0.6.0

### ISSUE THREAD

**Issue by CantelopePeel** [tensorforce/tensorforce#724]
Inquiring about what the timeline (if there is one) for a stable release of version 0.6.0? Is there a set of features that are currently being closed out before a release of 0.6? I am just an interested party, and depending on what the timeline is, I can pitch in to get things to a stable release.

**Comment by AlexKuhnle** [comment]
Quick update: I expect that there won't be any more substantial changes before 0.6 (apart from maybe docs), and the version should be pinned in the next 1-3 days.

**Comment by AlexKuhnle** [comment]
Fixed version 0.6.0 now.
