### ISSUE TITLE
running error in anaconda

### ISSUE THREAD

**Issue by lyly0309** [tensorforce/tensorforce#727]
Hello Alex
I install the tensorforce( the latest verion by using git clone installation)  in anaconda on a windows 7 workstation with following environment:
`
jupyter_client            6.1.6                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py38_0
jupyterlab                2.1.5                      py_0
jupyterlab_server         1.2.0                      py_0
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   21.2.1                   py38_0
kiwisolver                1.2.0            py38h74a9793_0
krb5                      1.18.2               hc04afaa_0
lazy-object-proxy         1.4.3            py38he774522_0
libarchive                3.4.2                h5e25573_0
libcurl                   7.71.1               h2a8f88b_1
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_1
libxml2                   2.9.10               h464c3ec_1
libxslt                   1.1.34               he774522_0
llvmlite                  0.33.0           py38ha925a31_0
locket                    0.2.0                    py38_1
lxml                      4.5.2            py38h1350720_0
lz4-c                     1.9.2                h62dcd97_0
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1            py38he774522_0
matplotlib                3.3.1                         0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
matplotlib-base           3.3.1            py38hba9282a_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
mccabe                    0.6.1                    py38_1
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.1                      216
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.1.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.2                      py_0
more-itertools            8.4.0                      py_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.1.0                    py38_0
msgpack-numpy             0.4.6.1                  pypi_0    pypi
msgpack-python            1.0.0            py38h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py38_0
navigator-updater         0.2.1                    py38_0
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.7                      py_0
networkx                  2.4                        py_1
nltk                      3.5                        py_0
nose                      1.3.7                    py38_2
notebook                  6.0.3                    py38_0
numba                     0.50.1           py38h47e9c7a_0
numexpr                   2.7.1            py38h25d0782_0
numpy                     1.18.5           py38h6530119_0
numpy-base                1.18.5           py38hc3f5095_0
numpydoc                  1.1.0                      py_0
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0
openpyxl                  3.0.4                      py_0
openssl                   1.1.1g               he774522_1    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.4                       py_0
pandas                    1.0.5            py38h47e9c7a_0
pandoc                    2.10                          0
pandocfilters             1.4.2                    py38_1
paramiko                  2.7.1                      py_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0
path                      13.1.0                   py38_0
path.py                   12.4.0                        0
pathlib2                  2.3.5                    py38_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py38_0
pep8                      1.7.1                    py38_0
pexpect                   4.8.0                    py38_0
pickleshare               0.7.5                 py38_1000
pillow                    7.2.0            py38hcc1f983_0
pip                       20.1.1                   pypi_0    pypi
pkginfo                   1.5.0.1                  py38_0
pluggy                    0.13.1                   py38_0
ply                       3.11                     py38_0
powershell_shortcut       0.0.1                         3
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
prompt_toolkit            3.0.5                         0
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.7.0            py38he774522_0
py                        1.9.0                      py_0
py-lief                   0.10.1           py38ha925a31_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.6.0                      py_0
pycosat                   0.6.3            py38he774522_0
pycparser                 2.20                       py_2
pycurl                    7.43.0.5         py38h7a1dbc1_0
pydocstyle                5.0.2                      py_0
pyflakes                  2.2.0                      py_0
pyglet                    1.5.0                    pypi_0    pypi
pygments                  2.6.1                      py_0
pylint                    2.5.3                    py38_0
pynacl                    1.4.0            py38h62dcd97_1
pyodbc                    4.0.30           py38ha925a31_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py38ha925a31_4
pyreadline                2.1                      py38_1
pyrsistent                0.16.0           py38he774522_0
pysocks                   1.7.1                    py38_0
pytables                  3.6.1            py38ha5be198_0
pytest                    5.4.3                    py38_0
python                    3.8.3                he1778fa_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.34.1                   py38_0
python-libarchive-c       2.9                        py_0
pytz                      2020.1                     py_0
pywavelets                1.1.1            py38he774522_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.3.1            py38he774522_1
pyzmq                     19.0.1           py38ha925a31_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.5                      py_0
qtpy                      1.9.0                      py_0
regex                     2020.6.8         py38he774522_0
requests                  2.24.0                     py_0
requests-oauthlib         1.3.0                    pypi_0    pypi
rope                      0.17.0                     py_0
rsa                       4.6                      pypi_0    pypi
rtree                     0.9.4            py38h21ff451_1
ruamel_yaml               0.15.87          py38he774522_1
scikit-image              0.16.2           py38h47e9c7a_0
scikit-learn              0.23.1           py38h25d0782_0
scipy                     1.5.0            py38h9439919_0
seaborn                   0.10.1                     py_0
send2trash                1.5.0                    py38_0
setuptools                50.0.0                   pypi_0    pypi
simplegeneric             0.8.1                    py38_2
singledispatch            3.4.0.3                  py38_0
sip                       4.19.13          py38ha925a31_0
six                       1.15.0                     py_0
snappy                    1.1.8                h33f27b4_0
snowballstemmer           2.0.0                      py_0
sortedcollections         1.2.1                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
sphinx                    3.1.2                      py_0
sphinxcontrib             1.0                      py38_1
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sphinxcontrib-websupport  1.2.3                      py_0
spyder                    4.1.4                    py38_0
spyder-kernels            1.9.2                    py38_0
sqlalchemy                1.3.18           py38he774522_0
sqlite                    3.32.3               h2a8f88b_0
statsmodels               0.11.1           py38he774522_0
sympy                     1.6.1                    py38_0
tbb                       2020.0               h74a9793_0
tblib                     1.6.0                      py_0
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.3.0                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
tensorforce               0.6.0                     dev_0    <develop>
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
toolz                     0.10.0                     py_0
tornado                   6.0.4            py38he774522_1
tqdm                      4.48.2                   pypi_0    pypi
traitlets                 4.3.3                    py38_0
typing_extensions         3.7.4.2                    py_0
ujson                     1.35             py38he774522_0
unicodecsv                0.14.1                   py38_0
urllib3                   1.25.9                     py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py38_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1                      py_0
wheel                     0.34.2                   py38_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0                    py38_0
win_unicode_console       0.5                      py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py38he774522_0
xlrd                      1.2.0                      py_0
xlsxwriter                1.2.9                      py_0
xlwings                   0.19.5                   py38_0
xlwt                      1.3.0                    py38_0
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.2                ha925a31_2
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py38_1
zope.event                4.4                      py38_0
zope.interface            4.7.1            py38he774522_0
zstd                      1.4.5                ha9fde0e_0

(base) E:\DRL\boatNav-master\src\training> conda activate tensorforce

(tensorforce) E:\DRL\boatNav-master\src\training>conda list
# packages in environment at E:\anaconda3\envs\tensorforce:
#
# Name                    Version                   Build  Channel
_tflow_select             2.2.0                     eigen    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
absl-py                   0.4.1                    py35_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
astor                     0.7.1                    py35_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
blas                      1.0                         mkl    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
certifi                   2018.8.24                py35_1    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
gast                      0.4.0                      py_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
grpcio                    1.12.1           py35h1a1b453_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
icc_rt                    2019.0.0             h0cc432a_1    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
intel-openmp              2020.2                      254    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
libprotobuf               3.6.0                h1a1b453_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
markdown                  2.6.11                   py35_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
mkl                       2018.0.3                      1    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
mkl_fft                   1.0.6            py35hdbbee80_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
mkl_random                1.0.1            py35h77b88f5_1    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
numpy                     1.15.2           py35ha559c80_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
numpy-base                1.15.2           py35h8128ebf_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
pip                       20.2.2                   pypi_0    pypi
protobuf                  3.6.0            py35he025d50_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
python                    3.5.6                he025d50_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
setuptools                40.2.0                   py35_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
six                       1.15.0                     py_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
tbb                       2020.2               h74a9793_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
tbb4py                    2018.0.5         py35he980bc4_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
tensorboard               1.10.0           py35he025d50_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
tensorflow                1.10.0          eigen_py35h38c8211_0    https://mirrors.sjtug.sjtu.edu.cn/
anaconda/pkgs/main
tensorflow-base           1.10.0          eigen_py35h45df0d8_0    https://mirrors.sjtug.sjtu.edu.cn/
anaconda/pkgs/main
termcolor                 1.1.0                    py35_1    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
vc                        14.1                 h0510ff6_4    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
vs2015_runtime            14.16.27012          hf0eaf9b_3    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
werkzeug                  1.0.1                      py_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
wheel                     0.35.1                     py_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
wincertstore              0.2              py35hfebbdb8_0    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main
zlib                      1.2.11               h62dcd97_4    https://mirrors.sjtug.sjtu.edu.cn/anaco
nda/pkgs/main

(tensorforce) E:\DRL\boatNav-master\src\training>
`
**the error message is :**

'runfile('E:/DRL/boatNav-master/src/training/train_1D.py', wdir='E:/DRL/boatNav-master/src/training')
Reloaded modules: tensorforce.exception, tensorforce.util, tensorforce.environments.environment, tensorforce.environments.multiprocessing_environment, tensorforce.environments.socket_environment, tensorforce.environments.arcade_learning_environment, tensorforce.environments.openai_gym, tensorforce.environments.openai_retro, tensorforce.environments.open_sim, tensorforce.environments.pygame_learning_environment, tensorforce.environments.vizdoom, tensorforce.environments.carla_environment, tensorforce.environments, tensorforce.core.utils.tf_util, tensorforce.core.utils.nested_dict, tensorforce.core.utils.tensor_spec, tensorforce.core.utils.dicts, tensorforce.core.utils.tensors_spec, tensorforce.core.utils, tensorforce.core.config, tensorforce.core.module, tensorforce.core.parameters.parameter, tensorforce.core.parameters.constant, tensorforce.core.parameters.decaying, tensorforce.core.parameters.linear, tensorforce.core.parameters.ornstein_uhlenbeck, tensorforce.core.parameters.piecewise_constant, tensorforce.core.parameters.random, tensorforce.core.parameters, tensorforce.core.layers.layer, tensorforce.core.layers.convolution, tensorforce.core.layers.dense, tensorforce.core.layers.embedding, tensorforce.core.layers.input_rnn, tensorforce.core.layers.keras, tensorforce.core.layers.misc, tensorforce.core.layers.normalization, tensorforce.core.layers.pooling, tensorforce.core.layers.preprocessing, tensorforce.core.layers.rnn, tensorforce.core.layers.linear, tensorforce.core.layers, tensorforce.core.memories.memory, tensorforce.core.memories.queue, tensorforce.core.memories.recent, tensorforce.core.memories.replay, tensorforce.core.memories, tensorforce.core.objectives.objective, tensorforce.core.objectives.deterministic_policy_gradient, tensorforce.core.objectives.plus, tensorforce.core.objectives.policy_gradient, tensorforce.core.objectives.value, tensorforce.core.objectives, tensorforce.core.optimizers.optimizer, tensorforce.core.optimizers.update_modifier, tensorforce.core.optimizers.clipping_step, tensorforce.core.optimizers.evolutionary, tensorforce.core.optimizers.global_optimizer, tensorforce.core.optimizers.solvers.solver, tensorforce.core.optimizers.solvers.iterative, tensorforce.core.optimizers.solvers.conjugate_gradient, tensorforce.core.optimizers.solvers.line_search, tensorforce.core.optimizers.solvers, tensorforce.core.optimizers.linesearch_step, tensorforce.core.optimizers.multi_step, tensorforce.core.optimizers.natural_gradient, tensorforce.core.optimizers.plus, tensorforce.core.optimizers.subsampling_step, tensorforce.core.optimizers.synchronization, tensorforce.core.optimizers.tf_optimizer, tensorforce.core.optimizers.optimizer_wrapper, tensorforce.core.optimizers, tensorforce.core.distributions.distribution, tensorforce.core.distributions.bernoulli, tensorforce.core.distributions.beta, tensorforce.core.distributions.categorical, tensorforce.core.distributions.gaussian, tensorforce.core.distributions, tensorforce.core.networks.network, tensorforce.core.networks.auto, tensorforce.core.networks.preprocessor, tensorforce.core.networks, tensorforce.core.policies.base_policy, tensorforce.core.policies.action_value, tensorforce.core.policies.policy, tensorforce.core.policies.state_value, tensorforce.core.policies.stochastic_policy, tensorforce.core.policies.value_policy, tensorforce.core.policies.parametrized_action_value, tensorforce.core.policies.parametrized_distributions, tensorforce.core.policies.parametrized_state_value, tensorforce.core.policies.parametrized_value_policy, tensorforce.core.policies, tensorforce.core, tensorforce.agents.recorder, tensorforce.agents.agent, tensorforce.core.models.model, tensorforce.core.models.constant, tensorforce.core.models.tensorforce, tensorforce.core.models.random, tensorforce.core.models, tensorforce.agents.constant, tensorforce.agents.random, tensorforce.agents.tensorforce, tensorforce.agents.a2c, tensorforce.agents.ac, tensorforce.agents.dpg, tensorforce.agents.double_dqn, tensorforce.agents.dqn, tensorforce.agents.dueling_dqn, tensorforce.agents.ppo, tensorforce.agents.trpo, tensorforce.agents.vpg, tensorforce.agents, tensorforce.execution.runner, tensorforce.execution, tensorforce
Traceback (most recent call last):

  File "E:\DRL\boatNav-master\src\training\train_1D.py", line 48, in <module>
    runner = Runner(

  File "c:\users\ll\tensorforce\tensorforce\execution\runner.py", line 176, in __init__
    self.agent = Agent.create(agent=agent, environment=environment)

  File "c:\users\ll\tensorforce\tensorforce\agents\agent.py", line 112, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)

  File "c:\users\ll\tensorforce\tensorforce\agents\agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)

  File "c:\users\ll\tensorforce\tensorforce\agents\agent.py", line 98, in create
    agent = agent(**kwargs)

  File "c:\users\ll\tensorforce\tensorforce\agents\ppo.py", line 178, in __init__
    raise TensorforceError.deprecated(

DeprecationWarning: Deprecated PPO argument baseline_network, use baseline instead.'

**Comment by AlexKuhnle** [comment]
Hi,
if the problem is about the error message at the end: a few arguments have been renamed to be more consistent, and here it seems that you still use `baseline_network` whereas the argument is now just `baseline`. Simply renaming the argument in your config should solve the problem.

**Comment by AlexKuhnle** [comment]
Did that help?

**Comment by lyly0309** [comment]
Sorry for late reply. Yes, it’s running well, thanks a lot. ^@^. These days I was busy with my postdoctoral evaluation and now I am doing the Boat project again with Wei we discussed  last .Now there are some  advance and some bugs have been found, let’s see it :)

刘义

**Comment by AlexKuhnle** [comment]
Okay, cool, let me know how it goes... :-)
