### ISSUE TITLE
Planned AirSim support?

### ISSUE THREAD

**Issue by elgalu** [tensorforce/tensorforce#728]
https://github.com/microsoft/AirSim

**Comment by AlexKuhnle** [comment]
Hi,

The framework relies largely on contributions when it comes to adding new environments. However, I would be very happy to assist with the integration and preparation for a PR, if you want to look into this. All that is needed is to wrap it in the [Environment interface](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/environments/environment.py), more concretely:

- `states()` returning the state space specification
- `actions()` returning the action space specification
- `reset()` starting a new episode and returning the initial state
- `execute(actions)` advancing the environment by one step based on the given actions and returning next state, reward and is-terminal-bool

I can help with details on this, like how to specify the state space etc.

**Comment by AlexKuhnle** [comment]
Any success with this? If there are no plans to implement the environment interface, the issue can be closed.
