### ISSUE TITLE
how to perform evaluating from the dump the model

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#729]
Hi Alex:

I am wondering whether I can evaluate the trained model from restart. I know @jerabaul29 use codes like:
https://github.com/jerabaul29/collaboration_DRL_parallel_UiO_Wei/blob/3909774bc7c87ab208ca4778eac2c8ce601d8fd5/code_parallel_2_rotating_cylinders/single_runner.py#L17
`saver_restore = dict(directory=os.getcwd() + "/saver_data/", load="best-model")`

but for my case, I only find a folder called model in the running folder and several files there. where I cannot found saver_data/" and "best-mode"

would you please give me some suggestion.

Wei

**Comment by jerabaul29** [comment]
Mmmh, I wonder if this may be different form tensorforce version to tensorforce version, and / or I was using a specific saver config:

https://github.com/jerabaul29/collaboration_DRL_parallel_UiO_Wei/blob/3909774bc7c87ab208ca4778eac2c8ce601d8fd5/code_parallel_2_rotating_cylinders/single_runner.py#L17

**Comment by AlexKuhnle** [comment]
Hey,

If you're using the most recent version 0.6, things have slightly changed there. So you can't find the directory `saver_data/`, right? What's the training saver specification? Unfortunately I can't seem to access the links you posted. But if you're using the `save_best_model` `Runner` option, maybe there is a problem here -- I haven't checked this option for a while.

**Comment by jerabaul29** [comment]
@waynezw0618 which code are you running? Is it on the repo where we are already invited? If so may you show us there which code you run?

**Comment by AlexKuhnle** [comment]
(You can just post the agent or at least the saver config here, as well as the runner config, ideally for both training and loading.)

**Comment by lyly0309** [comment]
Hi @jerabaul29  
yes it is our previous case on the repo. as discussed before, we change the motion equation to the dimensionless form. 
here is the link of the code https://github.com/waynezw0618/boatNav/blob/master/src/training/train_1DnoDim.py
@AlexKuhnle 
In fact, I find two directories - model and summaries.there are agent.json, checkpoint and several agent related files in the model directory. there are several directories (seems related to each training.)
shall we discuss that in our previous repo?

**Comment by jerabaul29** [comment]
Yes, lets discuss there on your updated issue! :) .

**Comment by AlexKuhnle** [comment]
Resolved now
