### ISSUE TITLE
GPU Problem when upgrading to Tensorforce 0.6

### ISSUE THREAD

**Issue by chinen93** [tensorforce/tensorforce#733]
I created a simple Colab to test the new version but couldn't run it with a GPU.

Use a GPU in the Colab Notebook.

> Edit > Notebook Settings > Hardware Accelerator > GPU

Code to install the right package.
```
! pip install Tensorforce==0.6
```
Python code to run the CartPole env.
```
from tensorforce.execution import Runner
runner = Runner(
    agent=dict(
       type="ppo",
       batch_size=2
    ),
    environment=dict(environment='gym', level='CartPole'),
    max_episode_timesteps=500
)
runner.run(num_episodes=20)
runner.run(num_episodes=10, evaluation=True)
runner.close()
```

And I got the following message:
```
InvalidArgumentError: Cannot assign a device for operation agent/StatefulPartitionedCall/agent/Gather: Could not satisfy explicit device specification '' because the node {{colocation_node agent/StatefulPartitionedCall/agent/Gather}} was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:GPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
Identity: GPU CPU XLA_CPU XLA_GPU 
ResourceScatterAdd: CPU XLA_CPU XLA_GPU 
_Arg: GPU CPU XLA_CPU XLA_GPU 
ResourceGather: GPU CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  agent_929 (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  agent/StatefulPartitionedCall/agent/Gather (ResourceGather) 
  agent/StatefulPartitionedCall/agent/ResourceScatterAdd (ResourceScatterAdd) 
  Func/agent/StatefulPartitionedCall/input/_90 (Identity) /job:localhost/replica:0/task:0/device:GPU:0

     [[{{node agent/Gather}}]] [Op:__inference_act_1063]
```

**Comment by chinen93** [comment]
Alexander Kuhnle said in the chat (https://gitter.im/tensorforce/community)

> Quick fix: just turn GPU off

**Comment by ThLind** [comment]
Same problem here. 
It works when I run the agent only on CPU but I hope there'll be a solution soon to be able to use GPU again.

**Comment by AlexKuhnle** [comment]
Hi @ThLind, unfortunately I have no idea which part of the code this exception is coming from or how to debug it. Moreover, it doesn't look like a Tensorforce problem to me, but more on side of TensorFlow. My impression is that a "gather" operation (`agent/StatefulPartitionedCall/agent/Gather`) is forced to use GPU (`was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'`), which seems not supported (`Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' [...] supported_device_types_=[CPU] possible_devices_=[]`, see GPU vs CPU and possible empty). I wonder whether you may be able to get help from the TensorFlow team?

**Comment by ZYtheNOOB** [comment]
I experienced the same problem. I printed out available GPUs in tensorflow and they are all ok. Does this have something to do with tf config `allow_soft_placement = True`? I can't find a way to add this execution spec in the latest version of tensorforce, can't find it in the documentation.

**Comment by AlexKuhnle** [comment]
That's what I would have suggested. Have you set the option before importing tensorforce?

**Comment by ZYtheNOOB** [comment]
Setting soft placement before or after importing tensorflow give the same error.

**Comment by AlexKuhnle** [comment]
Then, unfortunately, I still have no idea where the problem lies and how to fix it (from Tensorforce side).

**Comment by 644933925** [comment]
tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
                                        inputs, attrs, num_outputs)
param device_name is empty

**Comment by AlexKuhnle** [comment]
What does that mean?

**Comment by ruptse** [comment]
Getting same `InvalidArgumentError` error as in the original post above with the latest version. Is it possible to use GPU at all now? With GPU disabled, works fine with CPU only.

**Comment by AlexKuhnle** [comment]
I will try to debug this over the next days and let you know. (I don't usually use a GPU when working on Tensorforce, so I don't get this exception.)

**Comment by AlexKuhnle** [comment]
I think I managed to fix this problem now -- something related to some scatter operations in TensorFlow not having appropriate gradients registered whereas other similar operations do, or so. Anyway, it seemed to work alright for me, so will close this issue. Re-open if problems persist.
