### ISSUE TITLE
low latency use

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#737]
@AlexKuhnle we may get a project where we want to perform some real-time applications in experiments. We do not need to be embedded, having access to a powerful computer for the calculations would be ok. I put you in the loop if / as soon as things get going.

I am wondering about the following. It may be a bit "fuzzy", but may be a good way to get a discussion started:

Are there ways to reduce the latency of tensorforce for "near real time" uses? Do you think it may be possible to somehow compile with Numba or similar? Any other idea in this kind? Or is there a way to extract a compiled tf graph, and put a lightweight C++ API on top of it rather than Python?

**Comment by AlexKuhnle** [comment]
Hey,
That sounds interesting. Is the plan to deploy a trained agent in an optimized way (which is basically possible already via the SavedModel export format), or to train, i.e. act and observe, in an optimized setup (which is not possible right now)? If the latter, this doesn't mean that it's not possible to implement, and it would be interesting to try, but there could certainly be difficulties. If the former... all done. :-)

**Comment by jerabaul29** [comment]
I think both are interesting. If the trained model could be exported into a C++ standalone program that would be great for embedded deployment with low power electronics. I am afraid we may want to consider also the second point, because we still have to learn somehow... What are your thoughts about the second point? I think that we can keep it at the brainstorming level at the moment, as said I will let you know when the project really starts :) .

**Comment by AlexKuhnle** [comment]
It's really just about whether TensorFlow allows to export the model as SavedModel (and there is no real other way beyond reimplementing everything, which is probably not an option :-). For the act-only graph that's possible now, but required a little work, so it should be usable in all TensorFlow-supported languages incl C++. For the full computation graph to be exported, there may be additional problems and maybe it won't even be possible. Let's see... Probably best to look more into that when you start working on it.

**Comment by AlexKuhnle** [comment]
I will close this for now, obvs feel free to re-open if there is interest for looking into this more.
