### ISSUE TITLE
Policy entropy explode

### ISSUE THREAD

**Issue by ZYtheNOOB** [tensorforce/tensorforce#738]
Hi, I recently updated my tensorforce from 0.5.5 to 0.6.2, and I noticed the entropy explode in my PPO agent as shown in the image:
![1](https://user-images.githubusercontent.com/48122865/96075135-fd49d380-0edc-11eb-93eb-c89cef6b6511.png)

Is it because the flaws in my state, action, NN and reward design?

**Comment by AlexKuhnle** [comment]
Hi @ZYtheNOOB ,

That looks very strange -- can you post more details about your agent config and environment? Also, if I understand correctly, this wasn't the case with 0.5.5, but is with 0.6.2, right? Is the change just showing up in the entropy plot, or did the learning behavior / performance also change when moving to 0.6.2?

**Comment by ZYtheNOOB** [comment]
Yes, this is the case in 0.6.2 but not in 0.5.5, my problem is online 1D bin packing and settings:
```
agent = PPOAgent(
        states=environment.states(),
        actions=environment.actions(),
        network=network_spec,
        batch_size=4,
        memory=80000,
        learning_rate=1e-3,
        exploration=0.1,
        discount=0.99,
        max_episode_timesteps=max_timesteps,
        saver=dict(directory='./saver/', filename='PPO_model.ckpt', load=evaluate, frequency=500),
        summarizer=dict(directory='./record/', labels=["loss", "reward", "entropy", "graph"], frequency=500)
    )

network_spec = [
    [
        dict(type='retrieve', tensors=['item_spec']),
        dict(type='dense', size=512, activation='relu'),
        dict(type='reshape', shape=(4, 128)),
        dict(type='register', tensor='item_spec_layered')
    ],
    [
        dict(type='retrieve', tensors=['bin_spec']),
        dict(type='conv2d', window=5, size=32, activation='relu'),
        dict(type='conv2d', window=5, size=64, activation='relu'),
        dict(type='pool2d', reduction='max', window=2, stride=2),
        dict(type='conv2d', window=3, size=64, activation='relu'),
        dict(type='flatten'),
        dict(type='dense', size=512, activation='relu'),
        dict(type='reshape', shape=(4, 128)),
        dict(type='register', tensor='bin_spec_layered')
    ],
    [
        dict(
            type='retrieve', aggregation='concat',
            tensors=['item_spec_layered', 'bin_spec_layered']
        ),
        dict(type='flatten'),
        dict(type='dense', size=1024, activation='relu'),
        dict(type='dense', size=128, activation='relu')
    ]
]

    def states(self):
        return dict(
            item_spec=dict(type='float', shape=self.item_spec_shape),   # [25,]
            bin_spec=dict(type='float', shape=self.bin_spec_shape)      # [8, 8, 1]
        )

    def actions(self):
        return dict(type='int', num_values=self.action_num)             # 8
```

The reward is -1 when opening new bins and 0 for others, final reward is the space utilization [0, 1]

In 0.5.5, the curve looks like this:
![1](https://user-images.githubusercontent.com/48122865/96325534-2e501280-105b-11eb-8211-60a7f477e3ee.png)

The performance is also different, in 0.6.2 it is a bit worse than 0.5.5

**Comment by AlexKuhnle** [comment]
I've compared a few parts of the code between 0.5.5 and the current version, and spotted 2-3 details which could potentially cause a problem (although I don't yet see why they would). If you're okay with this, I can modify them in a branch for you to try whether it changes anything. Regarding the overall performance: have you averaged this over multiple runs? If so, what's the difference (do you have plots)? I generally monitored PPO performance in particular, so I would hope it wasn't affected negatively.

**Comment by AlexKuhnle** [comment]
(The weird thing about the entropy plot is that entropy is not supposed to "explode", but has an upper bound, so that certainly seems like a numerical bug or so.)

**Comment by AlexKuhnle** [comment]
I've created a branch `ppo-revert` -- would be great if you could try that one to see whether anything changes.

**Comment by ZYtheNOOB** [comment]
ok, I'll try with some runs.

**Comment by ZYtheNOOB** [comment]
Bug with the entropy plot is solved, looks like a numerical bug indeed. Thanks for the fix.

![myplot](https://user-images.githubusercontent.com/48122865/96366322-9eed5100-1179-11eb-9a31-e4f14a8aaa1d.png)
it averaged over multiple runs, seems like the performance is ok (blue is 0.5.5).

**Comment by AlexKuhnle** [comment]
Okay, then I will have to check what is causing this problem. Would you mind checking the latest version of the branch, where I changed back two of the modifications (not the one related to entropy) which I would expect are not affecting performance?

**Comment by ZYtheNOOB** [comment]
checked, performance is ok

**Comment by AlexKuhnle** [comment]
I have tried another, potentially preferable version of the entropy fix, but I'm not entirely sure whether it's numerically stable. Would you mind checking the entropy issue one last time with the latest version of the `ppo-revert` branch? Thanks very much for your help!

**Comment by AlexKuhnle** [comment]
And then we can close this issue... :-)

**Comment by ZYtheNOOB** [comment]
Now the entropy plot becomes 0, and loss plot is weird again.
![myplot](https://user-images.githubusercontent.com/48122865/97069595-f3724f80-1603-11eb-9e1e-b327d988b950.png)

and the following error appears at a short period of time after the training started, thought it may also related to this:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Invalid gradient: contains inf or nan. : Tensor had NaN values
	 [[{{node agent/StatefulPartitionedCall/agent/cond_1/then/_319/agent/cond_1/StatefulPartitionedCall/agent/StatefulPartitionedCall_5/policy_optimizer/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/while/body/_1832/policy_optimizer/while/StatefulPartitionedCall/policy_optimizer/cond/then/_2807/policy_optimizer/cond/StatefulPartitionedCall/policy_optimizer/VerifyFinite/CheckNumerics}}]] [Op:__inference_observe_9607]

Function call stack:
observe
```

**Comment by AlexKuhnle** [comment]
Okay, I will correct it accordingly on master then. Thanks agan!
