### ISSUE TITLE
error on env.state:‘dict’ object is not callable

### ISSUE THREAD

**Issue by wyz9756** [tensorforce/tensorforce#742]
Hi, I recently updated my tensorforce from 0.4 to 0.6.2, and I was trapped in the error: ‘dict’ object is not callable. It seems that something wrong exist in states of environment scripts. Error message I received: 

> Traceback (most recent call last):
  File "perform_learning.py", line 37, in <module>
    states=environment.states(),
  File "/home/wyz/.local/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 360, in states
    return self._environment.states()
TypeError: 'dict' object is not callable

I have check states in environment and also the agent, here they are: 
`

    def states(self):

        Num = 200
        jNum = 3
        
        if self.params["type"] == 'type1':
            return dict(type='float', shape=( Num,) )

        elif self.params["type"] == 'type2a':
            return dict(type='float', shape=(2 * Num,))

    def actions(self):

        minj = self.params["min_value"]
        maxj = self.params["max_value"]
        return dict(type='float', shape=(jNum, ),min_value=minj, max_value=maxj)`

and:
`        
        
    env = resume_env( step=100, dump=100)
    environment = Environment.create(environment = env)
    
    network_spec = [
        dict(type='dense', size=512),
        dict(type='dense', size=512),
    ]
    
    agent = Agent.create(
        agent='ppo',
        environment=environment,
        network=network_spec,
        batch_size=20,
        learning_rate=1e-3,
        subsampling_fraction=0.2,
        optimization_steps=25,
        likelihood_ratio_clipping=0.2,
        memory=10000,
        entropy_regularization=0.01,
        baseline=dict(
            type='auto',
            sizes=32,
            depth=2
        ),
        baseline_optimizer=dict(
            type='multi_step',
            optimizer=dict(
                type='adam',
                learning_rate=1e-3
            ),
            num_steps=5
        )
    )
    
    runner = Runner(agent=agent, environment=environment)
    
    
    def episode_finished(r):
        print("Finished episode {ep} after {ts} timesteps (reward: {reward})".format(ep=r.episode, ts=r.episode_timestep,
                                                                                     reward=r.episode_rewards[-1]))
    
        name_save = "./saved_models/ppo_model"
    
        r.agent.save_model(name_save, append_timestep=False)
    
        return True
    
    # Start learning
    
    runner.run(num_episodes=500, max_episode_timesteps=100, episode_finished=episode_finished)
    
    runner.close()
    
    
`
Is there any mistake I haven't found？HELP!

**Comment by AlexKuhnle** [comment]
Hi, 0.4 to 0.6.2 -- that's quite a step... :-)  I think the reason for the problem you encounter is that, at the time, the environment `states()` and `actions()` methods had a `@property` decorator, so were supposed to be used as `environment.states` instead of `environment.states()`. This has changed by now, so likely you need to just remove these decorators in your environment code.

**Comment by wyz9756** [comment]
Ahhh, I remove them and it work! Thanks very much!
