### ISSUE TITLE
How to access CustomEnvironment methods and attributes from environment

### ISSUE THREAD

**Issue by guglielmosanchini** [tensorforce/tensorforce#743]
Hi,
after initializing a custom agent as shown in the docs
```
environment = Environment.create(
    environment=CustomEnvironment(), 
    max_episode_timesteps=100)
```
in the evaluation step I would like to access some other methods and attributes of CustomEnvironment aside from the required ones (like states,  reset etc) from **environment**, but I dont see how to do it right now

**Comment by AlexKuhnle** [comment]
Can't you access them in the normal way, so `environment.XXX`? If not, what is the name of these attributes?

**Comment by guglielmosanchini** [comment]
unfortunately not,

here is a snippet of my class

```
class CustomEnvironment(Environment):
    N_ACTIONS = 69
    ACTION_INDEX = -1
    ASSIGNED_WEIGHT = 4
    FINAL_WEIGHT = 1
    INHIBITED_SEATS_WEIGHT = 1
    SEATS_DICT = DICT_POS_POSTI_CORR_v2.copy()

    def __init__(self, reward_function, seed=None):
        super().__init__()

        assert reward_function in ['step_negative', 'final_difference', 'step_and_final', 'step_positive']

        self.bus = Bus_v3()

        self.prec_still_to_inh = []

        self.inhibit = None

        self.RESERVATIONS, self.len_RES, self.reserv = create_reservations_v2(3, SIZE + 20, seed=seed)

        self.max_heu = evaluate_reservation_list_v2(self.reserv)

        self.reward_function = reward_function
```

**Comment by guglielmosanchini** [comment]
Ok, found the solution, sorry for the waste of time.
For others who may end up with the same problem, 
the inner environment can be accessed via `environment._environment`, I dont know if it is worth mentioning in the docs

**Comment by guglielmosanchini** [comment]
Ok, found the solution, sorry for the waste of time.
For others who may end up with the same problem, 
the inner environment can be accessed via `environment._environment`, I dont know if it is worth mentioning in the docs

**Comment by AlexKuhnle** [comment]
Is this using the latest version of Tensorforce? Because recently I added [getattr forwarding](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/environments/environment.py#L401), so I would expect that `environment.bus` should work directly... Not class attributes like `N_ACTIONS`, but regular attributes like `bus` should work, I would expect...

**Comment by guglielmosanchini** [comment]
You are actually right, it works as you say, there is no need to use the workaround I mentioned above.
Only the main methods, though, are highlighted by Ipython (e.g. when working in a notebook), the other ones are hidden, but they work nonetheless. 
Surprinsingly, class attributes are accessible, too!

**Comment by AlexKuhnle** [comment]
Great. Actually, yes, no reason why class attributes should be different. The only thing I'm not sure about are methods. And yes, editors won't be able to give feedback about the presence of these attributes, unfortunately.
