### ISSUE TITLE
Logging Environment Variables

### ISSUE THREAD

**Issue by tahaeghtesad** [tensorforce/tensorforce#746]
Hello,

I was wondering how I can log the state of the environment (for each timestep) in Tensorboard. I couldn't find any examples of this in the documentation.

**Comment by AlexKuhnle** [comment]
Hi, this is currently not possible. However, can't you just record whichever values you're interested in as part of the environment implementation?

**Comment by AlexKuhnle** [comment]
The recommended approach here is to implement logging of environment-related values on the environment side, since Tensorforce is agnostic to details of the environment.
