### ISSUE TITLE
Tracking action-values tensor returns nan

### ISSUE THREAD

**Issue by ZYtheNOOB** [tensorforce/tensorforce#747]
Hi, 

I'm using `tracking="all"` to see the action values in my ppo agent and print them out in testing like this:
```
    for _ in range(len(test_data)):
        states = environment.reset()
        internals = agent.initial_internals()
        terminal = False
        while not terminal:
            actions, internals = agent.act(states=states, internals=internals, independent=True, deterministic=True)
            states, terminal, reward = environment.execute(actions=actions)
            print(agent.tracked_tensors())
```

However print out values are all nan:
```
{'agent/policy/action_distribution/probabilities': array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan], dtype=float32)}
{'agent/policy/action_distribution/probabilities': array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan], dtype=float32)}
{'agent/policy/action_distribution/probabilities': array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan], dtype=float32)}
...
```

How can I correctly output these values?

**Comment by AlexKuhnle** [comment]
Hi,

I see that you're running this in "evaluation mode" (independent, deterministic). What happens if you run it without these flags (and you probably need to add `agent.observe(...)`)? If the latter works, that may give a hint where the problem lies. But either way, will definitely look into this, as it should work.

**Comment by ZYtheNOOB** [comment]
If I left the evaluation flags, the output is normal.
```
{'agent/policy/action_distribution/probabilities': array([1.0000000e+00, 5.7712182e-09, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3764792e-18],
      dtype=float32)}

{'agent/policy/action_distribution/probabilities': array([1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 1.376474e-18],
      dtype=float32)}
```

I noticed that the sum of probabilities are greater than 1, is this just a rounding error?

**Comment by AlexKuhnle** [comment]
That will be a rounding error, but won't be problematic in practice. However, these values look "extreme", a completely converged categorical distribution -- are these after training, and/or do you use action masking? I need to check whether there are any numerical instabilities with such values... Generally I wouldn't expect a distribution to converge to that degree.

**Comment by ZYtheNOOB** [comment]
Yes they are after training, and a lots of action masks are applied (all 0s are masked).

**Comment by AlexKuhnle** [comment]
Okay. Last question: are you using the latest GitHub version? If not, can you confirm that the same happens for this version? I will check what is causing the instability.

**Comment by ZYtheNOOB** [comment]
I just updated to the latest version and tracking works fine, thanks.

**Comment by AlexKuhnle** [comment]
Great -- I just remembered that there was a potentially related fix recently, and apparently it also fixed this problem. I guess this can be closed then.
