### ISSUE TITLE
AssertionError when first training

### ISSUE THREAD

**Issue by venturi123** [tensorforce/tensorforce#750]
Hi,

I am trying to define a CustomEnvironment and running with PPO agent. But i got some AssertionError look like this

```
Episodes:   0%|                                                       | 0/100 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]
Traceback (most recent call last):
  File "script/perform_learning.py", line 88, in <module>
    runner.run(num_episodes=100)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/execution/runner.py", line 545, in run
    self.handle_act(parallel=n)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/execution/runner.py", line 579, in handle_act
    actions = self.agent.act(states=self.states[parallel], parallel=parallel)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 388, in act
    deterministic=deterministic
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/agents/recorder.py", line 179, in act
    states=states, function_name='Agent.act'
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/agents/recorder.py", line 502, in _process_states_input
    assert states.shape[1:] == self.states_spec.value().shape
AssertionError
```

Then I add `f'{states}, {states.shape[1:]}, {self.states_spec.value().shape}'` after the original source code `assert states.shape[1:] == self.states_spec.value().shape` to get more detials.  It shows that
```
Episodes:   0%|                                                       | 0/100 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]
Traceback (most recent call last):
  File "script/perform_learning.py", line 88, in <module>
    runner.run(num_episodes=100)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/execution/runner.py", line 545, in run
    self.handle_act(parallel=n)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/execution/runner.py", line 579, in handle_act
    actions = self.agent.act(states=self.states[parallel], parallel=parallel)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 388, in act
    deterministic=deterministic
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/agents/recorder.py", line 179, in act
    states=states, function_name='Agent.act'
File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/agents/recorder.py", line 502, in _process_states_input
    assert states.shape[1:] == self.states_spec.value().shape, f'{states}, {states.shape[1:]}, {self.states_spec.value().shape}'
AssertionError: None, (), (40,)
```
And my custom environment state space is indeed (40, ) demensions.

**Comment by AlexKuhnle** [comment]
Hi,
it looks like your environment may not return the correct value for `execute()` or `reset()`. My suspicion is that it might be `reset()` where you forgot to add a return statement giving the initial episode state? (That would explain the fact that `states` seems to be `None`.)

**Comment by venturi123** [comment]
Thanks for your advice. It's very helpful!  I forgot to initial the environment and thus return nothing which is the reason why `states.shape[1:] = ()`. but I still have two questions:

1. My CustomEnvironment states function is defined as follow
```
def states(self):
    return dict(type='float',
        shape=(40, )
        )
```
which means the dimensions of state space is (40, ) (equals to self.states_spec.value().shape), then I define the initial state as (40, ) dimensions too,  but states.shape[1:] returns NULL value beacuse the second dimension equals to NULL. For this reason, the program will raise an AssertionError `assert states.shape[1:] == self.states_spec.value().shape`. I try to solve it by transposing my states array into ( ,40) dimensions and it seems to be working properly. I wonder if it's a correct solution?

2. I adopt the act-observe method to solve my problem. Here is my main function:
```
environment = Environment.create(environment=env.instantiate_env())

agent = Agent.create(agent='ppo', environment=environment, batch_size=10, learning_rate=1e-3, max_episode_timesteps=500,
    saver=dict(directory='saved_models/checkpoint', frequency=100),
    summarizer=dict(directory='summary'))

for episode in range(100):
    states = environment.reset()
    terminal = False
    sum_reward = 0.0
    num_updates = 0
    while not terminal:
        actions = agent.act(states=states)
        states, terminal, reward = environment.execute(actions=actions)
        num_updates += agent.observe(terminal=terminal, reward=reward)
        sum_reward += reward
    print('Episode {}: return={} updates={}'.format(episode, sum_reward, num_updates))
```
There exists another error.
```
WARNING:root:No min_value bound specified for state.
Traceback (most recent call last):
  File "script/perform_learning.py", line 47, in <module>
    actions = agent.act(states=states)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 388, in act
    deterministic=deterministic
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/agents/recorder.py", line 297, in act
    actions = input_type(function(actions[n]) for n in range(num_parallel))
TypeError: expected sequence object with len >= 0 or a single integer
```
Again, I try to print `actions` `input_type` `num_parallel` `function(actions[0])`. The results are as follow:
```
actions = [[-1.0676212  -0.03580761]]
input_type = <class 'numpy.ndarray'>
num_parallel = 1
function(actions[0]) = [-1.0676212  -0.03580761]
```
It seems to be a proper return value with `len(function(actions[0]))` equals to 2

**Comment by venturi123** [comment]
Sorry for asking a stupid question!  
After I tried to reshape the dimension of states array, all the problems were solved. 
More precisely, I use `.resahpe(1, -1)` meshod to conver all my 1D ndarray(n, ) to 2D ndarray(1, n). The function can work properly!

**Comment by AlexKuhnle** [comment]
Actually, the agent should accept unbatched inputs of shape `(40,)` and not require `(1, 40)`, if the inputs are consistently unbatched (they will be wrapped in singleton batches internally). So if this is not working for you, it may be worth checking the shapes of `reset()` and `execute()` outputs in detail. A potential problem: if you pass `(1, 40)` as state, you will get `(1, ?)` as action, whereas if you pass `(40,)`, you will get an unbatched action. Preferably, your environment returns unbatched states and consequently accepts unbatched actions.

**Comment by venturi123** [comment]
Thanks a lot, I took some time to check the dimension of all variables to let them consistent. It did work.  : )
