### ISSUE TITLE
epsilon greedy and decaying exploration

### ISSUE THREAD

**Issue by BaiLiping** [tensorforce/tensorforce#751]
is there an example as of how to code for decaying exploration rate?

**Comment by AlexKuhnle** [comment]
Hi @BaiLiping,
Yes, there are some examples [here](https://tensorforce.readthedocs.io/en/latest/modules/parameters.html). Basically, whenever you see an argument with type `parameter`, e.g. `exploration` [here](https://tensorforce.readthedocs.io/en/latest/agents/tensorforce.html), this means that, in addition to specifying it as a constant number, you can specify it as a scheduled parameter, using the available parameter types as illustrated in the first link.
I will close this, but feel free to ask another question if it's unclear.
