### ISSUE TITLE
How to use socket method for parallel training

### ISSUE THREAD

**Issue by venturi123** [tensorforce/tensorforce#753]
Hi Alex, 

I tried to use the `socket` method mentioned in `tensorforce/examples/parallelization.py` for parallel training but encountered some errors.
```
Episodes:   0%|                                                                        | 0/100 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%, comm=0.0%]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 634, in finish_reset
    self._observation = (self.reset(), -1, None)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 611, in reset
    states, seconds = self.receive(function='reset')
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 537, in receive
    success, result = self.__class__.proxy_receive(connection=self._connection)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/socket_environment.py", line 86, in proxy_receive
    result = msgpack.unpackb(packed=str_result)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/msgpack_numpy.py", line 273, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 202, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 634, in finish_reset
    self._observation = (self.reset(), -1, None)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 611, in reset
    states, seconds = self.receive(function='reset')
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 537, in receive
    success, result = self.__class__.proxy_receive(connection=self._connection)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/socket_environment.py", line 86, in proxy_receive
    result = msgpack.unpackb(packed=str_result)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/msgpack_numpy.py", line 273, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 202, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```
I have checked the port availability by using `netstat -anp | grep port`, and the result shows that it is already in `listening` state.

I set up two parallel learning environment processes and added the environment object to the `environments` list. Also, my code looks like this (defining each environment object is omitted, which can train normally in a single thread)
```
def launch_one_server(environment, port):
    Environment.create(environment=environment, remote='socket-server', port=port)

for env_obj in environments:
    proc = Process(target=launch_one_server, args=(env_obj, port_list[index]))
    proc.start()
    processes.append(proc)
    time.sleep(2.0)
    index += 1

agent = Agent.create(
    agent='ppo', environment=environments[0], batch_size=20, network=network_spec, learning_rate=1e-3, state_preprocessing=None,
    entropy_regularization=0.01, likelihood_ratio_clipping=0.2, subsampling_fraction=0.2, parallel_interactions=len(environments),
    saver=dict(directory='saved_models/checkpoint', frequency=1), summarizer=dict(directory='summary')
)

runner = Runner(
    agent=agent, num_parallel=len(environments), remote='socket-client', host='127.0.0.1', port=shell_args.ports_start
)
runner.run(num_episodes=shell_args.max_episode_timesteps)
runner.close()

for proc in processes:
    proc.join()
```

**Comment by AlexKuhnle** [comment]
Hi, is there any reason why you want to use socket communication instead of multiprocessing? Because the [multiprocessing example](https://github.com/tensorforce/tensorforce/blob/master/examples/parallelization.py#L56) seems much more suitable and doesn't require all the manual environment setup. Also, does it work for you to run the plain `parallelization.py` script?

**Comment by venturi123** [comment]
Because I designed a custom environment class, which involves calling external binary programs for interaction (non-python), and involves reading and writing a large number of files (subprocesses), I want to create folders for each interactive environment to avoid confusion. I am not sure if using `multiprocessing` mode can solve my problem.

Besides, running the parallelization.py script directly seems to have similar problems like this:
```
Traceback (most recent call last):
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 524, in send
    self.__class__.proxy_send(connection=self._connection, function=function, kwargs=kwargs)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/socket_environment.py", line 63, in proxy_send
    bytes_sent = connection.send(str_num_bytes + str_kwargs)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parallelization.py", line 93, in <module>
    main()
  File "parallelization.py", line 24, in main
    socket()
  File "parallelization.py", line 83, in socket
    agent=agent, num_parallel=2, remote='socket-client', host='127.0.0.1', port=65432
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/execution/runner.py", line 154, in __init__
    states = environment.states()
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 585, in states
    self.send(function='states', kwargs=dict())
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 526, in send
    self.__class__.proxy_close(connection=self._connection)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/socket_environment.py", line 92, in proxy_close
    connection.shutdown(SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by jerabaul29** [comment]
Mmh, if I remember well the choice of the host name was sometimes a bit tricky and may be machine / software stack dependent. Have you tried with for example:

```host = socket.gethostname()```

or

```host="localhost"```

The socket implementation here is an adapted / updated version of what I was using there:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/blob/master/Cylinder2DFlowControlWithRL/RemoteEnvironmentClient.py

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/blob/master/Cylinder2DFlowControlWithRL/RemoteEnvironmentServer.py

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/blob/master/Cylinder2DFlowControlWithRL/script_launch_parallel.sh

Maybe if you have some problems you can have a look at what was done there, though the material here has been updated by Alex and is probably much better than what I was doing.

**Comment by venturi123** [comment]
Thanks for your advice @jerabaul29.

I tried your suggestions but still, raise the same error. Then I tried to run my code without `runner.run()`  (just define a `Runner` object), no errors were raised during running.
```
runner = Runner(
    agent=agent, num_parallel=2, remote='socket-client', host='127.0.0.1', port=8000
)
```
 then I input `netstat -anp | grep 8000` and `netstat -anp | grep 8001` (which are chosen to be the socket server port) on the linux terminal, the results displayed are as follows 
```
$ sudo netstat -anp | grep 8000
tcp        0      0 127.0.0.1:47550         127.0.0.1:8000          ESTABLISHED 25459/python        
tcp        0      0 127.0.0.1:8000          127.0.0.1:47550         ESTABLISHED 29966/python  


$ sudo netstat -anp | grep 8001
tcp        0      0 127.0.0.1:59418         127.0.0.1:8001          ESTABLISHED 25459/python        
tcp        0      0 127.0.0.1:8001          127.0.0.1:59418         ESTABLISHED 30240/python  
```

I think it shows that those three processes have established connection correctly (which means host and ports may set up correctly?), but there are indeed some problems in communication between them.

**Comment by jerabaul29** [comment]
Mmmh, are you trying to use port 8000? I think this is one of the "magic port values" that are used for some stuff by your system. Can you try with a few random port numbers, like 65433 or some stuff like this?

If not, you may want to use the classes that I linked to a bit earlier. They were working with an old tf version, maybe you will  need to do a bit of fixing here and there, but they have worked fine for me.

**Comment by AlexKuhnle** [comment]
I think the multiprocessing remote option will actually help -- particularly since you seem to use multiprocessing anyway for the remote environment (`proc = Process(target=launch_one_server, args=(env_obj, port_list[index]))`, `Process` comes from `multiprocessing`, I assume?).

In fact, could this be the problem here? If these remote environment processes run on the same system, but all attempt to communicate via certain ports, both the sending and receiving end listen on the same port? (Socket communication is mainly for when communication happens between multiple machines.)

**Comment by AlexKuhnle** [comment]
Hmm, not sure whether my last comment makes sense, since the parallelization example does the same thing.

**Comment by AlexKuhnle** [comment]
I am able to run the parallelization example, so that's a bit weird. Maybe could you try again after restarting? Not sure whether some ports are blocked if processes are not terminated correctly on an exception.

**Comment by venturi123** [comment]
In fact, I had read `Cylinder2DFlowControlDRLParallel` before. But I found that some methods are no longer supported. For example, in `Version 0.5.4`, `ParallelRunner()` method has been merged into `Runner()`. As a novice in reinforcement learning, I still have some difficulty in reading the source code of `tensorforce`.

So, after seeing all of your suggestions, I tried the following.
1. Changing the socket-server port to 65432. Unfortunately, the same error is still displayed. (**failed**) Also, I wrote a function to detect port availability to ensure that each port is not occupied by other programs. 
2. Re-running the plain `parallelization.py` script. Because there was some error in setting python working directory, the function could not read the JSON file correctly. After modification, the script can run normally. (**succeed**)
3. Running external programs directly (multi-process methods without `tensorforce`). (**succeed)**
4. Separately running the single-threaded training of each sub-environment. (**succeed**)

Based on the above experiment, I think the following conclusions can be drawn
1. The settings of the `Agent`, `Runner` and `Environment` objects are correct, the problem lies in the communication between `client` and `server`
2. The error is not caused by a conflict between the server process and its children

Besides, I am still curious about the error message
`msgpack.exceptions.ExtraData: unpack(b) received extra data.` 

I tried to use `pdb` to find out the cause of the error, but for some unknown reason, it was unable to enter the child process in the call stack.

**Comment by AlexKuhnle** [comment]
Thanks, good to know that `parallelization.py` is working. Have you also tried running the setup in `multiprocessing` mode, or do you mind trying it? Here the code (note also, fyi, you can just pass the agent config dict without `environment` and `parallel_interactions` information):

```python
agent = dict(
    agent='ppo', batch_size=20, network=network_spec, learning_rate=1e-3, state_preprocessing=None,
    entropy_regularization=0.01, likelihood_ratio_clipping=0.2, subsampling_fraction=0.2,
    saver=dict(directory='saved_models/checkpoint', frequency=1), summarizer=dict(directory='summary')
)

runner = Runner(agent=agent, environments=environments, remote='multiprocessing')

runner.run(num_episodes=shell_args.max_episode_timesteps)
runner.close()
```

I agree that this looks like a communication problem, and I'm also wondering what this "extra data" is about... The exception is thrown [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/environments/socket_environment.py#L86), could you maybe insert a `print(str_result)` just before?

**Comment by venturi123** [comment]
`multiprocessing` mode works!  Thank you so much for your helpful suggestions!

And then, I insert `print(f'str_result = {str_result}')` before `result = msgpack.unpackb(packed=str_result)` like this
```
@classmethod
def proxy_receive(cls, connection):
    str_success = connection.recv(1)
    if len(str_success) != 1:
        raise TensorforceError.unexpected()
    success = bool(str_success)

    str_num_bytes = connection.recv(8)
    if len(str_num_bytes) != 8:
        raise TensorforceError.unexpected()
    num_bytes = int(str_num_bytes.decode())
    str_result = b''
    for n in range(num_bytes // cls.MAX_BYTES):
        str_result += connection.recv(cls.MAX_BYTES)
        if len(str_result) != n * cls.MAX_BYTES:
            raise TensorforceError.unexpected()
    str_result += connection.recv(num_bytes % cls.MAX_BYTES)
    print(f'str_result = {str_result}')
    if len(str_result) != num_bytes:
        raise TensorforceError.unexpected()
    result = msgpack.unpackb(packed=str_result)

    return success, result
```
The error messages are as follow
```
str_result = b'\x82\xa4type\xa5float\xa5shape\x91('
str_result = b'\x84\xa4type\xa5float\xa5shape\x91\x02\xa9min_value\xec\xa9max_value\x14'
str_result = b'\x82\xa4type\xa5float\xa5shape\x91('
str_result = b'\x84\xa4type\xa5float\xa5shape\x91\x02\xa9min_value\xec\xa9max_value\x14'
Episodes:   0%|                                                                        | 0/100 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%, comm=0.0%]
str_result = b'4\x93\xb3<class \'TypeError\'>\xd9!can not serialize \'Series\' object\x98\xd9\xc9  File "/home/user3/anaconda3/envs/w'
str_result = b'4\x93\xb3<class \'TypeError\'>\xd9!can not serialize \'Series\' object\x98\xd9\xc9  File "/home/user3/anaconda3/envs/w'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 634, in finish_reset
    self._observation = (self.reset(), -1, None)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 611, in reset
    states, seconds = self.receive(function='reset')
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 537, in receive
    success, result = self.__class__.proxy_receive(connection=self._connection)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/socket_environment.py", line 87, in proxy_receive
    result = msgpack.unpackb(packed=str_result)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/msgpack_numpy.py", line 273, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 202, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 634, in finish_reset
    self._observation = (self.reset(), -1, None)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 611, in reset
    states, seconds = self.receive(function='reset')
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/environment.py", line 537, in receive
    success, result = self.__class__.proxy_receive(connection=self._connection)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/tensorforce/environments/socket_environment.py", line 87, in proxy_receive
    result = msgpack.unpackb(packed=str_result)
  File "/home/user3/anaconda3/envs/wql/lib/python3.6/site-packages/msgpack_numpy.py", line 273, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 202, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

**Comment by AlexKuhnle** [comment]
Thanks, I think this gives us an idea what is going wrong: `...<class \'TypeError\'>\xd9!can not serialize \'Series\' object...`

Could it be that you're using pandas, hence the `Series` object? If so, the fix for this is hopefully to turn the `Series` object into a numpy array (`X.to_numpy()`?). If you could check that, that would be great. However, ideally this exception should have been thrown instead of causing weird "extra data" downstream problems. I'll check why that happens...

**Comment by venturi123** [comment]
Yes! That's the problem！

Some function's return value in my custom environment is pandas `Series` object. After converting all variables into `NumPy` object, the program using the `socket` method can run correctly.

**Comment by jerabaul29** [comment]
Do you think it is possible to provide an error message that pinpoints this kind of problems @AlexKuhnle ? Maybe some assert on type?

**Comment by AlexKuhnle** [comment]
I've improved output shape/type checks of the environment object, which hopefully addresses above problem. Would you mind trying the original wrong setup with the pandas Series object once more? I'm not sure whether the changes also help with the communication problem... That would be great, thanks.

Anyway, I assume this can be closed. If this change doesn't help, I'm not sure how else to improve the exception.
