### ISSUE TITLE
UnboundLocalError when using LSTM layers with Summarizer

### ISSUE THREAD

**Issue by joconnor22** [tensorforce/tensorforce#754]
When I define a network with LSTM layers and also switch on the summarizer I get an error of the form:

``` python
    arg = spec.kwargs_to_args(kwargs=arg, to_dict=to_dict, is_outer=False)
UnboundLocalError: local variable 'arg' referenced before assignment
```

To reproduce you can use this:

``` python
from tensorforce import Agent, Environment, Runner

# Number of environments
num_envs = 1

# Create environments
environments = []
for _ in range(num_envs):
    environments.append(dict(environment='gym', level='CartPole', max_episode_timesteps=500))

# Create agent
agent = Agent.create(
    agent='ppo',
    environment=Environment.create(environments[0]),
    batch_size=32,
    parallel_interactions=num_envs,
    network=dict(layers=[dict(type='lstm', size=32, horizon=32), dict(type='lstm', size=32, horizon=32)]),
    summarizer=dict(directory='.', filename='Record', summaries='all'),
)

# Create and run runner
runner = Runner(agent=agent, environments=environments, num_parallel=num_envs)
runner.run(num_episodes=256, use_tqdm=True)

# Close
runner.close()
agent.close()
```

If I comment out either the `network` or `summarizer` options then it works fine, as well as if I switch to `dense` layers. It also seems to work if I define the `baseline` network separately. Is this a bug or am I misusing it?

**Comment by AlexKuhnle** [comment]
Hi @joconnor22,
This looks very much like a (probably minor) bug, but I need to investigate first. Will let you know soon.

**Comment by AlexKuhnle** [comment]
The bug should be fixed now, however, while looking at it, I remembered that it's currently not possible to have multiple RNN layers (I've now added an exception for this). This is mostly for technical/implementation reasons (related to temporal horizon), and the easiest way to improve this is to make it possible to specify the number of actual layers within one single "Tensorforce RNN layer". Obviously, these would then have to be successive, but that shouldn't be a too problematic restriction. I can probably add this soon as well, but for now you have to stick to one LSTM layer.

**Comment by AlexKuhnle** [comment]
Closing this, feel free to re-open if there are still problems.

**Comment by joconnor22** [comment]
It seems to be working now - thanks a lot. Also, thanks for the heads up about multiple RNN layers.
