### ISSUE TITLE
Pybullet

### ISSUE THREAD

**Issue by BaiLiping** [tensorforce/tensorforce#755]
Can you create a Pybullet environment? Maybe you guys should consider this, since Pybullet free, Mujoco is no

**Comment by AlexKuhnle** [comment]
Yes, makes sense. Are you working with Pybullet? Contribution would be very welcome, and I'm happy to help if there are problems.

**Comment by bezineb5** [comment]
Hi, I've been using tensorforce with PyBullet, I could help on this. But honestly, there's not much to do, it's quite simple to integrate it in a custom Environment. There's not much generic code. Maybe to reset the state between each episode?

**Comment by AlexKuhnle** [comment]
If you don't mind, it would be great to have a PyBullet wrapper, even if the wrapper code is only minimal. PR very welcome, and if there's a detail you're not sure about, happy to help.

**Comment by AlexKuhnle** [comment]
Closing this issue. Still, if you're willing to contribute the environment implementation, that's very welcome.
