### ISSUE TITLE
error creating PPO agent

### ISSUE THREAD

**Issue by BaiLiping** [tensorforce/tensorforce#758]
layers=[
            dict(type='dense',size=input_size,    activation='relu'),
            dict(type='dense',size=input_size*2,  activation='relu'),
            dict(type='dense',size= output_size*3,activation='relu'),
            dict(type='dense',size=output_size,   activation='relu')
           ]    
agent_normal=Agent.create(
                                agent='ppo',
                                environment=environment,
                                network=dict(type='layered',layers=layers),
                                use_beta_distribution='true',
                                memory='minimum',
                                batch_size=10,
                                update_frequency=10,
                                learning_rate=5e-3,
                                multi_step=5,
                                subsampling_fraction=0.91,
                                likelihood_ratio_clipping=0.09,
                                discount=1.0,
                                predict_terminal_values='false',
                                baseline=dict(type='layered',layers=layers),
                                baseline_optimizer=dict(optimizer="adam",learning_rate=5e-3,multi_step=5),
                                state_preprocessing='linear_normalization',
                                reward_preprocessing='null',
                                exploration=exploration,
                                variable_noise=0.0,
                                l2_regularization=0.0,
                                entropy_regularization=0.0            
                              )

**Comment by BaiLiping** [comment]
agent_normal=Agent.create(
  File "/home/blp/Desktop/tensorforce/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/home/blp/Desktop/tensorforce/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
  File "/home/blp/Desktop/tensorforce/tensorforce/agents/ppo.py", line 249, in __init__
    super().__init__(
  File "/home/blp/Desktop/tensorforce/tensorforce/agents/tensorforce.py", line 431, in __init__
    self.model = TensorforceModel(
  File "/home/blp/Desktop/tensorforce/tensorforce/core/models/tensorforce.py", line 110, in __init__
    self.reward_preprocessing = self.submodule(
  File "/home/blp/Desktop/tensorforce/tensorforce/core/module.py", line 503, in submodule
    module = module_cls(*args, **kwargs)
  File "/home/blp/Desktop/tensorforce/tensorforce/core/networks/preprocessor.py", line 55, in __init__
    super().__init__(
  File "/home/blp/Desktop/tensorforce/tensorforce/core/networks/network.py", line 259, in __init__
    self.layers = list(self._parse_layers_spec(spec=layers, counter=Counter()))
  File "/home/blp/Desktop/tensorforce/tensorforce/core/networks/network.py", line 264, in _parse_layers_spec
    yield from self._parse_layers_spec(spec=s, counter=counter)
  File "/home/blp/Desktop/tensorforce/tensorforce/core/networks/network.py", line 289, in _parse_layers_spec
    yield self.submodule(name=name, module=spec)
  File "/home/blp/Desktop/tensorforce/tensorforce/core/networks/network.py", line 166, in submodule
    module_cls, args, kwargs = Module.get_module_class_and_args(
  File "/home/blp/Desktop/tensorforce/tensorforce/core/module.py", line 398, in get_module_class_and_args
    return Module.get_module_class_and_args(
  File "/home/blp/Desktop/tensorforce/tensorforce/core/module.py", line 436, in get_module_class_and_args
    raise TensorforceError.value(
tensorforce.exception.TensorforceError: Invalid value for Module.add_module argument module: null.

**Comment by BaiLiping** [comment]
if I try to create a PPO agent with the following, it would work:
    agent_normal=tensorforce.agents.ProximalPolicyOptimization(
                                states=environment_normal.states(),
                                actions=environment_normal.actions(),
                                max_episode_timesteps=1000,
                                batch_size=10,
                                network=dict(type='custom',layers=layers),
                                use_beta_distribution='true',
                                memory='minimum',
                                update_frequency=10,
                                learning_rate=5e-3,
                                multi_step=5,
                                subsampling_fraction=0.91,
                                likelihood_ratio_clipping=0.09,
                                discount=1.0,
                                predict_terminal_values='false',
                                baseline=dict(type='custom',layers=layers),
                                baseline_optimizer=dict(optimizer="adam",learning_rate=5e-3,multi_step=5),
                                l2_regularization=0.0,
                                entropy_regularization=0.0,           
                                state_preprocessing='linear_normalization',
                                exploration=exploration,
                                variable_noise=0.0,
                                recorder=None,
                                parallel_interactions=1
                                )

**Comment by BaiLiping** [comment]
if I tried the following with the PPO agent, the following error message would come up:
AttributeError: 'ProximalPolicyOptimization' object has no attribute 'timestep_completed'

    states=environment_normal.reset()
    terminal=False
    actions=agent_normal.act(states=states)
    environment_normal.execute(actions=actions)
    agent_normal.observe(terminal=terminal,reward=reward)

**Comment by AlexKuhnle** [comment]
Hi @BaiLiping,
So `'custom'` is accepted, but `'layered'` is not? Or is it that `Agent.create(...)` is not working? As far as I can tell, you're changing two things in the second example. And for the last problem, you need to first initialize the agent via `agent.initialize()` -- this happens automatically when using `Agent.create(...)`, but not when manually constructing. But the exception should definitely be better...

**Comment by AlexKuhnle** [comment]
Any updates?
