### ISSUE TITLE
Parallelization with Custom Environment

### ISSUE THREAD

**Issue by manuelknott** [tensorforce/tensorforce#759]
Hello,
I want to enable parallel execution and therefore I initialized an Agent with `agent = Agent.create(..., parallel_interactions=4)` and a Runner instance as follows:
```
runner = tensorforce.execution.Runner(agent=agent, environment=environment, num_parallel=4)
```
`environment` is a custom environment inherited from the Tensorforce Environment class.

I run into the following error:
`Invalid type for Runner argument environment given num_parallel: <class 'CustomEnvironment'> is not specification.`

I am wondering if I do something wrong or if there is possibly a bug in the following line:
https://github.com/tensorforce/tensorforce/blob/master/tensorforce/execution/runner.py#L135

Maybe I do not fully understand it, but shouldn't it be `if **not** isinstance(environment, Environment)`?

**Comment by AlexKuhnle** [comment]
Hi @manuelknott, the reason why an *instance* of an Environment object is not accepted for `environment ` in the parallel execution case is that Runner needs to be able to create `num_parallel` environment copies, which isn't possible with an instance. So instead you need to pass e.g. `environment=CustomEnvironment` or `environment=dict(type=CustomEnvironment, **kwargs)` or similar, which then makes it possible for the Runner to instantiate the appropriate number of instances.

The exception should be clearer about this, though.
