### ISSUE TITLE
Error sometimes occurs when performing training

### ISSUE THREAD

**Issue by yue19960831** [tensorforce/tensorforce#760]
Hi @AlexKuhnle. When I perform training, I meet an error sometimes as follow:

 ```
Traceback (most recent call last):
  File "parallel_training.py", line 63, in <module>
    runner.run(
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/execution/runner.py", line 551, in run
    self.handle_act(parallel=n)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/execution/runner.py", line 579, in handle_act
    actions = self.agent.act(states=self.states[parallel], parallel=parallel)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 386, in act
    return super().act(
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/agents/recorder.py", line 264, in act
    actions, internals = self.fn_act(
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 424, in fn_act
    actions, timesteps = self.model.act(
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/core/module.py", line 128, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[0] = [0, 10] does not index into shape [1,10,52]
	 [[{{node agent/StatefulPartitionedCall/agent/TensorScatterUpdate}}]] [Op:__inference_act_918]

Function call stack:
act
```

This error not always occurs. I can't figure out what the error means. When I use the modified CustomEnvironment example as follow, the error also occurred sometimes:

```
import numpy as np
import csv
import pandas as pd
import os
from tensorforce import Environment

Class CustomEnvironment(Environment):

    def __init__(self):
        super().__init__()

    def states(self):
        return dict(type='float', shape=(52,))

    def actions(self):
        return dict(type='float', shape=(1,), min_value=0, max_value=1)

    # Optional
    def close(self):
        super().close()

    def reset(self):
        state = np.random.random(size=(52,))
        return state

    def execute(self, actions=None):
        next_state = self.get_next_state()#np.random.random(size=(52,))
        terminal = np.random.random() < 0.5
        reward = np.random.random()
        for i in range(53):
            self.drag = self.dl.Drag[i]
            self.lift = self.dl.Lift[i]

        return next_state, terminal, reward

    def get_next_state(self):
        self.pv = pd.read_csv('Probe.his', sep='\s+', header=None,
                              names=['Time', 'velocity_u', 'velocity_v', 'p'],
                              skiprows=53)

        probes_values_p = self.pv.p[-52:]

        next_state = np.array(probes_values_p)

        return next_state

```
FYI, my agent setting is like that:

```
environments=[]

for i in range(number_environments):
    environment = Environment.create(environment=CustomEnvironment())
    environments.append(environment)

network_spec = [dict(type='dense', size=512), dict(type='dense', size=512)]

agent = dict(
    agent='ppo',
    max_episode_timesteps=nb_actuations,
    network=network_spec,
    batch_size=15, learning_rate=3e-4, subsampling_fraction=0.33, update_frequency=2, multi_step=10,
    likelihood_ratio_clipping=0.2, discount=0.99,
    entropy_regularization=0.01, l2_regularization=0.0,
    saver=dict(directory=os.path.join(os.getcwd(), 'recent_model'), frequency=1, max_checkpoints=5),
)


runner = Runner(
    agent=agent, environments=environments, remote='multiprocessing',
    evaluation=True
)

runner.run(
    num_episodes=1200, sync_episodes=True,
    save_best_agent=os.path.join(os.getcwd(), 'best_model')
)

runner.close()
```

Is it possible caused by environment setting? or agent setting?

**Comment by yue19960831** [comment]
I think I found the solution. Just add the parameter `max_episode_timesteps=` into the `Environment.create`, then the error won't occur again. But what role does the parameter `max_episode_timesteps=`  in agent play?

**Comment by yue19960831** [comment]
Besides, I found that the random functions of parallel environments generate the same value and the agent also took the same action. However, I want that the agent can take different actions interacting with different environments, how can I achieve that?

**Comment by AlexKuhnle** [comment]
Hi @yue19960831,

The `max_episode_timesteps` argument limits the maximum number of timesteps an episode can have before being aborted. Having this maximum length is important in particular for episode-based algorithms like PPO, so that internal episode buffers can be allocated with a known maximum size. This value shouldn't affect training significantly unless chosen too small (episodes are aborted before interesting stuff happens) or potentially far too big (if one episode goes on forever, whereas others terminate after a normal time).

Regarding the second point, I don't know what you mean by "random functions of parallel environments"?

**Comment by yue19960831** [comment]
Sorry, I don't make it clear. I reorganise my language and try to let you get the point.
(1) I kown that having  `max_episode_timesteps` is important in PPO. In my agent config dict, the `max_episode_timesteps` was already set, but the error still occured unless I set the `max_episode_timesteps` in `Environment.create`. Thus, it seems that the argument `max_episode_timesteps` in agent config can't work like counterpart in `Environment.create`. What does the argument `max_episode_timesteps` in agent config do?
(2)Just like what  the CustomEnvironment example shows. The next state is given by the function `np.random.random`. 
When I use agent setting above to perform parallel training, the first states of all environments are same, and every single environment will get same state in every `execute`, it seems that agent takes the same action in all environments. But I need that agent can take different actions in different environments.

**Comment by AlexKuhnle** [comment]
Regarding (1): the agent argument tells the agent what the maximum number of timesteps is, as explained above. However, specifying this argument means that the agent expects the environment to actually terminate/abort at that point, and presumably in your case the "maximum" timestep just looks like a normal timestep (in particular `terminal=False`), which then causes problems for the agent. The recommendation is: specify `max_episode_timesteps` for the environment, then Tensorforce will automatically introduce the abort termination at this number, and specify `environment` to the agent, then Tensorforce will know `states`, `actions` and `max_episode_timesteps` of the environment. If for some reason this should not be possible, that's when you can modify things in more detail by specifying these agent arguments directly (but in that case it's your responsibility to make sure the environment behaves accordingly). Hope that makes it clear... :-)

Regarding (2): I have to double-check this, I don't know why that would happen, but in principle it shouldn't.

**Comment by yue19960831** [comment]
I found why the problem happened! In all processes, the random seeds are same leading to the same random values generated by `np.random.random()`. As long as you **set different random seed for different process**, that situation won't happen! 

Moreover, the agent actually does makes different action value in different process which was vertified by my own custome environment. Previous case, the next state is decided by` np.random.random()` in fact, rather than action. I'm so careless!

However, I still encoutered some error in cilent-server method before. When I read data from external files by `pandas` or `csv`, error will happened. A few days later, I will duplicate that case!

**Comment by AlexKuhnle** [comment]
Okay, let me know once you have more details about the pandas/csv problem you've mentioned.

**Comment by yue19960831** [comment]
@AlexKuhnle Sorry, I got another question. Why can't I load the best model stored by the argument `save_best_agent` of `Runner.run`? I code it like this:

`agent = Agent.load(directory='best_model', format='checkpoint', environment=example_environment)`

and get the error:

```
Traceback (most recent call last):
  File "evaluation.py", line 29, in <module>
    agent = Agent.load(directory='best_model', environment=example_environment)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 210, in load
    agent = Agent.create(agent=agent, environment=environment, **kwargs)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 112, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/scratch/pylai/ENV3/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
TypeError: __init__() missing 4 required positional arguments: 'update', 'optimizer', 'objective', and 'reward_estimation'
```
and the best_model file is as follow:

```
(ENV3) pylai:DRL$ ls best_model/
best-model-15.data-00000-of-00001  best-model-25.data-00000-of-00001  best-model-33.data-00000-of-00001  best-model-35.data-00000-of-00001  best-model.json
best-model-15.index                best-model-25.index                best-model-33.index                best-model-35.index                checkpoint
```
However, if load the model stored by the argument `saver` of `agent`, it works.

**Comment by AlexKuhnle** [comment]
Hmm, good question. My suspicion is that it's because the filename is "non-standard", `best-model` instead of `agent`. So what happens if you use `Agent.load(directory='best_model', filename='best-model', environment=example_environment)`? (Certainly not obvious that this is needed, so would need to think how to handle this better.)

**Comment by AlexKuhnle** [comment]
Any update here?

**Comment by 12jr** [comment]
I have the same problem:
If the checkpoint is called `agent-4000-2` it doesnt work (I get the same `missing 4 required positional arguments` error as above), but if I rename it to `agent-2` it does (checkpoints are saved manually using `agent.save`.
