### ISSUE TITLE
ValueError: Cannot feed value of shape (1,) for Tensor 'agent/state-input:0', which has shape '(?, 236)'

### ISSUE THREAD

**Issue by XueminLiu111** [tensorforce/tensorforce#761]
I create an environment whose state shape is (236,) and I define the states function as follows
`    def states(self):
        return dict(type='float', shape=(236,))`

When I use a parallel runner to train it, the following error shows:

`  File "train_oldTensorforce.py", line 167, in <module>
    evaluation_callback=evaluation_callback_2
  File "/home/fenics/local/tensorforce/tensorforce/execution/parallel_runner.py", line 299, in run
    states=states, parallel=(parallel - int(evaluation)), evaluation=evaluation
  File "/home/fenics/local/tensorforce/tensorforce/agents/agent.py", line 317, in act
    deterministic=deterministic, independent=independent, **kwargs
  File "/home/fenics/local/tensorforce/tensorforce/core/module.py", line 560, in fn
    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1,) for Tensor 'agent/state-input:0', which has shape '(?, 236)'`

The tensorforce version is 0.5.3

Help appreciated.

**Comment by AlexKuhnle** [comment]
It looks like your environment doesn't return the right state shape. Since you are using the `parallel_runner`, it seems like you're on a very old version of Tensorforce... Could you update to the most recent version? Otherwise I won't be able to provide help.

**Comment by XueminLiu111** [comment]
> It looks like your environment doesn't return the right state shape. Since you are using the `parallel_runner`, it seems like you're on a very old version of Tensorforce... Could you update to the most recent version? Otherwise I won't be able to provide help.

When I update Tensorforce==0.6.2, the following error shows


`  File "train.py", line 138, in <module>
    runner.run(
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/site-packages/tensorforce/execution/runner.py", line 545, in run
    self.handle_act(parallel=n)
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/site-packages/tensorforce/execution/runner.py", line 579, in handle_act
    actions = self.agent.act(states=self.states[parallel], parallel=parallel)
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 386, in act
    return super().act(
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/site-packages/tensorforce/agents/recorder.py", line 178, in act
    states, batched, num_parallel, is_iter_of_dicts, input_type = self._process_states_input(
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/site-packages/tensorforce/agents/recorder.py", line 502, in _process_states_input
    assert states.shape[1:] == self.states_spec.value().shape
AssertionError`

So I print `self.states_spec` and it gives
`TensorsSpec(SINGLETON=TensorSpec(type=float, shape=(236,)))
`
but the `states`  is `array(1)`.

I have no idea about this. Could you help me? Thank you very much!

**Comment by AlexKuhnle** [comment]
Is this without parallel mode, just single environment execution? Do you use a custom environment? If you can share the code (if it's not much), or otherwise make sure that the returned state looks like you expect of shape `(236,)` (for both `reset()` and `execute()`), that would be good to confirm. Because the problem seems to be that the state is shaped wrong.

**Comment by XueminLiu111** [comment]
Yes, I use a custom environment and it is a parallel mode. The environment code is here (a little bit long):

`from __future__ import division

import tensorforce  #this line must befor the next line!
from tensorforce.environments import Environment

import numpy as np
import sys
import matplotlib
#matplotlib.use('pdf')
import matplotlib.pyplot as plt
import matplotlib.animation as anim
from mpl_toolkits import mplot3d
from matplotlib import cm
from matplotlib.colors import LogNorm
import pdb
import argparse


from dolfin import *
from mshr import *


from flow_solver import solve_flow
from probes import PointProbe, ObservationPoints

class inflow_pass_cylinder_env(Environment):

    def __init__(self,T=0.01, num_steps=100, mu=0.01, rho=1, max_steps=100):

        self.T = T#0.1#5.0            # final time
        self.num_steps = num_steps#100#5000   # number of time steps
        self.dt = self.T / self.num_steps # time step size  #dt=0.0001 is working

        self.mu = mu#0.01         # dynamic viscosity   mu = 1.0/reynolds
        #self.reynolds = 100
        #assert self.mu == 1/self.reynolds
        self.rho = rho#1            # density
        self.max_steps = max_steps
        self.max_act = 1.0
        self.min_act = -1.0
        self.act_dim = 4

        self.ep = 0
        #parameters to compute reward
        self.comp_dir = '.'

        # Initialize arrays
        self.drag       = np.array([])
        self.lift       = np.array([])
        self.reward     = np.array([])
        self.avg_drag   = np.array([])
        self.avg_lift   = np.array([])
        self.avg_reward = np.array([])
        self.penal      = np.array([])


        #state
        self.probe_type = 'pressure'
        self.output_params = ObservationPoints(self.probe_type)


        self.list_save_states = []
        self.list_save_actions = []
        self.list_save_reward = []


    def reset(self):
        # Create mesh
        channel = Rectangle(Point(0, -0.2), Point(2.2, 0.21))
        cylinder = Circle(Point(0.2, 0), 0.05)
        domain = channel - cylinder
        self.mesh = generate_mesh(domain, 128)
        self.action= np.zeros(4)
        self.steps = 0
        
        self.list_save_states = []
        self.list_save_actions = []
        self.list_save_reward = []

        self.u_n, self.u_, self.p_n, self.p_, self.drag_, self.lift_, self.solved, self.xdmffile_u, self.xdmffile_p, self.timeseries_u, self.timeseries_p, self.vtkfile_u, self.vtkfile_p = solve_flow(self.T ,
                                                                                                                                                                                                        self.num_steps,
                                                                                                                                                                                                        self.dt, 
                                                                                                                                                                                                        self.mu, 
                                                                                                                                                                                                        self.rho, 
                                                                                                                                                                                                        self.mesh, 
                                                                                                                                                                                                        self.action, 
                                                                                                                                                                                                        is_reset=True,
                                                                                                                                                                                                        Envsteps=self.steps,
                                                                                                                                                                                                        ep=self.ep,
                                                                                                                                                                                                        xdmffile_u=None,
                                                                                                                                                                                                        xdmffile_p=None,
                                                                                                                                                                                                        timeseries_u=None,
                                                                                                                                                                                                        timeseries_p=None,
                                                                                                                                                                                                        vtkfile_u=None, 
                                                                                                                                                                                                        vtkfile_p=None)
        
        next_state = self.get_obs()
        self.list_save_states.append(next_state)
        return next_state



    def get_obs(self):  # self.u_n & self.p_n ---> states and observations

        # Setup probes
        if self.output_params["probe_type"] == 'pressure':
            self.ann_probes = PointProbe(self.p_, self.output_params['locations']) #PressureProbeANN(self.flow, self.output_params['locations'])
            self.probes_values = self.ann_probes.sample(self.p_).flatten()
            assert self.probes_values.shape == (236, )        
        elif self.output_params["probe_type"] == 'velocity':
            self.ann_probes = PointProbe(self.u_, self.output_params['locations']) #VelocityProbeANN(self.flow, self.output_params['locations'])
            self.probes_values = self.ann_probes.sample(self.u_).flatten()
            assert self.probes_values.shape == (472, )
        else:
            raise RuntimeError("unknown probe type")

        obs = np.array(self.probes_values)# (236,)
        #obs = np.transpose(np.array(self.probes_values))   # shape (236,)
        #pdb.set_trace()
        print(obs.shape)

        return obs

    def compute_reward(self, meshed=True):
        # If meshing was successful, reward is computed normally
        if (meshed):
           
            # If solver was successful
            if (self.solved):
                # Drag is always <0 while lift changes sign
                penal  = 0.0
                #self.lift_  = -self.lift_ # Make lift positive
                #pdb.set_trace()
                if (self.lift_ > 2.0): self.lift_=2.0*self.lift_ # Shaping for faster convergence
                reward = self.lift_/abs(self.drag_)
                reward = max(reward, -10.0)

            # If solver was not successful
            else:
                self.drag_   =-1.0
                self.lift_   = 0.0
                reward =-5.0
                penal  = 5.0

        # If meshing was not successful, we just return a high penalization
        else:
            self.drag_   =-1.0
            self.lift_   = 0.0
            reward =-5.0
            penal  = 5.0

        # Save drag, lift, reward and penalization
        self.drag   = np.append(self.drag,   self.drag_)
        self.lift   = np.append(self.lift,   self.lift_)
        self.reward = np.append(self.reward, reward)
        self.penal  = np.append(self.penal,  penal)


        # shape.index will +1 in function modify_shape_from_field when env.excute once!
        # therefore, if we don't change the shape of cylinder, shape.index=1 
        val_drag   = np.sum(self.drag)#/env.shape.index
        val_lift   = np.sum(self.lift)#/env.shape.index
        val_reward = np.sum(self.reward)#/env.shape.index
        self.avg_drag   = np.append(self.avg_drag,   val_drag)
        self.avg_lift   = np.append(self.avg_lift,   val_lift)
        self.avg_reward = np.append(self.avg_reward, val_reward)

        return  self.reward[-1]

    def actions(self):
        return dict(type='float', shape=(self.act_dim,), min_value=self.min_act, max_value=self.max_act)  #shape=(4,) for ppo



    def states(self):
        # self.optimization_params["num_steps_in_pressure_history"]=1
        if self.output_params["probe_type"] == 'pressure':
            return dict(type='float',
                        shape=(len(self.output_params["locations"]) * 1,)
                        )

        elif self.output_params["probe_type"] == 'velocity':
            return dict(type='float',
                        shape=(2 * len(self.output_params["locations"]) * 1,)
                        )

    def max_episode_timesteps(self):
        return self.max_steps  #None
  
    def execute(self,actions=None):
        self.steps += 1
        self.action = actions
        self.u_n, self.u_, self.p_n, self.p_, self.drag_, self.lift_, self.solved, self.xdmffile_u, self.xdmffile_p, self.timeseries_u, self.timeseries_p, self.vtkfile_u, self.vtkfile_p = solve_flow(self.T , 
                                                                                                                                                                        self.num_steps, 
                                                                                                                                                                        self.dt, self.mu, 
                                                                                                                                                                        self.rho, self.mesh, 
                                                                                                                                                                        act=self.action, 
                                                                                                                                                                        is_reset=False, 
                                                                                                                                                                        u_n=self.u_n, 
                                                                                                                                                                        u_=self.u_, 
                                                                                                                                                                        p_n=self.p_n, 
                                                                                                                                                                        p_=self.p_,
                                                                                                                                                                        Envsteps=self.steps,
                                                                                                                                                                        ep=self.ep,
                                                                                                                                                                        xdmffile_u=self.xdmffile_u,
                                                                                                                                                                        xdmffile_p=self.xdmffile_p,
                                                                                                                                                                        timeseries_u=self.timeseries_u,
                                                                                                                                                                        timeseries_p=self.timeseries_p,
                                                                                                                                                                        vtkfile_u=self.vtkfile_u, 
                                                                                                                                                                        vtkfile_p=self.vtkfile_p)                                                                                            
                                                                                    

        next_state = self.get_obs()
        if self.steps >= self.max_steps:
            terminal = True
            self.ep += 1
        else:
            terminal = False

        reward = self.compute_reward()

        self.list_save_states.append(next_state)
        self.list_save_actions.append(actions)
        self.list_save_reward.append(reward)

        return next_state, terminal, reward  

`


`state` shape in both `reset()` and `execute()` are `(236,)`

**Comment by AlexKuhnle** [comment]
That looks right. Just to double-check: if you don't run it in parallel mode, just using the single-env runner interface, does it work then? Could you also post the specification of the runner, for completeness (so both the `Runner(...)` constructor and the `runner.run(...)` call)? It looks like it might be a bug on Tensorforce side, but need to see why it isn't already caught by unittests.

**Comment by XueminLiu111** [comment]
Yes, the code works when using single-env.
Here is the agent and runner:

`if alg=="ppo":
    #result of PPO is good/bad
    agent = Agent.create( 
        agent='ppo', environment=environment,  max_episode_timesteps=environment.max_episode_timesteps(),
        states = environment.states(), actions = environment.actions(),
        #actor
        network=network, 
        batch_size=10, learning_rate=learning_rate, likelihood_ratio_clipping=0.2,

        # Critic
        #critic_network=network,

        #critic_optimizer=dict(
        #    type='multi_step', num_steps=5,
        #    optimizer=dict(type='adam', learning_rate=1e-3)
        #),
        entropy_regularization=0.01,
        
        parallel_interactions=number_servers,
        saver=dict(directory=os.path.join(os.getcwd(), 'saver_data/'+alg), frequency=10),  
        recorder=dict(directory=os.path.join(os.getcwd(), 'recorder_data/'+alg), frequency=10),

        exploration=0.005
    )



#parallel training
cwd = os.getcwd()

runner = Runner(
    agent=agent, environments=environments,# evaluation_environment=evaluation_environment,
    num_parallel=number_servers,
     max_episode_timesteps=MAX_STEPS
)

evaluation_folder = "env_" + str(number_servers )
sys.path.append(cwd + evaluation_folder)


runner.run(
    save_best_agent=best_model_path, num_episodes=MAX_EPISODES
)

runner.close()`

**Comment by AlexKuhnle** [comment]
I can't see anything obviously problematic with your configuration. Could you try one more thing: what happens if you replace your environment with simply CartPole?

**Comment by XueminLiu111** [comment]
Thanks very much for your help! The CartPole env works when I change `environment=environment` to `environments=environments` in the `runner = Runner()` function. However, the code cannot finish automatically after training and I have to press `Ctrl+C` to interrupt it as follows

`Episodes: 100%|█| 100/100 [01:01, reward=246.00, ts/ep=246, sec/ep=0.91, ms/ts=3
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
`
Do you have any idea about this problem?

**Comment by AlexKuhnle** [comment]
No, I'm not sure why that is, in particular because it seems to work alright for me. Does it still happen if you remove the `save_best_agent` argument?

Since CartPole is working, it seems to be something about your environment which isn't working well. Is your state returned as a NumPy array? Could you add a print statement before this line in the stacktrace (`Runner.handle_act()`:  `actions = self.agent.act(states=self.states[parallel], parallel=parallel)`), to print `self.states` and `parallel`. Maybe something with the parallel indexing doesn't work.

**Comment by XueminLiu111** [comment]
Thanks very much for your reply! 
The custom env also works when changing `environment=environment` to `environments=environments`. However, the parallel-env doesn't speed up the training when `remote` in the `runner = Runner()` function is `default: local execution`. 

When I  set `remote='socket-client'` in the `runner = Runner()` function, I'll get an error like this 
`  File "train.py", line 115, in <module>
    runner = Runner(
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/site-packages/tensorforce/execution/runner.py", line 149, in __init__
    environment = Environment.create(
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/site-packages/tensorforce/environments/environment.py", line 108, in create
    environment = SocketEnvironment(host=host, port=port, blocking=blocking)
  File "/home/xuemin/anaconda3/envs/fenicstest/lib/python3.8/site-packages/tensorforce/environments/socket_environment.py", line 156, in __init__
    raise TensorforceError("Remote socket connection could not be established.")
tensorforce.exception.TensorforceError: Remote socket connection could not be established.
`

Do you know how to solve this problem?
 I really appreciate your help!

**Comment by XueminLiu111** [comment]
I solve the above problem according to the example [here](https://github.com/tensorforce/tensorforce/blob/master/examples/parallelization.py).
Thanks very much for your help!

**Comment by AlexKuhnle** [comment]
Cool. Not entirely clear why the `ctrl+c` problem happened, but sounds as if it's working now (and yes, local execution does not really bring benefits, only minor ones in some circumstances). Glad the examples helped.
