### ISSUE TITLE
Cannot convert a symbolic Tensor (agent.act/agent.core_act/strided_slice:0) to a numpy array

### ISSUE THREAD

**Issue by clwillingham** [tensorforce/tensorforce#764]
Just looking into this library, I installed all necessary dependencies and installed tensorforce using pip before directly copying the first example it the root readme file. The result:
```
Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.9/site-packages/tensorforce/core/models/model.py", line 1093, in api_act
    actions, internals = self.core_act(
  File "/home/chris/.local/lib/python3.9/site-packages/tensorforce/core/module.py", line 571, in fn
    results = tf_function(*args, **kwargs)
  File "/home/chris/.local/lib/python3.9/site-packages/tensorforce/core/models/tensorforce.py", line 522, in tf_core_act
    lengths = tf.ones(shape=(batch_size,), dtype=util.tf_dtype(dtype='long'))
  File "/usr/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 3120, in ones
    output = _constant_if_small(one, shape, dtype, name)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 852, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (agent.act/agent.core_act/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```
Considering that this issue has not been brought up in the issue list anywhere else, I'm thinking it must be something specific to my system, I am not using any virtualenv setup (I know I probably should be, but I figured i'd start with a bare minimum setup first), I am using Arch Linux, installed tensorflow and numpy through pacman package manager and everything else through pip. Is there something else I am missing?

**Comment by AlexKuhnle** [comment]
Yes, something seems to be wrong here, since based on [the unittests](https://github.com/tensorforce/tensorforce/blob/master/test/test_documentation.py#L158), this should certainly be working. It looks like a problem with TensorFlow, judging from the stacktrace. The following line is apparently problematic, but it's only creating a static tensor of 1s, and it's unclear why this should be causing problems:
```
lengths = tf.ones(shape=(batch_size,), dtype=util.tf_dtype(dtype='long'))
```
Could you check whether maybe there are problems with Arch Linux and TensorFlow?

**Comment by clwillingham** [comment]
turns out in a way it is, as you saw in the log I was using python 3.9. I was also using TensorFlow v2.4.1. I just tested with Tensorflow v2.4.0 as is specified in the requirements file within the repository by using Docker and had no problem running the readme example.

Side note: putting the readme example in the unit tests is brilliant :-)

**Comment by AlexKuhnle** [comment]
Cool, solved then, so closing.

**Comment by clwillingham** [comment]
Any chance you'll get the library working with the latest tensorflow version? running through docker is working but there are some limitations when it comes to using plotting libraries in some scenarios.

**Comment by AlexKuhnle** [comment]
Oh, I see, this is a change in 2.4.1... I will certainly look into that, but might take a few days.

**Comment by AlexKuhnle** [comment]
I've looked into this, and for me everything works fine with 2.4.1. One thing I came across is that it may be a problem with NumPy (see e.g. [here](https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy)) -- what version are you using? Does it work if you down/upgrade to 1.19.5?
