### ISSUE TITLE
Using a custom OpenAiGym crashes when creating the environment

### ISSUE THREAD

**Issue by HadiSDev** [tensorforce/tensorforce#765]
I created I new OpenAiGym environment but when I pass it to the Environment.create function I get an error saying the the class does not contain an attribute called unwrapped.

**Comment by AlexKuhnle** [comment]
There is no attribute `unwrapped` in the Tensorforce code, so are you sure this is not happening in your environment implementation? If so, can you give more detail, e.g. where this attribute is specified and where it is used?

**Comment by HadiSDev** [comment]
I must have made a mistake then. I will close this
