### ISSUE TITLE
Code from document `Getting started` raised exception

### ISSUE THREAD

**Issue by cmsax** [tensorforce/tensorforce#769]
Hi, thanks for the project!

I want to use a customized Environment and tried to run the hello-world code from the document, in `Getting started` part, but it cannot start correctly... Following exception raised:

![图片](https://user-images.githubusercontent.com/18530762/111123176-f87f6d80-85a9-11eb-97da-3365cad43c38.png)

```
tensorforce.exception.TensorforceError: Invalid Environment.create argument max_episode_timesteps given EnvironmentWrapper instance.
```

I'm using:

- Tensorforce             0.6.2
- tensorflow               2.3.1
- python                     3.8.7

Can anyone help me plz? Thanks!

following is the code:

```python
import numpy as np
from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensorforce.execution import Runner


class CustomEnvironment(Environment):
    def __init__(self):
        super().__init__()

    def states(self):
        return dict(type="float", shape=(8,))

    def actions(self):
        return dict(type="int", num_values=4)

    # Optional: should only be defined if environment has a natural fixed
    # maximum episode length; otherwise specify maximum number of training
    # timesteps via Environment.create(..., max_episode_timesteps=???)
    def max_episode_timesteps(self):
        return super().max_episode_timesteps()

    # Optional additional steps to close environment
    def close(self):
        super().close()

    def reset(self):
        state = np.random.random(size=(8,))
        return state

    def execute(self, actions):
        next_state = np.random.random(size=(8,))
        terminal = np.random.random() < 0.5
        reward = np.random.random()
        return next_state, terminal, reward


environment = Environment.create(
    environment=CustomEnvironment, max_episode_timesteps=100
)
agent = Agent.create(
    agent="tensorforce",
    environment=environment,
    update=64,
    optimizer=dict(optimizer="adam", learning_rate=1e-3),
    objective="policy_gradient",
    reward_estimation=dict(horizon=20),
)

run = Runner(
    agent=agent,
    environment=environment,
    max_episode_timesteps=500,
)

run.run(num_episodes=200)

run.close()
```

**Comment by cmsax** [comment]
It seems to be a duplicate issue of [issue-669](https://github.com/tensorforce/tensorforce/issues/669#issue-606811839), and it has been solved by the author, so I will close this issue.

**Comment by cmsax** [comment]
the problem is the duplicate argument passed to `Runner`'s `__init__` func: `max_episode_timesteps`. I removed it and the code just runs smoothly.

It would be more friendly for beginners like me if the `getting started` part of the document offers a more complete code. Since I'm a beginner and it's quite a tiny issue, maybe @AlexKuhnle you could update the document by the way next time you update the codebase. 😁

**Comment by AlexKuhnle** [comment]
Hi @cmsax , I will improve the exception message you got, which currently is not very telling. However, I think the docs are fine -- there is no example where `max_episode_timesteps` is specified twice.
