### ISSUE TITLE
parallelized custom environments

### ISSUE THREAD

**Issue by luigiannelli** [tensorforce/tensorforce#772]
the file `examples/act_observe_vectorized.py` for vectorized environment operations calls 'custom_cartpole' environment that i did not find anywhere. Is it possible to see how this custom environment is defined in order to be able to define my own parallelized custom environment?

**Comment by AlexKuhnle** [comment]
Hi @luigiannelli, it's actually included in the codebase [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/environments/cartpole.py), but re-mapped to `custom_cartpole` to not "overwrite" the standard Gym version. Hope this helps. I will close the issue for now, but if you have any more questions about the parallelized environment feature, feel free to post here.
