### ISSUE TITLE
Saved-model export fails if a summarizer is specified

### ISSUE THREAD

**Issue by bezineb5** [tensorforce/tensorforce#774]
Hi,

When a summarizer is specified in an agent, the export to saved model fails with the following error:
```
AssertionError: Tried to export a function which references untracked object Tensor("15384:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
```

Example source code:
```python
from tensorforce import Environment, Agent


environment = Environment.create(environment='cartpole.json')
agent = Agent.create(
    agent='double_dqn',
    environment=environment,
    batch_size=64,
    memory=500,
    summarizer = {
        'directory': './summaries',
        'summaries': 'all',
    },
)

# Save agent SavedModel
agent.save(directory='saved-model', format='saved-model')
```

If I remove the summarizer, it works.
Any idea?

Thanks a lot!

Benjamin

**Comment by AlexKuhnle** [comment]
I will try it out and see whether this can be fixed. However, TensorFlow saved-model comes with a few peculiarities, so I'm not too sure whether there will be an easy solution. Also, question: is the intention to have summaries for the saved-model, or just that you want to save a model as saved-model after training with summaries? Because there won't be many summaries due to saved-model being inference-only.

**Comment by bezineb5** [comment]
In fact, in my program, I train with the summary. Then I save and then I run the script a 2nd time, to reload and export the saved model. So it's perfectly easy in my own case to avoid the issue.
I just wanted to give a heads up on that issue which might not be easy to understand if it happens to someone else. Maybe simply return a clear error referencing this ticket when trying to export a saved-model when summaries are enabled?

**Comment by AlexKuhnle** [comment]
Hi @bezineb5, I've just looked into that -- simply added a line saving the agent as saved-model to the [summaries unittest](https://github.com/tensorforce/tensorforce/blob/master/test/test_summaries_tracking.py) -- and it didn't throw an exception. Hence the question: are you using the latest version, ideally Github master?

**Comment by AlexKuhnle** [comment]
Any updates here?
