### ISSUE TITLE
Error saving / loading Agent when using Keras Network

### ISSUE THREAD

**Issue by rsanchezgarc** [tensorforce/tensorforce#778]
Hello,

I am trying to use a keras defined network for my Agent, and it seems to be working but when I try to save and load the model, I am getting an error at loading time:
```
Traceback (most recent call last):
  File "/home/ruben/oxford/myProjects/deepLearningCompounds/graphEdition/minimun_example.py", line 61, in <module>
    new_agent = Agent.load(tmp)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 210, in load
    agent = Agent.create(agent=agent, environment=environment, **kwargs)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 112, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
TypeError: __init__() missing 4 required positional arguments: 'update', 'optimizer', 'objective', and 'reward_estimation'
```

I am also attaching some code to reproduce the error.

```
import tempfile

import gym
import tensorflow as tf
from tensorforce import Agent
from tensorforce import Environment
from tensorforce.core.networks import KerasNetwork

TRAIN_EPISODES = 3
env = gym.make('CartPole-v1')

environment = Environment.create( env , max_episode_timesteps=500)

class KerasNet(tf.keras.Model):
  def __init__(self, last_layer_size=64):
    super().__init__()
    self.last_layer_size = last_layer_size
    self.layer1 = tf.keras.layers.Dense(64, input_shape=(4,), activation=tf.nn.relu)
    self.layer2 = tf.keras.layers.Dense(last_layer_size, activation=tf.nn.relu)

  def call(self, inputs):
    x = self.layer1(inputs)
    x = self.layer2(x)
    return x

  def compute_output_shape(self, input_shape):
    return tf.TensorShape(input_shape[0:1] + (self.last_layer_size,))

# KerasNet = KerasNetwork(model=KerasNet, name="myModel") #This also raises estrange error

agent = Agent.create(
    agent='tensorforce',
    environment=environment, 
    memory=10000,
    policy=dict(network= KerasNet),
    objective='policy_gradient',
    reward_estimation=dict(horizon="episode", discount=0.9),
    exploration= 0.1,
    update = dict(unit='timesteps', batch_size=32),
    optimizer = dict(type='adam', learning_rate=3e-4),
)

for i in range(TRAIN_EPISODES):

    # Initialize episode
    states = environment.reset()
    terminal = False
    print("%d/%d      "%(i+1, TRAIN_EPISODES), end="\r")
    while not terminal:
        actions = agent.act(states=states, deterministic=False)
        states, terminal, reward = environment.execute(actions=actions)
        agent.observe(terminal=terminal, reward=reward)


with tempfile.TemporaryDirectory() as tmp:

  agent.save(directory=tmp)
  print("saved!")
  new_agent = Agent.load(tmp)
  print("loaded!")

```

My tensorforce version is 0.6.3 installed from pip and my tensorflow version is 2.4.1

Thank you very much.

Ruben

**Comment by AlexKuhnle** [comment]
Hi,

The problem is very likely due to the network specification as class object, `policy=dict(network= KerasNet)`, which can't be saved as JSON config file (failing silently which is not great and should be changed), and thus the agent config can't be recovered when loading. Two options:

- You can specify the network in a separate module and then specify the "module path" as the network value, see [here](https://tensorforce.readthedocs.io/en/latest/basics/agent-specification.html#module-path-plus-additional-arguments). Since this is a string, it can be saved and loaded.
- You can provide the agent arguments again as part of `Agent.load(tmp, ... agent args ...)`, so to not rely on the non-existent agent config file.
- 
The Keras network feature is relatively recent, so I still need to look into whether there's a better way.

**Comment by rsanchezgarc** [comment]
Hi,

Thank you very much for your quick response and thank you very much for your great work. Tensorfoce is so useful.

I did also tried to create the agent using an instance of the network (which I though it was serializable) `policy=dict(network= KerasNet())` and also failed.

I have tried what you proposed, but I am only able to make the second option work

- Moving the KerasNet  to a separate module is breaking the whole process and the agent is not able to train.
If I move the same network as in the above example, it complains about the type of the argument, since an unexpected parameter is reaching the KerasNet __init__ function. 
```
Traceback (most recent call last):
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ruben/oxford/myProjects/deepLearningCompounds/graphEdition/minimun_example.py", line 68, in <module>
    actions = agent.act(states=states, deterministic=False)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 398, in act
    deterministic=deterministic

MANY MEANINGLESS TENSORFLOW lines!!
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/core/module.py", line 108, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/core/layers/misc.py", line 243, in apply
    x = self.function(x)
  File "/home/ruben/oxford/myProjects/deepLearningCompounds/graphEdition/kerasNet.py", line 29, in __init__
    self.layer2 = tf.keras.layers.Dense(last_layer_size, activation=tf.nn.relu)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py", line 1160, in __init__
    self.units = int(units) if not isinstance(units, int) else units
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tensor'
```

Similarly, if I change the builder to  __init__(self, *, last_layer_size=64) know it complains about one positional argument required
```
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/core/module.py", line 108, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/home/ruben/app/anaconda3/envs/deepMols/lib/python3.7/site-packages/tensorforce/core/layers/misc.py", line 243, in apply
    x = self.function(x)
TypeError: __init__() takes 1 positional argument but 2 were given
```

Again, thank you very much.

Ruben

**Comment by AlexKuhnle** [comment]
Thanks, glad to hear you find it useful. :-)

Serializing the network object might be possible, but I would be surprised if it worked right now out of the box. I will look into it, though, curious what's possible.

You're right, the first option is actually not possible right now, since the network is an argument, not a "Tensorforce module" -- my bad. However, this should definitely be possible, so I will look into that option. I assume you're okay for now with option 2, though?

**Comment by rsanchezgarc** [comment]
Hi Alexander,

Yes, I think that option 2 should be enough. Again, thank you very much and good luck while implementing these new features!

Ruben

**Comment by AlexKuhnle** [comment]
This should be resolved.

**Comment by sbo5** [comment]
> Hi,
> 
> The problem is very likely due to the network specification as class object, `policy=dict(network= KerasNet)`, which can't be saved as JSON config file (failing silently which is not great and should be changed), and thus the agent config can't be recovered when loading. Two options:
> 
> * You can specify the network in a separate module and then specify the "module path" as the network value, see [here](https://tensorforce.readthedocs.io/en/latest/basics/agent-specification.html#module-path-plus-additional-arguments). Since this is a string, it can be saved and loaded.
> * You can provide the agent arguments again as part of `Agent.load(tmp, ... agent args ...)`, so to not rely on the non-existent agent config file.
> 
> The Keras network feature is relatively recent, so I still need to look into whether there's a better way.


Hello,
I am new to TensorFlow and TensorForce and I am also trying to save and load


> 

Hello,

I am new to TensorFlow and TensorForce, so please bear with my question if it is too naive. 
I am also trying to do the same and facing the same error when I load the agent. 
Could you please elaborate more on the second point? How can I provide the agent arguments when I try to load? Where should I get these arguments?
Thank you.
