### ISSUE TITLE
How to save episode reward fast during training instead of using recorder in the agent.creat to saved trace?

### ISSUE THREAD

**Issue by XueminLiu111** [tensorforce/tensorforce#782]
Hi, I want to plot a figure to record the training process of the agent. Therefore, I need the reward for each episode during training, which is the reward number shown as follows:
`Episodes: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [09:50, reward=500.00, ts/ep=500, sec/ep=1.20, ms/ts=2.4, agent=97.1%]
` 

Is there a convenient way to save this value instead of using the recorder in the agent
`agent = dict(
        agent='ppo',
        recorder=dict(directory='recorder_data/run'+str(run), frequency=1))`

Help appreciated.

**Comment by AlexKuhnle** [comment]
Hi @XueminLiu111 ,

You're right, the `recorder` is definitely not the way to go. There are currently 2-3 options: You can either access the values at the end of the run via `runner.episode_rewards`, or record it manually via a callback for `Runner` while you're training (`runner.run()` arguments `callback` and `callback_episode_frequency`), or you can use the `summarizer` argument to record and visualize in TensorBoard. The first one is probably the simplest, let me know how it goes.

**Comment by XueminLiu111** [comment]
Great! Thanks very much for your help!
