### ISSUE TITLE
Details about last layer

### ISSUE THREAD

**Issue by berse2212** [tensorforce/tensorforce#783]
Hi,

I am currently a bit confused about the last layer of the network. The only thing the documentation says about it is: "Note that the final action/value layer of the policy/baseline network is implicitly added, so the network output can be of arbitrary size and use any activation function, and is only required to be a rank-one embedding vector, or optionally have the same shape as the action in the case of a higher-rank action shape."

So I am guessing the last layer is actually a dense layer with N outputs? (N being the number of actions) If this is true is there a way to not implicitly add this last layer? Reason I am asking is that each action has it's own subset of relevant tensors so I don't want them to get mixed in the last layer.

Also on an additional note while I tried to verify my network I called 

`agent.get_architecture()`

But unfortunately got this error:

`Traceback (most recent call last):
  File "file.py", line 302, in <module>
    main()
  File "file.py", line 245, in main
    print(agent.get_architecture())
AttributeError: 'DoubleDQN' object has no attribute 'get_architecture'`

Are the [docs](https://tensorforce.readthedocs.io/en/latest/modules/networks.html) outdated here or am I missing something?

**Comment by berse2212** [comment]
Hi @AlexKuhnle , 

thanks for your response. Yes you right I am actually on the pip version so I might upgrade to the git version to use this feature.

For the first part of the answer, I will describe my problem in a very simplified version: suppose my agent can choose between 4 different actions. Each action can be described with a few values. So what I want to do is basically have 4 different networks predicting the result value for each action and then do the action with the highest value. This is because the values of action 3 give no information about action 1. It would be really unnecessary effort for the network to figure that out, so I want to skip this process to gain a faster / better end result. 

My real problem is obviously more complex but I think this narrows it down the best. I hope this makes it more clearer since English isn't actually my first language I have kind of a hard time describing my plan.

**Comment by AlexKuhnle** [comment]
Is the set of values to be predicted the same or different between actions? I assume the number of values `N` is greater than the number of actions `A`? Would it make sense to reframe the problem and define the agent's actions as these values `N`, and then interpret these `N` values into `A` actions on the environment side? I assume this is kind of what you want to do. Problem with not adding this "last layer" is that this is the distribution layer, and algorithms like policy gradient need the log-probability to compute the update.

**Comment by berse2212** [comment]
The set of values to be predicted is always the same and also exactly matches the number of actions. So basically `A = N`

I am not sure if you completely understood correctly what I wanted to say so I drew a graphic to show it more simple:

![network_example](https://user-images.githubusercontent.com/11964952/117583601-53e05e80-b108-11eb-80d5-efe71699c680.png)

There is 7 different inputs but only input 1 & 2 are relevant for Action 1, Input 3 - 5 are for action 2 and Input 6 & 7 for action 3. They are registered as different tensors. What I now want is that the automatically added last layer just takes one Tensor for each action. Is this somehow possible?

**Comment by berse2212** [comment]
Yes the example is extreme but I created it just for explaining purposes. My real problem is not as distinct as this one in a sense that some actions share bigger parts of the network so it looks more like this:

![network_example2 0](https://user-images.githubusercontent.com/11964952/117831836-43012b80-b275-11eb-8e94-7a2ff75b3c76.png)

**Comment by AlexKuhnle** [comment]
I've implemented the feature supporting this now, have a look e.g. [the third code snippet here](https://tensorforce.readthedocs.io/en/latest/modules/networks.html). Basically, by setting `single_output=False` in the policy, you can specify outputs per action distribution head via registered tensors (still excluding the final linear layer). You need to work with the more general "Tensorforce agent" (so `agent='tensorforce'`) for now.

**Comment by berse2212** [comment]
This is awesome!

**Comment by AlexKuhnle** [comment]
Sorry, wasn't notified of the edit here. You're right, I misunderstood what you meant then. Why would you want to do that, though? This is exactly the type of thing a neural network should be able to learn -- and if it doesn't, that's not a good signal for the overall learning success, I would say... :-)

**Comment by berse2212** [comment]
You right the network should probably learn this on it's own, but it's just a step of optimization I wanted to use. Just like when the network is learning how to drive you would never input the information about the car's color since it adds nothing of value. So the idea is to skip some information for certain actions since they are not relevant for those actions. Does this make sense or, since you obviously more advanced in this topic, is that something you would not recommend in doing?

**Comment by AlexKuhnle** [comment]
I don't think I've encountered this type of modelling where the individual logits per option of a discrete action are parametrized with different inputs. Moreover, I don't think your comparison to irrelevant inputs like a car's color is right, though: If the choice is between action 1/2/3, and the input matters for the choice of some options, e.g. 2/3, it also matters for the choice among all options, since whether to choose 1 is still affected by this input which influences the likelihood of 2/3. So it seems to me like the modelling assumptions are not quite right, and either way a network should be able to learn this, hence my recommendation to just try the standard setup.

If you want to give it a go, though, I could add the option to "skip" the final linear layer and leave it to the user to provide appropriate logits, which should allow you to do what you want.

**Comment by berse2212** [comment]
I would kinda like to try it out. But since this seems to be a rather odd request I would only do it depending on how much work it is for you and how complex it would be for me to add the needed logits.

**Comment by AlexKuhnle** [comment]
Shouldn't be too problematic, can soon do that.

**Comment by berse2212** [comment]
Any updates about this?

**Comment by AlexKuhnle** [comment]
Oh sorry, I completely forgot about this :-/  I can add the option to skip the linear layer this weekend.

**Comment by AlexKuhnle** [comment]
Latest commit now offers a `skip_linear` argument for the `categorical` distribution, see [the unittest here](https://github.com/tensorforce/tensorforce/blob/master/test/test_policies.py#L104) for an example. Hope that looks like what you need, and sorry for the wait. :-)
