### ISSUE TITLE
Issue with default module

### ISSUE THREAD

**Issue by MANU-CHAUHAN** [tensorforce/tensorforce#786]
Hi all,

Followed the official documentation for installation and example but got this:

`ModuleNotFoundError: No module named 'agent'`

Previously, similar but not same & closed  [issue](https://github.com/tensorforce/tensorforce/issues/641)
Running on:
Windows 10
Python 3.8

**Comment by MANU-CHAUHAN** [comment]
> Can you give a bit more detail, like exception stacktrace, how you run the command and in which directory? Also, which example are you running, because I'm not aware of one using `agent` as a module?



I could be wrong here but the [docs ](https://tensorforce.readthedocs.io/en/latest/basics/getting-started.html#initializing-an-agent)have this:

    from tensorforce.agents import Agent

    agent = Agent.create(
    agent='tensorforce', environment=environment, update=64,
    optimizer=dict(optimizer='adam', learning_rate=1e-3),
    objective='policy_gradient', reward_estimation=dict(horizon=20)
    )

**Comment by AlexKuhnle** [comment]
So this snippet is causing the exception?
