### ISSUE TITLE
Tensorflow v2.5.0rc3

### ISSUE THREAD

**Issue by johnnync13** [tensorforce/tensorforce#788]
Tensorflow v2.5.0rc3 is full compatible with tensorforce library
![image](https://user-images.githubusercontent.com/22727137/117841586-7778e580-b27d-11eb-8763-47b0f969b655.png)

**Comment by AlexKuhnle** [comment]
Hi @johnnync13 , what's the issue here? Sounds like everything is working... :-)

**Comment by johnnync13** [comment]
@AlexKuhnle release:  https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0

**Comment by AlexKuhnle** [comment]
Thanks for letting me know. I've updated the requirements now, should hopefully all work. :-)
