### ISSUE TITLE
What is entropy_regularization in ac policies? 

### ISSUE THREAD

**Issue by XueminLiu111** [tensorforce/tensorforce#789]
What is `entropy_regularization` in ac policies?  Could you explain more explicitly or is there any reference I can take a look at?

**Comment by AlexKuhnle** [comment]
Hi @XueminLiu111, entropy regularization simply adds a loss component encouraging entropy of the policy distribution. This means that, on the one hand, the agent is encouraged to be certain which decision to take and, on the other hand, don't be too certain (low entropy) unless necessary, so it's a way of avoiding "overfitting". Have a look e.g. [here](https://awjuliani.medium.com/maximum-entropy-policies-in-reinforcement-learning-everyday-life-f5a1cc18d32d), and there are lots of similar resources. However, note that there is a related approach (see blogpost), called maximum-entropy RL, which incorporates entropy into the reward signal, not simply as an additional loss component (as `entropy_regularization` does) -- same motivation, but different approach, maybe available in Tensorforce soon as well.

**Comment by XueminLiu111** [comment]
Thanks very much for your explanation. It really helps!
Is the source code at here:
https://github.com/tensorforce/tensorforce/blob/633d46cb5c0043768dc5f0d703daf5b4c14730e3/tensorforce/core/models/tensorforce.py#L2721

**Comment by AlexKuhnle** [comment]
Yes, that's the place in the code.

Assume this can be closed then. :-)
