### ISSUE TITLE
how to add Attentional mechanism

### ISSUE THREAD

**Issue by asenasen123** [tensorforce/tensorforce#790]
how to add attention mechanism?

**Comment by AlexKuhnle** [comment]
Hi @asenasen123, what kind of attention mechanism are you interested in? You can e.g. use a custom layer implementation for that, but I'm also happy to add an attention layer to the set of available layers.

**Comment by asenasen123** [comment]
Hello,Alexander Kuhnle.Could you&nbsp; briefly show me how to add an attention mechanism？And in ppo algorithm framework,I only see the critic network,where is the actor network?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月15日(星期六) 晚上11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
Hi @asenasen123, what kind of attention mechanism are you interested in? You can e.g. use a custom layer implementation for that, but I'm also happy to add an attention layer to the set of available layers.

**Comment by asenasen123** [comment]
for example,
network_spec = [
     [
          dict(type='input', names=['image']),
          dict(type='conv2d', size=32, window=(8, 6), stride=4, activation='relu', padding='SAME'),
          dict(type='conv2d', size=64, window=(4, 3), stride=2, activation='relu', padding='SAME'),
          dict(type='pool2d', pooling_type='max', window=2, stride=2, padding='SAME'),
          dict(type='conv2d', size=64, window=2, stride=2, activation='relu', padding='SAME'),
          dict(type='flatten'),
          dict(type='output', name='image_output')
     ],
    
     [
          dict(type='input', names=['image_output', 'previous_act', 'relative_pos'], aggregation_type='concat'),
          dict(type='dense', size=512, activation='relu'),
          dict(type='dense', size=512, activation='relu'),
     ]
]

how could I add an attention mechanism in the network?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "夏森"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 晚上7:35
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [tensorforce/tensorforce] how to add Attentional mechanism (#790)



 



------------------ 原始邮件 ------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月15日(星期六) 晚上11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
Hi @asenasen123, what kind of attention mechanism are you interested in? You can e.g. use a custom layer implementation for that, but I'm also happy to add an attention layer to the set of available layers.

**Comment by AlexKuhnle** [comment]
PPO has an argument `network` ([see here](https://tensorforce.readthedocs.io/en/latest/agents/ppo.html)) which is the policy network.

You can implement a custom layer by sub-classing [Layer](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/layers/layer.py#L27), similar to e.g. [Dense layer](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/layers/dense.py#L22). You can then use the layer e.g. via ` dict(type='my_layer', ...)` if the layer is specified in `my_layer.py`.

Where exactly do you want to use what kind of attention? I wanted to add attention for a while, so alternatively maybe I can look into that.

**Comment by asenasen123** [comment]
After a long time of trying,I failed.Could you briefly show me how to&nbsp;implementation the my_layer.py that include the attentional mechanism.Thank you very much!!!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorforce/tensorforce"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 晚上7:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
PPO has an argument network (see here) which is the policy network.
 
You can implement a custom layer by sub-classing Layer, similar to e.g. Dense layer. You can then use the layer e.g. via  dict(type='my_layer', ...) if the layer is specified in my_layer.py.
 
Where exactly do you want to use what kind of attention? I wanted to add attention for a while, so alternatively maybe I can look into that.

**Comment by AlexKuhnle** [comment]
What attention are you intending to use, and where exactly? Can you post your implementation for this so far? There is no single attention layer, so I don't know what you are trying to achieve.

**Comment by asenasen123** [comment]
Thanks for your replay. I want to use spatial attention module like this. Could you help me write a 'my_layer.py' about the spatial attention module.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月22日(星期六) 凌晨0:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
What attention are you intending to use, and where exactly? Can you post your implementation for this so far? There is no single attention layer, so I don't know what you are trying to achieve.

**Comment by asenasen123** [comment]
Could you help me put an attention mechanism in the middle of this network?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorforce/tensorforce"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月22日(星期六) 凌晨0:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
What attention are you intending to use, and where exactly? Can you post your implementation for this so far? There is no single attention layer, so I don't know what you are trying to achieve.

**Comment by AlexKuhnle** [comment]
I've added a new basic self-attention layer which is maybe what you're looking for. You can add it via `dict(type='self_attention', size=???, attention_size=???)`. Note that this implementation currently does not scale well with image size, so unless your images are very small, this probably won't work well yet.

**Comment by AlexKuhnle** [comment]
I have some ideas how to make it more "scalable", can add that later.

**Comment by asenasen123** [comment]
Thanks for your replay! Could you tell me Where is the directory of 'self-attention'.I want to see the source code of the 'attention mechanism'.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月23日(星期天) 晚上6:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
I've added a new basic self-attention layer which is maybe what you're looking for. You can add it via dict(type='self_attention', size=???, attention_size=???). Note that this implementation currently does not scale well with image size, so unless your images are very small, this probably won't work well yet.

**Comment by AlexKuhnle** [comment]
It's [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/layers/attention.py).

**Comment by asenasen123** [comment]
Thanks for your replay.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月23日(星期天) 晚上9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
It's here.

**Comment by asenasen123** [comment]
Sorry to botter you.I would like to ask you a question：where is the&nbsp;directory of 'input'?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月23日(星期天) 晚上9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
It's here.

**Comment by AlexKuhnle** [comment]
What do you mean by "directory" of "input"?

**Comment by asenasen123** [comment]
dict(type='self_attention'),the directory of 'self_attention' is 'tensorforce/tensorforce/core/layers/attention.py'.Could you tell me where is the 'directory' of 'input','conv2d' and 'pool2d'?





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月24日(星期一) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
What do you mean by "directory" of "input"?

**Comment by AlexKuhnle** [comment]
You can all find them in the files here: `tensorforce/tensorforce/core/layers/`  E.g. `conv2d` in `convolution.py` etc. If you want to dig into the code more, it's worth having a look through these files.

**Comment by asenasen123** [comment]
Thanks for your replay. Could you tell me where is the directory of 'input'. I only find the input_rnn.py.

And could you tell me the naming rules of "the dict(type='conv2d')" .(we name the type according to the specification key?)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月24日(星期一) 晚上9:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
You can all find them in the files here: tensorforce/tensorforce/core/layers/  E.g. conv2d in convolution.py etc. If you want to dig into the code more, it's worth having a look through these files.

**Comment by AlexKuhnle** [comment]
Actually, good point, `input` and `output` in your spec should be `retrieve` and `register`, respectively... However, `input`/`output` are actually good aliases, maybe I will introduce them.

Yes, `type` is what the documentation calls "specification key". There is no strict rule here, and the assignment is defined [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/layers/__init__.py#L40).

**Comment by asenasen123** [comment]
Sorry&nbsp; to botter you.&nbsp;Actually, I'm not familiar with your framework. Could you tell me how to retrieve and register in my spec.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander ***@***.***&gt;; 
发送时间: 2021年5月25日(星期二) 凌晨4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
Actually, good point, input and output in your spec should be retrieve and register, respectively... However, input/output are actually good aliases, maybe I will introduce them.
 
Yes, type is what the documentation calls "specification key". There is no strict rule here, and the assignment is defined here.

**Comment by AlexKuhnle** [comment]
There you go, just change `type` and argument name `tensors`/`tensor`:

```
network_spec = [
     [
          dict(type='retrieve', tensors=['image']),
          dict(type='conv2d', size=32, window=(8, 6), stride=4, activation='relu', padding='SAME'),
          dict(type='conv2d', size=64, window=(4, 3), stride=2, activation='relu', padding='SAME'),
          dict(type='pool2d', pooling_type='max', window=2, stride=2, padding='SAME'),
          dict(type='conv2d', size=64, window=2, stride=2, activation='relu', padding='SAME'),
          dict(type='flatten'),
          dict(type='register', tensor='image_output')
     ],

     [
          dict(type='retrieve', tensors=['image_output', 'previous_act', 'relative_pos'], aggregation_type='concat'),
          dict(type='dense', size=512, activation='relu'),
          dict(type='dense', size=512, activation='relu'),
     ]
]
```

**Comment by asenasen123** [comment]
Hello,I have downloaded the version 0.4.3 of tensorforce. And I want to know what does 'update' mean in 'tensorforce/tensorforce/core/networks/layer.py'? And I have achieved the attentional mechanism in 'tensorforce/tensorforce/core/networks/layer.py'.Could you help me modify it?
class SE(Layer):
&nbsp;&nbsp;&nbsp; def __init__(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; self,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; size=None,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; weights=None,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; l2_regularization=0.0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; l1_regularization=0.0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; named_tensors=None,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; scope='se',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; summary_labels=()
&nbsp;&nbsp;&nbsp; ):
&nbsp; super(SE, self).__init__(named_tensors=named_tensors, scope=scope, summary_labels=summary_labels)


&nbsp; self.dense1 = Dense(size?, activation='relu')
&nbsp; self.dense2 = Dense(size?, activation='sigmoid')
&nbsp;
&nbsp;def tf_apply(self, x, update??):
&nbsp; squeeze = tf.reduce_mean(residual, axis=[0,1], keepdims=True)
&nbsp; squeeze = self.dense1.apply(x=squeeze)
&nbsp; squeeze = self.dense2.apply(x=squeeze)
&nbsp; scale = x * squeeze
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return scale
&nbsp;
&nbsp;def tf_regularization_loss(self):
&nbsp; regularization_loss = super(SE, self).tf_regularization_loss()
&nbsp;&nbsp;
&nbsp; if regularization_loss is None:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; losses = list()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; else:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; losses = [regularization_loss]
&nbsp;&nbsp;
&nbsp; regularization_loss = self.dense1.regularization_loss()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if regularization_loss is not None:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; losses.append(regularization_loss)
&nbsp; regularization_loss = self.dense2.regularization_loss()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if regularization_loss is not None:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; losses.append(regularization_loss)
&nbsp;&nbsp;
&nbsp; if len(losses) &gt; 0:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return tf.add_n(inputs=losses)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; else:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return None
&nbsp;
&nbsp;def get_variables(self, include_nontrainable=False):
&nbsp; layer_variables = super(SE, self).get_variables(include_nontrainable=include_nontrainable)
&nbsp; dense1_variables = self.dense1.get_variables(include_nontrainable=include_nontrainable)
&nbsp; dense2_variables = self.dense2.get_variables(include_nontrainable=include_nontrainable)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return dense1_variables + dense2_variables




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 凌晨3:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
There you go, just change type and argument name tensors/tensor:
 network_spec = [      [           dict(type='retrieve', tensors=['image']),           dict(type='conv2d', size=32, window=(8, 6), stride=4, activation='relu', padding='SAME'),           dict(type='conv2d', size=64, window=(4, 3), stride=2, activation='relu', padding='SAME'),           dict(type='pool2d', pooling_type='max', window=2, stride=2, padding='SAME'),           dict(type='conv2d', size=64, window=2, stride=2, activation='relu', padding='SAME'),           dict(type='flatten'),           dict(type='register', tensor='image_output')      ],      [           dict(type='retrieve', tensors=['image_output', 'previous_act', 'relative_pos'], aggregation_type='concat'),           dict(type='dense', size=512, activation='relu'),           dict(type='dense', size=512, activation='relu'),      ] ]

**Comment by AlexKuhnle** [comment]
I can't help with older versions of Tensorforce, unfortunately. I recommend using the latest version and above mentioned `self_attention` layer.

**Comment by asenasen123** [comment]
Could you tell me what's the difference between 'network' and 'critic'?And Could you tell me where is the actor network?Could you briefly introduce the method of constructing DDPG network？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 晚上9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
I can't help with older versions of Tensorforce, unfortunately. I recommend using the latest version and above mentioned self_attention layer.

**Comment by AlexKuhnle** [comment]
- `network` is the actor/policy network, `critic` is the critic (or "baseline") network.
- There are no constraints on how to construct a DDPG `network`, as long as it processes the inputs and produces a single output embedding (as is required for essentially all networks in Tensorforce).

**Comment by asenasen123** [comment]
Could you tell me how to get the value of 'loss'?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月31日(星期一) 晚上7:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





  
network is the actor/policy network, critic is the critic (or "baseline") network.
 
There are no constraints on how to construct a DDPG network, as long as it processes the inputs and produces a single output embedding (as is required for essentially all networks in Tensorforce).

**Comment by AlexKuhnle** [comment]
You can set the agent argument `tracking='all'`  and then use `agent.tracked_tensors()` (see [here](https://tensorforce.readthedocs.io/en/latest/agents/agent.html#tensorforce.agents.TensorforceAgent.tracked_tensors)) which should contain the relevant values. Note that you need to update to the latest Github commit, as loss value tracking was not yet implemented.

**Comment by asenasen123** [comment]
When I instantiate a ddpg agent,something went wrong here. Could you tell me how to solve it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月7日(星期一) 凌晨0:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
You can set the agent argument tracking='all'  and then use agent.tracked_tensors() (see here) which should contain the relevant values. Note that you need to update to the latest Github commit, as loss value tracking was not yet implemented.

**Comment by asenasen123** [comment]
When I instantiate a ddpg agent,something went wrong here. Could you tell me how to solve it?






states = dict(
    image=GazeboMaze.states,
    relative_pos=dict(shape=(2,), type='float'),
    previous_act=dict(shape=(2,), type='float'),
    previous_reward=dict(shape=(1,), type='float')
)


network_spec = [
     [
        dict(type='input', names=['image']),
        dict(type='conv2d', size=32, window=(8, 6), stride=4, activation='relu', padding='SAME'),
        dict(type='conv2d', size=64, window=(4, 3), stride=2, activation='relu', padding='SAME'),
        dict(type='pool2d', pooling_type='max', window=2, stride=2, padding='SAME'),
        dict(type='conv2d', size=64, window=2, stride=2, activation='relu', padding='SAME'),
        dict(type='flatten'),
        dict(type='dense', size=32, activation='relu'),
        dict(type='output', name='image_output')
     ],
     [
        dict(type='input', names=['image_output', 'relative_pos'], aggregation_type='concat'),
        dict(type='internal_lstm', size=256),
        dict(type='output', name='lstm_output'),
     ],

     [
        dict(type='input', names=['lstm_output', 'previous_act', 'previous_reward'], aggregation_type='concat'),
        dict(type='internal_lstm', size=256),
        dict(type='dense', size=256, activation='relu'),
     ]

]

critic_network_spec = [
    [
        dict(type='input', names=['image']),
        dict(type='conv2d', size=32, window=(8, 6), stride=4, activation='relu', padding='SAME'),
        dict(type='conv2d', size=64, window=(4, 3), stride=2, activation='relu', padding='SAME'),
        dict(type='pool2d', pooling_type='max', window=2, stride=2, padding='SAME'),
        dict(type='conv2d', size=128, window=2, stride=2, activation='relu', padding='SAME'),
        dict(type='flatten'),
        dict(type='output', name='image_output')
    ],
    [
        dict(type='input', names=['image_output', 'relative_pos', 'angular_vel', 'linear_vel'],
             aggregation_type='concat'),
        dict(type='dense', size=256, activation='relu'),
        dict(type='dense', size=128, activation='relu'),
        dict(type='output', name='output2')
    ],
    [
        dict(type='input', names=['output2', 'previous_act', 'previous_reward'], aggregation_type='concat'),
        dict(type='dense', size=64, activation='relu'),
        dict(type='dense', size=1, activation='tanh')
    ]
]

memory = dict(
    type='replay',
    include_next_states=True,
    capacity=10000
)

exploration = dict(
    type='epsilon_decay',
    initial_epsilon=1.0,
    final_epsilon=0.1,
    timesteps=100000,
    start_timestep=0
)

optimizer = dict(
    type='adam',
    learning_rate=0.0001
)

critic_optimizer = dict(
    type='adam',
    learning_rate=0.001
)

# Instantiate a Tensorforce agent
agent = DDPGAgent(
    states=states,
    actions=GazeboMaze.actions,
    network=network_spec,
    critic_network=critic_network_spec,
    # update_mode=update_model,
    # memory=memory,
    actions_exploration=exploration,
    saver=dict(directory=saver_dir, basename='E2E_DDPG_rnn_model.ckpt', load=restore, seconds=6000),
    summarizer=dict(directory=summarizer_dir, labels=["graph", "losses", "reward", "entropy"], seconds=6000),
    optimizer=optimizer,
    critic_optimizer=critic_optimizer
)





























------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月7日(星期一) 凌晨0:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
You can set the agent argument tracking='all'  and then use agent.tracked_tensors() (see here) which should contain the relevant values. Note that you need to update to the latest Github commit, as loss value tracking was not yet implemented.

**Comment by AlexKuhnle** [comment]
Hi, sorry for the late response. Could you post the exception, so I can see what went wrong?

**Comment by asenasen123** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月12日(星期六) 晚上7:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
Hi, sorry for the late response. Could you post the exception, so I can see what went wrong?

**Comment by AlexKuhnle** [comment]
There is no content in your last message, apart from the reply copy?

**Comment by asenasen123** [comment]
sorry to botter you.Could you help me add a intrinsic curiosity module in ppo?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月14日(星期一) 下午4:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tensorforce/tensorforce] how to add Attentional mechanism (#790)





 
There is no content in your last message, apart from the reply copy?

**Comment by AlexKuhnle** [comment]
This is unfortunately not provided as an option right now, so it requires going deep into the code and making fundamental modifications. While this is vaguely on the roadmap, I don't expect it to happen anytime soon, given my limited time recently -- I'm sorry. (I would consider committing time to adding such features in return for sponsoring, if you want to consider that -- feel free to drop me a mail in that case, alexkuhnle@t-online.de).
