### ISSUE TITLE
Saving special Agents

### ISSUE THREAD

**Issue by berse2212** [tensorforce/tensorforce#794]
Hi there,

I tried saving either a DQN or a DDQN Agent via

`runner.agent.save(directory='saved-model', format='saved-model')`

and both of them failed to do so:

`Traceback (most recent call last):
  File "/home/berse2212/git/masterarbeit/PyQL/de/pyql/PyQl.py", line 258, in <module>
    main()
  File "/home/berse2212/git/masterarbeit/PyQL/de/pyql/PyQl.py", line 253, in main
    runner.agent.save(directory='saved-model', format='saved-model')
  File "/home/berse2212/git/tensorforce/tensorforce/agents/agent.py", line 596, in save
    path = self.model.save(directory=directory, filename=filename, format=format, append=append)
AttributeError: 'DoubleDQN' object has no attribute 'model'`

Is it currently only possible to save the generic Tensorforce agent?

**Comment by AlexKuhnle** [comment]
That certainly shouldn't be the case. Can you post the code snippet? I don't see how this is possible, but it almost looks like you attempt to save before things are properly initialized...

**Comment by berse2212** [comment]
Nevermind this error, I already found the fix for it. Turns out closing the runner before calling the save method is not a good idea.

However I am still unable to save my agent:

`Traceback (most recent call last):
  File "/home/berse2212/git/masterarbeit/PyQL/de/pyql/PyQl.py", line 257, in <module>
    main()
  File "/home/berse2212/git/masterarbeit/PyQL/de/pyql/PyQl.py", line 248, in main
    runner.agent.save(directory='saved-model', format='saved-model')
  File "/home/berse2212/git/tensorforce/tensorforce/agents/agent.py", line 596, in save
    path = self.model.save(directory=directory, filename=filename, format=format, append=append)
  File "/home/berse2212/git/tensorforce/tensorforce/core/models/model.py", line 840, in save
    return tf.saved_model.save(obj=checkpoint, export_dir=directory, signatures=signatures)
  File "/home/berse2212/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1032, in save
    _, exported_graph, object_saver, asset_info = _build_meta_graph(
  File "/home/berse2212/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/home/berse2212/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1151, in _build_meta_graph_impl
    asset_info, exported_graph = _fill_meta_graph_def(meta_graph_def,
  File "/home/berse2212/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 687, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, resource_map)
  File "/home/berse2212/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 552, in _generate_signatures
    outputs = _call_function_with_mapped_captures(
  File "/home/berse2212/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 504, in _call_function_with_mapped_captures
    export_captures = _map_captures_to_created_tensors(function.graph.captures,
  File "/home/berse2212/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 420, in _map_captures_to_created_tensors
    raise AssertionError(
AssertionError: Tried to export a function which references untracked resource Tensor("29359:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.

Trackable Python objects referring to this tensor (from gc.get_referrers, limited to two hops):
<tf.Variable 'agent/policy/action-values-tracking:0' shape=(10,) dtype=float32>`

I am using just "normal" layers in my network setup and nothing custom made. Nonetheless here is my current (rather big) network setup:

`network = [
        [
            dict(type='retrieve', tensors=['move1']),
            dict(type='dense', size=30, activation='relu'),
            dict(type='register', tensor='move1-embedding')
        ],
        [
            dict(type='retrieve', tensors=['move2']),
            dict(type='dense', size=30, activation='relu'),
            dict(type='register', tensor='move2-embedding')
        ],
        [
            dict(type='retrieve', tensors=['move3']),
            dict(type='dense', size=30, activation='relu'),
            dict(type='register', tensor='move3-embedding')
        ],
        [
            dict(type='retrieve', tensors=['move4']),
            dict(type='dense', size=30, activation='relu'),
            dict(type='register', tensor='move4-embedding')
        ],
        [
            dict(type='retrieve', tensors=['active_pokemon']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='active_pokemon-embedding')
        ],
        [
            dict(type='retrieve', tensors=['active_opposing_pokemon']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='active_opposing_pokemon-embedding')
        ],
        [
            dict(type='retrieve', tensors=['pokemon1']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='pokemon1-embedding')
        ],
        [
            dict(type='retrieve', tensors=['pokemon2']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='pokemon2-embedding')
        ],
        [
            dict(type='retrieve', tensors=['pokemon3']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='pokemon3-embedding')
        ],
        [
            dict(type='retrieve', tensors=['pokemon4']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='pokemon4-embedding')
        ],
        [
            dict(type='retrieve', tensors=['pokemon5']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='pokemon5-embedding')
        ],
        [
            dict(type='retrieve', tensors=['pokemon6']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='pokemon6-embedding')
        ],
        [
            dict(type='retrieve', tensors=['opposing_pokemon1']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='opposing_pokemon1-embedding')
        ],
        [
            dict(type='retrieve', tensors=['opposing_pokemon2']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='opposing_pokemon2-embedding')
        ],
        [
            dict(type='retrieve', tensors=['opposing_pokemon3']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='opposing_pokemon3-embedding')
        ],
        [
            dict(type='retrieve', tensors=['opposing_pokemon4']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='opposing_pokemon4-embedding')
        ],
        [
            dict(type='retrieve', tensors=['opposing_pokemon5']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='opposing_pokemon5-embedding')
        ],
        [
            dict(type='retrieve', tensors=['opposing_pokemon6']),
            dict(type='dense', size=150, activation='relu'),
            dict(type='register', tensor='opposing_pokemon6-embedding')
        ],
        [
            dict(type='retrieve',
                 tensors=['pokemon1-embedding', 'pokemon2-embedding', 'pokemon3-embedding', 'pokemon4-embedding',
                          'pokemon5-embedding', 'pokemon6-embedding'], aggregation="stack"),
            # dict(type='keras', layer='MaxPooling3D', pool_size=(2, 1, 2), strides=None, padding='valid'),
            dict(type='flatten'),
            dict(type='dense', size=500, activation='relu'),
            dict(type='register', tensor='team-embedding')
        ],
        [
            dict(type='retrieve',
                 tensors=['opposing_pokemon1-embedding', 'opposing_pokemon2-embedding', 'opposing_pokemon3-embedding',
                          'opposing_pokemon4-embedding',
                          'opposing_pokemon5-embedding', 'opposing_pokemon6-embedding'], aggregation="stack"),
            # dict(type='keras', layer='MaxPooling3D', pool_size=(2, 1, 2), strides=None, padding='valid'),
            dict(type='flatten'),
            dict(type='dense', size=500, activation='relu'),
            dict(type='register', tensor='opposing_team-embedding')
        ],
        [
            dict(type='retrieve',
                 tensors=['team-embedding', 'opposing_team-embedding', 'side', 'opposing_side', 'weather'],
                 aggregation="concat"),
            dict(type='dense', size=500, activation='relu'),
            dict(type='register', tensor='info_blob-embedding')
        ],
        [
            dict(type='retrieve',
                 tensors=['move1-embedding', 'active_pokemon-embedding',
                          'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='move1-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['move2-embedding', 'active_pokemon-embedding',
                          'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='move2-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['move3-embedding', 'active_pokemon-embedding',
                          'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='move3-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['move4-embedding', 'active_pokemon-embedding',
                          'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='move4-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['pokemon1-embedding', 'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='switch1-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['pokemon2-embedding', 'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='switch2-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['pokemon3-embedding', 'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='switch3-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['pokemon4-embedding', 'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='switch4-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['pokemon5-embedding', 'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='switch5-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['pokemon6-embedding', 'active_opposing_pokemon-embedding', 'info_blob-embedding'],
                 aggregation="concat"),
            dict(type='dense', size=1, activation='relu'),
            dict(type='register', tensor='switch6-action')
        ],
        [
            dict(type='retrieve',
                 tensors=['move1-action', 'move2-action', 'move3-action', 'move4-action',
                          'switch1-action', 'switch2-action', 'switch3-action', 'switch4-action', 'switch5-action',
                          'switch6-action', ],
                 aggregation="concat")
        ]
    ]`

**Comment by AlexKuhnle** [comment]
That is a rather big network :-D  I think the problem here may be related to tracking being used -- could you try without tracking, just to confirm? Unfortunately the `saved-model` format is rather restrictive in what graph patterns it seems to accept, so: (a) if you don't "need" the `saved-model` format, I would recommend using one of the others; (b) if it is indeed the tracking feature causing the problem, I can investigate whether there's an easy way to fix this problem.

Re formatting: did you use the triple ``` environment?

**Comment by berse2212** [comment]
Yes you absolutely right. A checkpoint save did indeed work.

I am unsure on what I need thought. The documentation is a bit ... short. Can you explain to me a bit more in detail what the differences are? That would be great!

**Comment by AlexKuhnle** [comment]
Well, the documentation is supposed to "forward" to the corresponding TensorFlow documentation about Checkpoints vs SavedModels. :-)  But basically, on the one hand, `checkpoint` stores weights and graph information in some format which can be loaded again with TensorFlow in Python (as opposed to `numpy` and `hdf5` which only store weights -- but the difference doesn't really matter in case of Tensorforce). On the other hand, `saved-model` stores the weights and graph in a "language-independent" / deployment-ready format, so the model should be possible to be loaded e.g. in TensorFlow for C++, and be deployed via TensorFlow Serving (that's at least the idea, but I've never tried that myself). However, the SavedModel format comes with more TF graph constraints, so is incompatible with some features, and because of that, Tensorforce only stores an optimized act-only  deployment version, so training won't be possible anymore with a SavedModel. In summary: unless you need to use a trained model in another language or seriously deploy it, you shouldn't use the `saved-model` format, and instead the default `checkpoint` format will do.

**Comment by berse2212** [comment]
Then the checkpoint format is perfectly!
