### ISSUE TITLE
Sharing layers between networks

### ISSUE THREAD

**Issue by cipollone** [tensorforce/tensorforce#795]
What I'm trying to do is to share some layers between policy and baseline. I've tried register/retrieve, and block/reuse, without success. Is there a way to use a common network between the two models?
I've found few issues #269 and another one I can't find anymore, but they refer to an old release.

I'm using Tensorforce agent class, and an updated github master version.

The design of the library is very good. The project would benefit a lot from some other clarifications in the documentation.

Thanks for the support

**Comment by AlexKuhnle** [comment]
Hi @cipollone,

The `block` and `reuse` layers are indeed supposed to enable this. Could you post your agent/network config, and what exception you get? Also, [this unittest](https://github.com/tensorforce/tensorforce/blob/master/test/test_layers.py#L122) may help...

Re documentation: totally agree, the docs are currently rather minimal. I would very much encourage you (and/or others) to contribute docs and examples -- whatever you would have found helpful and whenever you come across something unclear. I'm also trying to do that, but it's sometimes hard to predict what's unclear, plus of course time constraints. :-)

**Comment by cipollone** [comment]
After few tests, I see that I only get an error because I'm trying to add an RNN in my model. So it migth be an issue related to that:
```
  File "/home/cipollor/.cache/pypoetry/virtualenvs/recurrl-DmI5t0b4-py3.8/lib/python3.8/site-packages/tensorforce/core/module.py", line 128, in decorated
    graph_args = input_signature.kwargs_to_args(
  File "/home/cipollor/.cache/pypoetry/virtualenvs/recurrl-DmI5t0b4-py3.8/lib/python3.8/site-packages/tensorforce/core/utils/dicts.py", line 211, in kwargs_to_args
    assert spec.is_compatible_with(spec_or_tensor=arg), (name, spec, arg)
AssertionError: ('horizons', TensorSpec(shape=(None, 2), dtype=tf.int64, name='horizons'), <tf.Tensor: shape=(19, 32), dtype=float32, numpy=...............)
```
Part of the agent configuration in yaml format:
```
agent:
  agent: a2c
  network:
    - type: block
      name: core_net
      layers:
      - type: dense
        size: 32
      - type: lstm
        size: 64
        horizon: 10
  critic:
    - type: reuse
      layer: core_net
```
no problems if I remove the lstm layer instead.

A probably unrelated issue, unfortunately, is that the agent always fails to be saved if I have a reuse layer inside (even without lstm). Both with saver, or manual save, it raises:
```
ValueError: Unable to save the object
ListWrapper([<tensorforce.core.layers.dense.Dense object at 0x7f58f0042dc0>])
(a list wrapper constructed to track trackable TensorFlow objects). A list
element was replaced (__setitem__, __setslice__), deleted (__delitem__,
__delslice__), or moved (sort). In order to support restoration on object
creation, tracking is exclusively for append-only data structures.

If you don't need this list checkpointed, wrap it in a non-trackable object; it will be subsequently ignored.
```
I'm using the default "checkpoint" format.

Actually, about the documentation, let me correct myself. It's very well organized.
However, for development, I find that understanding the internals a little bit is very useful. I've found the configurations benchmarks/configs/ppo.json and benchmarks/configs/ppo_tensorforce.json very useful to start looking into Tensorforce Agent/Model. Few more agent configurations like those would be great to understand.

**Comment by AlexKuhnle** [comment]
I will need to investigate both problems over the weekend. Particularly the saving problem is interesting -- I haven't realised that the reuse layer causes weird graph tracking problems (but similarly unexpected TensorFlow exceptions come up here and there, particularly when it comes to saving).

Re docs/configs: I can certainly add a few more configs like this. And I know, there are a lot of details about internal structure that is helpful to understand -- hope I get the time to write a blogpost or so about that at some point. :-)

**Comment by AlexKuhnle** [comment]
I think I've managed to fix all of these problems with `block` and `reuse`, with and without an RNN layer.

Closing this, re-open if there are still problems.

**Comment by AlexKuhnle** [comment]
Also added another Tensorforce-agent-based config, for DQN, in case you're interested: [here](https://github.com/tensorforce/tensorforce/blob/master/benchmarks/configs/dqn_tensorforce.json). More to come...
