### ISSUE TITLE
Error: Invalid Gradient

### ISSUE THREAD

**Issue by Zebin-Li** [tensorforce/tensorforce#797]
Hi!
I got this error during the training which I never saw before. Could you please help me with it?

Thank you very much!
Zebin Li

Traceback (most recent call last):
  File "C:/Users/lizeb/Box/research projects/active learning for image classification/code/run_manytimes_RAL_AL_samedata_0522.py", line 18, in <module>
    performance_history_RL, performance_history_RL_test, performance_history_AL, performance_history_AL_test, test_RL, test_AL, rewards = runmanytimes()
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\RAL_AL_samedata_0522.py", line 407, in runmanytimes
    agent.observe(terminal=terminal, reward=reward)
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorforce\agents\agent.py", line 510, in observe
    updated, episodes, updates = self.model.observe(
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorforce\core\module.py", line 128, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Invalid gradient: contains inf or nan. : Tensor had NaN values
	 [[{{node agent/StatefulPartitionedCall/agent/cond_1/then/_262/agent/cond_1/StatefulPartitionedCall/agent/StatefulPartitionedCall_5/policy_optimizer/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/while/body/_1185/policy_optimizer/while/StatefulPartitionedCall/policy_optimizer/cond/then/_1464/policy_optimizer/cond/StatefulPartitionedCall/policy_optimizer/VerifyFinite/CheckNumerics}}]] [Op:__inference_observe_5103]

Function call stack:
observe

**Comment by AlexKuhnle** [comment]
Hi @Zebin-Li ,

Can you post your agent config? This shouldn't happen, ideally... :-)

**Comment by CycloneMAO** [comment]
I also encountered with this error when I used Gaussian distribution in PPO:

    2021-05-28 17:26:02.084595: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
    2021-05-28 17:26:09.372638: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_147
    2021-05-28 17:26:15.274455: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
    2021-05-28 17:38:25.170580: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/cond/else/_88/policy/cond/StatefulPartitionedCall_1/action_distribution/cond/branch_executed/_208
    2021-05-29 00:16:36.096373: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/assert_equal_3/Assert/AssertGuard/branch_executed/_157
  
    2021-05-28 17:26:02.084595: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
    2021-05-28 17:26:09.372638: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_147
    2021-05-28 17:26:15.274455: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
    2021-05-28 17:38:25.170580: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/cond/else/_88/policy/cond/StatefulPartitionedCall_1/action_distribution/cond/branch_executed/_208
    2021-05-29 00:16:36.096373: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/assert_equal_3/Assert/AssertGuard/branch_executed/_157
    2021-05-29 00:16:41.774127: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
    Traceback (most recent call last):
    
      File "F:\MoneyCodes\TensorTrade\RL_strat_PPO.py", line 239, in <module>
        runner.run(num_episodes=10)
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorforce\execution\runner.py", line 634, in run
        self.handle_observe(parallel=n)
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorforce\execution\runner.py", line 756, in handle_observe
        updated = self.agent.observe(
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorforce\agents\agent.py", line 539, in observe
        updated, episodes, updates = self.model.observe(
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorforce\core\module.py", line 136, in decorated
        output_args = function_graphs[str(graph_params)](*graph_args)
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
        result = self._call(*args, **kwds)
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorflow\python\eager\def_function.py", line 846, in _call
        return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
        return self._call_flat(
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
        return self._build_call_outputs(self._inference_function.call(
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
        outputs = execute.execute(
    
      File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
        tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
    
    InvalidArgumentError:  Invalid gradient: contains inf or nan. : Tensor had NaN values
	     [[{{node agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/StatefulPartitionedCall_5/policy_optimizer/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/while/body/_1357/policy_optimizer/while/StatefulPartitionedCall/policy_optimizer/cond/then/_1756/policy_optimizer/cond/StatefulPartitionedCall/policy_optimizer/VerifyFinite/CheckNumerics}}]] [Op:__inference_observe_26747]
    
    Function call stack:
    observe

The code incurs this error is as following:(tensorflow=2.3.0, tensorforce=0.6.3)
```
network_spec = [
    dict(type = 'flatten'),
    dict(type='dense', size=32, activation='relu'),
    dict(type='dense', size=32, activation='relu'),
]
bs_network_spec = [
    dict(type = 'flatten'),
    dict(type='dense', size=32, activation='relu'),
    dict(type='dense', size=32, activation='relu'),
]
# with tf.device('/CPU:0'):
tsfc_agent = Agent.create(
    environment = tsfc_env,
    max_episode_timesteps = tsfc_env.max_episode_timesteps(),
    states = tsfc_env.states(),
    actions = tsfc_env.actions(),
    policy=dict(type='parametrized_distributions',
                use_beta_distribution = False,
                network = network_spec),
    objective = dict(type = 'policy_gradient', 
                     importance_sampling = True, 
                     clipping_value = 0.1),
    baseline = dict(type='parametrized_state_value', 
                    network=bs_network_spec),
    baseline_objective = dict(type='state_value'),
    update = dict(unit = "episodes", batch_size = 1), 
    optimizer = dict(
            optimizer='adam', learning_rate=1e-5, multi_step=10,
            subsampling_fraction=.33),
    reward_estimation = dict(
                horizon="episode", discount=.9, 
                predict_horizon_values="early",
                estimate_advantage=True),
    memory = dict(type='recent', capacity=1000))

runner = Runner(
    agent=tsfc_agent,
    environment=tsfc_env,
)

runner.run(num_episodes=10)

runner.run(num_episodes=100, evaluation=True)

runner.close()
```
But when I switch to beat distribution (by passing `use_beta_distribution = True`), the error disappears while the output action is always either 0.5 or 1(my action space is [0,1])

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle! My agent config is very simple, just:
`agent = Agent.create(agent="ppo", states= environment.states(), actions= environment.actions(),
                   max_episode_timesteps = 30, batch_size=10, learning_rate=0.0005)`

**Comment by Zebin-Li** [comment]
I think I solved this issue. For my case, The direct reason is the update of the state had some problems that it went to extremely small after several episodes, and the reseting of the state also had some problems. After fixing these, now my code can run till finish rather than raise this error.

**Comment by AlexKuhnle** [comment]
@CycloneMAO  Can you check whether the error is reproducible for another continuous environment, e.g. `Pendulum`? Otherwise, maybe a similar issue to @Zebin-Li's is the cause?

**Comment by CycloneMAO** [comment]
- @AlexKuhnle  Yeah I got some categorical variables in my states and the environment will take a window with size 30 to look back at those variables(say, the states is of shape (30, num_features). Then sometimes the agent will observe all zero along those columns, like (0,0,0,..., 0) for some columns. Therefore I just delete all of them and only remain two continuous variables, the problem for NaN gradient disappears. But right now I feel confused about it. My networks looks like this: 

```
network_spec = [
    dict(type = 'flatten'),
    dict(type='dense', size=32, activation='relu'),
    dict(type='dense', size=32, activation='relu'),
]
bs_network_spec = [
    dict(type = 'flatten'),
    dict(type='dense', size=32, activation='relu'),
    dict(type='dense', size=32, activation='relu'),
]
```
The first one is the policy network while the second is for baseline estimator. I don't know why such "all-zero" along a column will cause NaN gradient problem. Maybe it's related to the network structure or the default "tanh" transorm for Gaussian action since when it turns to Beta, the NaN gradient also disappears? 

- By the way, I found that the log bar `Episodes:   0%|          | 0/10 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]` only shows up once. How can I fix that? I really need to track the training process. My whole training log is as following:(`Target position:  xxx` is some printed value from the environment for each step)
  

> Episodes:   0%|          | 0/1 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]
>   Target position:  0.28872538
>   Target position:  0.5744672
>   Target position:  0.47066408
>   Target position:  0.56823653
>   Target position:  0.32070285
>   Target position:  0.5813164
>   Target position:  0.448924
>   Target position:  0.5807468
>   Target position:  0.33148962
>   Target position:  0.43450934
>   
>   2021-05-30 00:10:49.022425: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
>   2021-05-30 00:12:59.625188: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/cond/branch_executed/_265
>   2021-05-30 00:14:16.505766: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/StatefulPartitionedCall_5/policy_optimizer/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/while/body/_1357/policy_optimizer/while/StatefulPartitionedCall/policy_optimizer/cond/then/_1756/policy_optimizer/cond/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/agent/cond/branch_executed/_2655
>   2021-05-30 10:09:34.438387: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/assert_equal_1/Assert/AssertGuard/branch_executed/_244
>   2021-05-30 10:09:41.009214: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
>   2021-05-30 10:10:09.676389: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/cond/else/_88/policy/cond/StatefulPartitionedCall_1/action_distribution/cond/branch_executed/_203
>   2021-05-30 10:29:59.491350: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/cond/branch_executed/_265
>   2021-05-30 10:30:05.107479: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
>   2021-05-30 10:35:32.811237: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/assert_equal_3/Assert/AssertGuard/branch_executed/_157
>   2021-05-30 10:35:38.790465: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
>   2021-05-30 11:04:19.991481: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_147
>   
>   2021-05-30 00:10:49.022425: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
>   2021-05-30 00:12:59.625188: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/cond/branch_executed/_265
>   2021-05-30 00:14:16.505766: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/StatefulPartitionedCall_5/policy_optimizer/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/while/body/_1357/policy_optimizer/while/StatefulPartitionedCall/policy_optimizer/cond/then/_1756/policy_optimizer/cond/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/agent/cond/branch_executed/_2655
>   2021-05-30 10:09:34.438387: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/assert_equal_1/Assert/AssertGuard/branch_executed/_244
>   2021-05-30 10:09:41.009214: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
>   2021-05-30 10:10:09.676389: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/cond/else/_88/policy/cond/StatefulPartitionedCall_1/action_distribution/cond/branch_executed/_203
>   2021-05-30 10:29:59.491350: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/StatefulPartitionedCall/policy/cond/branch_executed/_265
>   2021-05-30 10:30:05.107479: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
>   2021-05-30 10:35:32.811237: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/assert_equal_3/Assert/AssertGuard/branch_executed/_157
>   2021-05-30 10:35:38.790465: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676
>   2021-05-30 11:04:19.991481: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_147
>   2021-05-30 11:04:26.297288: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: agent/StatefulPartitionedCall/agent/cond_1/then/_277/agent/cond_1/StatefulPartitionedCall/agent/assert_equal_1/Assert/AssertGuard/branch_executed/_676

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle! I have another quick question that, I want to check the network details by using "agent.get_architecture()", but an error says that PPO has no such attribute (please see below). I am not sure how to correctly use  "agent.get_architecture()". Thank you!
![image](https://user-images.githubusercontent.com/52910998/120243889-b70c6f00-c236-11eb-91d7-1363da9f19a1.png)

**Comment by AlexKuhnle** [comment]
@CycloneMAO  will look into this

@Zebin-Li  I assume you're on the pip version, not the Github version? `get_architecture()` was a recent addition, but I will fix another pip version over the next days.

**Comment by Zebin-Li** [comment]
@AlexKuhnle Yes, I am using the pip version. Thank you!

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle! I have some questions regarding the utilization of seed, and "deterministic" and "independent" when evaluating the agent. 
For the seed, the explanation is as follows:
![image](https://user-images.githubusercontent.com/52910998/120419308-2fa32680-c330-11eb-9900-613d62535083.png)
The way I set random seed is when creating the agent, using agent = Agent.create(agent="ppo", config=dict(seed=21), ...). My questions are:

1. What does it mean by saying "both set globally"? Does it mean the seed will affect other parts of the code rather than only the RL related code? For example, if I want to split the original dataset into training and testing, and I write the code together with creating RL environment, agent and training the agent in the same file. Will the original dataset be split based on the seed in the RL environment? 
2. What does it mean by saying "environment seed may have to be set separately for fully deterministic execution"? What does the "separately" refer to? In fact, the motivation for me to use random seed is, when evaluating the agent (I use actions = agent.act(states=states, independent=True, deterministic=True)), for several episodes, the actions the agent will take are not exactly the same for each timestep. I think this is because the output of PPO is a probability distribution of taking actions. But I want the agent to take the same action for each timestep in every episode (actually, for the evaluating, I just have one episode. I just ran the code several times, and found that the actions at each timestep were not the same).
3. How does the random seed affect the agent when training? Does the agent also take deterministic execution?

For "deterministic" and "independent" when evaluating the agent, my questions are:

4. What is the difference between using agent.act(states=states, independent=True, deterministic=True)) and set random seed?
5. (This question seems to be stupid). For evaluating the agent, the sample code in the documentation using 100 episodes (please see below). I just wonder why we need multiple episodes when evaluating rather than only one episode?
![image](https://user-images.githubusercontent.com/52910998/120422295-f40b5b00-c335-11eb-9a5a-50dc63f7a191.png)

I know recently I have bothered you a lot. Thank you very much and I really appreciate your time!

**Comment by AlexKuhnle** [comment]
No problem. :-)

1. The code sets the global Python and Numpy random seed, so whenever any random functions are called afterwards without explicit random number generator object, this will be deterministic also outside of Tensorforce.
2. If you want perfect reproducibility, you may need to make sure that the environment is truly deterministic, as it may use its own random seed and number generator object.
3. If all works as expected, the training runs will be exactly the same.

We should distinguish between two kinds of "determinism": (a) the agent chooses its actions deterministically, so given the exact same state the exact same action will be returned, and (b) the aim is a perfectly reproducible experiment, so everything including environment development is supposed to be fully deterministic. The `seed` is to enable (b), but it sounds like you're interested in (a), so you don't need to worry about setting a seed. (Generally, I wouldn't recommend aiming for (b) anyway, since it's kind of meaningless to have a fully deterministic setup.)

Regarding the question of `independent` vs `deterministic`: `independent` specifies that this act call is not part of the training act-observe loop, so it's inputs/outputs/internals are not stored in memory and used for updates. This is what you want to use e.g. when you evaluate your agent, in which case you don't call observe and feed rewards. `deterministic` can only be used with `independent`, is true by default, and means (a) above, so e.g. action distributions are not sampled 
(as is the case e.g. for policy gradient methods during training) but the mode is taken instead.

Hope that helps.

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle! Thank you very much! I still have a few questions as follows for a better understanding:

1. For the third point you mentioned above, it seems that setting a random seed when training is not a good idea. I think if all the training runs are exactly the same, then it is not meaningful. In that case, I should create an environment without a random seed for training and create another same environment with a random seed for testing. But it seems not implementable because the seed is created with the agent, not with the environment. Or is there a way to turn on the random seed for the agent like (agent.config(seed=12))?

2. By saying "action distributions are not sampled" in the second line from the bottom, do you mean even though the action is a probability, it is still deterministic when I use "independent" to evaluate the agent? If it is true, then I may not need to use "seed". But it seems not true.

Actually, my concern about "seed" or "independent" is, when I evaluating the agent with "independent" and "deterministic" on, the trajectory is different. And I assume this is because the actions are taken from a probability distribution, then I want to use "seed" to fix it.

Thank you again!

**Comment by AlexKuhnle** [comment]
1. If you ask me, I would never bother with random seeds, since even for evaluation the "environment noise" should be part of the benchmark. But nonetheless, you have a good point. What should work is to save and then load your agent, but when loading you add the config with seed. So:

```python
environment = ...
agent = ...
# train agent
agent.save(...)
agent.load(..., config=dict(seed=12))  # This sets the global seed for NumPy/Python, so also affects the environment
# evaluate agent
```

Let me know if this doesn't seem to work, i.e. yield exactly the same results.

2. Yes, with `deterministic=True` (implicitly the case for `independent=True`), the action is not sampled, but the max action is taken. This is also why the `seed` option really mostly makes sense for training, since testing is "determinstic" anyway.

Could you show an example of actions being different? For instance, try something like this:

```python
states = environment.reset()
print(agent.act(states))
print(agent.act(states))
print(agent.act(states))
```

The output should always be the same, since it's the same input state. Obviously, if there is randomness in the environment, the trajectories will end up being different (and there generally should be randomness in the environment, at least in the starting conditions).

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle! 

Thank you for the explanations! And for the second point, please see the screenshots below.

The first screenshot is without seed, and the second screenshot is with seed. I use 5 episodes to train and use 1 episode to evaluate (i.e., turn independent and deterministic on), and the curve is for the evaluating episode, each episode has 30 timesteps. I run the experiment for each situation twice. All these four experiments use the same dataset and the same initial state. You can see that if there is no seed, even though it is evaluating mode, the curve (as well as the actions) are not the same (the first screenshot). And if I use seed, the curve (as well as the actions) are exactly the same (the second screenshot). What I want is something like second screenshot, because next I may want to tune the parameters of the agent, so I want to eliminate any random effects from the system. Thank you!
![image](https://user-images.githubusercontent.com/52910998/120856022-35298800-c54d-11eb-91eb-2201b84dba5e.png)
![image](https://user-images.githubusercontent.com/52910998/120856106-54281a00-c54d-11eb-88fe-7e5ebb675707.png)

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle! I am sorry I encountered another issue that I had no idea why it happened. I really appreciate it if you could give me some hints on figuring it out. Thank you very much!


> Traceback (most recent call last):
  File "C:/Users/lizeb/Box/research projects/active learning for image classification/code/search for parameter_PPO.py", line 316, in <module>
    GridSearchTensorForce(
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\gridsearch_PPO_func.py", line 146, in GridSearchTensorForce
    actions = agent.act(states=states)
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorforce\agents\agent.py", line 386, in act
    return super().act(
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorforce\agents\recorder.py", line 260, in act
    self.buffers['states'][name][parallel[n]].append(states[name][n])
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorforce\core\utils\nested_dict.py", line 224, in __getitem__
    assert self.is_singleton()
AssertionError

**Comment by AlexKuhnle** [comment]
@Zebin-Li FYI: I fixed a new pip version now. And I will look into the randomness issue.

**Comment by Zebin-Li** [comment]
Thank you @AlexKuhnle!

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle! I was trying to use`agent.save(...)
agent.load(..., config=dict(seed=12)) ` to set the random seed when evaluating the agent, however, I got this error:

>   File "C:/Users/lizeb/Box/research projects/active learning for image classification/code/PPO parameters 0604.py", line 416, in <module>
    agent.load(directory="C:\\Users\\lizeb\\Box\\research projects\\active learning for image classification\\saved agents\\parameter tuning",
  File "C:\Users\lizeb\Box\research projects\active learning for image classification\code\venv\lib\site-packages\tensorforce\util.py", line 70, in overwritten
    raise TensorforceError(message="Function {}() is a static method.".format(qualname))
tensorforce.exception.TensorforceError: Function Agent.load() is a static method.

I tried to solve it but I failed. Could you please provide some hints on solving it? Thank you!

**Comment by AlexKuhnle** [comment]
As the exception says, `Agent.load()` is a static method, so you don't use it like this, `agent = Agent.create(...); agent.load(...)`, which I assume you did, but like this, `agent = Agent.load(...)`, so not after `Agent.create()` but as an alternative. ;-)

**Comment by Zebin-Li** [comment]
Thank you @AlexKuhnle for the explanation!

**Comment by CycloneMAO** [comment]
Hi Alex! I haven't figure out the missing log bar of my runner's output. I guess it may be some problem with my tensorflow version or something changed in the release version for 0.6.3 since I just reinstalled it recently while the problem still existed. Is it the same situation on your computer?

**Comment by AlexKuhnle** [comment]
Hi @CycloneMAO ,

- I have no idea about the TQDM progress bar. It works for me. Where are you running this, on what system, anything special about the environment? One thing you could try is whether [this change] in `runner.py` has caused this problem (in your case). Just reverse by removing `.auto`.
- I also get these TensorFlow logging warnings, and I don't know what they mean. However, Tensorforce uses while loops in a few places, which is otherwise rather untypical, I think, in supervised learning for instance. However, the fact that it couldn't optimize them, doesn't mean that they're slow, at least empirically I don't find it to be very slow.

**Comment by AlexKuhnle** [comment]
Sorry, I just realised "this change" was missing the linking url: find it [here](https://github.com/tensorforce/tensorforce/commit/deb2957a6cd98b66d83246cb118495885b4fb9d9).

**Comment by AlexKuhnle** [comment]
I assume this can be closed? For the issue re randomness despite setting seed, I don't know how to investigate this. If there is a "reproducible" example with e.g. a standard Gym environment, let's open a separate issue for that. If there is an issue, it should of course be fixed, however, I would generally recommend not fixing random seeds, since this makes experiments much less representative.
