### ISSUE TITLE
Error when saving with hdf5

### ISSUE THREAD

**Issue by Tianyue-Zhao** [tensorforce/tensorforce#798]
When saving an agent with agent.save(directory, format="hdf5"), a h5py occurs.
I am using a PPO agent and a custom Keras network.

It seems to me that when saving the network layers, tensorforce.core.model.save still tries to strip off the word "agent" from the beginning of the variable name (line 899). However, the layer variable names no longer begin with the word "agent", and instead the layer name is stripped off.
This results in a duplicate name ("kernel" in my case), and triggers the h5py error.

Please find attached my agent definition line and the error screenshot.
The error screenshot includes the variable names that I printed trying to figure out the issue.

Thanks.

![agent_definition](https://user-images.githubusercontent.com/29241353/120062371-c01ef580-c016-11eb-83ce-76a914c0fe00.png)
![model_save](https://user-images.githubusercontent.com/29241353/120062355-aa113500-c016-11eb-8db7-e8d65303d062.png)
![error_screenshot](https://user-images.githubusercontent.com/29241353/120062354-a9789e80-c016-11eb-9bd1-e8380f4a6927.png)

**Comment by AlexKuhnle** [comment]
Hi @Tianyue-Zhao,

Thanks, I will fix this. Out of interest, what is your network specification?

**Comment by AlexKuhnle** [comment]
Should be fixed now, I think.

**Comment by Tianyue-Zhao** [comment]
It is indeed working great now. Thank you!

Here's my network setup in case that's relevant.
![network_spec](https://user-images.githubusercontent.com/29241353/121557128-56fd9180-c9c9-11eb-9593-c1adb07d4d23.png)
