### ISSUE TITLE
No "return_processing" for PPO?

### ISSUE THREAD

**Issue by Zebin-Li** [tensorforce/tensorforce#801]
To whom it may concern,

I am applying PPO and when I exploring the parameter "return_processing" I got an error:
> TypeError: __init__() got an unexpected keyword argument 'return_processing'

My implementation is:
`agent = Agent.create(agent="ppo", states= environment.states(), actions= environment.actions(), subsampling_fraction=0.1,
                     likelihood_ratio_clipping= 0.1,network=network_spec,
                   max_episode_timesteps = 30, batch_size=5, learning_rate=0.001, exploration= 0.001, discount = 0.99,
                return_processing=dict(type='exponential_normalization', decay = 0.99))`

And in the documentation, there is "return_processing" in the parameter list of PPO:
![image](https://user-images.githubusercontent.com/52910998/121837125-e1344700-cca2-11eb-88f8-ffa8f96c2b36.png)
So I am not sure where is wrong.

By the way, I have two other questions:

1. What is the difference between "reward_preprocessing" and "return_processing"?
2. The explanation of the exponential_normalization is "_Normalization layer based on the exponential moving average of mean and variance over the temporal sequence of inputs_". Does it mean first minus the mean then divided by variance?

Thank you!
Zebin Li

**Comment by AlexKuhnle** [comment]
Hi @Zebin-Li,

Could you check whether you're on the latest version? The addition of `return_processing` to PPO has been a recent change... Regarding your other questions: first, yes, normalization is first minus mean then divided by variance. Second, reward refers to the raw signal coming from the environment at every timestep, whereas return is the estimate of the "overall cumulative future rewards" at each timestep (so in case of PPO the discounted sum of all rewards coming afterwards). So the return is the signal actually used for updates (or the advantage, which is based on it). I've started a little "guide" to explain the reward estimation process a bit more, coming very soon.

**Comment by Zebin-Li** [comment]
Thank you for the quick response! 

Recently I read a paper "_Implementation Matters in Deep RL: A Case Study on PPO and TRPO_" that mentions there are some code-level optimizations in the PPO code but not being mentioned in the original PPO paper. So I wonder does the Tensorforce include those code-level optimizations by default for PPO, or as parameters that can be turned on (I think it is the latter circumstance)? 

Thank you!

**Comment by AlexKuhnle** [comment]
Oh yes, implementation differences are very common (see e.g. also [here](https://costa.sh/blog-the-32-implementation-details-of-ppo.html)). It might sound surprising, but you can expect that no PPO implementation is quite like another. In particular, the Tensorforce implementation has its own peculiarities, as the README warns:

> Note that in general the replication is not 100% faithful, since the models as described in the corresponding paper often involve additional minor tweaks and modifications which are hard to support with a modular design (and, arguably, also questionable whether it is important/desirable to support them). On the upside, these models are just a few examples from the multitude of module combinations supported by Tensorforce.

One emphasis of Tensorforce is to offer as much as possible as configurable argument. So looking at the list of modifications in the paper, I think you can implement all of them, apart from value function clipping -- but it seems to actually perform somewhat better when turned off anyway? Oh, and reward scaling is also not quite possible right now, but that only requires a small change that I wanted to do anyway...

**Comment by AlexKuhnle** [comment]
Actually, I take that back -- the reward scaling doesn't look quite like what I had in mind. I can't really make sense of it, I have to say...

**Comment by Zebin-Li** [comment]
Thank you for the clarification! So what is the difference between "reward_preprocessing" in Tensorforce and "reward scaling" you mentioned in the last comment?

**Comment by AlexKuhnle** [comment]
Ah, the reward scaling is one specific method of preprocessing the reward, so it could be implemented in Tensorforce, but this specific way of normalization they apply is currently not available out of the box. But you're right, it's kind of the same thing.

**Comment by Zebin-Li** [comment]
Thank you for the explanation!

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle! Sorry for bothering you... Could you please tell me more about the implementation of PPO in Tensorforce? For example, what is the objective function the Tensorforce refers to? If it is using the equation (9) in the PPO paper (please see below)
![image](https://user-images.githubusercontent.com/52910998/122507882-0db3d000-cfcf-11eb-8925-de38da8b2b99.png)
How do you define the L VF and S in the equation? 
Thank you very much!

**Comment by AlexKuhnle** [comment]
In Tensorforce, the policy and critic are actually optimized separately, so there is a loss function for the policy, `L^CLIP` as defined in the paper (plus optional entropy loss component), and then there is a separate loss function, `L^VF`, which is an L2 loss (and particularly not clipped as it is in some implementations of PPO). Does that help? What else would you like to know?

**Comment by Zebin-Li** [comment]
Thank you very very much for the clarification!
