### ISSUE TITLE
Wrong matplotlib version in tensorflow docker

### ISSUE THREAD

**Issue by A-Boudi** [tensorforce/tensorforce#803]
I'm using a docker to run tensorforce. The main issue is that when installing tensorforce 0.4.2, it tries to install matplotlib version 3.4.2. Unfortunately, this version is not available from the docker image of tensorflow 2.5.0.

Dockerfile
```
FROM tensorflow/tensorflow:2.5.0
...
RUN python3 -m pip install --upgrade pip
RUN pip install tensorforce
...
```

I saw that requirement.txt is referencing 3.3.4 but it was referencing 3.4.2 not long ago.

Any idea on how to sort this?

Thanks,

**Comment by AlexKuhnle** [comment]
Hi @A-Boudi 

I update the version requirements of the modules every now and then, to be on the latest version. Seems like this is not necessarily a good idea. I could down-grade it again for the Github version, if that helps. Or can you "ignore" that requirement and install what version you need? There is no strict requirement for that version.

**Comment by A-Boudi** [comment]
Hello @AlexKuhnle

Actually, the current mentioned version would work. But when I install it from within docker image, I get the requirement of matplotlib version 3.4.2.

What should I do to ignore that requirement? Because for now I can't build my tensorforce docker image.

What I think is happening is that the 0.6.4 tag has been originally set on commit d322c0f then updated to commit 5075dda. But in the meantime the pypi repository has already stored the d322c0f version. And I think that repositories are updated only when a new version is released.

Therefore, I think one easy solution would be to bump tensorforce version so the repositories would update the code.

### My two cents about versioning
I agree with you that it is not necessarily a good idea to always force the use of the latest version of the modules. What would be better IMHO is to have an interval of versions. I would use >= than the minimum version that the code supports and then update it for security concerns or when some new feature is needed. And I would use <= than the newest version that does not break the code.

**Comment by AlexKuhnle** [comment]
So the version currently in `requirements.txt` with 3.3.4 is good? Can't you then install the version from Github?

```bash
pip install git+https://github.com/tensorforce/tensorforce.git
```

And I agree, it makes sense to use versions that way, I just thought it's not a bad idea in addition to regularly update the requirements. Maybe I should not (over-)do that. :-)

**Comment by A-Boudi** [comment]
Yes using git works, but it requires the installation of git inside the container. 

In order to not inflate the container image, the git should be installed then deleted.

Dockerfile:
```
FROM tensorflow/tensorflow:2.5.0
...
RUN apt-get update && apt-get install -y git
RUN pip install -r requirements.txt
RUN apt-get purge -y git && apt-get autoremove -y && rm -rf /var/lib/apt/lists
...
```
requirements.txt:
```
...
git+https://github.com/tensorforce/tensorforce.git@0.6.4
...
```

I think we should keep this issue open until the next version of Tensorforce where we'll check if this issue is fixed or not.

**Comment by AlexKuhnle** [comment]
Fixed a new version with the downgraded matplotlib requirement.
