### ISSUE TITLE
Multi-agent system scenario

### ISSUE THREAD

**Issue by KiloNovemberDelta** [tensorforce/tensorforce#805]
Hello everyone,

My question is linked to this closed issue : 
https://github.com/tensorforce/tensorforce/issues/371

I want to implement a RL in the case of multi agent systems. But I don't find a straightforward way to implement it.
Each agent has its own observation and action, but they can share all the same model (/strategy). 

Is there anyone who succeed to do it ?

Thanks in advance ! 
@AlexKuhnle

**Comment by AlexKuhnle** [comment]
Hi @KiloNovemberDelta, are all the agents active in the same environment, or are they interacting with their own environment each?

**Comment by AlexKuhnle** [comment]
Have a look at these new examples, it sounds like what you want is a "multi-actor" environment like [here](https://github.com/tensorforce/tensorforce/blob/master/examples/multiactor_environment.py), or potentially rather a vectorized environment like [here](https://github.com/tensorforce/tensorforce/blob/master/examples/vectorized_environment.py). Note that these were added with the latest commit, so you need to use the Github version of Tensorforce, not pip.

**Comment by KiloNovemberDelta** [comment]
> 
> 
> Hi @KiloNovemberDelta, are all the agents active in the same environment, or are they interacting with their own environment each?

All the agents active in the same environment 



> 
> 
> Have a look at these new examples, it sounds like what you want is a "multi-actor" environment like [here](https://github.com/tensorforce/tensorforce/blob/master/examples/multiactor_environment.py), or potentially rather a vectorized environment like [here](https://github.com/tensorforce/tensorforce/blob/master/examples/vectorized_environment.py). Note that these were added with the latest commit, so you need to use the Github version of Tensorforce, not pip.

Oh, great, thank you, I will have a look on it ! 
Currently, I'm using PettingZoo (https://github.com/PettingZoo-Team/PettingZoo) as a multiagent environment. And I try to integrate Tensorforce on it. But I don't know the workload to do it.

**Comment by AlexKuhnle** [comment]
If you work on PettingZoo, implementing it as an `Environment` object, it would be great if you would contribute it to Tensorforce. :-)  Happy to help.

**Comment by edkinssimon** [comment]
> Have a look at these new examples, it sounds like what you want is a "multi-actor" environment like [here](https://github.com/tensorforce/tensorforce/blob/master/examples/multiactor_environment.py), or potentially rather a vectorized environment like [here](https://github.com/tensorforce/tensorforce/blob/master/examples/vectorized_environment.py). Note that these were added with the latest commit, so you need to use the Github version of Tensorforce, not pip.

@AlexKuhnle Amazing work here, just to clarify, when you say multi-actor, do you differentiate this from multi-agent i.e. Are the actors using the same agent and model? i.e. will this method work if I want different state perspectives for each agent each with a differentiated reward function?

**Comment by AlexKuhnle** [comment]
I assume this can be closed then.

**Comment by larkz** [comment]
Hi @AlexKuhnle , if we are not using the runner to run the episode, I am not sure how do we pass the states object to the `agent.act()` method in the multi-actor version for PPO. Is there an example to show precisely how,
```
actions = agent.act(states)
state, reward, terminal_state = environment.execute(action)
agent.observe(state, action, reward, terminal_state)
```
would be handled in the multi-actor parallel setting? A bit of support here would be nice. I have a notebook here, that is demonstrating the error on your example https://github.com/tum-logistik/gpu-multiagent/blob/larkin/wip/tensorforce_multi_agent_norunner.ipynb

**Comment by AlexKuhnle** [comment]
Hi @larkz,

Does [this example](https://github.com/tensorforce/tensorforce/blob/master/examples/act_observe_vectorized.py) help? In general you pass a batched state value instead of a single value `state = [state1, state2, state3]`, and the `parallel` argument with the indices indicating to which parallel interaction this timestep belongs, e.g. `parallel = [0, 1, 2]`. In the multiactor example that you're using, note that `reset()` returns two values `parallel, states`, which you have to pass to `act(states=states, parallel=parallel)`. Hope that helps.

**Comment by larkz** [comment]
Thank you for the support!, My example code is running now... Some additional follow up questions

- In [your example](https://github.com/tensorforce/tensorforce/blob/master/examples/act_observe_vectorized.py), the state is a vector, so potentially each agent can see a different state at each iteration right? In the case where all agents share the same state, need we just copy the same state for each agent at each iteration? 

- the `parallel` index is basically the same throughout the entire run right? When would we ever want to alter parallel indexes?

**Comment by AlexKuhnle** [comment]
Sorry for the late response:
- Yes, but often it's the case that, despite all agents looking at the "same world state", each agent's state should still have a different perspective on this state. For instance, if you have a two-player game, since both players are controlled by the same agent, each agent's state has to distinguish between "self" (player 1 or 2) and "the other" (player 2 or 1, respectively).
- The reason why it's there is that some players might terminate earlier than others, in which case the `parallel` vector gets smaller (and correspondingly you only pass the states of the remaining players). There are probably other scenarios one could imagine, but that was the motivation.

**Comment by larkz** [comment]
> 

Understood thanks!

**Comment by larkz** [comment]
> Sorry for the late response:
> 
> * Yes, but often it's the case that, despite all agents looking at the "same world state", each agent's state should still have a different perspective on this state. For instance, if you have a two-player game, since both players are controlled by the same agent, each agent's state has to distinguish between "self" (player 1 or 2) and "the other" (player 2 or 1, respectively).
> * The reason why it's there is that some players might terminate earlier than others, in which case the `parallel` vector gets smaller (and correspondingly you only pass the states of the remaining players). There are probably other scenarios one could imagine, but that was the motivation.

Understood thanks!

**Comment by hkeramat** [comment]
I have a question regarding multiactor environment. How would I be able to add more than two actors?
