### ISSUE TITLE
RNN bias parameter default

### ISSUE THREAD

**Issue by cipollone** [tensorforce/tensorforce#812]
The documentation says that all RNN layers have the bias parameter set to True by default. Instead, looking at the source code, LSTM and GRU have `bias=False` in the constructor. Either the default, or the documentation should be fixed to match.

By the way, why default to False? (just to learn if there's a motivation for not using one here)

**Comment by AlexKuhnle** [comment]
Hi @cipollone, thanks for pointing that out. There is no reason for that, and in this cade the code should correspond to the docs -- seems like I updated the "parent" RNN class accordingly, but not the sub-classes. Will correct that soon.

**Comment by AlexKuhnle** [comment]
Fixed this now -- FYI the mismatch was not just for `bias`, but also for `activation` which according to the docs should be `'tanh'` and now indeed is.
