### ISSUE TITLE
state_preprocessing 

### ISSUE THREAD

**Issue by bezineb5** [tensorforce/tensorforce#813]
Hi,

I updated to tensorforce 0.6.4 and it seems that it's no longer to remove the LinearNormalization state processing, even by passing state_processing=None to the DDQN agent constructor.
That's what I get in the output model:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/1782448/126776741-c1f8cf77-24c1-4ce0-acf4-f07921e4f38c.png">

With version 0.6.3, I had:
<img width="157" alt="image" src="https://user-images.githubusercontent.com/1782448/126776797-bd8e9049-dc5a-4a36-9a30-83ffa3e81e05.png">

And the names of those nodes are like that:
StatefulPartitionedCall/agent/StatefulPartitionedCall/state_preprocessing/PartitionedCall/linear_normalization0/PartitionedCall/linear_normalization0/truediv

The problem, is that it makes very hard to infer such boolean operation on some frameworks, and my data is already normalized.

How can I remove the normalization?

Thanks!
Benjamin

**Comment by AlexKuhnle** [comment]
Hi @bezineb5, that's a good point -- the intention is to use `linear_normalization` as default, since it is beneficial most of the time and usually doesn't hurt, but to still allow to turn it off via `None`, as you note. So that's a bug in the code, I will look into that.

**Comment by bezineb5** [comment]
Thanks @AlexKuhnle ! However, I had a look at the changes since version 0.6.3, and I couldn't find anything related to that.

**Comment by AlexKuhnle** [comment]
This should now work as expected with the latest commit. Sorry for the wait.
