### ISSUE TITLE
assert baseline_optimizer is None

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#822]
Hi Alex:
This is Wei. we have some discussion last year with @jerabaul29 , I have some update. but I met error of agent 
I get following errors:

```Traceback (most recent call last):
  File "train_path.py", line 25, in <module>
    agent = Agent.create(
  File "/public3/home/sc51719/tensorforce/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/public3/home/sc51719/tensorforce/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
  File "/public3/home/sc51719/tensorforce/tensorforce/agents/ppo.py", line 225, in __init__
    assert baseline_optimizer is None
```

and the setup for agent is :
```
agent = Agent.create(
    agent='ppo',
    environment=myboat,
    network=network_spec,
    # PPO optimization parameters
    batch_size=10, update_frequency=2, learning_rate=3e-4, multi_step=10,
    subsampling_fraction=0.33,
    # Reward estimation
    likelihood_ratio_clipping=0.2, discount=0.99, predict_terminal_values=False,
    # Baseline network and optimizer
    baseline=dict(type='auto', size=32, depth=1),
    baseline_optimizer=dict(optimizer='adam', learning_rate=1e-3, multi_step=10),
    # Preprocessing
    # preprocessing='linear_normalization',
    # Exploration
    exploration=0.0, variable_noise=0.0,
    # Regularization
    l2_regularization=0.0, entropy_regularization=0.0,
    # Default additional config values
    config=None,
    # Save model every 10 updates and keep the 5 most recent checkpoints
    # saver=dict(directory='model', frequency=100, max_checkpoints=5),
    # Log all available Tensorboard summarie
    #summarizer = dict(directory='summaries', labels=['reward', 'loss']),
    #summarizer = dict(directory='summaries', labels='all'),    #2020.11.2

    # Do not record agent-environment interaction trace
    recorder=None
)
```

Can you provide some suggestion ?

Best Regards
Wei

**Comment by AlexKuhnle** [comment]
Hi @waynezw0618,

Could you update to the latest Tensorforce version and check again, if you haven't already? It looks like that might be the problem here...

**Comment by waynezw0618** [comment]
Hello @AlexKuhnle 
what is the latest version I can have? now I am using 0.6.5 from pip3. is that the latest One

**Comment by AlexKuhnle** [comment]
0.6.5 is fine. Is it still showing the same error?

**Comment by waynezw0618** [comment]
yep. the same error. the strange thing is that I am using the same codes with my colleagues who is using windows, but those codes works for her.

**Comment by AlexKuhnle** [comment]
Could you try removing and re-installing the latest Tensorforce? If it works for your colleagues (and I don't see why it wouldn't work from looking at the config), maybe something got messed up with your local Tensorforce version. If it still persists, I can also try above config on a toy example.

**Comment by waynezw0618** [comment]
Hi Alex
sorry for late reply, I was busy with other business in the past month 
I still can not reach the solution I expected yet. 
I wonder whether  the actor and critic network architecture as well as the activation function are the same as in the reference.as those mentioned  in the section 5.4.5 and 5.4.6 in page 57

here is the link in the reference. https://ntnuopen.ntnu.no/ntnu-xmlui/handle/11250/2731248


Best regards
