### ISSUE TITLE
Issue about reward_preprocessing

### ISSUE THREAD

**Issue by Zebin-Li** [tensorforce/tensorforce#825]
To whom it may concern,

I am trying to use reward_preprocessing.
`    agent=Agent.create(agent="ddqn", states= environment.states(), actions= environment.actions(),network=network_spec, memory = 500, batch_size = 10, config=dict(seed=123), reward_estimation=dict(reward_processing = dict(type='exponential_normalization', decay = 0.85)))
`
However, I got an error that 

>   File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\RAL_AL_samedata_0522.py", line 341, in runmanytimes
    agent=Agent.create(agent="ddqn", states= environment.states(), actions= environment.actions(),network=network_spec, memory = 500, batch_size = 10, config=dict(seed=123), reward_estimation=dict(reward_processing = dict(type='exponential_normalization', decay = 0.85)))
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorforce\agents\agent.py", line 124, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorforce\agents\agent.py", line 98, in create
    agent = agent(**kwargs)
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorforce\agents\double_dqn.py", line 231, in __init__
    saver=saver, summarizer=summarizer, tracking=tracking, **kwargs
TypeError: __init__() got multiple values for keyword argument 'reward_estimation'

I am not sure where I wrong used it. Thank you!

Sincerely,
Zebin Li

**Comment by Zebin-Li** [comment]
I think the issue is solved.

**Comment by AlexKuhnle** [comment]
I assume you found the `reward_processing` argument... :-)

**Comment by Zebin-Li** [comment]
Yes. Actually, at the beginning, I was trying to use `reward_processing`, but it said it was not supported and recommended to use `reward_estimation`, then this issue came up. Then I went back to try `reward_processing` and this time it worked. Maybe I wrong used it at the beginning...
