### ISSUE TITLE
parallel training issue

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#827]
Hello 

I set 'num_parallel = 10' for the runner and 'parallel_interactions = 10' for the agent. I select 10 simply because the batch_size is 10.  But then the sec/ep is 10 times larger than the serial case. that means I get no acceleration for parallel training.  for my case the typical running time for a single environment is about 10 secs.  is there anything wrong for my setup? 

Best regards
Wei

**Comment by AlexKuhnle** [comment]
Hi @waynezw0618,

When you set up the parallel runner, do you specify the `remote` argument? Because if not, the 10 parallel environments will all be simulated sequentially in the current thread/process, so it wouldn't be surprising since 10 parallel environments for 1 episode are basically equivalent to 1 environment for 10 episodes. If you use `remote='multiprocessing'`, that may speed things up but depends on your system.

**Comment by waynezw0618** [comment]
Hi @AlexKuhnle 
Yes, I have 'remote='multiprocessing' in the runner. and I have checked that there are 10 python processes in the system. but thing is that why the sec/eps get much larger? I suppose they are independed  thread. and single one should finished the same time as in the serial case. 

BTW.  I have upload the tensorboad plots for my case. would you please give me some suggestion for the setup?[https://github.com/waynezw0618/boatNav/issues/18](url)

Wei

**Comment by AlexKuhnle** [comment]
Parallelization comes with a communication overhead, so if you're environment already runs very fast, there might not be much (or any) benefits to parallelization. For instance, for CartPole there is none when I tried it at some point. In such cases, [vectorization](https://github.com/tensorforce/tensorforce/blob/master/examples/vectorized_environment.py) may be applicable.

**Comment by AlexKuhnle** [comment]
Can you post the sec/ep etc values of the runner in the single-env and parallelization case?

**Comment by waynezw0618** [comment]
Hi @AlexKuhnle 
for single-env:
'[return = 345.39, ts/ep=399, sec/ep = 10.95, ms/ts=27.4, agent=84.2%]'
for parallel running case:
'[return = 430.49, ts/ep=399, sec/ep = 252.02, ms/ts=631.6, agent=84.2%,agent=3.9&, comm = 95.3%]'

**Comment by waynezw0618** [comment]
> Hi @AlexKuhnle
> for single-env:
> `[return = 345.39, ts/ep=399, sec/ep = 10.95, ms/ts=27.4, agent=84.2%]`
> for parallel running case:
> `[return = 430.49, ts/ep=399, sec/ep = 252.02, ms/ts=631.6, agent=3.9%, comm = 95.3%]`

sorry, this is for num_parallel = 24. here sec/ep is about 10 times of that of single-env case. the situation for 10 envs is similar sec/ep  is about 10 times of single-env case

**Comment by AlexKuhnle** [comment]
I see. Could you try the same setup, but with the argument `batch_agent_calls=True` for `runner.run(...)`? I think that might be the reason for the linear slowdown here.
