### ISSUE TITLE
How does adam work with policy gradient methods?

### ISSUE THREAD

**Issue by DaniiltheGreat** [tensorforce/tensorforce#830]
Good evening, people.

It might be another stupid question, but I can't really understand how are network parameters updated when I use adam optimizer?
Is it made is a similar fashion as for value-based methods?:

w = w + \frac{\alpha}{\sqrt{\hat{v}_t}+\epsilon}  \hat{m}_t

Thank you in advance!

**Comment by AlexKuhnle** [comment]
You should find this information in the [Adam paper](https://arxiv.org/abs/1412.6980) -- there is nothing specific about Tensorforce or RL in how the Adam update is computed.
