### ISSUE TITLE
Bugs to do with experience

### ISSUE THREAD

**Issue by ishanpai** [tensorforce/tensorforce#831]
While exploring TensorForce with @fkiraly-shell, I came across what I think are two bugs in TensorForce. They were both to do with the experience method of an agent. I have created a notebook with a reproducible example of all the problems I describe. I have attached this notebook in a draft pull request #832.

I am using python 3.9.7 and Tensorforce 0.6.5 and pandas 1.3.3. My environment has no other packages installed separately.

**Problem 1**
The first problem is that `experience` does not seem to work in "batch" mode. We have the following set up:
```python
import numpy as np
import pandas as pd
from tensorforce.agents import Agent
np.random.seed(0)
n_train = 10
X_train = pd.DataFrame(np.random.uniform(size=n_train), columns=["A"])
Z_train =  pd.DataFrame(np.array([np.random.uniform(size=n_train), np.random.uniform(size=n_train)]).T, columns=["B", "C"])
Y_train = pd.DataFrame(np.random.uniform(size=n_train), columns=["D"])

agent = Agent.create(
    agent='tensorforce', states=dict(type='float', shape=(2,), min_value=(0,0), max_value=(1,1)),
    actions=dict(type='float', shape=(1,), min_value=0, max_value=1),
    max_episode_timesteps=2, update=64,
    optimizer=dict(optimizer='adam', learning_rate=1e-3),
    objective='policy_gradient', reward_estimation=dict(horizon=1),
    exploration=10.0, parallel_interactions=n_train
)
```

Here, `X_train`, `Z_train`, `Y_train` are all `pd.DataFrame`.
I tried batch mode with the following code:

```python
states = [{"state": np.array(Z_train.iloc[i])} for i in range(len(Z_train))]
actions = [{"action": np.array(X_train.iloc[i])} for i in range(len(X_train))]
rewards = np.reshape(np.array(Y_train), (-1,))
terminal = np.full(rewards.shape, True)

agent.experience(states=states, actions=actions, terminal=terminal, reward=rewards)
```

- This runs into the following error: `TensorforceError: Invalid value for Agent.experience actions argument value: ArrayDict(action=[[0.54881352]]).` which suggests that `experience` does not actually want an array of dictionaries for `actions`, while it does seem to want this for `states`.
- I then tried using just an `np.ndarray` for `actions` as looking at the source code for `experience`, this seems like it would be a valid input. The only line changed is that actions are now defined as `actions = np.array(X_train)`. This now runs but does not give me the expected result as the agent does not "learn enough" given the data it receives (comparing it to doing experience individually on each data point). It seems like the agent thinks that all those `actions` were just for one episode.
- I also tried running it with defining actions as `actions = list(np.array(X_train))` but the same issue persists.

**Problem 2**
The second problem is to do with the documentation of TensorForce. In the [documentation](https://tensorforce.readthedocs.io/en/latest/agents/agent.html#experience-update-interface), it says that `actions` should be a dictionary containing arrays of actions. This has the same initial set-up as the situation before. However, when I run the following code I get an error:
```python
states = {"state": np.array(Z_train.iloc[0])}
actions = {"action": np.array(X_train.iloc[0])}
rewards = np.reshape(np.array(Y_train.iloc[0]), ())
terminal = np.full(rewards.shape, True)

agent.experience(states=states, actions=actions, terminal=terminal, reward=rewards)
```

- The error is : `TensorforceError: Invalid value for Agent.experience actions argument value: ArrayDict(SINGLETON=ArrayDict(action=[[0.5488135]])).`
- Looking into the source code of `experience`, it seems like the error is line 532. 
![image](https://user-images.githubusercontent.com/86784281/129154670-3b98ca95-273f-48ca-8d80-e959d691e897.png)

- This is conditional on passing a dictionary rather than a list of dictionaries for `states`. Here, we see that if we define actions as a dictionary, then since it is not an `np.ndarray`, it makes it into an `ArrayDict` with the singleton which is already an `ArrayDict` as we passed a dictionary for `actions`.
- It also doesn't accept actions to be an `np.ndarray` because of this line and gives the error: `TensorforceError: Invalid type for Agent.experience argument actions: <class 'numpy.ndarray'> is not dict.`
- The only input format of actions it accepts seems to be a list containing `np.ndarray`.

- Additionally, the example workflow of the act-experience-update interface (https://github.com/tensorforce/tensorforce/blob/master/examples/act_experience_update_interface.py) does not use dictionaries for either `states` or `actions`.
- From my exploration, it seems as though `states` can be either a dictionary or a list, but `actions` must be a list.

It would be great if somebody could have a look and either confirm or contradict my findings and feel free to ask me any questions about this.

**Comment by AlexKuhnle** [comment]
Hi @ishanpai, thanks for attaching a notebook, that is very helpful for debugging what's going on. I will have a look at that soon and come back to you.

**Comment by AlexKuhnle** [comment]
The latest commit should fix the problems you mentioned. Let me know if you encounter others.

One comment on the last cell in the notebook:

```python
states = {"state": np.array(Z_train.iloc[0])}
actions = list(np.array(X_train.iloc[0]))
rewards = np.reshape(np.array(Y_train.iloc[0]), ())
terminal = np.full(rewards.shape, True)
```

This doesn't work since the "input format" is inconsistent between `states` being passed as a single item (i.e. unbatched) whereas `actions` is passed as a list of items (i.e. batched). If you remove the `list(...)` wrapper, it will work.

**Comment by AlexKuhnle** [comment]
I assume this is fixed?

**Comment by ishanpai** [comment]
Yes, the problem seem to be solved, sorry for the late response.
