### ISSUE TITLE
doubts about parameters and summaries

### ISSUE THREAD

**Issue by matteoem** [tensorforce/tensorforce#837]
Hello everyone. This is my first time writing on github looking for a question,if I'll do anything wrong, just let me know and I will fix it.

I'm working on a project using for the first time tensorforce. I have a custom gym environment and I'm using the double_dqn algorithm.
I have some questions:

1. **About the "exploration" parameter**. The documentation says: "_exploration (parameter | dict[parameter], float >= 0.0) – Exploration, defined as the probability for uniformly random output in case of bool and int actions, and the standard deviation of Gaussian noise added to every output in case of float actions, specified globally or per action-type or -name (default: no exploration). 
As far as I understood, this value is giving me a probability with which the algorithm decide to do or not do a random action. Why the parameter is not bounded to be in the interval [0, 1.0] but just  float >= 0.0? I've tested it and I can use values greater than 1.0 and nothing is going to break. Also the task I'm trying to solve hasn't yet converged so I'm not even 100% sure this parameter work as I thought it does.

2. **About the Summary**. I'm using it on VSCode to get nice plots in tensorboard. I've readed the [documentation](https://tensorforce.readthedocs.io/en/latest/agents/tensorforce.html) about the summary part(link embedded, I will not copy paste to avoid verbosity), and I am not getting a grasp of what I'm being shown on tensorboard. In the specific:

![immagine_2021-10-26_103825](https://user-images.githubusercontent.com/65607815/138842170-61180352-18f2-4b06-b0f3-970d1947a91f.png)
                               _fig.1: two different plots for two set of parameters. No convergence here,as we can clearly see._

I got plots for the following values: "agent/cond/episode_length", "agent/cond/episode_return" , "agent/reward", "agent/update-return". 
Among these, the only clear elements are the agent reward and the episode length. About the update-return and the episode-return, they seem to be directly a mesure of the convergence of the algorithm. So I was wondering what does it means more specifically. Can someone explain this to me? Such answers are important to improve my knowledge and comprehension of the library.

Thank to whoever will try to give me an answer,it means a lot.

Kindest Regards,

Matteoem

**Comment by AlexKuhnle** [comment]
No further activity.
