### ISSUE TITLE
tensorforce.exception.TensorforceError: Environment.execute: invalid component {name} for state.

### ISSUE THREAD

**Issue by Jeonous** [tensorforce/tensorforce#838]
Hi!

I'm implementing Custom Environment using _Environment_ Class of TensorForce Library.
While implementing the environment, I got the following error code:

> tensorforce.exception.TensorforceError: Environment.execute: invalid component {name} for state.

This error came from def _check_states_output( ) in _Environment_ Class in environment.py.

The part where the error occurred in that function is as follows:
`
### Skip
        if 'type' in states_spec or 'shape' in states_spec:
            states_spec = TensorSpec(**states_spec)
            if isinstance(states, dict):
                print("Library, states:", states, type(states))
                for name in states:
                    print("Library, name of states:", name, type(name))
                    if name != 'state' and not name.endswith('_mask'):
                        raise TensorforceError(function + ': invalid component {name} for state.')
                _states = states['state']
            else:
                _states = states
### Skip
`

I think it has something to do with the def _states_(self) method in my Custom Environment.

Here are codes of the states( ) I wrote:

    def states(self):
        """
        Method to return the state space specification
        """
        self.observation_space = {  # State (Observation) space
            'type': "float",
            'shape': (len(ATT_STATES),),  # integer
            # 'num_values': len(ATT_STATES),  # not used
        }
        return self.observation_space
`

I referred to the following example and documentation to implement a custom environment.

https://tensorforce.readthedocs.io/en/0.6.5/index.html
https://github.com/tensorforce/tensorforce/blob/0.6.5/examples/vectorized_environment.py

I'm not sure what the problem is...
Can you help in this regard?

Thank you.

**Comment by info2metlab** [comment]
Have the same issue when calling: 
states = environment.reset()

My states space definition looks like this:
def states(self):
        return  dict(type='float', shape=(7,)) # 7 dimensions

My reset function looks like this:
def reset(self):
        """Reset state."""
        Id          =  'Cooper'
        sessionId       = 'User'
        unknowns        = ['a', 'b', 'c', 'd', 'e','f', 'd']
        raw_unknown     = get_unknowns(xfrmId, sessionId, unknowns)
        return dict((u, np.random.uniform(np.float(raw_unknown.get(u, 0)[0]), np.float(raw_unknown.get(u, 0)[1]))) for u in set(raw_unknown))

When calling states = environment.reset(), 
I've got the the following exception popping up:

File "/Users/Thierot/miniconda3/lib/python3.8/site-packages/tensorforce/environments/environment.py", line 454, in _check_states_output
    raise TensorforceError(function + ': invalid component {name} for state.')
tensorforce.exception.TensorforceError: Environment.reset: invalid component {name} for state.


Any idea what might be happening? I am bumping my head around this. Can you please help out?
