### ISSUE TITLE
tensorforce.exception.TensorforceError: Environment.reset: invalid component {name} for state.

### ISSUE THREAD

**Issue by info2metlab** [tensorforce/tensorforce#841]
I have an "Environment.reset: invalid component {name} for state" issue when calling:
states = environment.reset()

My states space definition looks like this:
def states(self):
return dict(type='float', shape=(7,)) # 7 dimensions

My reset function looks like this:
def reset(self):
"""Reset state."""
Id = 'Cooper'
sessionId = 'User'
unknowns = ['a', 'b', 'c', 'd', 'e','f', 'd']
raw_unknown = get_unknowns(xfrmId, sessionId, unknowns)
return dict((u, np.random.uniform(np.float(raw_unknown.get(u, 0)[0]), np.float(raw_unknown.get(u, 0)[1]))) for u in set(raw_unknown))

When calling states = environment.reset(),
I've got the the following exception popping up:

File "/Users/Thierot/miniconda3/lib/python3.8/site-packages/tensorforce/environments/environment.py", line 454, in _check_states_output
raise TensorforceError(function + ': invalid component {name} for state.')
tensorforce.exception.TensorforceError: Environment.reset: invalid component {name} for state.

Any idea what might be happening? I am bumping my head around this. Can you please help out?

**Comment by AlexKuhnle** [comment]
Hi @info2metlab,

Simple solution here: you just need to turn your state into a `(7,)` array instead of a dict with 7 entries. :-)   Something like:

```python
return np.asarray([
    np.random.uniform(np.float(raw_unknown.get(u, 0)[0]), np.float(raw_unknown.get(u, 0)[1])))
    for u in raw_unknown
])
```

In general, the state needs to look exactly as specified in the `states()` function. So in your case a single float array of shape `(7,)`. States can also be dictionaries of numpy arrays, but that would be for multi-component states, e.g. when the `states()` spec looks something like `dict(image=dict(type='float', shape=(X, Y)), status=dict(type='int', shape=(N,)))`.

Hope that helps!

**Comment by info2metlab** [comment]
> Hi @info2metlab,
> 
> Simple solution here: you just need to turn your state into a `(7,)` array instead of a dict with 7 entries. :-) Something like:
> 
> ```python
> return np.asarray([
>     np.random.uniform(np.float(raw_unknown.get(u, 0)[0]), np.float(raw_unknown.get(u, 0)[1])))
>     for u in raw_unknown
> ])
> ```
> 
> In general, the state needs to look exactly as specified in the `states()` function. So in your case a single float array of shape `(7,)`. States can also be dictionaries of numpy arrays, but that would be for multi-component states, e.g. when the `states()` spec looks something like `dict(image=dict(type='float', shape=(X, Y)), status=dict(type='int', shape=(N,)))`.
> 
> Hope that helps!

**Comment by info2metlab** [comment]
It worked. Thanks a lot!
