### ISSUE TITLE
Custom Action-distributions layer activation function

### ISSUE THREAD

**Issue by AndPazzaglia** [tensorforce/tensorforce#842]
Hi @AlexKuhnle,
Thank you for the great library!

I created an action with the following dictionary:
`dict(type='float', min_value=0.0, max_value=1.0, shape=(8,))
`
However the action layer is automatically created with a linear specification:
```
Action-distributions:
Mean:  Linear(name=mean, size=8, bias=True, initialization_scale=0.01)
Stddev:  Linear(name=stddev, size=8, bias=True, initialization_scale=0.01)

```
I would like to define something like a softmax activation layer in order to get the action outputs normalized.
Is it possible?

Thank you in advance

**Comment by AlexKuhnle** [comment]
Hi @AndPazzaglia, this is not really intended to be done. Why do you want to do that?

**Comment by AndPazzaglia** [comment]
Hi @AlexKuhnle, for my experiment I want to define an agent with a portfolio proportion as output. For this reason I would like a N-dimensional float action which sums up to unity (like for softmax activation function).

**Comment by AlexKuhnle** [comment]
In that case I think it makes more sense to consider the softmax an environment processing step, so the agent outputs arbitrary float values and the environment processes them as softmax.
