### ISSUE TITLE
Not convergence of TensorForce agents training

### ISSUE THREAD

**Issue by carlorop** [tensorforce/tensorforce#844]
I have realized that, in general, the predictions of TensorForce agents during the training get stuck either in the middle of the action range or in the extremes. I have tried to replicate a minimal example of my code using the cart-pole environment using the same act-observe structure that I am employing in my experiments. The code is the following:

```python
import time
from collections import deque
from typing import List, Dict, Deque
import matplotlib.pyplot as plt
import numpy as np
from common.tensorforce_wrapper import TensorForceAgent
import gym
from tensorforce import Agent


env = gym.make("CartPole-v1")

exploration = dict(
     type='linear',
     unit="timesteps",
     num_steps=100,
     initial_value=0.9,
     final_value=0
)

agent= Agent.create(agent='dqn', states={"type":"float","shape":(4,)}, actions={"type":"int","num_values":2}, batch_size=64,memory=6500,exploration=exploration)

scores_window: Deque = deque(maxlen=1000)  # last 100 scores
n_episodes=1000
for i_episode in range(1, n_episodes + 1):
    score=0
    observation = env.reset()
    for w in range(1000):
      action = agent.act(states=observation, deterministic=False, independent=False)
      observation, reward, done, info = env.step(action)
      agent.observe(reward=reward, terminal=done)
      score = score + reward
      if done:
          break
    scores_window.append(score)  # save most recent score
    print("\nIt took ",w," steps until finish ")
    print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, float(np.mean(scores_window))), end="")

plt.plot(scores_window)
test=list(scores_window)
test_mean=[]
for i in range(len(test)-51):
    test_mean.append(np.mean(test[i:i+50]))
plt.plot(test_mean)
plt.show()

```

This training led to the following figures for the mean of a moving window with the reward of 50 consecutive episodes, after running it two times:

![cartpole_tf1](https://user-images.githubusercontent.com/86785014/144840180-12e53839-fbd0-4195-9627-b6236419acad.png)
![cartpole_tf2](https://user-images.githubusercontent.com/86785014/144840183-3c517d64-d97d-484b-b4d4-1125d5ae1015.png)

As can be seen, the reward is oscillating. Is there anything wrong with the code?

edit: I have tried to run some experiments using the [pendulum](https://gym.openai.com/envs/Pendulum-v0/) environment, the following code:

```python

import time
from collections import deque
from typing import List, Dict, Deque
import matplotlib.pyplot as plt
import numpy as np
from common.tensorforce_wrapper import TensorForceAgent
import gym
from tensorforce import Agent


env = gym.make("Pendulum-v0")


agent = Agent.create(agent='ddpg', states={"type":"float","shape":(3,)}, actions={"type":"float","shape":(1,)}, batch_size=64,memory=6500)


scores_window: Deque = deque(maxlen=1000)  # last 100 scores
n_episodes=1000
for i_episode in range(1, n_episodes + 1):
    score=0
    observation = env.reset()
    for w in range(1000):
      action = agent.act(states=observation, deterministic=False, independent=False)
      observation, reward, done, info = env.step(action)
      agent.observe(reward=reward, terminal=done)
      score = score + reward
      #print(action,reward)
      if done:
          print(action,reward)
          break
    scores_window.append(score)  # save most recent score
    print("\nIt took ",w," steps until finish ")
    print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, float(np.mean(scores_window))), end="")

plt.plot(scores_window)

test=list(scores_window)
test_mean=[]
for i in range(len(test)-51):
    test_mean.append(np.mean(test[i:i+50]))
plt.plot(test_mean)
plt.show()

```

leading to the following result for the mean of a moving window with the reward of 50 consecutive episodes:

![pist](https://user-images.githubusercontent.com/68447176/144846304-b2b391a1-5acd-49c4-aa78-25496be34c2b.png)

**Comment by AlexKuhnle** [comment]
Hi @carlorop,

The oscillation is simply due to the learning improvement not being stable, that's not untypical. In your case, DQN is timestep-based, so you perform an update every 64 timesteps, which means generally multiple updates per episode in the CartPole case, which can lead to minor overfitting to a few successful episodes and subsequent "collapse". However, it looks like the trend is upwards, which is good.

I can't say much about the Pendulum case apart from that the oscillation here is not meaningful and the agent is not learning anything, considering the large negative reward. More tuning should help, at least a bit, but Pendulum is definitely not as easy as CartPole.

**Comment by AlexKuhnle** [comment]
Closing since no issue, but feel free to continue posting here.
