### ISSUE TITLE
I am getting InvalidArgumentError at the beginning of training. 

### ISSUE THREAD

**Issue by Jeonous** [tensorforce/tensorforce#848]
Hi,

I had a problem with "Runner"...

The entire error message is as follows:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Invalid gradient: contains inf or nan. : Tensor had NaN values
	 [[{{node agent/StatefulPartitionedCall/agent/cond_1/then/_297/agent/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/VerifyFinite/CheckNumerics}}]] [Op:__inference_observe_4620]
```

Function call stack:
observe

I'm using a custom vectorized environment and DQN algorithm.

The parameters for the DQN algorithm applied are as follows:

```
agent = Agent.create(  # DeepQNetwork agent
                agent='dqn', environment=environment,
                batch_size=64, memory=5000,
                start_updating=64* 5,
                learning_rate=0.001
            )
```
The states( ) and actions ( ) of the custom environment is as follows:

```
    def states(self):
        """
        Method to return the state space specification
        """
        self.observation_space = {  # State (Observation) space
            'type': "float",
            'shape': (4,),            
            'min_value': 0.0,
            'max_value': 1.0,
        }
        return self.observation_space

    def actions(self):
        """
        Method to return the action space specification
        """
        self.action_space = {  # Action space
            'type': "int",
            'shape': (20, ),  
            'num_values': 2,  # 1 or 0
        }
        return self.action_space
```
This error occurred after 2 episodes. (There was only 1 case with about 20 episodes)
And there were about 1~2 experiences during 1 episode.

So I couldn't not only understand why it occurred but also why this error happened at this initial timing (after 2 episodes).
Since I thought that not enough data was accumulated for training because start_updating is 320.

I read similar issues like the below links and applied some of them, but I couldn't solve the problem...
[https://github.com/tensorforce/tensorforce/issues/839](url)
[https://github.com/tensorforce/tensorforce/issues/797](url)
[https://github.com/tensorforce/tensorforce/issues/738](url)

The difference is that they used the PPO algorithm and I did the DQN algorithm, and the environment is different too.

I have had difficulty figuring it out on myself.
Will I get any hints or solutions?

Thank you.

**Comment by Jeonous** [comment]
When I changed the algorithm of the agent from _DQN_ to _Tensorforce_, the above error didn't occur.

The parameters I used for the _Tensorforce_ agent is as follows:

```
agent = Agent.create(  # TensorForce agent
                agent=agent_type, environment=environment,
                policy=dict(network=[  # Policy
                    dict(type='dense', size=16, activation='tanh'),
                    dict(type='dense', size=32, activation='tanh')
                ]),
                update=32,
                optimizer=dict(optimizer='adam', learning_rate=1e-3),
                objective='policy_gradient', reward_estimation=dict(horizon=20)
```
            
I think there may be a problem with DQN, but I haven't been able to find the cause when I look through the library code...

**Comment by AlexKuhnle** [comment]
Hi @Jeonous, can you share the full code incl environment, by any chance? Or otherwise can you see whether you can reproduce it on a simple Gym environment? I don't know why this error comes up, why there would be inf or nan anywhere (and particularly so early on in training), but I also don't know how I would debug it without being able to reproduce it.

**Comment by AlexKuhnle** [comment]
Any updates?

**Comment by Jeonous** [comment]
Hi, @AlexKuhnle 

Thank you for applying and sorry for the late answer.

I will apply your solution as soon as possible.

**Comment by Jeonous** [comment]
Dear @AlexKuhnle,

I close this issue now and will re-open it after applying solutions.

Sorry for being late.
