### ISSUE TITLE
UserWarning tensorflow

### ISSUE THREAD

**Issue by ValentinGlaser** [tensorforce/tensorforce#850]
I got the following `UserWarning` while training. The training process aborts a few episodes after this warning. 

Any ideas how to handle the warning?

```
/root/miniconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:447: UserWarning: 
Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("policy_optimizer/PartitionedCall:2", shape=(None,), dtype=int32), 
values=Tensor("policy_optimizer/PartitionedCall:1", shape=(None, 64), dtype=float32), 
dense_shape=Tensor("policy_optimizer/PartitionedCall:3", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. 
This may consume a large amount of memory.
warnings.warn(
```

**Comment by AlexKuhnle** [comment]
Hi @ValentinGlaser, the warning comes up often and shouldn't be a problem -- presumably you're using an `int` or `bool` state space? What is your overall state/action and network spec, and what's the abortion exception?

**Comment by ValentinGlaser** [comment]
As you mentioned "the warning comes up often and shouldn't be a problem" the warning was not the reason for the abortion. Thanks to your hint I searched for other reasons and solved it. 

And yes I am using an bool state space.

**Comment by ValentinGlaser** [comment]
This is the abortion exception:

```
TypeError: __init__() missing 3 required positional arguments: 'node_def', 'op', and 'message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "my_file.py", line 3243, in <module>
    env.run(until=SIM_TIME)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/simpy/core.py", line 254, in run
    self.step()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/simpy/core.py", line 206, in step
    raise exc
TypeError: __init__() missing 3 required positional arguments: 'node_def', 'op', and 'message'
```

**Comment by AlexKuhnle** [comment]
Is this still a problem? What version of TensorFlow are you using?

**Comment by ValentinGlaser** [comment]
Yes, but I'm not sure if the origin of the problem is `Tensorforce` because of the abortion exception.

I'm using `TensorFlow 2.6.0`.
