### ISSUE TITLE
quick start install/tensorflow version?

### ISSUE THREAD

**Issue by hpcpony** [tensorforce/tensorforce#862]
I'm trying to do the quick start example in the "documentation":

> [user]$ python quick.py
> Traceback (most recent call last):
>   File "/scr/tensorforce/quick.py", line 1, in <module>
>     from tensorforce import Agent, Environment
>   File "/opt/Anaconda3-2021.11_RL/envs/tensorforce/lib/python3.10/site-packages/tensorforce/__init__.py", line 23, in <module>
>     import tensorflow as tf
> ModuleNotFoundError: No module named 'tensorflow'

I thought I was following the install documentation but only did the `pip3 install tensorforce` and `pip3 install gym[all]` (that's enough frustration for one day) so I'm missing something.  pip only gave me tensorforce 0.5.5 (from 2020) so I'm not sure which version of tensorflow I should be installing (if any since it seems weird that it wasn't installed as a dependency or mentioned in the install instructions).

**Comment by hpcpony** [comment]
Just to follow up on what I've been learning so others don't have to go through this...

Don't use Anaconda (I was using 2021.11) and `pip3 install tensorforce`.  For some reason the pip there picks up an old version of tensorforce (0.5.5).

I have had better luck by grabbing a plain version of Python (3.10.4) and building it locally (be sure you're building the SSL stuff otherwise you get done and pip won't work anyway).  Then download the 0.6.5 and do `pip3 install ./tensorflow`.  Don't do the "-e" and make sure you add the "./" (otherwise I think it goes out to the net and grabs a different version; I went with this).

That got me through with a basic install but as you can see from other "issues" there are still  bugs to be dealt with.

**Comment by AlexKuhnle** [comment]
Hi @hpcpony, I'm surprised that Anaconda is pointing at an earlier version, but outside of Anaconda you should be able to simply do `pip install tensorforce` and get the latest fixed version of Tensorforce as well as the corresponding version of TensorFlow.
