### ISSUE TITLE
PPO agent horizon params

### ISSUE THREAD

**Issue by devantheryl** [tensorforce/tensorforce#865]
Hi, 

I just wonder where is the horizon parameter for the PPO agent? I don't know much about this agent yet, but the horizon parameter seems to be essential

**Comment by AlexKuhnle** [comment]
Hi @devantheryl, if you want to play with the `horizon` parameter, it's best to use the more general `tensorforce` agent. For PPO, since it's a typical policy gradient algorithm, the discounted-sum reward horizon is the full episode, so it's internally specified as `horizon='episode'`.
