### ISSUE TITLE
How to change epsilon value when using epsilon-greedy policy?

### ISSUE THREAD

**Issue by Zebin-Li** [tensorforce/tensorforce#891]
Hi,

I want to use epsilon-greedy policy for DQN, but I cannot find a parameter related to epsilon. So how to set the epsilon value if using epsilon-greedy policy? Besides, are DQN family algorithms (e.g., double DQN and Dueling DQN) by default using epsilon-greedy policy? Thank you very much!

Best,
Zebin

**Comment by Zebin-Li** [comment]
I guess it is the "exploration" parameter.

**Comment by AlexKuhnle** [comment]
Yes, that's right.
